### ISSUE TITLE
ZeroMQ libs folder not being included for Standalone --New for pyzmq 22.0.x

### ISSUE THREAD

**Issue by KevinSydaptic** [Nuitka/Nuitka#1007]
I'm running the latest Nuitka via pip.  The only other package in this clean Python 3.8.7 virtualenv is pyzmq.  The latest is 22.0.3.  From version 21 to version 22 they seemed to have moved or added some dlls.  They got moved to a new folder directly in site-packages named pyzmq.libs.  Copying the folder over to the dist folder (when producing a standalone dist) solves the issue.

Nuitka==0.6.12.3
pyzmq==22.0.3
Python: 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)]
OS: Windows
Arch: x86_64

```
import zmq
import random
import time


def main():

    bind_to = "tcp://127.0.0.1:5555"


    context = zmq.Context()
    socket = context.socket(zmq.PUB)
    socket.bind(bind_to)

    while True:
        topic = random.randrange(9999, 10005)
        messagedata = random.randrange(1, 215) - 80
        print("%d %d" % (topic, messagedata))
        socket.send_string("%d %d" % (topic, messagedata))
        time.sleep(1)

if __name__ == "__main__":
    main()
```

The command I used to create the standalone dist was

`nuitka3.exe --standalone zmqtest.py`

When running the program from a cmd prompt I get:

```
Traceback (most recent call last):
  File "C:\Users\user\SERIAL~1\ZMQTES~1.DIS\zmqtest.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\user\SERIAL~1\ZMQTES~1.DIS\zmq\__init__.py", line 19, in <module zmq>
  File "C:\Users\user\SERIAL~1\ZMQTES~1.DIS\zmq\__init__.py", line 10, in _delvewheel_init_patch_0_0_10
  File "C:\Users\user\SERIAL~1\ZMQTES~1.DIS\os.py", line 1109, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: `'C:\\Users\\user\\SERIAL~1\\ZMQTES~1.DIS\\pyzmq.libs'`

```

**Comment by kayhayen** [comment]
Interestingly, that new code is marked with something that indicates the tool used:

https://pypi.org/project/delvewheel/

That's making me believe, that this might be something, we could handle in a plugin. Can you state if you have any urgency with this, because I could also do it right and attempt to make something that detects such delvewheel generated code and instrument it. In this instance, e.g. hooking `os.add_dll_directory` and `ctypes.WinDLL` seem to be good.

This is the code I am talking about:

```
# start delvewheel patch
def _delvewheel_init_patch_0_0_10():
    import os
    import sys
    libs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, 'pyzmq.libs'))
    if sys.version_info[:2] >= (3, 8):
        os.add_dll_directory(libs_dir)
    else:
        from ctypes import WinDLL
        with open(os.path.join(libs_dir, '.load-order-pyzmq-22.0.3')) as file:
            load_order = file.read().split()
        for lib in load_order:
            WinDLL(os.path.join(libs_dir, lib))


_delvewheel_init_patch_0_0_10()
del _delvewheel_init_patch_0_0_10
# end delvewheel patch
```

Given this is a frequent problem, this could be something to point people to. I am not sure how much upstream decision of pyzmq is in the `..\pyzmq.libs` part of this, but I guess, instrumenting it or extracting it into something where globals is hooked just enough to tell us what this registers, would be extremely fine.

For Nuitka this could be something to point upstreams to as a way of doing it then, and having only some sort of detector for the presence of these functions, that could resolve the many handmade solutions people have and that in Nuitka are to be reproduced.

**Comment by kayhayen** [comment]
I created a new zmq plugin that is always enabled, and more code specific to zmq there, while also adding a detection of the `delvewheel` that runs a snippet of the code to extra the DLL directory. This works with pyzmq 22 on Windows and Python3.8 or higher, but I also believe older versions should work fine too. The code is relatively generic for `delvewheel` usage. I am not making a generic one right away, but it's at the core of this new plugin supporting the DLLs.

Check out this https://nuitka.net/doc/factory.html but consider the usual warnings. I am not yet sure if this is suitable for a hotfix, and I need to checkout pyzmq 21 and before if they are still working, which I would assume. Also it may cause issues with pyzmq on Linux now, but the `delvewheel` code shouldn't trigger there though.

**Comment by KevinSydaptic** [comment]
Thanks for the follow up. My urgency is not high since it's only copying the folder over to make it work. 

When I get a chance I'll give it a try.

**Comment by kayhayen** [comment]
This is part of the recent pre-release.

**Comment by kayhayen** [comment]
Part of the 0.6.13 release.
