### ISSUE TITLE
Pass 2 does not use list/number of modules from pass1?

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#1033]
Using nuitka 0.6.13 --standalone, the list of module keeps growing during pass1. I guess it can't be helped  as I suppose you are parsing modules & detecting their dependencies as you see them (unless you add a pass just to detect dependencies), but there is the same behavior for pass 2 which seems odd to me.

**Comment by kayhayen** [comment]
That's funny, because I was just thinking of that too.

So, basically what happens is that there is a set of root modules, and then Nuitka executes the module abstractly, and finds other modules used, which are then queued up to be worked on.

So it does from 0/1 to 800/900 to 1111/1200 and has no idea about the future. Each global pass does this.

However, I think the total during pass 2 indeed could be assumed to be more like the max from pass 1. What can happen, theoretically, is that an optimization removes an import from execution, and therefore the number would be much lower, imagine e.g. finding out that PyQt5 and PySide2 are not both used, because the first one is then detected to be there. This kind of thing.

It's definitely not an easy subject. I also wonder how caching will factor into this one day.

**Comment by gdementen** [comment]
As far as the progress bar is concerned, it is better IMO to have too many modules counted in the total (and just increment the "done" counter by 1 without doing anything else if a module does not need any work anymore -- whether because it is cached or optimized away), than to have a moving target as total (because then the % done can stall for a long time or even go backwards, which is a bit frustrating). 

The ideal situation would be to know in advance the total number of modules which still need actual work but I don't know if it is possible to know that at the end of the first pass.

**Comment by kayhayen** [comment]
On a re-execution Nuitka could re-use previous knowledge, that was on my mind. So only the first compile would do that, and then it would know.

Another thing could be to remember time spent per module and base percentage off that. But luckily I found something that I will refactor, and maybe that brings us back to all modules are fast. :)

**Comment by kayhayen** [comment]
So, I managed to add a `min_total` to the progress bar and respect that, so PASS 2 is looking nicer now, this is on factory right now, which as fixed a off by one previously, where a module was counted as progress when being started, rather than being finished, that made pass1 in particular flashy as it could from back from even 100% (still can go backwards, but never is at 100% until that's real).

I think along with some sort of fingerprint of the Python install (think `sys.path` file listing contents (not wrong to get that into cache, Nuitka is looking at that anyway for imports), `sys.executable`, maybe more, I think I have that for test result caching of CPython somewhere already), the `min_value` for pass1 could be read and written in cache file. 

That way it would look smooth the second time you compile it. Obviously the progress bar is work in progress, pun intended.

**Comment by kayhayen** [comment]
The off by one error is part of 0.6.13.1 hotfix, the pass2 improvement is part of the current develop release.

**Comment by kayhayen** [comment]
Part of the 0.6.14 release.

**Comment by gdementen** [comment]
Thanks for the quick turnaround!
