### ISSUE TITLE
Tests ask for password on macos

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#1039]
```
Consider output of standalone mode compiled program: BrotliUsing.py
Comparing output of 'BrotliUsing.py' using '/usr/local/opt/python@3.9/bin/python3.9' with flags silent, expect_success, --standalone, remove_output, cpython_cache, timing ...
CPython took 0.03s vs 17.06s Nuitka.
Password:

Determining run time loaded files took 1017.19
...
```
The 1017.19 comes from me walking away expecting the tests to run to completion, and the delay entering passowrd was being timed. 

Under the covers I see it is running `sudo dtruss...`

It would be nice if there was some notice to explain why `sudo` is prompting for a password.

**Comment by jayvdb** [comment]
In order to run unattended, it would be better to run the test without dtruss, and then re-run under `sudo dtruss ..` only if there was a problem detected.

**Comment by kayhayen** [comment]
That's a bit of a problem there, as the test shall check for file accesses of the program, and `dtruss` to my knowledge won't run without `sudo`, but maybe that's not even correct, in which case we could remove it. No idea what to do about that otherwise.

**Comment by kayhayen** [comment]
I have this in my sudo configuration, 

> nuitka-buildslave ALL = (ALL) NOPASSWD: ALL

and if you were to only allow dtruss, I believe it would make very little sense, because practically then arbitrary code could be run as root via dtruss, so there is no point. And I believe one even has to disable the safety measures in the BIOS. I was e.g. not able to run it on a hosted machine, where  that could not be done. Essentially, you cannot run the standalone and onefile tests therefore.

For the later, there is a detection in `doesSupportTakingRuntimeTrace` and it should not prompt from sudo unless ran in a terminal. I think that has to be good enough.
