### ISSUE TITLE
Add option to set Nuitka's base cache directory

### ISSUE THREAD

**Issue by Ben-Faessler** [Nuitka/Nuitka#1090]
Can you please add an option and/or an environment variable to change the default cache path?
For me, for example, the default is problematic because all my cache paths are virtual directories.

**Comment by kayhayen** [comment]
I think, appdirs reacts to configuration. We probably just need to figure out which, and document that, or we can add our own environment variable to override it, but that's lazy.

I was wondering what virtual directories means. Are you saying they are being discarded later on, and this is in containers?

**Comment by kayhayen** [comment]
@Ben-Faessler if you don't mind, I will try our your PR first, and then try to put the missing bits there, rather than explaining it in the PR, then hand it back to you. This feature is on my hot list as a big thank you for going there, it seems you got that PR pretty much done, but it takes me to know which code path is OK for the early bytecode module you create there.

**Comment by Ben-Faessler** [comment]
What do you mean by code path?

**Comment by kayhayen** [comment]
I added the `NUITKA_CACHE_DIR` environment, which ought to point to the base of all caching folders for Nuitka. This will be needed for container builds to allow reusing the cache, e.g. by mounting it to the specified place. Other uses might be to not put things in a network home directory, but rather on a local disk.

The change is currently on factory: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
Part of the 0.6.16 release.
