### ISSUE TITLE
Markdown module could use a plugin for its extensions

### ISSUE THREAD

**Issue by notback2020** [Nuitka/Nuitka#1121]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version
`0.6.14.7
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:34:34) [MSC v.1928 32 bit (Intel)]
OS: Windows
Arch: x86`

* How did you install Nuitka and Python
`python -m pip install nuitka`

code:
` md = markdown.Markdown(extensions=["fenced_code","footnotes","tables","nl2br","toc"],extension_configs=configs)`

cli
`python -m nuitka --warn-implicit-exceptions --warn-unusual-code --follow-import-to=markdown --follow-import-to=pyquery  --follow-import-to=click --follow-import-to=MBPython --follow-import-to=lxml --follow-import-to=requests --follow-import-to=cssselect  --output-dir=dist --mingw64`

err:
`ModuleNotFoundError: No module named 'markdown.extensions.fenced_code'`

**Comment by kayhayen** [comment]
I think you should try to use `--include-module=markdown.extensions.fenced_code` as there really is no way for Nuitka to know that, outside of a plugin that would attempt to recognize this specifically.

**Comment by walkinrain2021** [comment]
I guess nuitka can follow to all of markdown include extensions.

I will try `--include-module`, but if a program needs to be configured this way, the length of the command line is unacceptable.

In fact, my program has been unable to run normally using `--standalone`, but in the simplest way, adding `--nofollow-imports` to run it. So I have been trying various combinations.

I think if nuitka can do a preprocessing, generate a configuration file [such as include.json], and then compile, whether it can be easier to debug.

My English is poor! :)

**Comment by kayhayen** [comment]
Well, you can put options in the main file with what's called project options. That's nicer surely.

I am not sure, why it wasn't loading the extensions. Are these Python modules, because if they are, Nuitka cannot at runtime load Python code into a compiled module, but so far only extension modules, or that's what I might be misremembering. It actually should have worked without standalone to locate the plugins, but maybe it insists on funny things.

For standalone, I don't understand how nofollow can improve things, clarify the problem.

**Comment by walkinrain2021** [comment]
`python -m nuitka --standalone --warn-implicit-exceptions --warn-unusual-code --follow-imports --include-module=markdown.extensions.fenced_code --output-dir=dist --mingw64 --quiet --show-scons --show-modules`
error:
```
 File "dist\MDV~1.DIS\markdown\core.py", line 96, in __init__
  File "dist\MDV~1.DIS\markdown\core.py", line 123, in registerExtensions
  File "dist\MDV~1.DIS\markdown\core.py", line 162, in build_extension
  File "importlib.py", line 127, in import_module
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fenced_code'
```
main code:
`md = markdown.Markdown(extensions=["fenced_code","footnotes","tables","nl2br","toc"],extension_configs=configs)`

From the error message, it is mainly caused by the dynamic loading of `fenced_code`.
But my program relies heavily on this package `markdown`
`python -m pip install markdown`.
And `markdown`package loading extensions are all in the way of `registerExtensions`.

How should I write command line parameters?

I think `Python for Windows embeddable package` + exe(Nuitka create) is also a good standalone way.

**Comment by kayhayen** [comment]
I see, it seems it loads plugins not in a namespace or exposes them like that, so markdown plugins need a special treatment unfortunately. With the right `PYTHONPATH` you will have `--include-module=fenced_code` working. Where does that extension code live in the Python install?

**Comment by walkinrain2021** [comment]
fenced_code path : `Python3\Lib\site-packages\markdown\extensions`

`--include-module=fenced_code` ,nuitka error ,can not find module

i used 
`python -m nuitka --standalone --warn-implicit-exceptions --warn-unusual-code --follow-imports  --include-plugin-directory=D:\Python3\Lib\site-packages\markdown\extensions --output-dir=dist --mingw64 --quiet --show-scons --show-modules   mdv.py   --include-data-file=node.dll=./ --include-data-file=test.md=./ --include-data-file=mdviewer.tplt=./ --windows-icon-from-ico=res/mdv.ico --windows-company-name=StartPointTeam --windows-product-name=mdviewer --windows-file-version=1.0.0.0`

still
`ModuleNotFoundError: No module named 'fenced_code'`

**Comment by walkinrain2021** [comment]
`pythonpath=C:\Python3`

**Comment by walkinrain2021** [comment]
path：
python installed `c:\python3`
markdown package installed(by `python -m pip install markdown`) `c:\python3\Lib\site-packages\markdown`
fenced_code `c:\Python3\Lib\site-packages\markdown\extensions`

**Comment by kayhayen** [comment]
And if you execute that python, doesn't `import markdown.extensions.fenced_code` work? Ah wait, you are using an outdated version of Nuitka.

**Comment by kayhayen** [comment]
So since the markdown extension list may not be compile time recognizable, this is really something we should let the user handle, but we ought to have a plugin of nuitka that allows this. Maybe if the new yaml based approaches make this kind of thing generally easy, we can add this. I am not sure I want to add implicit dependencies on all plugins here, that seems over the edge.

**Comment by walkinrain2021** [comment]
O(∩_∩)O，i know what 's your means . you want that let me insert `import markdown.extensions.fenced_code` into my code .

I have added `from markdown.extensions import *` to the code just now.
Use the cli:
```
python -m nuitka --standalone --warn-implicit-exceptions --warn-unusual-code --follow-imports --output-dir=dist --mingw64 --quiet --show-scons --show-modules   mdv.py   --include-data-file=node.dll=./ --include-data-file=test.md=./ --include-data-file=mdviewer.tplt=./ --windows-icon-from-ico=res/mdv.ico --windows-company-name=StartPointTeam --windows-product-name=mdviewer --windows-file-version=1.0.0.0
```
The error remains:
```
Traceback (most recent call last):
  File "D:\MyCode\dist\MDV~1.DIS\mdv.py", line 215, in <module>
  File "D:\MyCode\dist\MDV~1.DIS\click\core.py", line 1137, in __call__
  File "D:\MyCode\dist\MDV~1.DIS\click\core.py", line 1062, in main
  File "D:\MyCode\dist\MDV~1.DIS\click\core.py", line 1404, in invoke
  File "D:\MyCode\dist\MDV~1.DIS\click\core.py", line 763, in invoke
  File "D:\MyCode\dist\MDV~1.DIS\mdv.py", line 73, in main
  File "D:\MyCode\dist\MDV~1.DIS\markdown\core.py", line 96, in __init__
  File "D:\MyCode\dist\MDV~1.DIS\markdown\core.py", line 123, in registerExtensions
  File "D:\MyCode\dist\MDV~1.DIS\markdown\core.py", line 162, in build_extension
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fenced_code'
```
Now I will try `import markdown.extensions.fenced_code`

**Comment by walkinrain2021** [comment]
I have added `import markdown.extensions.fenced_code` to my code.
The error is still `ModuleNotFoundError: No module named'fenced_code'`

**Comment by kayhayen** [comment]
Added the extensions all, it's not too heavy in terms of dependencies it seems.

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.7.4 that I just made.
