### ISSUE TITLE
Question: execution time of print statements

### ISSUE THREAD

**Issue by RichardFevrier** [Nuitka/Nuitka#1150]
Profiling simple HelloWords gives interesting results:

_Python script:_
```
real	0m0.117s
user	0m0.068s
sys	0m0.053s
```
_Nuitka --standalone:_
```
real	0m0.124s
user	0m0.119s
sys	0m0.005s
```
_C script:_
```
real	0m0.003s
user	0m0.000s
sys	0m0.003s
```

The Nuitka result is not better than Python for this exercise, and both are far behind C by around 40 times.
How is this possible? Is there a way to improve those results?

**Comment by kayhayen** [comment]
The print statement is not optimized, it usually doesn't matter.

**Comment by RichardFevrier** [comment]
I wish you did not close this question so fast, because I just replaced the print by a simple integer assignment.
And the results are exactly the same.

Is this normal @kayhayen ?

**Comment by kayhayen** [comment]
I am closing questions, it doesn't mean I won't continue to discuss. The overhead of launching a Python environment are relatively big, and esp. for standalone mode, it's even potentially bigger. The startup time is not what you should compare. Nuitka has tests for constructs, comparing performance to Python, e.g. integer addition here: https://speedcenter.nuitka.net/constructs/construct-inplaceoperationintegeradd.html

Generally if startup time, and in that disk IO mostly, is the limiting factor, there is not a lot to do here. Nuitka is not translating to C. You may want to look at Shedskin which converts your program to C++ and aims at no compatibility. Nuitka is better geared at full integration with the Python stack, e.g. PySide, otherwise write your program in C if you don't need any Python libraries.

**Comment by RichardFevrier** [comment]
Interesting, so Nuitka is probably not suited for embedded devices projects (our target; phones, watches..) where any ms is important to keep the user experience fluid.
Thank you for sharing other projects.
And thank you even more for taking the time to answer.
Have a nice day.
