### ISSUE TITLE
Question: Hiding functions in compiled module

### ISSUE THREAD

**Issue by ricky0123** [Nuitka/Nuitka#1219]
I'm thinking of using Nuitka to compile a module. However, there are certain functions in the module that I want to be private. I don't want end users to be able to import these functions. Do you have any ideas about how I might achieve this?

**Comment by kayhayen** [comment]
Yes, in Nuitka commercial, there is information about how to achieve this, such that e.g. dir() etc. only show what you allow, this is esp. important if you have no control over the execution environment. And there is a offer out there, that if accepted, will have a shim type system that will hide your actual module, classes and objects, and only expose configured methods and attributes, and even allow fine grained access control.

In order to find Nuitka commercial, go here: https://nuitka.net/pages/commercial.html

So far, this is not advertised, as it's effectively in the making. In any case, I would recommend you to join.

**Comment by kayhayen** [comment]
Questions are closed when answered.

**Comment by ricky0123** [comment]
@kayhayen just to clarify, is this possible to do with Nuitka Commercial right now or is it scheduled for the future?

**Comment by kayhayen** [comment]
@kayhayen the information is still there, the shim offer has not yet been taken

**Comment by kayhayen** [comment]
@ricky0123 can you send me a private email? I think you filled out the form in the past, but with wrong email, and it would be good to solve that.
