### ISSUE TITLE
Cannot ignore PyQt5 with --no-follow-import

### ISSUE THREAD

**Issue by JoeyBallentine** [Nuitka/Nuitka#1235]
version: latest hotfix, upgraded via pip (also happened on the older versions I tested)

Basically I've tried adding --no-follow-import=PyQt5 as well as specifying it's submodules in separate nofollows. However, it still gets included in my compilation. It's not a huge deal as I don't think it causes too much bloat, but it would be nice if I could actually get it to be ignored.

**Comment by kayhayen** [comment]
Now it says 

> Nuitka-Plugins:INFO: pyside2: Unwanted import of 'PyQt5' that conflicts with 'PySide2' encountered, preventing                                     
> its use. As a result an "ImportError" might be given at run time. Uninstall it for full compatible
> behaviour with the uncompiled code to debug it.

Not making it a warning, because the plugin gets asked about this too late, before you prevent it yourself (which you do not have to actually).

Without standalone mode, after pass 2, the plugin warns like this:

> Nuitka-Plugins:WARNING: pyside2: Unwanted import of 'PyQt5' that conflicts with 'PySide2' encountered. Use '--nofollow-import-to=PyQt5' or uninstall it.

I am starting to consider this as hotfix material, as it is only a plugin feature addition.

**Comment by kayhayen** [comment]
I cannot reproduce this, and in fact it shouldn't happen.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
