### ISSUE TITLE
libQt5QmlModels.so.5 missing on Ubuntu 20.04

### ISSUE THREAD

**Issue by ryansg8** [Nuitka/Nuitka#1252]
Running on Ubuntu 20.04, Python 3.8.10, installed Nuitka via pip. 

python3 -m nuitka --standalone --onefile --plugin-enable=qt-plugins application.py

It seems like everything compiles correctly, I receive an output of a .bin file in my directory, but when I run it via terminal I get the following issue:

```
Qt WebEngine resources not found at //resources. Trying parent directory...
Qt WebEngine resources not found at /. Trying application directory...
Installed Qt WebEngine locales directory not found at location /translations/qtwebengine_locales. Trying application directory...
Qt WebEngine locales directory not found at location /tmp/.mount_launchqSkew8/qtwebengine_locales. Trying fallback directory... Translations MAY NOT not be correct.
[1024/213158.907613:WARNING:resource_bundle_qt.cpp(115)] locale_file_path.empty() for locale 
/tmp/.mount_launchqSkew8/QtWebEngineProcess: error while loading shared libraries: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory
/tmp/.mount_launchqSkew8/QtWebEngineProcess: error while loading shared libraries: libQt5QmlModels.so.5: cannot open shared object file: No such file or directory
Trace/breakpoint trap (core dumped)
```
Not sure what to do, not seeing anything on google / this repo's issues about this.

**Comment by kayhayen** [comment]
You needd to include Qt plugins for qml and webengine this to work, try that.

**Comment by ryansg8** [comment]
> You needd to include Qt plugins for qml and webengine this to work, try that.

Even when including --include-qt-plugins=all it does not work. 
I also tried --include-qt-plugins=sensible,qml,webengine but it says that webengine is not found for pyqt5.

**Comment by kayhayen** [comment]
Ah, PyQt5 is not well supported, use PySide2 if you can. On factory branch I have improved the plugin operation with PyQt5, but at runtime it has bugs:  https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
The plugin change in on develop, I would appreciate feedback if it works better with pyqt5 for you now.

**Comment by ryansg8** [comment]
> The plugin change in on develop, I would appreciate feedback if it works better with pyqt5 for you now.

No, it now crashes using developer (not factory). 

`Nuitka-Plugins:INFO: pyqt5: Copying QtWebEngine binaries.
Traceback (most recent call last):
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 187, in <module>
    main()
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 173, in main
    MainControl.main()
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 823, in main
    addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module))
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/Plugins.py", line 372, in considerExtraDlls
    for extra_dll in plugin.considerExtraDlls(dist_dir, module):
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/PluginBase.py", line 383, in considerExtraDlls
    for included_entry_point in self.getExtraDlls(module):
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 769, in getExtraDlls
    for filename, filename_relative in listDir(qt_web_engine_dir):
  File "/home/server/.local/lib/python3.8/site-packages/nuitka/utils/FileOperations.py", line 230, in listDir
    [(os.path.join(path, filename), filename) for filename in os.listdir(real_path)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/server/.local/lib/python3.8/site-packages/PyQt5/Qt/libexec'`

**Comment by ryansg8** [comment]
> > The plugin change in on develop, I would appreciate feedback if it works better with pyqt5 for you now.
> 
> No, it now crashes using developer (not factory).
> 
> Using the following command line arguments:
> 
> python3 -m nuitka --standalone --onefile --plugin-enable=qt-plugins --include-qt-plugins=sensible,qml,webengine application.py
> 
> `Nuitka-Plugins:INFO: pyqt5: Copying QtWebEngine binaries. Traceback (most recent call last): File "/home/server/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 187, in <module> main() File "/home/server/.local/lib/python3.8/site-packages/nuitka/__main__.py", line 173, in main MainControl.main() File "/home/server/.local/lib/python3.8/site-packages/nuitka/MainControl.py", line 823, in main addIncludedEntryPoints(Plugins.considerExtraDlls(dist_dir, module)) File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/Plugins.py", line 372, in considerExtraDlls for extra_dll in plugin.considerExtraDlls(dist_dir, module): File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/PluginBase.py", line 383, in considerExtraDlls for included_entry_point in self.getExtraDlls(module): File "/home/server/.local/lib/python3.8/site-packages/nuitka/plugins/standard/PySidePyQtPlugin.py", line 769, in getExtraDlls for filename, filename_relative in listDir(qt_web_engine_dir): File "/home/server/.local/lib/python3.8/site-packages/nuitka/utils/FileOperations.py", line 230, in listDir [(os.path.join(path, filename), filename) for filename in os.listdir(real_path)] FileNotFoundError: [Errno 2] No such file or directory: '/home/server/.local/lib/python3.8/site-packages/PyQt5/Qt/libexec'`

This is likely because the libexec is stored in the Qt5 folder, not Qt folder. (At least on my machine).

**Comment by kayhayen** [comment]
Thanks for the feedback, going to look at it now.

**Comment by kayhayen** [comment]
Looking into this, turns out, there is a Qt function to ask where these binaries live, using that now. Also translations and resources, while taken from the directory, Qt needs a `qt.conf` to stop complaining about using defaults. In this case also many binding and platform differences go away.

Also added target paths for the standalone bundle, which the plugin probably needs to enforce as being used, not sure if macOS Qt can work without, I think it did in the past, but I might not want to make the different solutions.

**Comment by kayhayen** [comment]
Updated factory with the current state. I need to look into what Debian reacts like to this, maybe Qt from apt packages is not very relocatable at all.

**Comment by kayhayen** [comment]
More improvements on factory, should also work with PyQt6 now, added a plugin for it, and did the necessary tweaks to make up for their differences introduced.

**Comment by ryansg8** [comment]
> More improvements on factory, should also work with PyQt6 now, added a plugin for it, and did the necessary tweaks to make up for their differences introduced.

Alright so - it is compiling into the .bin file with no errors now. The only error shows up when running the .bin file from terminal

`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "" This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

**Comment by kayhayen** [comment]
Did you include Qt plugins or did you forget this time?

**Comment by ryansg8** [comment]
> Did you include Qt plugins or did you forget this time?

Nope 100% including them in the command line ,and the binary file size is large enough where I would believe QT is in it.

**Comment by kayhayen** [comment]
The qt plugins live in a separate folder. I will try on the Linuxes tomorrow. For now PySide2, PySide6, PyQt5 and PyQt6 working for QtWebEngine was quite a feat. Potentially Qt plugins need to live under a non-standard folder for PyQt5 too, and doing what's right for PySide2 won't cut it. If you want to help, play around with this:

```            target_plugin_dir = os.path.join(full_name.asPath(), "qt-plugins") ```

Adding `Qt` in the middle, or remove the `ull_name.asPath()` part or both (add Qt, remove binding name) ought to do the trick. For that, compile only standalone and modify the file `nuitka/plugins/standard/PySidePyQtPlugin.py` accordingly.

**Comment by kayhayen** [comment]
The code is now on develop, I didn't have the time yet to try it out on Linux, but it ought to work for the ones previouslyworking, i.e. the PySide2/6 packages.

**Comment by kayhayen** [comment]
I had change to complete this and make my way through it finally on an Ubuntu 20.04, which is normally too new to compile, but it gave some interesting points.

a) The Qt webengine process must be executable, which of course was never an issue with Windows. So added a special exe object to yield rather than dll, and make it set x bit.
b) The `libnss3` was included and prevented things from working, that's a library that must not be included and was missing, I noticed that there is inconsistency with so subversion or not in checks, rectified that too.
c) The paths for PySide2, PySide6, PyQt5, PyQt6 should no clear patterns. I added a `qt.conf` to convince them to use application folder, but no key set there seemed to ever impact the loading. Mayweb that exe ignores things, not sure. On most bindings there are more or less complains about where it's not, but putting at complained application dirs never works. Full of bugs, I will need to check with upstreams what this is about. I seem unable to specify the folders myself unlike we do for QML files.
d) And finally, the webengineprocess binary is using libraries which then use library that will not load unless convinced with a rpath added. They don't have it, so we need to switch from chrpath to patchelf, and for consistency, Nuitka now will always change all of them to have it.
e) And "all" was broken in the plugin, which was annoying, it was ignored. I rebased develop with a fix for that.
f) Files were copied even if already copied in some cases, esp. libuuid was subject to that, no big deal, that's rare I guess.
g) And there were duplicate DLLs warnings, because we don't normpath the DLL names when detected. The generic logic doesn't think it would have to do that, the files being the same, the auto-pick worked fine, but not needed of course.

That's a huge chunk of my life not coming back ever. Hopefully the result is good. I will have to check on macOS still, what kinds of pain we have there now.

**Comment by kayhayen** [comment]
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
This is now part of the current pre-release. macOS has still not been checked, but will before release.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
