### ISSUE TITLE
Speed up test-suite execution

### ISSUE THREAD

**Issue by brupelo** [Nuitka/Nuitka#128]
Please correct me about these assumptions:

 - Each time you want to fix a bug or add a feature, after planning and researching how you're gonna code it you're probably are creating a test before implementing the feature or fixing the bug
 - Then you'll just implement the feature till your freshly created test becomes ok or the bug is gone
 - Finally, you'll push it and make sure the whole test suite passes

Is this +/- correct? If it's so, I understand there is a real need about having separate tests per feature/bug/edge_case,  as that means it's the best choice for you to improve nuitka.

Now... would it be too difficult to improve the testing execution somehow? For instance, right now each test you run means you're spawning a new "nuitka process", right?

If it's so, wouldn't be possible to merge a whole bunch of tests in a single file and just testing that? wouldn't that mean just spawning 1 nuitka process? ie, imagine we've got:

 - test1.py
 - test2.py
 - ...
 - testn.py

Wouldn't be possible to merge all of them into something like `merged_tests.py` that contained:

  from test1 import *
  from test2 import *
  ...
  from testn import *

By doing so running that file would be relatively "lightweight", wouldn't?  Of course, when I say "merging" I mean merging the tests that have a similar `tearUp`/`tearDown` methods

Am I talking nonsense here?

Anyway, my whole question is, would it be possible to speed up the test-suite somehow so CI will be able to give us a much faster feedback?

**Comment by kayhayen** [comment]
@brupelo That is actually an excellent idea.

Obviously only some kinds of tests lend themselves to that idea. Some test program exitcodes, but others just check different kinds of constructs. Effectively concatenating tests/basics/ tests into one should be doable. Compilation then ought to be faster.

Same goes for CPython test suites. Actually they, i.e. CPython upstream have a test runner for that loads them all, which might do that dynamically though, but a static one would be easy to create I suppose.

The amount of memory used would go up by a lot. And one small downside, which is not too relevant right now, if only one test would be affected by a code change, i.e. actually change stuff, then it would not matter, but now it does.

As for Travis, I think even if it only used "ccache", it would already become dramatically faster. At this point however, I think that cache has no means to survive. Maybe you could look into how people achieve that, must be possible, right? That alone will cut down compilation times for everything do did on your "wip" branch to near zero. And only actual codegen or optimization changes would have an impact.

Also, Travis suffers from not having "libnuitka" implemented a lot more, much like my Windows setup, just because of that. The compiled types will be most of the compilation time for "hello world" type of scipts, that most of the tests compiled there are.

For me I was looking at "clcache" recently, because the Windows tests have become too much to complete before many days now. I need to go over issues and search/replace with that name, because I used the wrong name in the past. That is of course not affecting Travis which doesn't even do Windows.

Also, use "./bin/check-nuitka-with-pylint" and have the PyLint from requirements-devel.txt installed or else you get false reports for PyLint regressions after those releases for Python3. That very often avoids Travis to find stuff in the first place, esp. with changes like you do in "wip" PR branch.

**Comment by kayhayen** [comment]
I am no longer sure this idea is all that good. The practical implication are pretty nasty. It will add a layer of indication, and I believe caching CPython output, and caching object files will cover most ground already, although as I am noticing, ccache is not fully effective yet, and might need more help, but that should be separate issues.
