### ISSUE TITLE
Nuitka doesn´t allow to compile __init__

### ISSUE THREAD

**Issue by aipatr** [Nuitka/Nuitka#1312]
I have a directory with few modules and an __init__ file where I import methods and classes from those modules. If I compile with Nuitka only the modules files ("as external modules" in the  documentation), everything works. If I try to compile the __init__ file additionally my software is not able to import the modules.
Could you help me with this problem? I really like the Nuitka tool

**Comment by kayhayen** [comment]
There is a description on how to compile packages in the User Manual. Compiling individual modules is wasteful. That said, if you compile the directory, and not the `__init__` file, it will create something that replaces the directory as a package. And then, in said directory, you can still import other extension modules.

But most likely you are doing what you are doing, because you do not realize that packages are best compiled as one thing.

**Comment by aipatr** [comment]
Hi, I would love to compile the directory but in the documentation it is not clear at all how to do this.
I see the following use cases:
Use Case 1 - Program compilation with all modules embedded
Use Case 2 - Extension Module compilation
Use Case 3 - Package compilation
Use Case 4 - Program Distribution
Maybe if you could point out how to do it, it would be helpful for anyone that is using Nuitka.

**Comment by aipatr** [comment]
Just for information the solution was with Package Compilation
python -m nuitka –module some_package –include-package=some_package
where some_package is the name of the directory containing all the py files.
Moreover execute the script outside of the directory.
