### ISSUE TITLE
LTO is limiting gcc/clang to -O2  on Windows, despite this being unnecessary

### ISSUE THREAD

**Issue by kamgha** [Nuitka/Nuitka#1333]
Nuitka 0.6.19rc5 (from source)
CPython 3.7.12 on Windows 7 SP1
GCC+MinGW64: 11.2.0 with MinGW64 master from mid december 2021

648387917b2bfc82c8614552e655cbf48dc40335 restored `-O3` flag for `--lto=no` but not for `--lto=yes` case which still uses `-O2`.

**Comment by kayhayen** [comment]
There was nothing to restore though, it was always `-O2`, but that is just wording. I agree it can be -O3 on Windows, because the optimization of static libpython is not happening.

So this will work I think:

```
        env.Append(LINKFLAGS=["-O3" if nuitka_python or win_target or not static_libpython else "-O2"])
```

In this scenario, Fedora and other weak Pythons are benefiting as well, Anaconda has static link library on Windows potentially, but it's pseudo, to the platform test is necessary for it.

**Comment by kayhayen** [comment]
Will be part of the next release, no need to break existing configurations, -O3 is still a significant change, which reminds me, I should factor in low memory mode.

**Comment by kayhayen** [comment]
I wonder if it's possible to mix `-O3` for `CCFLAGS` and `-O2` for link flags, and achieve something there as well.

**Comment by kayhayen** [comment]
This now part of the current pre-release and will be part of 0.6.19 which should arrive shortly.

**Comment by kayhayen** [comment]
Part of the 0.6.19 release I just made.
