### ISSUE TITLE
[Nuitka Commerical] Question about obfuscation

### ISSUE THREAD

**Issue by FuckingToasters** [Nuitka/Nuitka#1380]
Everything works fine so far, i do not own the Commerical Version but i am intressted in it therefore i want to know some important things that not were addressed in the docs.
I was wondering, if its possible to split the python sourcecode in different files and subfolders and then add a argument, that obfuscate them in the same way as the main file. The filestructure would look something like that:

```
main.py
drivers\
  chrome\
    chromedriver.exe
  firefox\
     geckodriver.exe
data\
  config.json
other_files\
  a.py
  b.py
  c.py
```

**Comment by kayhayen** [comment]
The `drivers` are like data files, and not covered by Nuitka at all, because for execution they need to be written to disk. The `data` file can be included in the main binary, unless of course outside programs or your users have to see it, then it can be done, but there is less of a point, but you may still want to do that.

And well, for `other_files`, well, imported files are of course included in your binary, and there is no python source code anymore, so delivering `.py` files makes no sense. 

If you are talking about some sort of plugin mechanism, that can work in one of two ways. These plugins can be compiled separately and loaded using proper standard methods, or they can be included in the binary and loaded with the same methods. In Nuitka itself, plugin directory is iterated over with `pkgutil.iter_modules`, 

Hope this addresses your question. That last part is actually independent of Nuitka commercial, and I will add an example with code snippets to the user manual. This is a typical problem, as many people tend to listdir, open().read() and exec to do this, which is just not only inferior code, but requires these files to be in the file system for no good reason.

**Comment by FuckingToasters** [comment]
> The `drivers` are like data files, and not covered by Nuitka at all, because for execution they need to be written to disk. The `data` file can be included in the main binary, unless of course outside programs or your users have to see it, then it can be done, but there is less of a point, but you may still want to do that.
> 
> And well, for `other_files`, well, imported files are of course included in your binary, and there is no python source code anymore, so delivering `.py` files makes no sense.
> 
> If you are talking about some sort of plugin mechanism, that can work in one of two ways. These plugins can be compiled separately and loaded using proper standard methods, or they can be included in the binary and loaded with the same methods. In Nuitka itself, plugin directory is iterated over with `pkgutil.iter_modules`,
> 
> Hope this addresses your question. That last part is actually independent of Nuitka commercial, and I will add an example with code snippets to the user manual. This is a typical problem, as many people tend to listdir, open().read() and exec to do this, which is just not only inferior code, but requires these files to be in the file system for no good reason.

I did not understood, what you meant with the second part in your response.
Lets take other_files/a.py as an example:

In the main file im able to import things, definied in a.py such as a class by using `from other_files.a import classname`
I hope, that this is something that Nuitka Commercial is able to do.

Binarys such as the drivers not need to be obfuscated. It make sense that they are written to disk and thats not what i meant.

**Comment by kayhayen** [comment]
Well, I was not assuming that you didn't know that Nuitka follows imports when asked to do so. From say 2000 modules, it will create a single binary no problem and needs no other compilation unless you have a very special use case, like e.g. these plugins that I mentioned.

That is not related to commercial or not. With `--standalone` and `--onefile` one of which you use for deployment, that is the default to follow and include imports.

**Comment by kayhayen** [comment]
I hope your questions are answered, create a new issue as needed.
