### ISSUE TITLE
Nuitka does not let os signals pass to python code

### ISSUE THREAD

**Issue by haptiq-darko** [Nuitka/Nuitka#1383]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version

```
0.6.18.2
Commercial: None
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\darko\AppData\Local\pypoetry\Cache\virtualenvs\cloudberrie-processor-zEAQEtpU-py3.9\Scripts\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

Installed with pip in virtual env.

* The specific PyPI names and versions

  > python -m pip freeze

https://pastebin.com/gfU3e0Gv

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

This works with python interpreter (3.97, e.g.)

```
import signal
import os


def signal_handler(sig, frame):
    print('You pressed Ctrl+C!')
    os._exit(1)


signal.signal(signal.SIGINT, signal_handler)


print('Press Ctrl+C')

while True:
    pass
```

However, nutika compiled version just hangs and does not react to `Ctrl+C`.

* Provide in your issue the Nuitka options used

```
--onefile --remove-output --prefer-source-code --assume-yes-for-downloads --enable-plugin=anti-bloat --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --plugin-enable=pylint-warnings --plugin-enable=pkg-resources --plugin-enable=numpy --windows-onefile-tempdir
```

* Note if this is a regression

This does not seem to work in any versions of Nuitka.

**Comment by kayhayen** [comment]
That's strange, there is even an automatic test for CTRL-C to work with onefile, but they become `KeyboardInterrupt` exceptions. Not sure if your loop at the end allows it to raise though, but it might not do it, that would be the bug then. The test works on at least Windows and on Linux, on macOS I think I have test environment issues. I will look into it.

**Comment by kayhayen** [comment]
Your Nuitka version reported is old. I honestly forgot if this was ever improved, can you retry with latest stable 0.6.19.3 ?

**Comment by haptiq-darko** [comment]
Thanks for the prompt answer. 

In our production, we use a version without the loop and it still does not work. The loop here is just for the convenience of the self-contained example.

I'll test the code with the newer version of Nuitka and report the results here.

**Comment by kayhayen** [comment]
Are you using with `--windows-disable-console` or not?

**Comment by d-00-b** [comment]
No we're not using that command.

**Comment by kayhayen** [comment]
I managed to reproduce it indeed and the automatic test says this, which explains why this went unnoticed. 

> Skipped, KeyboardInteruptTest.py (Testing cannot send KeyboardInterrupt on Windows yet).

It works in standalone mode, but somehow in onefile, I seem unable to get any signal through, although this is very roughly the same binary. I am checking if it's because of how it's started.

**Comment by kayhayen** [comment]
I found the solution already, seems an option that got added to launching the process had the opposite effect. The onefile bootstrap correctly handles CTRL-C by sending CTRL-C to the child process, but it was launched with a flag that disables signal handling explicitly, rather than detaching it only. I will shortly have this on factory branch.

**Comment by kayhayen** [comment]
This is currently on factory. I am very annoyed with myself that the automatic test was not implemented, even if it's a bit more difficult.

**Comment by kayhayen** [comment]
I remember now, why this cannot be tested, Windows will not allow sending a signal like that with `taskkill.exe` sideways, so it's not working to do that. So that CTRL-C is actually not very relevant to Windows Services and such. This is really only testable and possible to occur within the terminal if I am not mistaken.

In case you are a commercial user, make sure to consider https://nuitka.net/doc/commercial.html esp. if you operate your code in a Windows service environment.

**Comment by kayhayen** [comment]
@levi-boy For you information

**Comment by kayhayen** [comment]
Part of the 0.6.19.4 hotfix release I just made.

**Comment by haptiq-darko** [comment]
> Part of the 0.6.19.4 hotfix release I just made.

@kayhayen great! We'll test it out.
