### ISSUE TITLE
Is the comment here wrong?

### ISSUE THREAD

**Issue by xiaodeyue2** [Nuitka/Nuitka#1385]
OptionParsing.py

parser.add_option(
    "--module",
    action="store_false",
    dest="executable",
    default=True,
    help="""\
Create an extension module executable instead of a program. Defaults to off.""",
)

all versions， Is the comment here wrong?

**Comment by kayhayen** [comment]
The flag is called `executable` because, if I recall correctly, originally module was the default. And you had to say that you want an executable. However, most people want a binary. And those who want a module, in my experience, are more likely to find out than the others that do not know what it is. 

I cleaned the option, and make the wording match the use, and pushed that to factory. Never good when code is confusing to read: https://nuitka.net/doc/factory.html

I am closing it immediately due to lack of general relevance though.

**Comment by kayhayen** [comment]
This is part of the 0.7 release now.
