### ISSUE TITLE
Nuitka should be able to package extension modules that use extension modules and datafiles into standalone forms

### ISSUE THREAD

**Issue by sarahcrimi** [Nuitka/Nuitka#140]
Hello,
I created a Python script to turn on pins using the FT232H Adafruit Breakout. It uses import Adafruit_GPIO and import ADAFRUIT_GPIO.FT232H (non standard imports).
I  am getting the following errors when I try to package this python file with the command:
`python -m --standalone matlab_to_adafruit.py`

"Nuitka: WARNING:matlab_to_adafruit.py:5: Cannot find 'Adafruit_GPIO' as relative or absolute import"
"Nuitka: WARNING:matlab_to_adafruit.py:6: Cannot find 'Adafruit_GPIO-FT232H' as relative or absolute import"

There were additional packages that I had to use in Python to set this up. It is located here:
https://learn.adafruit.com/adafruit-ft232h-breakout/windows-setup

**Comment by kayhayen** [comment]
Hello Sarah,

good to see you report this. The warnings are telling you that Nuitka already knows that these imports will fail later on, should that code in your script ever get executed, which may not happen. Typically you are expected to know if that is the case or not.

Now when this happens, there is two possibilities. Your program will also have the same error, if you execute it in the same environment where you run Nuitka. BTW: You command hopefully was "python -m nuitka". Just remove the "-m nuitka" and the Nuitka options, does it also not work? Well, make it work. Only if it works, i.e. normal Python finds something, then it has a chance to be found in Nuitka compilation.

The the other options is a bug in Nuitka import location code. That is course always a possibility. But now that I look at it, something strikes me as odd, because "Adafruit_GPIO-FT232H" is not a module name at all, due to the "-" it will be illegal in Python code.

You didn't include the relevant lines 5 and 5 in your report. I would very much like to see it, because that looks most definitely like a Nuitka bug, something must be going on. It should never attempt to find such a name, because it would be illegal, except these were "__import__()" calls that it predicted at run time, and even then it would be strange. If you can, attach the whole file matlab_to_adafruit.py

Thanks for your report!

**Comment by sarahcrimi** [comment]
Hello,
I am attaching the file. I do get two red marks in the python code that say:
No module named Adafruit_GPIO 
No module named Adafruit_GPIO.FT232H
even though the code runs and does what it is supposed to. 

Here is the file:
[matlab_to_adafruit.zip](https://github.com/kayhayen/Nuitka/files/2393306/matlab_to_adafruit.zip)
Now that I have packaged the code, what do I do to use it on deployment machine?

Thanks,
Sarah C.

**Comment by kayhayen** [comment]
As for the "-" in the message, I now think you might have not used copy&paste, but typed it something you saw, and Nuitka says "." and you write "-" ? Is that possible?

As for it also being red in Python,  I assume you are speaking of something like Eclipse, a Python IDE of some sort, giving the same complaint. It might be using a different Python environment.

I checked the code, and would give ImportError if the module is not found, no way around it. Can you explain to me, how you execute it, from the command line or otherwise? And which command precisely, then I will be less confused. :-)

**Comment by sarahcrimi** [comment]
Yes. I did not use copy and paste. That was an accident. I use Pycharm to view my Python files, but yes, I was speaking of the complaint. The way that I utilize this code is my calling definitions from MATLAB. 
In MATLAB, I use:  testmat2 = py.importlib.import_module('matlab_to_adafruit');
Then I call the function definitions like this from MATLAB:
       %Clear then ten pins to be used and the array switches
        testmat2.cleartwopins(int32(5))

**Comment by kayhayen** [comment]
Hello Sarah,

Matlab embeds a Python and will provide an environment to the Python code. First of all, you need to compile an extension module to use it in Matlab. Use the --module option of Nuitka instead of standalone, that is going to give you a ".so" (Linux) or ".pyd" (Windows) file. That can be loaded in Python.

This can be made to --include-module and --include-package the AdaFruit stuff. However, deployment is not really what Nuitka does for extension modules. For standalone binaries, yes, but for extension modules, if AdaFruit needs data files, or loads or contains other extension modules, there is rather complex instructions to achieve that.

I previously mentioned to @brupelo how this works somewhat, we had numpy as an example, and it can be done, and Nuitka could even do it, but is work not yet done. But you could do it manually. But I have to admit, if you are not tech savy, it might not make you happy. This is not an out of the box experience, Nuitka is not designed for deploying extension modules yet. One day it will be, but not now.

**Comment by sarahcrimi** [comment]
Thanks so much for your thorough comments and help :-) I will try to find another way to do it. 
~Sarah

**Comment by kayhayen** [comment]
Hello Sarah,

assuming you want to find a solution outside of Nuitka. I am changing this to describe the missing feature, so one day you will know when this is actually implemented, but don't hold your breath for it.

Sorry,
Kay

**Comment by brupelo** [comment]
@sarahcrimi Sarah, hello, one fast remark here. Don't get discouraged about this one, my guts tell me right now this should be already possible to achieve but as Kay already explained to you, you'd need to be a bit tech savy about nuitka and python to understand how you could come up with a working extension module ready to be used by matlab directly. Said otherwise, as Kay already explained, right now this won't work out of the box so unfortunately it'd need a little bit of manual craftwork.

That doesn't mean the issue you've opened is bad, in fact I do think it's a quite cool issue. It's really nice to see people posting these type of "non-standard" issues... and if fact If I had the hardware and matlab over here I'd definitely help you out. Unfortunately I don't :) , last time I've played with matlab was like... ~10years ago? I don't even recall matlab supported python at that time (or maybe it did, dunno...). 

What I'm trying to say is, please keep on posting these type of cool Issues/use-cases, at the end of the day the whole Nuitka community will benefit from it in the long-term ;)

So yeah, suming up, thanks for your report!

B.

**Comment by jafd** [comment]
I'm not sure if this issue is the right one for my problem, but it's the only one mentioning package data and standalone at all.

For a tool I'm developing, I'm trying to compile different things with Nuitka. I've chosen the https://github.com/dbcli/pgcli as an exercise. What I do is:
* create a virtualenv, install Nuitka, pgcli into it;
* do `python3 -m nuitka --standalone --include-package=pygments.styles --include-package=pygments.lexers --include-package=pygments.formatters $(which pgcli)`
* try to launch `./pgcli.dist/pgcli -d template1` (that database should be available on a default install of PostgreSQL, in case you want to reproduce this)

Expected: pgcli is executed and I get a nice prompt.

Actual:
```
$ ./pgcli.dist/pgcli 
.../pgcli.dist/psycopg2/__init__.py:139: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Traceback (most recent call last):
  File ".../pgcli.dist/pgcli", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/home/jafd/git/pgcli.dist/pgcli/main.py", line 52, in <module pgcli.main>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File ".../pgcli.dist/pgcli/pgcompleter.py", line 18, in <module pgcli.pgcompleter>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File ".../pgcli.dist/pgcli/packages/pgliterals/main.py", line 7, in <module pgcli.packages.pgliterals.main>
NotADirectoryError: [Errno 20] Not a directory: '.../pgcli.dist/pgcli/packages/pgliterals/pgliterals.json'
```

Bummer! The binary name is the same as that of the package in which data resides, and in standalone mode, Nuitka won't allow me to override the binary file name. Here's a legit case when it might be actually useful.

To work around it, I do this:

```
cd pgcli.dist
mv pgcli pgcli.exe   # Burn the heretic! ;-)
mkdir -p pgcli/packages/pgliterals
cp $MY_SITE_PACKAGES/pgcli/packages/pgliterals/pgliterals.json pgcli/packages/pgliterals/
```

I try executing again, and now it works!

So, to compile an _arbitrary_ Python program in standalone mode, I'd need to
* rename the binary, just in case it needs package named the same as itself (but I'd really like to be able to override the output executable name!)
* walk through all packages used by the program (I guess this can be done in a user plugin, right?), and stash anything that's not a Python file (and not something setuptools/distutils generate) in a similar directory structure in the `dist` directory
* keep wondering what else might break...

**Comment by kayhayen** [comment]
Nuitka has gained support for setuptools in the latest release, and you can now easily create wheels, which will have the data files.

Consider this: https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels

Nuitka Commercial allows embedding of data files during compilation, that works for modules too and then these are not on disk, that may not be what you want, but it could also solve the problem for some:

https://nuitka.net/pages/commercial.html
