### ISSUE TITLE
ImportError: The 'jaraco' package is required when using setuptools 60.7

### ISSUE THREAD

**Issue by jtran** [Nuitka/Nuitka#1406]
Running the binary executable results in the import error.

It works using `setuptools` 60.6.0.  I get the error when using `setuptools` 60.7.0.

Offending line:

```python
from pkg_resources import parse_version
```

Relevant part of the backtrace:

```
    File "/app/my-app/pkg_resources/__init__.py", line 74, in <module>
    File "/app/my-app/pkg_resources/extern/__init__.py", line 52, in create_module
    File "/app/my-app/pkg_resources/extern/__init__.py", line 44, in load_module
  ImportError: The 'jaraco' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
```

Related: https://github.com/pyinstaller/pyinstaller/issues/6564

### Environment

- Nuitka `--version`
  ```
  0.6.19.3
  Commercial: None
  Python: 3.9.9 (main, Jan 28 2022, 01:01:20) 
  Flavor: Unknown
  Executable: /opt/venv/bin/python
  OS: Linux
  Arch: x86_64
  ```
- Debian 10 buster

Built Python from source.  Installed Nuitka with pip.  Used virtualenv.

Nuitka Options: `--standalone --python-flag=no_site --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --lto=yes`

**Comment by kdumontnu** [comment]
Possibly related, jaraco was recently [vendored](https://github.com/pypa/setuptools/pull/3061) in the latest release. Not sure why this would break nuitka though.

**Comment by kayhayen** [comment]
Puh, this vendoring non-sense, yes definitely related and causing it.

**Comment by kayhayen** [comment]
Also, under the assumption that `pkg_resources` is obsolete and will never change, the parsing of what is vendored was done against the source code, so that is now broken too. I am replacing it with the hard-coded list, under the assumption that it will only grow and that it being too big is not an issue.

This has created however the desire, to just ask the optimized module, for the global value `names`. It should have that, certainly, and that would be a smooth thing, it would kill however the ability to hotfix it. So I might go with hard-coding now, and then add the ability to look this up from the module for plugins to use and replace the hard coded list with the constant value there. The alternative would be to ask the module with a forked process, which we do for other plugins, but that seems wasteful.

**Comment by cattieinthere** [comment]
I have this very same problem. When will this be fixed?

**Comment by kayhayen** [comment]
This is part of 0.6.19.6 hotfix release.

**Comment by cattieinthere** [comment]
> This is part of 0.6.19.6 hotfix release.

how can I apply the hotfix?

**Comment by kayhayen** [comment]
You could start by install the Nuitka version 0.6.19.6

**Comment by cattieinthere** [comment]
Yeah, sorry. And thank you!

**Comment by VijiKK** [comment]
Just like to share with this group, I was also getting the 'jaraco' package required error. 

Giving correct path to site_packages solved the issues for me. Initially I was giving site-packages path from my local user environment. Even though with multiple --hidden-import the exe was kept on failing with error "Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!" and was looking for jaraco package. Then changed to global site-packages path, build the package again and it worked. Following is the command for reference

pyinstaller --exclude-module PyQt5 -p dataLoader_cy.py --hidden-import dataLoader_cy -p C:\ProgramData\Anaconda3\Lib\site-packages --hidden-import=torchvision --hidden-import=numpy --hidden-import=pkg_resources.py2_warn --hidden-import=packaging --hidden-import=pkg_resources --hidden-import=packaging.version --hidden-import=packaging.specifiers --hidden-import=packaging.requirements --hidden-import=pkg_resources._vendor.jaraco --onefile main.py
