### ISSUE TITLE
Switching xz for gzip in Linux standalone builds

### ISSUE THREAD

**Issue by squidink7** [Nuitka/Nuitka#1422]
In my testing I have found extracting and then repackaging using my own appimagetool options on an app compiled by Nuitka switching the default xz compressed version was 104MB while the gzip compressed one was 109MB, yet it launched in around 3 seconds compared to the 9.5 of the xz compression.

I can make a pull request switching the algorithm if everyone else agrees, however I wanted to ask here first if anyone had any objections or concerns with using gzip by default or wanted to propose alternate ideas.

OS: Linux
Nuitka Version: develop/main

**Comment by kayhayen** [comment]
You can also use `--onefile-temp-dir` if you are size conscious, that could be even better, because using `zstd` should decompress potentially faster. 

I agree that `xz` looks bad there. Seems AppImage doesn't support `zstd` which is sad. I don't mind if you make a PR with a check on `Options.isExperimental("appimage-gzip")` such that we can then compare this easily. With current develop, I would hope your distribution to shrink a bit more. It removes a lot of the offenders, esp. on Linux.

**Comment by squidink7** [comment]
> Seems AppImage doesn't support zstd which is sad

looks like it's almost added.... and has been in that state for the last few years. Might want to see where that's up to later
https://github.com/AppImage/AppImageKit/issues/478

On the topic of adding this, would it be preferable to (when the options flag is set) specify gzip for compression or leave it out and let appimagetool decide? (defaults to gzip as of now)

**Comment by kayhayen** [comment]
Is `gzip` the faster one or `xz`. I probably misunderstood your initial statement?

And yes, I saw it, regarding `zstd`, but you have to be aware, that by requiring a newer kernel, you limit the platforms it's running on. Many systems will just not be able to run the binary. Which is probably why it's not implemented yet. Since the git commit is from 2017, (?) enterprise distribution based stuff can probably not run it. Kind of kills the point of standalone binary.

**Comment by squidink7** [comment]
gzip is the faster one, and is the default for appimagetool. Nuitka specifically overrides this and passes the --comp xz argument to use xz compression, and this issue/potential PR would add a flag to switch back the gzip. I was wondering if we should do that by letting appimagetool decide by not specifying which will default to gzip, or specifying it which will mean any future updates to appimagetool that change the default won't apply here.

Indeed requiring a new kernel wouldn't be ideal, however for some apps that don't target older distributions having it as an option similar to how xz is treated now would be nice.

**Comment by kayhayen** [comment]
Ah ok, I meant to compare the two, I need to try and recall if there was some thought put into that default. It's probably the size argument. Exposing extra appimage arguments could be a general idea. But to be honest, I am not sure if it's worth the effort, I have e.g. had issues building it inside containers due to lack of fuse kernel support. 

As of recently, Nuitka can compress on all Python versions with `zstd` when using the bootstrap, with the option I mentioned. Once it gains some sort of caching for the uncompressed file stage, that could be superior, but it's not there yet.

You are welcome to make a PR that does allow the switching, default value can be `gzip`, if it is so dramatically faster. But it may also come to a point, where I will give up on or go deep with AppImage, that is not yet decided.

**Comment by kayhayen** [comment]
Of couse I would welcome for you to actually make those comparisons with your test case.

**Comment by squidink7** [comment]
Just made a PR #1424, although still very much a work in progress.
This is my first (ish) PR to a project (and first time poking around Nuitka's codebase) so I apologise if it's not up to scratch, and welcome any criticism/feedback.

**Comment by kayhayen** [comment]
You are welcome, I posted instructions for a rebase, unfortunately the 0.7rc develop releases were a bad timing, I was rewriting history recently. Let me know when it's finished from your side.

**Comment by kayhayen** [comment]
I consider this done, very good job. If you  find the time, please report timing comparisons for your case, using the new option and then `--onefile-tempdir`. Once it has caching, i.e. after first run, there will be an undeleted cache folder, that gets reused, I imagine though that using AppDir might not have all that much benefit anymore. And I would be curious how it fares for you today even with the deleting done.

**Comment by squidink7** [comment]
Thank you so much for your help! I tried both the gzipped AppImage and the zstd executable, and while neither of them launched due to a missing multiprocessing library (I assume some other bug in the develop branch, might add an issue later if I can't find one already) The zstd executable came out ahead with 730 milliseconds start-to-crash, the AppImage took 830. These numbers stayed relatively consistent after a few consecutive launches. The zstd file was much better compressed as well, at 64MB compared to 108 for the AppImage. As much as it pains me to say it looks like this patch is made already obsolete :sweat_smile:
Anyway, if you need any more info let me know! but I'll close this for now seeing as the PR has been merged.
Thanks again!

**Comment by squidink7** [comment]
Ok, I think it may have just been one of my modules needing an update, as it seems to be working again now.

**Comment by kayhayen** [comment]
This is part of the 0.7 release now.
