### ISSUE TITLE
Using options "--include-package" and/or "--include-module" override all other recursion options.

### ISSUE THREAD

**Issue by AnythingTechPro** [Nuitka/Nuitka#145]
I noticed by specifying packages and/or modules, this overrides all other recursion options. It may be better that it recurse automatically descending into imports while still specifying "--include-package" and/or "--include-module" options...

**Comment by kayhayen** [comment]
I am failing at guessing what you mean here. Example?

**Comment by AnythingTechPro** [comment]
For example, ```nuitka --standalone --recurse-all --include-package some_package some_module.py``` this will build the main module but will not automatically descend into imported modules but will instead include the package ```some_package```

**Comment by kayhayen** [comment]
When you used `--standalone`, this implies `--recurse-all`, which I think is stated in the help output, the code just sets the option to true.

I agree that it must include the package. I don't think it does change any of the behavior for other things.

If the imports in some_module.py were in the standard library, you would have to enable that with "--recurse-stdlib", that is not currently done by default yet. Otherwise I need a concrete example to discuss this.

**Comment by kayhayen** [comment]
Was my last response sufficient?

**Comment by AnythingTechPro** [comment]
I ran a few more tests using the "--include-package" argument, it seems that it does not recurse imports within any modules outside the included package and outside the Python included library. For example my directory structure:

* TestPackage2
  - __init__.py
  - TestModule.py
  - TestModule2.py

* TestPackage
  - __init__.py
  - TestModule.py
  - TestModule2.py

- ExampleModule.py - ```python
from TestPackage2 import TestModule
```
- Main.py

"TestPackage2" is not recursed to therefor it is not included in the executable, however TestPackage is included because it's explicitly included using the option "--include-package"... I think that including packages and/or maybe modules overrides the "--recurse-all" option?

**Comment by kayhayen** [comment]
Recursion, or in 0.6 it's called follow imports happens when it's enabled in an option or in standalone mode, where it is the default.

The --include-module and --include-package override this indeed and make it so that a specific module or an entire namespace must be included regardless of a visible import or not.

Does this answer your question?

**Comment by AnythingTechPro** [comment]
Seems so yeah. Thanks.
