### ISSUE TITLE
regression nuitka >= 0.6.19, incorrect array length saved

### ISSUE THREAD

**Issue by devkral** [Nuitka/Nuitka#1460]
# What

Referenced arrays lose the information how many items they contain and return the wrong length.

I abstracted from my code a simple example for this problem

# Environment

- Nuitka >= 0.6.19 (here is the regression introduced)
- simple archlinux environment (but also python docker images)
- python 3.9&3.10 tested

# Reproduce
- compile the code with build.sh
- compare the output of test.py with test.bin

Example:
```sh
./test.bin a b c
# returns: ['a'] ['b', 'c'] ['a', 'b', 'c'] 0 0 3
./test.py a b c
# returns correctly: ['a'] ['b', 'c'] ['a', 'b', 'c'] 1 2 3
```

Result:
the length of foo3 is set correctly but foo2 and foo are zero length even they contain items

Scripts:
build.sh
```sh
#! /bin/sh

nuitka3 --remove-output --python-flag=noasserts --warn-implicit-exceptions --warn-unusual-code test.py

```
test.py

```python3
#! /usr/bin/python3

import sys


def main():
    foo = []
    foo2 = []
    foo3 = []
    for f in sys.argv[1:]:
        if "a" in f:
            toextend = foo
        else:
            toextend = foo2
        toextend.append(f)
        foo3.append(f)
    print(foo, foo2, foo3, len(foo), len(foo2), len(foo3))


if __name__ == "__main__":
    main()

```

**Comment by devkral** [comment]
by bissecting I found the bad commit:
```
commit 737b2d6a05b300b4842ce308e3cc7e4124657692
Author: Kay Hayen <kay.hayen@gmail.com>
Date:   Sun Dec 5 13:02:36 2021 +0100

    Optimization: Recognize unused loop traces and remove them
```

**Comment by devkral** [comment]
```patch
diff --git a/nuitka/nodes/LoopNodes.py b/nuitka/nodes/LoopNodes.py
index 94a498052..3ed1b565f 100644
--- a/nuitka/nodes/LoopNodes.py
+++ b/nuitka/nodes/LoopNodes.py
@@ -250,12 +250,7 @@ class StatementLoop(StatementChildHavingBase):
                 )
 
                 # Only if the variable is re-entering the loop, annotate that.
-                if not loop_resume_traces or (
-                    len(loop_resume_traces) == 1
-                    and loop_entry_trace.compareValueTrace(
-                        next(iter(loop_resume_traces))
-                    )
-                ):
+                if not loop_resume_traces:
                     # Remove the variable, need not consider it
                     # ever again.
                     del self.loop_resume[loop_variable]
```

fixes the problem

**Comment by kayhayen** [comment]
Thanks for the effort, so this must be a bug in `compareValueTrace`. Very good report.

**Comment by kayhayen** [comment]
I shrunk the test case further to this:

```
#! /usr/bin/python3

def main(argv):
    foo = []

    for f in argv:
        if "a" in f:
            toextend = foo
        toextend.append(f)

    print(len(foo))


if __name__ == "__main__":
    main("a")
```

**Comment by kayhayen** [comment]
This tells us

> Nuitka-Optimization:INFO: Mini.py:3 : var_usage : Loop variable 'foo' usage ceased.

The aliasing that happens there, apparently, is not recognized as a usage. I think the commit you bisected, is just that, because previously unused loop variables were kept as that for no good reason, which may have prevented the usage.

The aliasing of a mutable value if not traced currently as such, but I think it should mark a value as escaped, and I think that ought to survive the loop, i.e. there should be a loop variable trace that is only escaped. Need to check what happens there.

**Comment by kayhayen** [comment]
Turns out, the assignment to a variable from a variable, didn't mark the variable as escaped. Right now this is needed. In the future, we could check if its trace itself is escaping of modifying, but with that, this very important corruption bug is fixed.

It's a bit said that it took so long to get to it. Sorry for the delay to all. I don't do hotfixes for 0.7 anymore, but I wanted this to be resolved for 0.8 release, which is now a true statement apparently, still undergoing internal CI before I publish this fix.

**Comment by kayhayen** [comment]
Moved to 0.8, fixed on develop for a while already.

**Comment by kayhayen** [comment]
Part of 0.8 release that I just made.
