### ISSUE TITLE
RuntimeError: No suitable plugin registered for imread when using skimage.io.imread

### ISSUE THREAD

**Issue by sooraj-if** [Nuitka/Nuitka#1468]
- Nuitka version:
```
0.7.3
Commercial: None
Python: 3.10.2 | packaged by conda-forge | (main, Mar  8 2022, 15:47:33) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\sooraj.a\Anaconda3\envs\testenv\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
- Installed Nuitka and Python using pip inside an anaconda environment.
- environment setup:
```
conda create --name testenv
conda activate testenv
conda install pip
pip install scikit-image
pip install nuitka
```
- My code is in main.py which looks like this:
```
from skimage import io
img = io.imread(r"C:\Users\sooraj.a\Pictures\2b_input.png") # please replace with path to any image in your system
print(img)
```
- running main.py should output a 2d array that looks something like this:
```
[[161 135 139 ... 168 145 147]
 [144 146 134 ... 160 174 154]
 [124 164 142 ... 153 160 143]
 ...
 [180 176 184 ... 153 130 149]
 [171 184 167 ... 125 129 153]
 [178 185 177 ... 154 154 146]]
```
- I compile the distributable by running the following Nuitka command:
`nuitka --standalone --show-progress --enable-plugin=numpy .\main.py`

- when I run main.exe I get:
```
  File "C:\Users\sooraj.a\WORK_S~1\TESTSK~1\MAIN~1.DIS\main.py", line 2, in <module>
  File "C:\Users\sooraj.a\WORK_S~1\TESTSK~1\MAIN~1.DIS\skimage\io\_io.py", line 53, in imread
  File "C:\Users\sooraj.a\WORK_S~1\TESTSK~1\MAIN~1.DIS\skimage\io\manage_plugins.py", line 194, in call_plugin
RuntimeError: No suitable plugin registered for imread.

You may load I/O plugins with the `skimage.io.use_plugin` command.  A list of all available plugins are shown in the `skimage.io` docstring.
```

**Comment by kayhayen** [comment]
In my Python install, it gives this as the available plugins.

```
skimage.io.manage_plugins.available_plugins
{'pil': ['imread', 'imsave', 'imread_collection'], 
 'matplotlib': ['imshow', 'imread', 'imshow_collection', 'imread_collection'], 
 'tifffile': ['imread', 'imsave', 'imread_collection'], 
 'qt': ['imshow', 'imsave', 'imread', 'imread_collection'], 
 'simpleitk': ['imread', 'imsave', 'imread_collection'], 
 'gdal': ['imread', 'imread_collection'], 
 'gtk': ['imshow'], 'fits': ['imread', 'imread_collection'], 
 'imageio': ['imread', 'imsave', 'imread_collection'], 
 'imread': ['imread', 'imsave', 'imread_collection']}
```

The scan uses `config_files = glob(os.path.join(pd, '_plugins', '*.ini'))` to find the plugins, but the dictionary above could be compile time detected and potentially be trimmed, as some of these will raise `ImportError` because of stuff not installed.

It might be necessary to also preserve `skimage.io.manage_plugins.plugin_meta_data` value, then we can not scan at all, removing the need for INI files.

I would say, it would be super sweet, if there was a `skimage` plugin, that offered to select by hand from the list of surviving plugins, as obviously including all these things will be very wasteful, but they more or less could be done with --nofollow style options too, forcing to override the plugin decision to include the plugin.

I will check what I can up with, the first goal of course being to become compatible. A minimal virtualenv will as usual be the best way to have minimal dependencies pulled in.

**Comment by KevinRodriguez777** [comment]
This works fine nowadays.
