### ISSUE TITLE
Question: Does Nuitka do local imports? 

### ISSUE THREAD

**Issue by BenTearzz** [Nuitka/Nuitka#147]
I'm not sure this is an issue or if this is just how Nuitka works. But in my script, I import 5 modules/scripts that are in the same directory. After compiling they aren't in the final .dist folder.

Is this where I'm supposed to use an --include-... command?

**Comment by kayhayen** [comment]
Python modules are not seen in the .dist folder, they occur as module.xx.c files in the .build folder only. 

From you speaking of .dist folder, I conclude this is for executable mode, standalone. For creating compiled extension modules in 0.6 or higher, following is not done by default. For creating standalone binaries, follow is done by default. For accelerated binaries, you get to specify with options.

The compiled modules are included in the main executable, so outside of the .build folder, is is more or less invisible what is contained. A report file is planned. Use --show-modules to be reported what is included during compilation.

The .dist folder is only there so it can contain DLLs, extension modules, and data files needed.

If you want to get really verbose output, use --explain-imports which produces rather bad output, that allows to debug why a module is imported or not. I think it is hidden in help because it has really rough output, although it should be comprehensible.

Yours,
Kay
