### ISSUE TITLE
Error on trapezoid integration with SciPy

### ISSUE THREAD

**Issue by 124C41p** [Nuitka/Nuitka#1478]
# What
After compiling a module which uses `scipy.integrate.trapz` in standalone mode, the resulting executable raises the following error:
> `TypeError: _copy_func.<locals>.<lambda>() got an unexpected keyword argument 'x'`

# Environment
* Nuitka 0.7.5
* Windows 10
* Python 3.10

# Reproduce - Variant 1
Install the requirements (pip freeze output)
> Nuitka==0.7.5
> numpy==1.22.3
> scipy==1.8.0

Create file `main.py` with the following content
> ```
> from scipy.integrate import trapz
> print(trapz([1,2], [3,4]))
> ```

Compile with Nuitka
> python -m nuitka --standalone --plugin-enable=numpy .\main.py

Run the executable
> .\main.dist\main.exe
> Output: `TypeError: _copy_func.<locals>.<lambda>() got an unexpected keyword argument 'x'`

# Reproduce - Variant 2
It seems that `scipy.integrate.trapz` is (more or less) a copy of `numpy.trapz`, and the bug is caused by the copying method used. You can produce a similar error message in the following way (which is very close to what scipy does, but it does not depend on numpy or scipy):

Install the requirements (pip freeze output)
> Nuitka==0.7.5

Create file `foo.py` with the following content
> ```
> def foo():
>    pass
> ```

Create file `main.py` with the following content
> ```
> from foo import foo as bar
> import functools
> import types
> 
> # copied as is from scipy.integrate._quadrature.py
> def _copy_func(f):
>     """Based on http://stackoverflow.com/a/6528148/190597 (Glenn Maynard)"""
>     g = types.FunctionType(f.__code__, f.__globals__, name=f.__name__,
>                            argdefs=f.__defaults__, closure=f.__closure__)
>     g = functools.update_wrapper(g, f)
>     g.__kwdefaults__ = f.__kwdefaults__
>     return g
>
> bar = _copy_func(bar)
>
> def foo():
>     return bar()
>
> foo()
> ```

Compile with Nuitka
> python -m nuitka --standalone .\main.py

Run the executable
> .\main.dist\main.exe
> Output: `SystemError: unknown opcode`

**Comment by kayhayen** [comment]
This was of copying function is assuming, the source is an uncompiled function, and is really an ugly way of doing these things, with remove it with anti-bloat, including this one:

```
scipy.integrate._quadrature:
  description: "remove useless function copying"
  change_function:
    "_copy_func": "'(lambda f: f)'"
```

That should be in the stable release too, so I don't know why that would happen. Actually the first trace is this: 

> Nuitka-Plugins:INFO: anti-bloat: Updated module 'scipy.integrate._quadrature' function '_copy_func'.

**Comment by kayhayen** [comment]
I strangely managed to reproduce this, after it reveals a few issues with current develop version, it seems. I don't see why the patched `copy_func` would not work, but this might be something severe indeed.

**Comment by kayhayen** [comment]
Ok, seems `lambda` replacements got broken roughly 4 months ago to produce a useless function body that returns the lambda, rather than taking the function body of the `lambda` as it once was. In most cases, this was harmless, as it is often only used to remove functions, but still keep them as callable that do nothing, but for this one, of course the return value actually matters.

This also affects Tensorflow in some versions at least, but that one seems to have issues in relevant versions anyway.

I guess this shows that the lack of test coverage for anti-bloat matters. This happened when I added allowance for `change_function` to also produce `def ... ` style values, which in hindsight was probably a bad idea anyway, and it's very complex now, you can provide return values, function body replacement via lambda, and full function definitions, that even replace only body too.

**Comment by kayhayen** [comment]
I think this has been fixed as part of a hotfix, but I forgot to attach the label, so this was never reported.
