### ISSUE TITLE
Nuitka using the clang-cl interface on Windows

### ISSUE THREAD

**Issue by Gustavo6046** [Nuitka/Nuitka#148]
## Pretextual Details

* Nuitka version: 0.5.33
* Platform: Win32 (of course), 64-bit
* Python: 3.7.0 (v3.7.01bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)], 32-bit

Nuitka was installed using **pip**.

## Prerequisite Contextual Details

I'm trying to compile some Python programs into slightly faster, compiled C++ versions, with the help of nuitka. Unfortunately, using `cl` (MSVC?) is too slow, heavy (it thoroughly, dangerously, slows the system down); in short, undesirable.

I've also attempted using `--clang`; however, it fails, since it assumes every compiler on Windows uses the `cl` CLI, but doesn't even use `clang-cl` accordingly to at least match the CLI.

## Solution

I propose that, whenver `--clang` is supplied, Nuitka checks whether

* the host Operating System is Win32;

* `clang-cl.exe` is available;

and, if both conditions are met, that it then uses `clang-cl` instead of `clang`, so that it isn't necessary to create a whole new interface just to map arguments to the clang format. This way, we can keep using the `cl` arguments.

**Comment by kayhayen** [comment]
The develop version, which is soon to be release as 0.6.0 has `clang-cl.exe` support if provided as `CC` environment variable, but for current stable it won't work. The compiler not found error message now says it, and it's in the User Manual then.

The checks you propose are not currently made. Neither does Nuitka find a `clang-cl.exe` in PATH, nor does the `--clang` force any preference over a potentially installed MSVC or MinGW64.

So this is very fresh but working for me at least. One thing I wasn't so sure about, is if pure LLVM is sufficient, or where the `windows.h` is taken from.

The idea is clearly to support LLVM and once it does, to benchmark the 3 C compilers for Windows to see if there are any differences.

Yours,
Kay

**Comment by kayhayen** [comment]
I have only used LLVM 6.0.1, the LLVM 7 release was made shorty after only, I expect it to work too, let me know if that is the case or not.

On the Nuitka download page, you will find how to install develop version via pip from git version I think.

I am looking into adding PATH based detection for 0.6.x down the line. Once it fully works, I am even thinking of deprecating/remove MinGW64, since LLVM is also a free compiler. And if it's faster than MSVC at program run time too, all the better.

**Comment by Gustavo6046** [comment]
Thank you.

Indeed, I believe PATH detection will work, or (if it's cluttered, too long, or otherwise), you might want to allow the user an option that overrides it with another string. You might also want to look if predefined paths exist (like `{OS_ROOT}/LLVM`, where OS_ROOT is `C:` on Windows and `/.` on Unix, or '{OS_BINDIR}/LLVM', where `OS_BINDIR` is `C:/ProgramFiles` on Windows and `/bin` on Unix, maybe some other common paths); and probably check whether they are _valid_ (i.e. contain a valid `clang` and - if on Windows - `clang-cl.exe` binary).

So far, I'll try fetching the development head, and see if it can use the `CC` environment variable when I `SET` it.

Thanks,
Gustavo

**Comment by Gustavo6046** [comment]
Additional, separate note:

as for the MinGW compiler, I believe you should not remove it (many people use it as their main C++ compiler, especially Code::Blocks users, the latter which come with MinGW by default); maybe deprecate it is a better solution, if at all.

**Comment by brupelo** [comment]
@Gustavo6046 I wouldn't say cl compilation is "slow", actually that compiler is pretty damm fast even when dealing with huge cpp blobs and gbs of cpp code, and if they live on SSD, crazy fast. On the other hand I do agree with you that using cl may become quite **heavy** and the system may become unresponsive when compiling many hundred mbs of c-11 code. 

In fact, I've already realized it doesn't matter how many parallel jobs you decide to spawn (1,2,4,8, ...), the cl spawned processes will try to eat as much cpu time as possible... and that's what's making the system unresponsive. 

For instance, let's assume you've a budget of 80% "free" cpu when run nuitka... 1cl process would try to use ~80%, 2cl processes ~40% each, 4cl proceses ~20% each and 8 processes ~10% each.  Those are rough numbers but yeah... overall it's annoying as the system will become unresponsive because this fact.

Unfortunately I haven't found any way (yet) to downcrease the thread priority of cl processes.... if you guys find something that could help, please share as this is quite interesting and having a responsive system while nuitka is compiling python code would be awesome.

**Comment by brupelo** [comment]
Maybe this one [https://stackoverflow.com/questions/4208/windows-equivalent-of-nice](https://stackoverflow.com/questions/4208/windows-equivalent-of-nice) could help?

**Comment by kayhayen** [comment]
I am most interested in hard data. How much CPU does every of the 3 compilers used spend on the subject, and how fast is the end result. In fact I am now going to finally measure it.

As for MinGW @Gustavo6046 there is a problem in that it's not MinGW64. And people will throw incompatible MinGW at Nuitka all the time, never reading the user manual about how that has nothing to do with bits.

As for hard data, on my Win64 box, with Python 2.7 and 64 bits:

MinGW64 0.172s best run
MSVC15 0.213s best run
LLVM6 0.207s best run
CPython 0.437s best run

I would say there is a clear winner, the distance is also larger for the average, MinGW64 binary achieves most often times better than best runs of the other 2. 

So in terms of actual run time performance, which is what Nuitka for me at least is all about, MSVC is the worst one. Relatively speaking, performance difference is quite stark. Got to check out LLVM7 because I read Firefox is switching to LLVM due to its faster performance with new release.

On Linux at least, clang-6 compiler of Debian stable beat the crap out of gcc-6.3, so I used that one for the updated performance of PyStone to 312% there (with 0.6.0 code). The speedup was also larger there, no idea why.

**Comment by kayhayen** [comment]
Also no improvement with latest MinGW based on gcc 8.1, in fact the 0.17s was not achieved, but 0.18s more often than before.

**Comment by kayhayen** [comment]
Also size of the accelerated binary speaks a clear language:

> du -sh pystone-*
> 296K    pystone-llvm6.exe
> 296K    pystone-llvm7.exe
> 208K    pystone-mingw64.exe
> 192K    pystone-mingw64_8.exe
> 340K    pystone-msvc15.exe

Only 2/3rd of the size for MinGW64 binaries vs. LLVM, and MSVC is even larger, almost twice as big. No wonder this is a thing. In a warm cache compilation of 4s overall there is no point in measuring differences for compile times. 

As previously stated, bigger binary needs not be worse, but often is a hint at quality of the C run time and/or generated code speed. It mirrors what I saw with execution times.

Maybe for 32 bits, MSVC is more optimized, and 64 bits was added, but not in a good way, I wouldn't be surprised about that. I don't know however. Maybe the MSVC options need more tuning, if even possible. I will try and automate this test somewhat in the future, but right now I feel that Nuitka ought to recommend using MinGW64 over MSVC for sure.

While surely LLVM support is coming, this kind of removes part of the point however.

Also, for LLVM it was quickest to go the "clang-cl.exe" route, but it is very possible, that using its C11 capabilities and pure C11 compilation instead going via C++03, which may not be needed for it, and might make it suffer performance. Emulating MSVC might come at a cost for generated code quality, e.g. for internal function calls following worse than necessary calling conventions, stuff like that.

So right now I will try and get "clang.exe" to work, just for fun, and silent hope it will then maybe outperform MinGW64.

But @Gustavo6046 you are right. Keeping MinGW64 for sure. The race between compilers is going to be fully on for years to come.  Even if one is now faster, the other might catch up and overtake the next release.

Yours,
Kay

**Comment by Gustavo6046** [comment]
I believe it is possible to pass [an argument](https://reviews.llvm.org/D6428) to `clang-cl`, but correct me if I'm wrong on this one (or misinterpreted the thread), I have not slept tonight. This might be relevant, and I believe might help.

**Comment by kayhayen** [comment]
@Gustavo6046 I think it's possible to get things to work, esp. if a WIndows SDK is at hand, but it's too much work, and only a suspect that it's better.

The current state, using MSVC and Clang hybrid is sort of OK for me now. I leave it to Scons to eventually implement it. Their clang tool however seems incomplete, or maybe I just failed to register Windows SDK as a tool. That should have rc.exe, mt.exe and so on. But then MSVC already does, so what would be the point of that.

And as it comes up frequently as a question, CMake, Ninja, I looked into those briefly, but I am not convinced I want to fight these things with all the details yet again. I doubt anybody will take this on in any near future. Certainly not me.

So for as long as I believe that MinGW64 is faster and better, I won't even care all that much. I will however look at compilation times for larger stuff, to tell if using "clang-cl.exe" for most compilations except a few to make sure MSVC still works, is something that can help my Buildbots get more work done.

Anyway, Clang on Windows seems somewhat off still. I might also have to clarify the User Manual that Clang works only with MSVC also installed.

**Comment by kayhayen** [comment]
So the hybrid stuff is now in a stable release. Anybody is welcome to provide instructions how Clang + Windows 10 SDK could be used to compile with pure Clang on Windows. I am keeping this open so people know it is of interest.

**Comment by kayhayen** [comment]
Ok, so I just tried it out, and it works as advertised, going to activate that for the next pre-release, getting us one step closer. So now only Windows tools are used from MSVC, but nothing really compiler-ish.

Binary sizes remain the same independent of linker, makes me think the LTO part doesn't come into play in MSVC compat mode.

Yours,
Kay

**Comment by kayhayen** [comment]
I did attempt to download the Windows SDK, but it refused to install, because I already have it. Very likely the Visual Studio 2017 pulled it in.

So I almost believe it should be as trivial as to find the correct Windows SDK path, and for that, I think Scons already got code, which looked to me outdated. However, checking registry paths can't be so hard at all. I saw all the binaries we will need, and a simple PATH should work. 

It would only be a matter of putting Scons into MSVC mode from LLVM and Windows SDK combination, then things will just work. No rocket science. I will try and describe it on TWN one week, and maybe there are takers.

**Comment by kayhayen** [comment]
So using that LLVM linker is part of the hotfix 0.6.0.1 too, because why not.

Only missing the Windows SDK stuff.

**Comment by Gustavo6046** [comment]
Thank you for your support.

A while ago, I've tried to make **scons** use `clang-cl` as well, though without much success. Recently, though, I found an interesting [Stack Overflow answer](https://stackoverflow.com/questions/6220444/issues-configuring-scons-to-use-posix-arguments-in-a-windows-command-prompt#6225736) that might be important.

> This way it will use the gcc toolset instead of the msvc one. If you only overwrite CC then all the flags
> are still MSVC style, while the compiler is really GNU. So the full SConstruct would be:
>
> ```
> import os
> path = [r'c:\compiler\GCC\i686\bin', '../../build/include']
> env = Environment(tools = ['gcc', 'g++', 'gnulink'],
>                   ENV = {'PATH' : path,'TEMP' : os.environ['TEMP']})
> env.Replace(CC = "i686-pc-elf-gcc")
> env.Program('hello.cpp')
> ```

An alternative would be for Nuitka to detect Clang (not `clang-cl`) on Windows (instead of any other compiler on Windows), and use Unix-like arguments (e.g. `-O` instead of `/O`).

**Comment by kayhayen** [comment]
Well, this seems to say that instead of `clang-cl.exe` one can use a `gcc` binary on Windows too, but that is not the missing part now that even the linker of Clang is used. Right now *only* `mt.exe` and `rc.exe` and probably another one I forgot are missing, nothing else really.

Using it with the more native (to Clang) `gcc` interface would certainly be good too. But I am somehow not so sure if it then will work with the MSVC style import lib that CPython provides. It definitely would have the advantage of not using the MSVC tool which will need to find something or be hacked to accept Clang as enough to offer its workings.

Surely can try this out easily. Most probably with --mingw and CC set, you are using as a MinGW64 and then if you go with 32 bits, you will quickly see if it's working. Replacing `env["mt"] `with `"mt"` and corresponding for `env["rc"]` and having them in PATH, and I bet it could be working.

Then try out 64 bits, and let me know, if the LIB migration is needed for Clang too. Could be guarded with a condition easily.

Yours,
Kay

**Comment by Gustavo6046** [comment]
I believe it would be simpler to detect whether we're on Windows, and whether the Windows SDK directory (Program Files?) exists. Optionally, we could use hash checks in some immutable files (like core DLLs) within the directory itself.

In the end, the issue is that SConstruct has to give the correct arguments to the Clang executable, which won't happen on Windows. I've tried to make it work with clang-cl as well.

**Comment by kayhayen** [comment]
I believe `clang-cl` itself and the linker is working just fine, I reported that before. It may not take full advantage of all abilities of Clang, but we can check that later. The issue is *only* with finding the Windows SDK, and it lives in the Windows registry of course. That is not rocket science and being done for the MSVC compilers already, it's more a matter of doing it.

**Comment by kayhayen** [comment]
Adding its bin dir via `PATH` ought to work, but I forgot if I really checked that, so the calls to `rc` and `gendef` should be working. The registry stuff would mostly be about automating that.

**Comment by ManPython** [comment]
1. There is LLVM 8 release. Can you do some comparison again?

2. Is this still actual that I must have MSVC for use LLVM Clang?

> File "E:\Python34\lib\site-packages\nuitka\build\SingleExe.scons", line 462, in createEnvironment
> Error, cannot locate suitable C compiler. You have the following options:
> 
> a) If a suitable Visual Studio version is installed, it will not be located
>    automatically, unless you install pywin32 for the Python installation
>    below "E:\PROGRAMY\SYSTEM\PROGRAMING\PYTHON\Python27".
> 
> b) To make it find Visual Studio without registry execute from Start Menu
>    the 'Visual Studio Command Prompt' or "vcvarsall.bat". That will add
>    Visual Studio to the "PATH". And it then will be detected.
> 
> c) Install MinGW64 to "C:\MinGW64" or "\MinGW", where then it is automatically
>    detected or add it to PATH before executing Nuitka. But be sure to pick the
>    proper variant (32/64 bits, your Python arch is 'x86_64'), or else cryptic er
> rors  will be shown.
> 
> **Normal MinGW will not work! MinGW64 does not mean 64 bits, just better
> Windows compatibility.
> Cygwin based gcc will not work.
> MSYS2 based gcc will not work.
> clang-cl will only work if MSVC already worked.**

3. Can we force in some easy way which compilator to use? Eg. by some vars --compilator-c-lang 
- then can be prepared some dedicated .bat's files
4. How you manage this in your enviorments?
-- I'm working on windows.
I was on idea to check do tests again on MVC aps in compilators to see how this looks now on nuitka.

**Comment by ManPython** [comment]
dam.. I ommited that we can use --clang 

..but.. it's not easy.. and simple.. 
I try simple print("hello")


-m nuitka --standalone --clang --output-dir=build_clang main.pyw
```
In file included from build_clang\main.build\module.__main__.c:19:
In file included from E:\Python36\lib\site-packages\nuitka\build\include\nuitka/prelude.h:43:
In file included from E:\Python36\include\Python.h:8:
E:\Python36\include/pyconfig.h:59:10: fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [build_clang\main.build\module.__main__.o] Error 1
In file included from build_clang\main.build\__constants.c:2:
In file included from E:\Python36\lib\site-packages\nuitka\build\include\nuitka/prelude.h:43:
In file included from E:\Python36\include\Python.h:8:
E:\Python36\include/pyconfig.h:59:10: fatal error: 'io.h' file not found
#include <io.h>
         ^~~~~~
1 error generated.
scons: *** [build_clang\main.build\__constants.o] Error 1
```
there is simple way to resolve this? Or in next steps are more.. ? : )

**Comment by kayhayen** [comment]
I think, LLVM may not include any of the standard include files. It sure does not do it for me.

So there is not going to be a `windows.h`, that I found something to be expected. But there not being an `io.h`, how is that supposed to work?

As for the LLVM 8, I had downloaded it, but not yet installed it. The last release made some progress in replacing `mt.exe` and some `rc.exe` usages, but not all. The `rc.exe` is still used to link a binary blob of the constant values and to add the icon. I think #226 can now be resolved, but icons are optional anyway, which leaves the usage for the constants blob, which stands to improve. I believe for modules, it creates a `.c` file with the content, and using the resources API, we can just directly attach the resources blob after the binary is created, and no need for `rc.exe`, and I think that the Python extension modules created in module mode, could get the same charm.

With these two improvements, Nuitka itself wouldn't use any Windows SDK binaries anymore (the Windows SDK is what actually is required, it just happens to be the case that MSVC installation contains one, and Scons has detection for it, so it's automatic to find it).

However, it may still need the include files from there for LLVM, which I think MinGW64 does not, which is strange and hopefully untrue. Got to web research a bit on how that is supposed to be done normally.

**Comment by kayhayen** [comment]
I am just testing the code that will avoid using `rc.exe` for the binary blob.

From my research, it may be that for LLVM the include files are taking by people from a MinGW64 installed in PATH. That is definitely not going to make things easier for users to install. Actually it's pretty crazy for requirements, esp. if MinGW64 turns out to be the faster compiler on Windows anyway, then what's the point if you have it already installed. Anyway, surely I am going to do it.

For now my focus is going to be to finish the resources work though. It would be very nice to be able to use resources with module mode too, and of course #226 should be low hanging fruit now. Not calling `rc.exe` can only make things faster for sure.

**Comment by ManPython** [comment]
I bothered earlier to LLVM team to observe this project and issue in case of usage in python.
Let this be inspiration to right managment of cordination in LLVM including the problems that we met here. Maybe some TODO list to changes can be useful in future to provide for LLVM in idea as bether usage this in nuitka.

Well.. this is IT.. we fighting with machines. I hate compilators.. : )
This same case about relations of compilators in GO lang (need old tdm64-gcc-5.1.0-2 that is comfy for go, and Msys for QT, then all QT need [10GB or something]). Not far with python, coz this same always need something like VCForPython, etc.). I miss old c++ borland solutions. 
When I decided to work in python i not expect that can be "soo easey" and "soo hard" (around production deployment, eg. as .exe ).
https://spectrum.ieee.org/view-from-the-valley/computing/hardware/david-patterson-says-its-time-for-new-computer-architectures-and-software-languages

**Comment by kayhayen** [comment]
@ManPython Now marvel in how Nuitka supports MSVC 2008 through 2017, MinGW64, LLVM with some help, against all kinds of Pythons from 2.6 to 3.7, it's doable. Sure, needed a trick here and there, but not exactly rocket science.

As for the header files, my theory was that they would be GPLed or so, but at least `windows.h` is in the public domain, so I don't know what is going on there.

**Comment by kayhayen** [comment]
So, I think `clang-cl.exe` is more or less designed to piggy back on a working `cl.exe` configuration, and `clang.exe` is usable to piggy back on a working `gcc.exe`.

**Comment by jayvdb** [comment]
I wonder if clang.exe support might avoid `cc1.exe`.  I have a common problem at https://github.com/Nuitka/Nuitka/issues/537 in that cc1.exe has a 1G or 2G memory limit.  https://www.google.com/search?q=mingw+cc1.exe+out+of+memory+65536+bytes shows it is a common problem.  This prevents compilation of bigger packages, especially `peewee`, `Pygments` &
`pyasn1-modules`.

**Comment by kayhayen** [comment]
@jayvdb it's not clear to me, if this is MinGW64 and 64 bits, is it? Because otherwise it would be simply a 2GB limit of the OS kicking in, hard to avoid. Some people use MinGW64 and 32 bits and there it would be expected at some point. If it's really  6t4 bit and memory, try to lower the job count, as bad as that feels.

I am initially only doing clang-cl for MSVC, because it's better in resulting performance than that, and more Free Software, but for gcc, this doesn't hold up.

**Comment by kayhayen** [comment]
So, `--clang` works to use `clangcl.exe`, and recent work has remove the usage of the `rc.exe` from Nuitka entirely, we handle all resource work now entirely in Nuitka itself. This was one of the prerequisites for using it with `gcc.exe` from MinGW64.

However, since I am at this time not convinced that clang is better than gcc on Windows for performance, and effectively you can use clang via MSVC installation, I do not intend to support using clang on top of MinGW64, so this is done from my side.

**Comment by kayhayen** [comment]
Actually, I see a way to do clang for gcc on Windows now, there is a download that includes `clang.exe`, so we could support it on Windows too: http://winlibs.com/

Integrating that could be very easy. I might have to open a new issue for that. Not sure when I get to implementing it, but it's naturally tempting as this is going to be what we require from users of gcc on Windows in the future anyway. Right now that is using the smaller download without clang though.

**Comment by jayvdb** [comment]
My Windows use case is cross-compiling on Wine using clang for distribution to normal Windows users.  i.e. being able to build distributables without any MS compiler, avoiding any click-through licenses and restrictions caused by that.

**Comment by kayhayen** [comment]
@jayvdb so that would then start working, for now the release is more important to me, but for that use case, gcc as downloaded by Nuitka should be fine already. I am speaking of changing that download to include clang when `--clang` is specified. As I previously said, it seems the clang on Windows needs either a working gcc or a working MSVC, or maybe only the Windows SDK, but that definitely is a click through thing, that I don't want to get into myself either.

**Comment by jayvdb** [comment]
my use case isnt a high priority even for me ;-)
I did generate a quite complicated binary for win,linux,osx a while ago, using a few hacks for the win cross-compile, and dont have a need to re-do it in the near-term.

**Comment by kayhayen** [comment]
Well, you know, "no click through" is aligned with free software only. I do not want to force people into using MSVC certainly, so I go to lengths with gcc to be supported. And generally, from clang I am hearing that scalability might be enhanced even if performance may not be. Obviously something I would like to test. In previous tests, I didn't use LTO on Windows yet, because MSVC didn't do it, it seems it now does, but it's not clear to me how much the clang-cl interface is behind the gcc interface driven clang. So curiosity is also a thing there.
