### ISSUE TITLE
Question: How to get rid of unnecessary libraries.

### ISSUE THREAD

**Issue by herokrat** [Nuitka/Nuitka#1497]
Hello,  I have a question. My project is simple Tkinter GUI exe with no extra packages and I noticed when using --standalone and --onefile options Nuitka packs libraries like "libcrypto-1_1.dll", "comctl32.dll", "libffi-7.dll", "libssl-1_1.dll" into my project. Is there a way not to use these libraries in my project?

Info:

0.7.6
Commercial: None
Python: 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
OS: Windows
Arch: x86_64
WindowsRelease: 10

I installed Nuitka by using pip.

Nuitka==0.7.6
zstandard==0.17.0

Nuitka options:
 python -m nuitka --standalone --enable-plugin=tk-inter  --disable-plugin=implicit-imports --windows-disable-console main.py

**Comment by kayhayen** [comment]
Using a virtualenv can help a lot, to not have them installed. You can always delete things you believe are not used from your Python installation, but you better make sure that the Python is still running it. There will be options coming to suppress inclusion of data files and DLL files, but they do not exist yet. Data files will come soon, DLLs after that.

Keeping the question open, because deletion is one way of doing it, suppressing will be another, but when it then doesn't work, you cannot test if that's a bug of Nuitka, so in a sense that's necessary at some point to decide that.

**Comment by herokrat** [comment]
I tried virtualenv, but the result is the same. Thanks for answer. Looking forward for new features.

**Comment by kenneth-ew** [comment]
Do you happen to know if files like "comctl32.dll" are allowed for redistribution by Microsoft ?

**Comment by kenneth-ew** [comment]
@kayhayen thanks. I have been trying to find a reference to "comctl32.dll" in the windows redist list (for example, https://docs.microsoft.com/en-us/legal/windows-sdk/redist ) and haven't found it. It seems it's not licensed for redistribution.

**Comment by kayhayen** [comment]
I think, this was from before Nuitka stopped including SxS libraries, and as such should be resolved.
