### ISSUE TITLE
Importing compiled module next to source package prefers source

### ISSUE THREAD

**Issue by Maxwell175** [Nuitka/Nuitka#1498]
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
```
0.7.6
Commercial: None
Python: 3.8.10 (default, Nov 26 2021, 20:14:08) 
Flavor: Debian Python
Executable: <path to venv>/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Neon (based on Ubuntu) 5.24
```

* How did you install Nuitka and Python

  Did you use pip, anaconda, deb, rpm, from source, git clone, then install into
  a virtualenv or not, this is very important usually.

In a venv: pip install nuitka

* The specific PyPI names and versions

  It should be taken from this output if there specific packages involved, e.g.
  `numpy`, you are expected to shorten this to the relevant ones.

  > python -m pip freeze

```
Nuitka==0.7.6
pkg_resources==0.0.0
```

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

```
mkdir test_module
echo "print('This is a compiled module')" > test_module/__init__.py
python -m nuitka --module test_module
echo "print('This is a source module')" > test_module/__init__.py
python -c 'import test_module'
```

Observe that the output displays "This is a source module".
Now, rename the source module and observe that the compiled module is now loaded.

```
mv test_module test_module_
python -c 'import test_module'
```

**Comment by kayhayen** [comment]
I must have misled you there, and indeed, if I then make a compilation that imports it, Nuitka too will ignore the extension module, due to its lower priority. That's something I changed at some point in recent months.

But for modules, not packages, that is not the case, I think. That is also, why we have `shallPreferSourcecodeOverExtensionModules()` fed from the command line to override this behavior.

So good citizen wheels can put the original source in the wheel and the extension module, and see the later used, but obviously when it comes to directories, that doesn't work, only for files. Oh so ugly.

And there is this when you use `--run`.

```
Nuitka:INFO: Launching 'test_module.cp39-win_amd64.pyd'.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Error, cannot launch extension module test_module, original package is in the way.
```

I added that at some point, because of confusion coming from not running what I want to.

Basically, I guess, we kind of wish that Python wasn't doing that, but it does? Nuitka is probably the only thing that creates package replacements.

**Comment by Maxwell175** [comment]
Yeah, it's unfortunate, but I doubt there is anything Nuitka can do about it really, so people are just stuck renaming the original packages. I mean if you want to be fancy you could either add a new path loader or inject something into the source `__init__.py` to check for the compiled module outside, but that can get dirty.

**Comment by kayhayen** [comment]
The bad thing really is that people will not notice it, and draw wrong conclusions. Makes sense to think of something there, but all ideas, like a user site module change e.g. are prone to problems by themselves. For me, the `--run` check is good enough, but people may not know. Potentially makes sense to warn people about the issue when finishing Nuitka compilation of the vulnerable case.

**Comment by Maxwell175** [comment]
Agreed. A warning at the end is all we can do for now really.

**Comment by kayhayen** [comment]
The warning is now on factory branch.

**Comment by kayhayen** [comment]
Part of the current pre-release. I noticed it fires during distutils test, maybe even normal during setuptools integration, where the original source will of course be deleted later, so we probably need a way to disable the warning or any warning now.

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
