### ISSUE TITLE
Package all standalone resources into a single file option

### ISSUE THREAD

**Issue by maaaaz** [Nuitka/Nuitka#16]
Hello @kayhayen,

Let me first greet you for that project who opens up new horizons, really.

I would like to bring an idea to improve it (at least, for my usages): could you propose an option to **pack all standalone resources into one single** file like the `--onefile` option for **pyinstaller** ? IMHO it's even more convenient for users to manipulate a single file than rather use entire folders.

Pyinstaller packs all resources into a single zip file (which is executable) and unzip them at runtime (check one of my compiled tools, for instance https://github.com/maaaaz/tibcopasswordrevealer) to see what it looks like).

Cheers!

**Comment by psutton00** [comment]
I don't think is as straight forward as packing resources into a zip. Using the standalone or portable flag gives you a dist folder with a compiled executable in it, alongside all DLLs required to run it. The idea being that you distribute the entire folder. I don't think creating some form of self-extracting archive instead of this folder is an elegant solution and it can be done outside of Nuitka using other tools (I wouldn't recommend it but IExpress).

I would however like to see an option to embed the DLLs that end up in the dist folder in the executable itself. I think this would be a great feature however sadly I'm not sure if developers are answering these requests. I really enjoy Nuitka and love the benefits, but shipping the dist folder to people can often lead to questions around trust, and there have been times where people have taken the exe out of the folder. Would be awesome to see this added.

If it helps, I've used this with great success in the past in Visual Studios and I believe C++ Builder have this feature built in. But I'm not sure how to include generated c++ source into such projects or if that's even possible:
https://github.com/Fody/Costura

**Comment by maaaaz** [comment]
I agree with you, my wish is to have only one standalone file: indeed the zip solution is not as a elegant as the DLL-embedded one.

**Comment by kayhayen** [comment]
On the mailing list, there was once a discussion. There is a library that py2exe uses, and that could also be integrated with Nuitka. I won't be doing that though.

**Comment by brupelo** [comment]
I don't see a lot of benefits about packaging the whole nuitka generated content in one single file, you can do that easily with some custom tool or using batch files so everything will be tidy up for the end-user... But, what it'd be really useful would be nuitka packaging just the minimal content for the projects, right now is adding more content (dlls) than necessary in certain projects, for instance pyqt projects. 

This has been already commented in #73 but it feels right to bring it up here as well, as this topic is quite popular (4 thumb ups in the opening section is quite a lot :))

**Comment by brupelo** [comment]
I think the idea of embedding shared libraries onto an executable is really a nasty/bad/ugly way to proceed here, period... For those one who like to hack around you can read more about it in this post [https://blog.kowalczyk.info/article/d7d08da8d2c643349463292a051293b5/embed-dll-in-an-exe.html](https://blog.kowalczyk.info/article/d7d08da8d2c643349463292a051293b5/embed-dll-in-an-exe.html). 

Of course, a different matter would be allowing to add more static code to the application if possible, ie: Embedding visual studio runtime library statically or maybe embedding CPython statically as that would allow the compiler global optimizations, that'd be cool.

What we all want at the end of the day is being able to ship nicely our software with little size over the internet, right? But embedding a bunch of shared libraries into an executable is definitely not a great idea for few reasons.

Let's say you got A) app1.exe + lib1.pyd + lib2.pyd = N bytes. If you embedded the whole thing into megaapp1.exe = N bytes, what'd be the benefit of it? Shipping a compressed form of either A) or B) would remain practically the same. 

I understand there is a real use-case to present the software properly to end-users, but... that should be responsability of providing a proper installer and adding proper shortcuts to the user, shouldn't? There is really nice existing software that already does that and I think these type of tasks should be out of scope of nuitka. Nuitka should be a python well-optimized compiler and shouldn't do extra stuff already done by package management software. Even more, if you ask me, I think the existing freezer shouldn't be nuitka's responsability although I see a point of giving that to the users to make nuitka more attractive. Even if that's not the real value of the product itself :)

Another example, consider:

 - A) app1.exe + lib1.pyd + lib2.pyd = Na bytes   <=> megaapp1.exe
 - B) app2.exe + lib1.pyd + lib2.pyd + lib3.pyd = Nb bytes <=> megaapp2.exe

Let's say you wanted to distribute both A and B, by distributing megaapp1/megaaapp2 you're shipping duplicated content... and the optimal way to ship both apps would be shipping app1.exe/app2.exe+{lib1.pyd,lib2.pyd, lib3.py} at once

Does it make sense? 

And don't get me wrong, I'm a huge geeky fan of as tiny as possible well-optimized standalone executables... but putting and wasting dev time on these tasks... would bring any benefit in the long term? I don't think so... 

If you ask me, I'd like to think more effort/time will be invested on much more interesting problems, for instance, optimizing further the generated c code and making it faster in all cases than vanilla python/pypy/... That'd be awesome and prove than nuitka is the best choice to help our lovely-but-slow dear python  :)

**Comment by brupelo** [comment]
@maaaaz , @psutton00 . Hello guys, If you don't mind... let me ask you this, let's hypothetically speaking I eventually decide to implement that feature you seem to be interested on, dll embedding into one single file, which I don't think it'd be really hard to code. What are the benefits you think this would have? 

First, let me fastly talk very fast about what that feature would imply:

 - In case you wanted to provide exe updates to your customers/community you'd have to force them to download few hundred of mbs over and over. And that fact would improve very little even when using exe compressors.
 - Uncompressing on memory/disk the whole stuff is really a crapy/nasty/ugly/intrusive thing to do, period. As a user I consider that not just intrusive but I think the software that does that has been poorly coded... even if dumping to temporary memory. Unless the reason is proper obfuscation/compression.
 - Would improve obfuscation of your software? Not the lightest bit, at some point the whole uncompressed code will be in memory ready to be used by reverse engineers. In fact, adding this feature and not warning properly to users would give this false sensation of being "safe".
 - Would it improve speed? On contrary, the unpacking adds a little overhead

And again, don't get me wrong, I'm a huge fan of standalone executables, even I love coding executables shipping my own startup runtime library to make the exes being as small as possible... but... in this particular case I don't see any real benefit other than having fun coding the packer/unpacker code.

I mean, if I wanted to ship 20 command line tools written in python and each one (~1mb per exe + 49mb of 3rdparty dlls)... would i have to ship 20mb + 980mb = 1Gb! plus decompressing... instead 20mb+49mb=69 (which is also quite a lot)? Nuts :)

But again, maybe I'm missing something here, so please, tell me so I can understand the rationale here, why do you think this would be a good feature worth considering? I don't get it

Thanks.

**Comment by kayhayen** [comment]
@brupelo There is no point is telling people to not want what they want, because they still are going to want it, until provided with a better alternative. So please do not discuss this issue in that way. Are you OK with me deleting the comments of yours, that I feel are distracting others from knowing that a solution is actually welcome?

For all I know, it's possible to package all in one and people do it. Clearly at least pyinstaller does it, and it makes life easy for deployment, surely. 

On the mailing list back then, concerns were raised, if this is something in scope of Nuitka, or if it is not to be a third party tool instead. Actually, if somebody were to look at how pyinstaller or py2exe do it, we might well find they are doing the same thing, or using the same library. If integration with Nuitka has any benefits other than convenience, I don't know yet, I would have to see the solution.

But like I said, one of the people who wants to have it, needs to create the PR and implement it in Nuitka, not necessary by implementing the loading of DLLs, which I understand is duplicating Windows functionality, but by using existing solutions. Feel free to go ahead if you are one of them, that is what the "help_needed" tag is for.

My hope is that this is actually only a matter of research, and not so much going to be a burden for actual Nuitka maintenance, with this being generic work, and that there could be an upstream responsible for problems if there are any.

**Comment by brupelo** [comment]
> @brupelo There is no point is telling people to not want what they want, because they still are going to want it, until provided with a better alternative. So please do not discuss this issue in that way. Are you OK with me deleting the comments of yours, that I feel are distracting others from knowing that a solution is actually welcome?

@kayhayen Mmm, maybe I expressed myself in the wrong way (although I don't see anything wrong on my previous comments, I'll re-read them again). Just to clarify, I will never order/ask people what to do, what to code or not and definitely what to ask or not, period! 

Plus, I code silly stuff all the time just for the [https://en.wikipedia.org/wiki/Art_for_art%27s_sake](https://en.wikipedia.org/wiki/Art_for_art%27s_sake), so my attitude about coding non-real-world useful stuff is rock solid :) . That said, I think in this case I was just giving my thoughts about the issue itself, and of course people can agree with me or not. It's not a bad thing explaining the disadvantages of some solution in particular cases, isnt? (even if it works for a very limited set of use-cases)

I like open discussions and in this case I was trying to understand the rationaly, that's why I asked them in a nice way (I think I did)... not only that, by understanding if the feature was useful or not I could consider to implement it myself and upload to upstream for people's benefit, dealing with PE/Packers/Unpackers is something I've got a bit of experience with in the first place.

What I definitely don't really like will be any kind of censorship attitude, If I haven't been unpolite or said anything out of scope... but of course, you're invited to point out if my comments won't favour nuitka to improve in certain way _and if I agree with your view I will prevent those type of comments to happen again_.

You need to think than writing comments like the ones I do isn't a 10s job and I've put quite a lot of effort writing them actually :) , so by just deleting them is like you're saying "I don't give a damm about what this guy has to say", which of course.... I wouldn't consider it a nice to do.

But again, let me repeat myself, telling me if certain attitude/comments are not good to improve Nuitka, please do so.

Does it make sense +/-?

**Comment by brupelo** [comment]
I remember I had tried this twitter utility couple of years ago called PEX and it was also implementing PEP441. Here's a nice video from one of the authors that explains the underlying [logic](https://www.youtube.com/watch?v=NmpnGhRwsu0&t=118s), it's actually quite simple stuff.

Not sure though whether that approach would allow you to load .pyd files though :/ 

Anyway, here's some links for those who want it to give it a shot to this feature (DISCLAIMER: windows stuff only):

 - https://github.com/sudachen/Molebox <-- abandoned, doesn't build properly on vs2010 so it needs a little bit of hacking, ie. build system is broken
 - [enigma protector](https://enigmaprotector.com/)  <-- commercial
 - [https://blog.kowalczyk.info/article/d7d08da8d2c643349463292a051293b5/embed-dll-in-an-exe.html](https://blog.kowalczyk.info/article/d7d08da8d2c643349463292a051293b5/embed-dll-in-an-exe.html)

**Comment by brupelo** [comment]
I've made a very fast test, which it's adding to a .zip file multiple .pyd files. Python3.6.x won't be able to load them, as expected... so I guess it can only load .pyc/.pyo/.py files from zip files, feels reasonable btw.

**Comment by golyalpha** [comment]
I think UPX could be a possible solution here. While PyInstaller is capable of packing files without it, most projects I've seen end up using UPX anyways because of it's performance.

**Comment by kayhayen** [comment]
Onefile is implemented for Nuitka and with Nuitka-commercial you can now even protect data files. https://nuitka.net/pages/commercial.html rendering this all obsolete.
