### ISSUE TITLE
Using nuitka to build wheels with setuptools.build_meta backend in pyproject.toml without changing code

### ISSUE THREAD

**Issue by markcampanelli** [Nuitka/Nuitka#1600]
I would like to use

```terminal
[build-system]
...
build-backend = "setuptools.build_meta"
```

in my Python package's `pyproject.toml`, but still be able to build wheels with nuitka analogously to the legacy `python setup.py bdist_nuitka` command. I tried using this `setuptools` backend with `build_with_nuitka=True` in the `setup.cfg`, but it seems to be ignored in PEP-517-compliant wheel-building commands such as `pip build .` (whereas `build-backend = "nuitka.distutils.Build"` does work with `pip build`).

I want to use only the `setuptools` backend because I also do "generic" builds without `nuitka`, and editing the `pyproject.toml` file in CI would screw up my automated version tracking with `setuptools_scm`.

```terminal
python -m nuitka --version
0.8.3
Commercial: None
Python: 3.9.7 (default, Sep 28 2021, 13:03:42) 
Flavor: pyenv
Executable: /home/campy/Documents/IMS/SolarPV/PVfit/venv/pvfit/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
```

**Comment by kayhayen** [comment]
I don't see how anything but `build-backend = "nuitka.distutils.Build"` could be made to use Nuitka without changing `build` to do what you want it to do. My understanding is that while it's compatible, it's not using its code, so there is nothing about that, and that is why the Nuitka `build` backend has to exist.

Now, of course since Nuitka build backend is merely a wrapper, with this being the build of the code:

```
class NuitkaBuildMetaBackend(setuptools.build_meta._BuildMetaBackend):
    def build_wheel(
        self, wheel_directory, config_settings=None, metadata_directory=None
    ):
        os.environ["NUITKA_TOML_FILE"] = os.path.join(os.getcwd(), "pyproject.toml")

        with suppress_known_deprecation():
            return self._build_with_temp_dir(
                ["bdist_nuitka"], ".whl", wheel_directory, config_settings
            )

```

We could consider a TOMP configuration, `build_with_nuitka` that defaults to `True` and that you could toggle, and then the above code could pass through, making it possible to deactivate Nuitka. That is kind of a missing feature. And well, then why not allow to provide configuration file overrides from environment variable(s), that would serve your wish to not modify things.

Right now I don't have the time to implement and test these things, so help or funding is wanted here, but I guess, I might eventually implement the disable trigger at least myself, seems cute for testing.

**Comment by kayhayen** [comment]
Right now, I don't see a way to switch the build backend, or to influence a build backend via command line with the `build` package in place. Since build doesn't allow command line arguments, or does it, we are kind of stuck there, are we not.
