### ISSUE TITLE
Windows: Unable to install with MSI files

### ISSUE THREAD

**Issue by jlgarnier** [Nuitka/Nuitka#1601]
Dear all,

I wanted to give a try to Nuitka but was quickly stopped by an installation issue (Windows 10 Family 21H2): I log as Administrator on th e machine but whatever the way I launch the installer (Nuitka-7.1.60.win-amd64.py310.msi), I systematically stumble on the message "The installer has insufficient privilieges to access this directory: [...] Log on as Administrator"! I **am** the Administrator...

The file doesn't look courrpted and I tried to download it again, but to no avail.

Did anyone experience the sale issue?

Thanks in advance for any help!

**Comment by WangXang** [comment]
why not install nuitka with pip?
`pip install nuitka`

**Comment by jlgarnier** [comment]
Because I thought that the Windows installer (.msi) would be ok on Windows... I'll try to install with PIP and hope it will go through!
Thanks for your help!

**Comment by kayhayen** [comment]
I am suspecting a policy by your company to inhibit it, I just verified with the latest version. I think it complains about the lack of signature. Since with 3.11 there won't be MSI support in Python anymore, I guess I should consider pulling them entirely, as they are likely not worth any effort. At that point, people will start to wonder, why 3.11 packages do not exist.

**Comment by kayhayen** [comment]
Ok, I pushed the change to Nuitka-website, but my CI is down during my holiday, will take  a week until it becomes visibile.

**Comment by kayhayen** [comment]
Also removed ability to build MSI files and version handling, etc. from Nuitka on factory branch.

**Comment by jlgarnier** [comment]
Thanks, this will prevent further issues!
