### ISSUE TITLE
progress bar keeps changing length and module numbers keeps changing position

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#1603]
During the "Python" compilation step, the changing module names length constantly changes the progress bar length and module counter position. This is visually displeasing and makes it harder than necessary to actually read those counters.

One (hopefully easy) way to fix this would be to pad the module names with whitespace. Initially use an arbitrary reasonable number and then use to the longest module name ever seen (probably capped to avoid pathologically long module names making the progress bar too small). Bonus points if the module counter is also padded to avoid even more resizing.

**Comment by kayhayen** [comment]
The counter increasing during phase 1 from 1 to infinity, due to the way we optimize out from start point. It's only pass 1, but right now pass2 is so fast, it is not noticeable anyway. Terminal size is actually a known thing in tracing, we could consider it, and for larger widths make use of the extra space.

I I kind of assume that tqdm must allow for keep the sizes of areas in the progress bar more stable.

**Comment by kayhayen** [comment]
The values for `total` and `n` are not possible to format it seems. It would be nice if it said `  99/100` at least, and ` 9/10`, but that would require overloading tqdm functionality, for which I am not prepared right now.

But giving the bar a fixed width is looking very unfamiliar, but makes sense, esp. for smaller terminal sizes, it now just cuts of module names or leaves out that area entirely, which is perfectly fine.

So that's small fix, and on factory right now.

**Comment by gdementen** [comment]
Thanks for the quick reaction (as always).

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by gdementen** [comment]
Works nicely, thanks!

**Comment by kayhayen** [comment]
Part of the 0.9 release that I just made.
