### ISSUE TITLE
.build folder not invalidated when it should

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#1617]
Here is a little story 😉:

I used --include-module=multiprocessing as a quick work around for a missing implicit dependency (see #1616), because I was in a hurry to make a release and this worked fine. Then, to clean things up after the release, I removed the .build folder. Several weeks later, I prepared a new release, updated Nuitka and tried to compile my program but forgot the --include-module part. The executable failed to run (see details below), but when I added back the --include-module workaround it continued to fail. I scratched by head for several days, tried to revert to the older version of Nuitka, to update to develop, and even doubting how I had made it work previously -- I finally changed my work around to add the missing dependency with an explicit "import multiprocessing" instead) until I thought (just an hour ago) to remove the .build folder again and that made it work again. 

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version

  ```
  0.9rc7
  Commercial: None
  Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
  Flavor: Anaconda Python
  Executable: [...]\Miniconda\envs\test_env\python.exe
  OS: Windows
  Arch: x86_64
  WindowsRelease: 10
  ```
* How did you install Nuitka and Python

  - Python from miniconda using: `conda create -n test_env python=3.9`

  - Nuitka stable or develop using pip (your instructions)

* The specific PyPI names and versions
  > python -m pip freeze

  ```
  Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip
  numpy==1.22.4
  pandas==1.4.2
  pyreadstat==1.1.7
  ```

* Many times when you get an error from Nuitka, your setup may be special

  Hello world works fine here:
  ```
  >type hello.py
  print("Hello World!")
  >nuitka --standalone hello.py
  >cd hello.dist
  >hello.exe
  Hello World!
  ```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

  ```
  >type test.py
  import pyreadstat

  >nuitka --standalone --lto=no --enable-plugin=numpy --include-module=multiprocessing test.py
  [...]
  Nuitka:WARNING: Did not follow import to unused 'multiprocessing', consider include options.
  [...]
  Nuitka:INFO: Successfully created 'test.dist\\test.exe'.

  >cd test.dist
  
  >test.exe
  Traceback (most recent call last):
    File "[...]\test.dist\test.py", line 1, in <module>
    File "[...]\test.dist\pyreadstat\__init__.py", line 17, in <module pyreadstat>
    File "pyreadstat\pyreadstat.pyx", line 22, in init pyreadstat.pyreadstat
  ModuleNotFoundError: No module named 'multiprocessing'
  ```

* Note if this is a regression

  Unsure whether it is a regression. I tried with both Nuitka 0.7.7, 0.8.4 and develop with my "broken" build folder and they all failed (incidentaly I think the build folder should be at least partially Nuitka-version specific and -- as this bug suggests -- at least partially option specific).

**Comment by kayhayen** [comment]
I think you are a victim of a Nuitka regression, as explained and fixed elsewhere.

**Comment by gdementen** [comment]
Sorry to insist, but I think the problem is more important than just the multiprocessing module. Unless I misunderstand something, I think you have just fixed the symptom but not the root cause and thus the problem is bound to happen again with another option or other modules. A user **never** expects the presence of the build folder to affect the final result. Ideally, it should affect the speed of compilation, but not to the detriment of giving a wrong result.

**Comment by kayhayen** [comment]
I was not convinced that it happened as described. One thing that I noticed with bytecode caching, was that dependencies of those are cached, and e.g. impacted, by whatever the Yaml configuration at the time is. Therefore, now with 0.9 that file is check summed and taken into account. The modules included as bytecode have their dependencies cached, but keyed by what is importable, etc. so it won't repeat the task unless there is reason to believe it will compile differently.

What could have happened in your case, is that you had originally a cache, that was supposed to be invalidated, but wasn't until later. Not sure if the ".build" folder change triggers a re-compilation.  Right now, the Nuitka version is not part of the hash, the idea was to bump the version when incompatible things happen, which wasn't the case outside Yaml file changes, which effectively happen a lot more often than code changes affecting the importing.

And since you changed code for dependencies (your pyreadstat) is old code, that didn't affect caching. It's very similar to me being confused about anti-bloat config changes not having an effect. These things in the code are going to die anyway, so not sure, but adding Nuitka version string is probably a good idea also, just to catch hotfix releases that address bugs in how modules are located.

The build folder itself is emptied by Nuitka right at the start of operation. Its contents should not be used.

So I think that part of the report is not too relevant anymore, since this caching bug has been solved.

**Comment by kayhayen** [comment]
To consider in your case btw, is that it's an extension module, or is it not, that you changed things for, it would always have had to have an effect right away with all versions of Nuitka, since these do not have cached dependencies at all.
