### ISSUE TITLE
Process exits after one minute. [question]

### ISSUE THREAD

**Issue by 345629655** [Nuitka/Nuitka#1659]
### Version:
0.9.3
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: D:\Code\yolov5\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
### Description:
I tried to compile a project with pyside6+yolov5

When I compile my script using:

`nuitka --standalone --show-progress --show-memory --plugin-enable=pyside6,numpy,torch --include-data-dir=./runs=./runs, --include-data-dir=./models=./models, --include-data-dir=./utils=./utils, --include-data-dir=./data=./data --remove-output --output-dir=dist main.py`

It finishes without any errors, but when I run the resulting .exe it says:

`[process exited with code 3221225477 (0xc0000005)]`

How can I track down why this .exe doesn't work?

**Comment by kayhayen** [comment]
You might want to compile and execute with `--debug` which should catch many errors of Nuitka itself. The torch has very recently seen a hotfix, that caused sporadic crashes, so using 0.9.5 would also likely help already. Please always provide a reproducer, because otherwise it's pretty much impossible to know this.
