### ISSUE TITLE
Errors with build/static_src/HelpersAttributes.c and build/include/nuitka/helper/attributes.h

### ISSUE THREAD

**Issue by ddegner** [Nuitka/Nuitka#166]
I'm trying to compile the most basic app on a Mac with the latest of everything and I always get [3 errors](https://pastebin.com/vY9auhtq) and the final app isn't compiled.

This is my setup:
`0.6.1rc4
Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
OS: Darwin
Arch: x86_64
`

I tried with the stable 0.6.0 and I installed the latest version on Nuitka with PIP, and Python3 with the installer downloaded from python.org, on a freshly installed macOS 10.13.3.  In a virtual environment and directly calling python3.

I started with a complex program and eventually whittled it down to 
`print("This line will be printed.")`

Then I ran 
`python3 -m nuitka hello.py`

And I get this error: [https://pastebin.com/vY9auhtq](https://pastebin.com/vY9auhtq)
`In file included from setup.build/CompiledCodeHelpers.c:2004:
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/static_src/HelpersAttributes.c:553:6: error: conflicting types for 'SET_ATTRIBUTE'
bool SET_ATTRIBUTE(PyObject *target, PyObject *attr_name, PyObject *value) {
     ^
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/include/nuitka/helper/attributes.h:34:13: note: previous declaration is here
extern bool SET_ATTRIBUTE(PyObject *target, PyObject *attr_name, PyObject *value);
            ^
In file included from setup.build/CompiledCodeHelpers.c:2004:
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/static_src/HelpersAttributes.c:594:6: error: conflicting types for 'SET_ATTRIBUTE_DICT_SLOT'
bool SET_ATTRIBUTE_DICT_SLOT(PyObject *target, PyObject *value) {
     ^
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/include/nuitka/helper/attributes.h:37:13: note: previous declaration is here
extern bool SET_ATTRIBUTE_DICT_SLOT(PyObject *target, PyObject *value);
            ^
In file included from setup.build/CompiledCodeHelpers.c:2004:
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/static_src/HelpersAttributes.c:646:6: error: conflicting types for 'SET_ATTRIBUTE_CLASS_SLOT'
bool SET_ATTRIBUTE_CLASS_SLOT(PyObject *target, PyObject *value) {
     ^
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/include/nuitka/helper/attributes.h:40:13: note: previous declaration is here
extern bool SET_ATTRIBUTE_CLASS_SLOT(PyObject *target, PyObject *value);
            ^
3 errors generated.
scons: *** [setup.build/CompiledCodeHelpers.o] Error 1`

**Comment by kayhayen** [comment]
Hello there,

I am deeply confused. The declarations seem to be absolutely identical, were not recently touched, and are not too special, are they?

Maybe some C include file changes what "bool" is, but I doubt it would affect only those functions, there must be more helper codes with bool return value than just the 3. If you could get a hand at the pre-processed outputs that would help, ``-E`` option would do that for gcc. 

Which C compiler is this that you are using? Since bool is not C11, maybe that is the issue. On MacOS people use Clang however, and then it is normally always good.

Yours,
Kay

**Comment by lordsutch** [comment]
I can reproduce the same issue with macOS 10.14 with nuitka 0.6.0.2; as far as I can tell, the problem seems to be that attributes.h declares the functions as 'extern' but they're actually available since they're being provided in the same object file by HelpersAttributes.c.

This is using the following clang: Apple LLVM version 10.0.0 (clang-1000.11.45.2)

It seems to be related to this change, since I do not have this problem if I revert to nuitka 0.5.33: https://github.com/Nuitka/Nuitka/commit/58129dd8eaeb3d0021b4a8fb45e015454e59a5a8#diff-8384615410497494ece07196f93ad105

**Comment by kayhayen** [comment]
I am partitioning the file with `#include *.c` to use multiple files and you think that it makes a difference?

You could test this hypothesis by use `cat HelpersAttribute.c >> CompiledCodeHelpers.c` and `echo >HelpersAttribute.c` in 0.6 and then I am lost, because I didn't ever consider it would make a difference what the file name of an include would be.

extern void f();
void() f(){
}

should be allowed in the same compilation unit and should both be seen, precisely so the C compiler can compare the signatures and raise the complaint if it's different, other than the "extern" part. I also wonder if adding extern to where it's defined will work.

Also I don't think I will be able to reproduce this, I can only have LLVM 8 I think, so please try these things out and let me know if the later already helps, it would be cheap.

Yours,
Kay

**Comment by kayhayen** [comment]
Yes, Nuitka insists on C11 for C or to use C++03 otherwise, so C99 would be a given. However, for me neither clang-6.0 nor gcc-8 cut it. The names true, false, and bool won't work without it. That is even with the option -std=c11 given. But the include is there for at least gcc-5 and clang-6, so I consider those a better solution. So guarded with a C++ check, prelude.h is now including this for all versions, and it appears to work.

I am putting it on factory first, let me know if it works:

http://nuitka.net/doc/factory.html

**Comment by lordsutch** [comment]
I just tested it with Python 2.7 (both homebrew and stock) and Python 3.7 on my system with a "Hello, world" program, and it worked in all 3 cases. Thanks!

**Comment by kayhayen** [comment]
So thanks for the testing, I dared push this out as a hotfix 0.6.0.3 therefore.
