### ISSUE TITLE
Question: What happened to Nuitka-Utilities?

### ISSUE THREAD

**Issue by qing-shang** [Nuitka/Nuitka#1668]

**Comment by qing-shang** [comment]
using a higher version will fail to compile

**Comment by kayhayen** [comment]
No, the implementation was never any good, and is not maintained anymore, and PGO (Profile Guided Optimization) on the Python level will supersede it. Also, we have been doing a lot of anti-bloat work that makes most things compile actually better than this ever did, because it could not really remove any bloat.
