### ISSUE TITLE
TypeError: arg 5 (closure) expected cell, found compiled_cell

### ISSUE THREAD

**Issue by JiaPai12138** [Nuitka/Nuitka#1674]
```
0.9.4
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\Development\Environment\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
Code:
```
def binder(func, name):
    gtec = types.FunctionType(func.__code__, func.__globals__, name=func.__name__, argdefs=func.__defaults__, closure=func.__closure__)
    gtec = functools.update_wrapper(gtec, func)
    gtec.__kwdefaults__ = func.__kwdefaults__
    gtec.__name__ = name
    return gtec
```
Pack
```
python -m nuitka --mingw64 --module --warn-implicit-exceptions --show-progress --remove-output --warn-implicit-exceptions some.py
```
Error:
```
TypeError: arg 5 (closure) expected cell, found compiled_cell
```

* How did you install Nuitka and Python
```
Download Python from https://www.python.org/ and install
pip install nuitka -U
```

* The specific PyPI names and versions
```
altgraph==0.17.2
appdirs==1.4.4
arc4==0.2.0
async-generator==1.10
attrs==21.4.0
backports.shutil-get-terminal-size==1.0.0
bandit==1.7.4
bezier==2021.2.12
certifi==2022.5.18.1
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.4
commonmark==0.9.1
cryptography==37.0.2
cx-Freeze==6.11.0
cx-Logging==3.0
cycler==0.11.0
Cython==0.29.30
ed25519==1.5
et-xmlfile==1.1.0
flatbuffers==2.0
fonttools==4.33.3
future==0.18.2
gitdb==4.0.9
GitPython==3.1.27
graphviz==0.20
h11==0.13.0
idna==2.6
importlib-metadata==4.11.4
joblib==1.1.0
keyboard==0.13.5
kiwisolver==1.4.2
lief==0.12.1
llvmlite==0.38.1
loguru==0.6.0
lxml==4.9.0
Mako==1.2.1
MarkupSafe==2.1.1
matplotlib==3.5.2
MouseInfo==0.1.3
mss==6.1.0
nltk==3.7
ntplib==0.4.0
Nuitka==0.9.5
numba==0.55.2
numpy==1.22.4
nvidia-pyindex==1.0.9
onnx==1.11.0
onnx-simplifier==0.3.10
onnxconverter-common==1.9.0
onnxmltools==1.11.1
onnxoptimizer==0.2.7
onnxruntime-directml==1.11.1
opencv-python==4.6.0.66
openpyxl==3.0.10
ordered-set==4.1.0
outcome==1.2.0
packaging==21.3
pandas==1.4.3
pbr==5.9.0
pefile==2022.5.30
Pillow==9.1.1
platformdirs==2.5.2
protobuf==3.20.1
psutil==5.9.1
pyadl==0.1
pyarmor==7.5.1
pyasn1==0.4.8
PyAutoGUI==0.9.53
pycocotools==2.0.4
pycparser==2.21
pycuda==2022.1
pygame==2.1.2
PyGetWindow==0.0.9
Pygments==2.12.0
PyHook3==1.6.1
pyinstaller==5.1
pyinstaller-hooks-contrib==2022.7
PyMsgBox==1.0.9
pynput==1.7.6
pynvml==11.4.1
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyperclip==1.8.2
PyRect==0.2.0
PyScreeze==0.1.28
pyserial==3.5
PySimpleGUI==4.60.1
PySocks==1.7.1
python-dateutil==2.8.2
pytools==2022.1.12
pytweening==1.0.4
pytz==2022.1
pywin32==304
pywin32-ctypes==0.2.0
PyYAML==6.0
regex==2022.6.2
reprint==0.6.0
requests==2.28.0
rich==12.4.4
rsa==4.8
scikit-learn==1.1.1
scipy==1.8.1
seaborn==0.11.2
selenium==4.3.0
simple-pid==1.0.1
six==1.16.0
skl2onnx==1.11.2
smmap==5.0.0
sniffio==1.2.0
sortedcontainers==2.4.0
srt==3.5.2
stevedore==3.5.0
tabulate==0.8.9
thop==0.0.31.post2005241907
threadpoolctl==3.1.0
tinyaes==1.0.3
torch==1.10.1+cu102
torchaudio==0.10.1+cu113
torchvision==0.11.2+cu102
tqdm==4.64.0
trio==0.21.0
trio-websocket==0.9.2
trtpy==1.2.6
typing_extensions==4.2.0
urllib3==1.26.9
vosk==0.3.42
win32-setctime==1.1.0
winput==1.4.0
WMI==1.5.1
wres==1.0.3
wsproto==1.1.0
zipp==3.8.0
zstandard==0.18.0
```

**Comment by gdementen** [comment]
AFAICT, this is a known limitation of Nuitka: https://nuitka.net/doc/user-manual.html#the-co-code-attribute-of-code-objects

As a side note, I personally never understood this limitation (but I readily admit I have no clue what I am talking about). Even though the bytecode is usually not used when a function is compiled, I don't see why it could not be included anyway to support cases like this . This would not work if the function is inlined but I don't see anything which would prevent it *in theory* in other cases. I guess that there is some reason this is not doable in practice otherwise Kay would have done it.

**Comment by kayhayen** [comment]
@gdementen you are wrong, this has nothing to do with code objects, but rather with code insisting on `cell` objects, while compiled functions only offer `compiled_cell` objects. This is usually done by code that attempts to copy a function object, by constructing from parts of the other. I never saw a good reason for it so far, and it's not portable to Nuitka normally.

The code object is not going to work with a proper constants object, which we don't have a compatible one either. I am sure there is other reasons, but attempts to execute it will not end up being very productive.

**Comment by kayhayen** [comment]
I think, it was never provided, what package has this code that you cited @JiaPai12138 but I will have to know the module name, to apply a workaround in the Yaml package configuration of Nuitka. It seems it does only exist, to change a name of a function, something which well, can normally just not be done, but I don't know what PyPI module listed has it.

**Comment by JiaPai12138** [comment]
> I think, it was never provided, what package has this code that you cited @JiaPai12138 but I will have to know the module name, to apply a workaround in the Yaml package configuration of Nuitka. It seems it does only exist, to change a name of a function, something which well, can normally just not be done, but I don't know what PyPI module listed has it.

I just used build-in package
```
import functools  # https://docs.python.org/3/library/functools.html
import types  # https://docs.python.org/3/library/types.html#module-types
```
And that "binder" function is just used to create a deep copy of another function, follow examples from [here](https://stackoverflow.com/questions/6527633/how-can-i-make-a-deepcopy-of-a-function-in-python)

**Comment by kayhayen** [comment]
So this is not from PyPI, but code you own, I see. So, step 1 would of course, to use `func.__class__` rather than hard coding, what one things it is. And step2, I am not sure about right now. I will check out what `copy.copy` and `deepcopy` are using. I feel, that supporting those is the sane way. For dill plugin, we do support creating function objects with pickle like API, but this might be something else needed.

**Comment by kayhayen** [comment]
Something bad about it of course, would be how `copy.deepcopy` on compiled functions would then be different from what happens with standard functions, so I am taking another route here, and that is to add a method:

```
def f():
        pass

import copy

g = copy.copy(f)
g.__doc__ = "lala"

print(f.__doc__)

h = copy.deepcopy(f)
h.__doc__ = "lele"

print(f.__doc__)

i = f.clone()
i.__doc__ = "lolo"

print(f.__doc__)
```

Output is

```
lala
lele
lele
```

If guarded with an attribute error, this would allow dual use code. The clone function is like a real deepcopy, although now that I am thinking of it, not quite so, since defaults are not copied, but mutable defaults are hopefully nothing you do anyway.

**Comment by kayhayen** [comment]
Compiled functions now have a method `.clone` which is described in the user manual too, part of the 1.0 release. Unfortunately the code will need to be changed, as there is no way uncompiled functions can be created from compiled ones, and that is of course also undesirable. Part of 1.0 release.
