### ISSUE TITLE
Tensorflow 2 import crashes during nuitka compilation( failed to resolve DLL _pywrap_py_utils.so) - Reopened

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1697]
**Environment:**
MACOS Monterey
Python:3.7.3
Nuitka 'Nuitka-0.8rc7' (downloaded 2 days ago)

**How did you install Nuitka and Python**
pip

**The specific PyPI names and versions**
tensorflow==2.8

**Provide in your issue the Nuitka options used**
sudo python3.7 -m nuitka ---standalone --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site test.py

**Content of test.py:**
import tensorflow as tf
print(tf.version)

**Error during nuitka standalone compilation:**
FATAL: Error, failed to resolve DLL path bazel-out/darwin-opt/bin/tensorflow/compiler/tf2tensorrt/lib_pywrap_py_utils_ccsharedlib.so (for /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/_pywrap_py_utils.so), please report the bug.

**whole output:**
https://www.dropbox.com/s/ftdior8mq875htt/temp?dl=0

**My nuitka --version output:**
emres-Air:inference emre$ sudo python3.7 -m nuitka --version
0.8rc7
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: Unknown
Executable: /usr/local/bin/python3.7
OS: Darwin
Arch: x86_64

**Notes:** 
1-I have also tried with following command(--include-data-file tf2tensorrt/*.so included, which has lib_pywrap_py_utils_ccsharedlib.so file inside) , unfortunately I am still getting the same error:

sudo python3.7 -m nuitka ---standalone --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=tensorflow --python-flag=no_site --include-data-file=/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow/compiler/tf2tensorrt/*.so=tensorflow/compiler/tf2tensorrt/ test.py

2-#1621 was totally the same issue as this one. Unfortunately I could not get the point why it was closed. I would be appreciated if you investigate my issue. If you need any logs or any other outputs from my environment, please do not hesitate to request. 

Thanks a lot in advance.

**Comment by kayhayen** [comment]
Doing 1 has no point and is actually likely to break working things, so your report is invalid, naturally. DLLs are not data files, but code that needs treatment before running elsewhere. The Windows mindset is pretty harmful, because DLLs there often work, but on Linux and macOS that is misguided.

Also, you report against `0.8rc7` but honestly, which is of course non-sense, given that 0.9.6 is currently the stable release, although I think it won't make a difference.

Making you understand 2 is not too interesting, but duplicate issues are not relevant to me, and ones where I do not get requested inputs, are totally useless to me. if the needs_example tag stays for too long, I close issues, such that other people who actually want to report, are not held off by existing but bad issues.

I also wonder, how the vendor detection fails for your Python again. I thought this was under better control now.

I recently rewrote the dependency parsing entirely, such that it will work on macOS much better. I think duplicate DLLs while being resolved, still lead to a failure to finalize things. That cannot happen anymore.

BTW: I managed to get the 2.0.0 of Anaconda to link, but it will not run, because it would need separate changes for the Python code, which are absolutely non-trivial. It will probably remain unsupported. The newer version you cite here, ought to work now with current factory, but I didn't have the chance to try that out. I also did the anti-bloat work to make Tensorflow generally work better. I do suspect that it will work with the factory branch now, but I didn't get to combine the pieces yet.

You can try it: https://nuitka.net/doc/factory.html 

But this report is so invalid and duplicate by admission, it hurts.
