### ISSUE TITLE
Wrong code execution with comparison chain

### ISSUE THREAD

**Issue by nguyencongminh090** [Nuitka/Nuitka#1721]
I compiled a simple code:
```
while True:
    print(4 <= 4 <= 5)
    input()
```
and have a bug:
![image](https://user-images.githubusercontent.com/63632371/183292045-29ad6d9f-341e-4930-9819-82f868c42074.png)

But this code return correct output.    
```
while True:
    print(3 < 4 < 6)
    input()
```

**Comment by kayhayen** [comment]
I can confirm this, necessary to be in a loop, which at this time prevented the optimization of the temporary variables used inside the loop. That is of course another story to address. The reformulation seems correct, otherwise the non-loop case could not come to the correct value. I have a worry that this is a regression of the 1.0 release and comparison helper changes.

**Comment by kayhayen** [comment]
This is indeed a regression, probably due to the use of less comparison helpers, probably we are making false assumptions somewhere. We use to do this:

```
            tmp_assign_source_9 = RICH_COMPARE_LE_OBJECT_LONG_LONG(tmp_cmp_expr_left_1, tmp_cmp_expr_right_1);
            tmp_args_element_value_1 = RICH_COMPARE_LE_OBJECT_LONG_LONG(tmp_cmp_expr_left_2, tmp_cmp_expr_right_2);
```

but now it is this:

```
           tmp_tmp_assign_source_9_cbool_1 = RICH_COMPARE_GT_CBOOL_LONG_DIGIT(tmp_cmp_expr_right_1, tmp_cmp_expr_left_1);
            tmp_tmp_args_element_value_1_cbool_1 = RICH_COMPARE_LE_CBOOL_LONG_DIGIT(tmp_cmp_expr_left_2, tmp_cmp_expr_right_2);
```

The first one has reversed arguments, and uses `GT`, while the later uses `LE` with both of them using the C long type argument, first question would be why reverse at all, where the first one exists. I used to have a misconception that on reversal of the operator, the result must be inverted, maybe there are remnants of that in the code.

**Comment by kayhayen** [comment]
Ok, it seems that for 2 <= var we reverse the arguments, but we do not reverse the results, when the C types are the same, but it's done when it's similar.

Unoptimized comparison chains are probably the only times, humans write that kind of code, which explains why it escaped the attention so far. I will want to do a rebase of main to correct this after bisecting it, as well as making it a hotfix of course.

**Comment by kayhayen** [comment]
This is currently on the develop branch and is going to be part of 1.0.2 hotfix later today. I am closing it as release is immanent.
