### ISSUE TITLE
Long time compilation and other

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#173]
I made many test last weeks with nuitka around P27,34,36 with my advanced MVC applications with QT4 and QT5. Started test with PySide2 but there is many issues around this.. so reporting bugs in this in relation to QT (that exist just in .c as wg. "not implemented").
After 2016 and after in next years, now is big progess coz in this time was impossible to do something ok with my project.  
I tested often.. to check.. when can be ready and nutika do something without errors.
I tested many other similar solution that should touch points as "exe", "standalone", "performance", but most of was far from need. Now.. my last rescue gives me dilema..

Let me put some comment to this all.

After .exe was prepared with P34 I checked this all by IDA and dependencyWalker.
Then missed:
ieshims.dll 
https://stackoverflow.com/questions/2465111/dependency-walker-reports-ieshims-dll-and-wer-dll-missing
After add to system32 next:
API-MS-WIN-DOWNLEVEL-ADVAPI32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-OLE32-L1-1-0.DLL
API-MS-WIN-DOWNLEVEL-SHLWAPI-L1-1-0.DLL
 ..but app working without this all

The app omitting QT icons in MDI, and other.
Small details.

Comaprison:

**P27** QT4
1500 files .c/.o and after **1h** faill
cc1.exe: out of memory allocating 7319352 bytes
cc1.exe: out of memory allocating 4072 bytes

**P34** QT5
74 files .c/.o and **15min** work with success

**P36** Pyside2
 77 file .c/.o and **30min** work without sucess (.exe exist but can't run corectly by bugs in PySide2 in this process - pure .py or cx_freze etc.. workin ok)
python36.dll next to

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.6.0.3

Python: 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]
Python: 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 20:20:57) [MSC v.1600 64 bit (AMD64)]
Python: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

OS: Windows w7sp1 x64
Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.
 PIP

**What suprised me.**
The sucess with my big project P34 QT5, fails with P27 QT4. Problems with P36 Pyside2.
The long time of compilation.
The long time of starting app as .exe - it is longest than in interpreter in my case (around 50sec, 1 min and more), can't explain this.

The working .exe is not faster than cf_freze or runed by Python. Thats why I start do some research by IDA, olyDB to see something (coz why?). Well there is some issue about https://github.com/Nuitka/Nuitka/issues/150 
..but on simple examples, not advanced clasess or something like this.

I hope that in next years can be bether situation here, and the result of compilation by nuitka can be some product for commercial. On this moment no. 

So the question is to the author.. 
Do You think that we can use nuitka in this direction (commercial apps) as some substitute for c/c++ apps produced in python in future?

**Comment by kayhayen** [comment]
Startup time is an area where I have not done any measurements yet. Constant values are produced ahead of time, which may incur a penalty at startup. So far I had no reason to assume this made a big difference. 

I think some in-place operations may well cause issues still. I recently added support for module variables. This may well affect you. Try out the develop version. Closure variables are still missing, but will come too, these would still have the issue. If you program does those a lot, slow downs could be incredible, and orders of magnitude like you suggest must be that. 

Nuitka definitely will still be slower than CPython for some things, there is just no way around this at this stage, as it has been optimized for what it does, and Nuitka plays catch up on the object level. The in-place `+=` operations are being dealt with, but are still work in progress. Otherwise, things are an either unknown or faster.

For Nuitka performance I am getting mixed reports. Without specificity they are all useless. Some are happy, some are unhappy. My impression is that Nuitka with Python3 has much smaller gains though, although there it would be more necessary with it being slower. With time, I think I will get to be the bottom of why this is.

As for commercial use. I don't really care unless its from people willing to pay me. For all I know, quite some people use it that way and are really happy. And then some people find it falls short and are unhappy, but I don't care unless it manifests in usable reports.

The goal is definitely to make Python approach C level performance. Currently my focus is more towards the C type code generation, because I am thinking of the object level optimization as basically good enough, and only needing some more tweaks. The in-place work that is happening, i.e. module variables, and closure variables, is also C type work, but a side kick. I could give it more priority, but I decided otherwise.

And the future is wide open. It all depends on how much man power the project can attract to fill out the details, so every operation is as fast as possible, so every C type integrates as well as possible, so every C binding method can be called with zero overhead, so Nuitka can integrate with "sip" to get at the lower levels of code directly, so Nuitka can integrate with Pythran for faster numpy operation.

Until then I will have to make choices, what to focus on. I did focus for a long time on the optimization stage, so it can carry the weight of type inference. And actually do some more, adding branch merges type information in last pre-release, and loop SSA in the next one, but these will be rather small things, with large effects though, for the new stuff that wants to use the type knowledge.

Not sure if I am going to succeed, but I definitely will try.

Yeah, so this is part of TWN 9 then.

**Comment by ManPython** [comment]
Thx @kayhayen for all explanation. As I consumed time to test this all I was idea to provide some feedback. I apreciated Your all warok aroudn big milestone in this all and in Python problems that You understand.

I'm in idea, many often big companies like MS, Google, etc. don't care the performance, eg. C# or Python (in case of GO as exception but, there are some mistaces, are more focus on network, not the desktop in this lang). Why? Coz.. clouds, mainframe's etc.. buy this.. support this.. etc.. the old model to made business.. that hiting coders problems that made they lossing.. time.. ideas, to solve something. 
The coment can be longest here.. but we know how this all looks I belive.

Good luck in next stages in developing nuitka. As I wrote the progess is good, maybe now it's time to optimize and as always some small detials that are important to offer suport in the main targets for nuitka (I think that are apps with QT,Pyside2,Glade/GTK).

**Comment by kayhayen** [comment]
Thanks for the feedback @ManPython I am closing this, please take no offense, it's too unspecific, but your input is still consumed.

Roughly everybody using Python right now does not care about performance too much or else would use something with better performance. Nuitka is about taking where it currently is not viable or enhancing it for some use cases.

I definitely will aim at getting the usual problem children for standalone to work. But that is not really all that much compiler work, rather packaging. Right now for all I know, most stuff actually works.
