### ISSUE TITLE
Issues with --onefile-tempdir-spec

### ISSUE THREAD

**Issue by Itad0ri** [Nuitka/Nuitka#1806]
* How did you install Nuitka >  pip
* Nuitka version > 1.0.7

Using the command below:
`nuitka --enable-plugin=numpy --onefile-tempdir-spec=%TEMP%\\%PROGRAM% --windows-icon-from-ico="FULL_ICO_PATH" --onefile main.py -o REMOVED.exe --windows-company-name="REMOVED" --windows-product-name="REMOVED" --windows-file-version=1.0.0.0 --windows-product-version=1.0.0.0 --windows-file-description="REMOVED"`

Opened the temp folder and saw multiple folders named "one_pid_time". So, I looked into the issue and got to know there is an option to unpack onefile into a specified folder. But when I try to build the exe using the above-mentioned command, It replaces %TEMP% with my temp path, and the command converts into:

`nuitka --enable-plugin=numpy --onefile-tempdir-spec=C:\Users\REMOVED\AppData\Local\Temp\\%PROGRAM% --windows-icon-from-ico="FULL_ICO_PATH" --onefile main.py -o REMOVED.exe --windows-company-name="REMOVED" --windows-product-name="REMOVED" --windows-file-version=1.0.0.0 --windows-product-version=1.0.0.0 --windows-file-description="REMOVED"`

Nuitka throws an error:
`Nuitka-Options:WARNING: Using an absolute path should be avoided unless you are targeting a very well known environment: anchor with e.g. %TEMP%, %CACHE_DIR% is recommended`

Already using %TEMP% in my command :/

How to fix this? I just don't want multiple folders named "one_pid_name" sitting in my temp folder. Instead, unpack the exe into 1 specified folder. It works if I use it on my system because the "temp" path is valid but if I use it on my other system then it throws an error (regarding temp path).

**Comment by kayhayen** [comment]
It's not an error, it's a warning.

Using `%PROGRAM%` is an absolute path, not sure how well that can work below the temporary folder, so that is non-sense. I doubt it works, because it's going to include a `\C:\` in the middle of things. Thanks for contributing a user error here. I guess, this should only be allowed at the start of values in all cases, sache from `%CACHE_DIR%`, `%HOME%` and what not. I would recommend using `%PRODUCT%` or something hard coded for that part.

And you not using `%TEMP%` is not your issue when you use `'%TEMP%\\onefile_%PID%_%TIME%'` . The uncached is detected, or should be detected, by using `%PID%` or `%TIME%`, for persisting files, I think `%CACHE_DIR%` ought to be used. But I might reconsider that part about `%TEMP%` and remove it from that list.

**Comment by kayhayen** [comment]
> FATAL: Absolute runtime path of '%PROGRAM%' can only be at the start of 
'--onefile-tempdir-spec=1%PROGRAM%' is not allowed.

**Comment by kayhayen** [comment]
The `%TEMP%` is the temp folder of the user executing the program, it is not resolved during compilation, but at run time, not sure if you understood that. I am excluding it from being assumed to want to enforce no caching behaviour, since for a given user it is of course static.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under constant development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Part of the 1.1 release
