### ISSUE TITLE
"--nofollow-imports" is not effective when use --standalone 

### ISSUE THREAD

**Issue by tianjiqx** [Nuitka/Nuitka#1815]
> python -m nuitka --version

1.1
Commercial: None
Python: 3.9.12 (main, Apr  5 2022, 01:53:17)
Flavor: Anaconda Python
Executable: /usr/local/anaconda3/bin/python3
OS: Darwin
Arch: x86_64

case :

```
import pandas as pd

def main():
    print('hello')
    res = pd.DataFrame()
    print(res)


if __name__ == '__main__':
    main()

1. too too slow, due to complie pandas, check all module on pass 1 ?  --nofollow-imports is not effective
python -m nuitka  --show-memory --show-progress --nofollow-imports  --standalone app.py

2. still check other module
python -m nuitka  --show-memory --show-progress --nofollow-imports  --nofollow-import-to=pandas --standalone app.py

3. fast due to without --standalone 
python -m nuitka  --standalone --enable-plugin=numpy --nofollow-imports app.py


```

 **if  we use old version like 0.6.15 --nofollow-imports will effective, even with --standalone ** 

Since my project depends on too many third-party modules, I don't actually want to compile them, just copy site-packages to depend on them.

**Comment by kayhayen** [comment]
I don't think that `--nofollow-imports` is ineffective, but it's warned about only, but I also do not care, because I do not intend to support this mode of operation. With changes coming, you will be able to use user yaml to specify bytecode compilation for modules, which then can be rerrived from cache. But the manual copying is entirely unsupported. If you can get it to work, all good, otherwise I guess 0.6.15 is still there for you.

**Comment by xlight** [comment]
--nofollow-imports really reduce the compilation process time .
because it do not compile these huge externel packages like numpy .
and we can include these packages like data-dir.
