### ISSUE TITLE
Enhancement: Handle SIGQUIT and SIGTERM on linux onefile

### ISSUE THREAD

**Issue by vinayinvicible** [Nuitka/Nuitka#1818]
Consider the following example

> pip install nuitka ordered-set zstandard gunicorn

> python -m nuitka --version
```
1.1
Commercial: None
Python: 3.10.7 (main, Sep 12 2022, 22:54:14) [GCC 11.2.0]
Flavor: pyenv
Executable: /home/vinay/code/testing/nuitka/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.1
```
> python -m pip freeze
```
gunicorn==20.1.0
Nuitka==1.1
ordered-set==4.1.0
zstandard==0.18.0
```

```python
#run.py
from gunicorn.app.wsgiapp import run

run()
```
```python
#wsgi.py
def application(environ, start_response):
    start_response('200', [])
    return [b"Hello World"]
```
> python -m nuitka run.py --static-libpython=yes --onefile --clang --standalone --include-package=gunicorn
> ./run.bin wsgi -b localhost:8000

Now send SIGQUIT/SIGTERM to process.
You can see that onefile dir still exists in the tmp folder.
I can see that child process are running as orphaned process. I am assuming this is the reason why the tmp folder is not deleted.
These files pile up over time as each runtime creates its own tmp directory.

I've made some changes to the OnefileBootstrap.c and able to resolve this issue. But am not sure it if applies for all envs and platforms.

```diff
diff --git a/nuitka/build/static_src/OnefileBootstrap.c b/nuitka/build/static_src/OnefileBootstrap.c
index d2b810daa..264dad47a 100644
--- a/nuitka/build/static_src/OnefileBootstrap.c
+++ b/nuitka/build/static_src/OnefileBootstrap.c
@@ -676,7 +676,7 @@ static char *downloadTextContentsSync(filename_char_t const *url) {
 }
 #endif
 
-static void cleanupChildProcess(void) {
+static void cleanupChildProcess(int sig) {
 
     // Cause KeyboardInterrupt in the child process.
     if (handle_process != 0) {
@@ -690,7 +690,7 @@ static void cleanupChildProcess(void) {
             // No error exit is done, we still want to cleanup when it does exit
         }
 #else
-        kill(handle_process, SIGINT);
+        kill(handle_process, sig);
 #endif
         // TODO: We ought to only need to wait if there is a need to cleanup
         // files when we are on Windows, on Linux maybe exec can be used to
@@ -790,7 +790,7 @@ BOOL WINAPI ourConsoleCtrlHandler(DWORD fdwCtrlType) {
 }
 
 #else
-void ourConsoleCtrlHandler(int sig) { cleanupChildProcess(); }
+void ourConsoleCtrlHandler(int sig) { cleanupChildProcess(sig); }
 #endif
 
 #ifndef MAXPATHLEN
@@ -1160,6 +1160,8 @@ int main(int argc, char **argv) {
     }
 #else
     signal(SIGINT, ourConsoleCtrlHandler);
+    signal(SIGQUIT, ourConsoleCtrlHandler);
+    signal(SIGTERM, ourConsoleCtrlHandler);
 #endif
 
 #if _NUITKA_ONEFILE_AUTO_UPDATE == 1
@@ -1510,11 +1512,11 @@ int main(int argc, char **argv) {
 
         if (res == -1 && errno != ECHILD) {
             printError("waitpid");
-            cleanupChildProcess();
+            cleanupChildProcess(0);
             exit_code = 2;
         } else {
             exit_code = WEXITSTATUS(status);
-            cleanupChildProcess();
+            cleanupChildProcess(0);
         }
     }
 
```

**Comment by vinayinvicible** [comment]
@kayhayen 
did you get any chance to look at this?

**Comment by kayhayen** [comment]
I did, but I was very confused about it and also undecided. I liked how only `KeyboardInterrupt` ever reached the bootstrapped application, but maybe that can be also considered a mistake. The `0` seems to be a mistake, I vaguely recall, that is how you check with kill if a process exists.

**Comment by kayhayen** [comment]
Maybe you see the `KeyboardInterruptTest` in onefile tests.  Can you add ones for other signals as well?

**Comment by kayhayen** [comment]
No feedback on this, if there is no PR coming, I guess we have to close it.

**Comment by mattbillenstein** [comment]
Running into this - SIGTERM is sorta the unix standard way to terminate a daemon application - Python itself exits if sent a SIGTERM, so I think this PR makes sense to me to maintain those semantics. I think passing all signals through to the child process is probably the most correct thing to do.

Also, this is notably probably naive, but why fork at all? Can the bundle be unpacked and then deleted by wrapping the python program instead of forking? I guess in the case of a hard segfault or abort, there's no opportunity to cleanup?

**Comment by mattbillenstein** [comment]
Posting a quick example, I start my daemon using a Nuitka build and also running under python3:

`(.venv) mattb@brix:~/src/mattb/salty master$ ps aux | grep salty | grep -v grep
mattb     846092  0.3  0.0   3080  2004 pts/4    S+   00:42   0:00 ../salty.Linux-x86_64 server 127.0.0.1:11110
mattb     846093  0.3  0.6  70744 53748 pts/4    S+   00:42   0:00 ../salty.Linux-x86_64 server 127.0.0.1:11110
mattb     846128  4.6  0.4  52960 38276 pts/9    S+   00:43   0:00 python3 ../salty.py server 127.0.0.1:11111
`

Send TERM to the python3 version, it exits "Terminated":
`
(.venv) mattb@brix:~/src/mattb/salty master$ kill 846128
(.venv) mattb@brix:~/src/mattb/salty master$ ps aux | grep salty | grep -v grep
mattb     846092  0.2  0.0   3080  2004 pts/4    S+   00:42   0:00 ../salty.Linux-x86_64 server 127.0.0.1:11110
mattb     846093  0.3  0.6  70744 53748 pts/4    S+   00:42   0:00 ../salty.Linux-x86_64 server 127.0.0.1:11110
`

Send TERM to the Nuitka version, it also exits "Terminated" - but leaves the child process running:
`
(.venv) mattb@brix:~/src/mattb/salty master$ kill 846092
(.venv) mattb@brix:~/src/mattb/salty master$ ps aux | grep salty | grep -v grep
mattb     846093  0.2  0.6  70744 53748 pts/4    S    00:42   0:00 ../salty.Linux-x86_64 server 127.0.0.1:11110
`

**Comment by kayhayen** [comment]
I agree, however, I think that SIGTERM to Python should be converted to SIGINT to the child. In fact, that should be trivial to add, and I agree it's kind of a deficit. I do not think, the signal should be passed on to the client. In many cases, e.g. SIGINT these are bound to the terminal group, and we were seeing duplication of signaling there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

The handling of SIGINT, SIGTERM and SIGQUIT is now just identical. Please rerun your tests to confirm the improvement. Beware the gace time allowed for the child to handle CTRL-C before doing SIGKILL on it, it may survive 5s in case it's misbehaving to CTRL-C, e.g. catching and ignoring it.

**Comment by mattbillenstein** [comment]
> I agree, however, I think that SIGTERM to Python should be converted to SIGINT to the child. In fact, that should be trivial to add, and I agree it's kind of a deficit. I do not think, the signal should be passed on to the client. In many cases, e.g. SIGINT these are bound to the terminal group, and we were seeing duplication of signaling there.

Why do you feel this should convert SIGTERM and SIGQUIT to SIGINT? Why ignore SIGHUP and SIGUSR*, etc?

It seems non-obvious to me that the compiled python program should see different signals in these cases when run under onefile vs run under python3, or even another nuitka run mode.

**Comment by kayhayen** [comment]
My goal is for this to be simple to use. People rarely convert existing programs, but just expect their program to work sensible, Python chooses to convert one of these signals to a code visible exception, which makes sense, such that code cleanup works nicely. Having to install signal handlers is not nice.

If I am not mistaken, SIGHUP is used by daemons to cause a reload. If there was an expansion to the tests of onefile made, that covers this propagation, I would maybe implement that. And maybe, even change the others to also do that. But not having a test that shows this works is a bummer.

But I think what I did, works for all the desired use cases. Now onefile is no longer stopped immediately and without cleanup, and the child gets to do cleanup handling that it is already required to do.

Forwarding SIGUP and SIGUSR would be nice to have too.

I made this other change part of 1.6.5 already, because it was too trivial to fail. But I don't think I want to carry signal handling like that, without tests that show it works.

I am absolutely open to a PR there, but one that includes test modifications. The pressing issue is solved in my book though, therefore I am closing it. For SIGHUP I invite you to open a new issue, maybe even with example code, of the signal not being delivered, etc. such that it can form the basis of such test enhancements. 

Right now I only have `tests/onefile/KeyboardInterruptTest.py` and that is something that would be needed to do more of these changes.
