### ISSUE TITLE
Nuitka resolves prebuilt module from watchfiles lib on macOS wrong

### ISSUE THREAD

**Issue by Aksem** [Nuitka/Nuitka#1844]
**Problem:** compilation of app in which [watchiles](https://github.com/samuelcolvin/watchfiles) library is used(just import is enough) fails on macOS. Nuitka resolves a module to `_rust_notify.cpython-310-darwin.so`, but library file is `_rust_notify.abi3.so`. If I create a copy of `_rust_notify.abi3.so` with file name `_rust_notify.cpython-310-darwin.so` before compilation, it doesn't fail anymore, and the app works.

Watchfiles is a library implemented in Rust, and its distribution includes the prebuilt module _rust_notify.

On Linux and Windows, the compilation is successful, and the app works as expected.

Repository with minimal example and CI: https://github.com/Aksem/nuitka_compile_watchfiles_bug

**Environment:**
```
1.1.5
Commercial: None
Python: 3.10.7 (main, Sep  6 2022, 15:18:47) [Clang 12.0.0 (clang-1200.0.32.29)]
Flavor: Unknown
Executable: /Users/runner/Library/Caches/pypoetry/virtualenvs/nuitka-load-module-regression-cKtR2lP0-py3.10/bin/python
OS: Darwin
Arch: x86_64
```
**Nuitka version:** tested both 1.1.5 and factory versions. Installed in pyenv environment via poetry.

**Compilation error:**
```bash
FATAL: Error, failed to find path @rpath/_rust_notify.cpython-310-darwin.so (resolved DLL to /Users/runner/Library/Caches/pypoetry/virtualenvs/nuitka-load-module-regression-cKtR2lP0-py3.10/lib/python3.10/site-packages/watchfiles/_rust_notify.cpython-310-darwin.so) for /Users/runner/Library/Caches/pypoetry/virtualenvs/nuitka-load-module-regression-cKtR2lP0-py3.10/lib/python3.10/site-packages/watchfiles/_rust_notify.abi3.so, please report the bug.
```

**Comment by kayhayen** [comment]
So, this is probably another case of DLLs being disguised as extension modules, and then also having an idea about what the extension module suffix should be, which is a very bad practice. I will have to check it out, if that's what's going on.

**Comment by kayhayen** [comment]
So, no, it's actually an extension module, and I didn't look closely enough. So in this case what's going on, is that the dependency on itself for an extension module on the macOS link level (whatever good it is for) is now wrong, and didn't get updated, because it doesn't see the file as matching.

This is actually a general issue. I am assuming, this is because of rust building an extension module here. I wonder if these self dependencies can be deleted without any harm taken.

**Comment by kayhayen** [comment]
Now this is crazy:

```
otool -L /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/watchfiles/_rust_notify.abi3.so
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/watchfiles/_rust_notify.abi3.so:
        @rpath/_rust_notify.cpython-310-darwin.so (compatibility version 0.0.0, current version 0.0.0)
```

But there is no such file. This is obviously an attempt at providing a self-reference, that has gone wrong, and Nuitka is sensitive to it, and now I don't have a clue why this works in CPython at all.

**Comment by Aksem** [comment]
Yes, you are right. `LC_ID_DYLIB` is wrong in _rust_notify.abi3.so. So it seems to be a problem in the build of watchfiles. I'll try to build it by myself and analyze the results. It doesn't make much sense to try to fix this on nuitka level but in watchfiles. I'll also open an issue in the watchfiles repo.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

Turns out, we can just accept filenames that are only different by more or less specific ABI naming under Python3, and it just works. This will come to a hotfix of 1.1 as it should be unproblematic, only catching cases that wouldn't work before.

**Comment by Aksem** [comment]
The factory branch works, thanks for the fix!

**Comment by kayhayen** [comment]
Can you also make reports to the rust upstream builds for the issues, I think having this wrong is not good, and not checking failed Python import and segfaulting is also not quite the standard. A bunch of C level bindings are better than Rust there it seems. ;-)

Yours,
Kay

**Comment by Aksem** [comment]
Fixed in maturin(rust toolset) as well: https://github.com/PyO3/maturin/pull/1208

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.1.6 that I just made.
