### ISSUE TITLE
Is it possible to build a `--onefile` app for Windows that doesn't open its own console, but will allow text output if run from a terminal?

### ISSUE THREAD

**Issue by mikenerone** [Nuitka/Nuitka#1847]
I'm aware of `--disable-console`, of course, and of the `--windows-force-stdout-spec` approach explained in #997, but I'm wondering if there's a set of options, or some other trick you might suggest, that would allow an app to be usefully run via the CLI if desired, with text output, etc., while also _not_ opening a console window when run via the icon on Windows. In my current case, it would be useful to give my app a `--no-gui` kind of option to facilitate this, but I haven't been able to make that jive with Windows` console behavior since the flag is on the executable as a whole. Any advice would be appreciated.

**Comment by kayhayen** [comment]
I believe that is not possible in Windows. I don't know if you can open a console after the fact, if you run from `pythonw.exe` (the GUI python). For macOS it should be possible, and I definitely might get that to work, because I think they dropped `pythonw` there at some point.

If you figure out how to do it with `pythonw.exe`, we surely can mimic that, but I believe due to security, there is no access to your launching console after you did that. However, opening a new console could be done by launching `cmd.exe` or `powershell.exe` with some sort pass through script, where the script echos all outputs and passes on inputs. Maybe somebody did something like that already. It's definitely beyond my scripting skills for Windows, but powershell surely seems like it can do these tricks.

**Comment by mikenerone** [comment]
Yeah, that's what I thought. Thanks very much for your response. If I do discover a way to accomplish it, I'll share it here.
