### ISSUE TITLE
After being compiled by nuitka, all spawned child processes are the main process

### ISSUE THREAD

**Issue by oldworldblue** [Nuitka/Nuitka#1889]
nuitka --version
1.2
Commercial: None
Python: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\eliot\Desktop\py310_slot\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

Requirements:
beautifulsoup4==4.11.1
bs4==0.0.1
certifi==2022.9.24
charset-normalizer==2.1.1
et-xmlfile==1.1.0
greenlet==2.0.1
idna==3.4
lxml==4.9.1
Nuitka==1.2
openpyxl==3.0.10
psutil==5.9.4
pycryptodome==3.15.0
PySide6==6.4.0.1
PySide6-Addons==6.4.0.1
PySide6-Essentials==6.4.0.1
requests==2.28.1
shiboken6==6.4.0.1
soupsieve==2.3.2.post1
SQLAlchemy==2.0.0b3 
typing_extensions==4.4.0
urllib3==1.26.12
XlsxWriter==3.0.3

## Here is question
I`m trying to make a gui application, it will perform some parallel tasks with concurrent.futures.processpoolexecutor.

But because several modules are imported in this project, after the subprocess is created, a lot of memory consumption is generated before the task function is executed. But the function of the parallel task has only a few lines of code and does not need these modules at all, so a line of code is added to prevent it from importing certain modules under the subprocess, like the following:
```python
from multiprocessing import current_process

# Let the process wait, which is enough to explain the situation in this example
def case():
    time.sleep(10)

if current_process().name.startswith('MainProcess'):
    import abc
    import traceback
    from traceback import format_exc
    from typing import Optional, Callable

    from PySide6.QtCore import Qt, QByteArray
    from PySide6.QtGui import QIcon, QStandardItemModel, QCursor, QGuiApplication, QPixmap
    from PySide6.QtWidgets import (QSystemTrayIcon, QMainWindow, QMenu, QPushButton, QTableView, QDialog, QVBoxLayout,
                                   QLabel, QLineEdit, QHBoxLayout, QApplication, QFrame, QComboBox, QMessageBox, QWidget)
    from requests.exceptions import ConnectionError, ConnectTimeout, ReadTimeout, SSLError

    ...
    for i in range(4):
        process_pool.submit(case)
    
    # memory usage in window task manager like this when create many tasks and optimized
    # MainProcess: 52MB
    # -SubProcess: 18MB
    # -SubProcess: 18MB
    # -SubProcess: 18MB
    # -SubProcess: 18MB
```
And this does save some memory. Before this line of code, creating a new child process will consume about 50MB of memory even if it does nothing. After adding this line of code, it will only be 18MB, and the parallel task can be executed normally.

But when I use the same code to run after nuitka packaging, the situation changed. Creating a new child process still consumes as much memory as the main process.
```python
    # nuitka compiled, i tryed include --standalone or not include that, but same result.
    # MainProcess: 52MB
    # -SubProcess: 48MB
    # -SubProcess: 47MB
    # -SubProcess: 48MB
    # -SubProcess: 48MB
```

This program will be made available to others. During the running of the program, 6~10 child processes  or more may be created, which will cause a lot of memory consumption. Everyone's computer configuration is different, and I want to keep the memory requirements as low as possible. I noticed that something seems to be done to the multiprocess module during the python script compiled by nuitka, but I don't know how to solve this problem.

I may have found where the problem is.
Run nuitka compiled executable, from the output log, no process is a child process, all processes created through ProcessPoolExcutor are the main process, but I have enabled multiprocessing.freeze_support() and multiprocessing plugin is default include when nuitka compiling
```python
2022-11-16 12:23:41 | MainProcess:19440 | config:78 | INFO | config file load done
2022-11-16 12:23:42 | MainProcess:19440 | session:404 | INFO | session manager start
2022-11-16 12:23:42 | MainProcess:19440 | main:105 | INFO | app start
also imported
also imported
also imported
also imported
also imported
also imported
also imported
also imported
2022-11-16 12:23:45 | MainProcess:20064 | config:78 | INFO | config file load done
also imported
also imported
also imported
2022-11-16 12:23:45 | MainProcess:6408 | config:78 | INFO | config file load done
also imported
2022-11-16 12:23:45 | MainProcess:19348 | config:78 | INFO | config file load done
2022-11-16 12:23:45 | MainProcess:18892 | config:78 | INFO | config file load done
2022-11-16 12:23:45 | MainProcess:16640 | config:78 | INFO | config file load done
2022-11-16 12:23:45 | MainProcess:3760 | config:78 | INFO | config file load done
2022-11-16 12:23:45 | MainProcess:20064 | session:404 | INFO | session manager start
2022-11-16 12:23:45 | MainProcess:19348 | session:404 | INFO | session manager start
2022-11-16 12:23:45 | MainProcess:6408 | session:404 | INFO | session manager start
2022-11-16 12:23:45 | MainProcess:16640 | session:404 | INFO | session manager start
2022-11-16 12:23:45 | MainProcess:3760 | session:404 | INFO | session manager start
2022-11-16 12:23:45 | MainProcess:18892 | session:404 | INFO | session manager start
```

**Comment by kayhayen** [comment]
I don't think Nuitka can statically optimize this: `if current_process().name.startswith('MainProcess'):`, so the code will be there, but not necessarily the memory. I recall checking before, if process names are compatible, and I thought they were.

**Comment by kayhayen** [comment]
I kind of hate it when I paste examples into an editor and immediately finds it incomplete.

**Comment by kayhayen** [comment]
Due to the bad quality of the report, I am assuming false report in the sense, that you misevaluated the memory usage. Naturally every launched process includes e.g. the PySide code, and its constants data, but it is not initialized before being used, and loaded as a Windows resource, which I think does not necessarily mean it's in memory, but only part of the virtual memory and probably shared by the OS internally.

However, traces of a program I do not have do me no good.

I used this program:

```
import time
from concurrent.futures import ProcessPoolExecutor
from multiprocessing import current_process


def run():
    print(current_process().name)
    time.sleep(1)


def main():
    with ProcessPoolExecutor(max_workers=3) as pool:
        pool.submit(run)
        pool.submit(run)
        pool.submit(run)


if __name__ == "__main__":
    main()
```

to verify. 

I am open to an assessment of actual memory usage, but so far I don't even know where the number is from that you presented, but so far it's unclear if the problem is not in your measurement. Nuitka compiled code will e.g. also be large and while shared by the OS internally, may easily be attributed to things. I think you need better numbers to convince me of the issue.

**Comment by 0x446** [comment]
@oldworldblue You are most likely being confused by the way Python works.
Python itself is not really intended to be used as a multithreaded/multiprocessed language. Because of GIL (Global interpreter lock, see https://realpython.com/python-gil/#how-to-deal-with-pythons-gil), each process created by multiprocessing runs its own slimmed down python interpreter.
The only thing that differs when such subprocesses are being spawned *on Windows* is the fact that it will *skip* the main routine that's defined under your `if __name__ == '__main__'` condition on your entry point of the application.
It then resolves the includes and goes to whatever file it needs to work with (in your example the one where the `case()` method lies.
It only executes this method and everything that's being referenced by it (see https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).
> ...from the output log, no process is a child process, all processes created through ProcessPoolExcutor are the main process...
Now this might be misleading. As you're under windows and when taking in account what I explained above, each subprocess runs as its own python interpreter. If you want to properly log messages from them, you might need to catch their standard / error outputs and redirect them to your main process using a `multiprocessing.Queue`.
If you do not do that, the stdout and stderr channel get rerouted to your main process by multiprocessing's logic which then indeed uses the logger of your main process which is why you're seeing the `MainProcess:nnn` in your log output.

Now that being said, I don't know that much about how Nuitka translates all of that into native C code and if it keeps process names and such, but you usually want to have your imports that are only being used by your child processes in the `run()` method (or in your case the `case()` method).
If there's anything else that your main process imports, that should be handled through a proper main routine (see https://docs.python.org/3/library/multiprocessing.html#programming-guidelines).

**Comment by 0x446** [comment]
@oldworldblue You are most likely being confused by the way Python works.
Python itself is not really intended to be used as a multithreaded/multiprocessed language. Because of GIL (Global interpreter lock, see https://realpython.com/python-gil/#how-to-deal-with-pythons-gil), each process created by multiprocessing runs its own slimmed down python interpreter.
The only thing that differs when such subprocesses are being spawned *on Windows* is the fact that it will *skip* the main routine that's defined under your `if __name__ == '__main__'` condition on your entry point of the application.
It then resolves the includes and goes to whatever file it needs to work with (in your example the one where the `case()` method lies.
It only executes this method and everything that's being referenced by it (see https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods).
> ...from the output log, no process is a child process, all processes created through ProcessPoolExcutor are the main process...

Now this might be misleading. As you're under Windows and when taking in account what I explained above, each subprocess runs as its own python interpreter. If you want to properly log messages from them, you might need to catch their standard / error outputs and redirect them to your main process using a `multiprocessing.Queue`.
If you do not do that, the stdout and stderr channel get rerouted to your main process by multiprocessing's logic which then indeed uses the logger of your main process which is why you're seeing the `MainProcess:nnn` in your log output.

Now that being said, I don't know that much about how Nuitka translates all of that into native C code and if it keeps process names and such, but you usually want to have your imports that are only being used by your child processes in the `run()` method (or in your case the `case()` method).
If there's anything else that your main process imports, that should be handled through a proper main routine (see https://docs.python.org/3/library/multiprocessing.html#programming-guidelines).

**Comment by kayhayen** [comment]
Nuitka also supports spawn mode on Linux, I am very familiar with multiprocessing, far more than I want to be. 

I was looking for actual measurements from you, detailing the methods used. For now I am perfectly valid in assuming that the report is unfounded in the conclusions you draw. There may ne non-optimal behavior, but you have not proviced any evidence.
