### ISSUE TITLE
Onefile finding files documentation suggestion

### ISSUE THREAD

**Issue by Bingdom** [Nuitka/Nuitka#1919]
For this part of the documentation:
https://nuitka.net/doc/user-manual.html#use-case-4-program-distribution

Can we make it include a warning about how we can make onefile properly access files? Preferably referencing this: 
https://nuitka.net/doc/user-manual.html#onefile-finding-files

It took me quite a bit of time to actually learn what was causing this problem, and about to submit an issue- only to find the answer further down the docs under a different section!

**Comment by kayhayen** [comment]
Yes, you are correct, going from standalone onefile is a no-brainer except for this one thing, and it should be pointed out.

**Comment by kayhayen** [comment]
I added that reference, and also updated a few information pieces there, it is much less Windows specific for many things now. I am closing the issue early due to lack of general relevance. You can see in on branch factory.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Now on the develop branch, will be in 1.3 shortly

**Comment by kayhayen** [comment]
This is part of the stable release 1.3 that I just made.
