### ISSUE TITLE
RDkit standalone does not run on Windows

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#1929]
* Nuitka version, full Python version, flavor, OS, etc. 
```
> python -m nuitka --version
Nuitka-Options:INFO: Used command line options: --version
1.3rc6
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\GregorGiesen\rdkit\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

* How did you install Nuitka and Python

Using a virtualenv with pip from the Git checkout of Nuitka.

* The specific PyPI names and versions

```
  > python -m pip freeze
Nuitka @ file:///C:/Users/<USER>/rdkit/Nuitka
numpy==1.23.5
ordered-set==4.1.0
Pillow==9.3.0
rdkit-pypi==2022.9.2
```

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
The following code `rdkit_test.py`
```
from rdkit.rdBase import rdkitVersion
print(rdkitVersion)
```

should print `2022.9.2` but compiled using 
```
python -m nuitka --standalone --include-package=rdkit --plugin-enable=numpy rdkit_test.py
```
yields instead

```
Traceback (most recent call last):
  File "C:\Users\<USER>\rdkit\RDKIT_~1.DIS\rdkit_test.py", line 1, in <module>
  File "C:\Users\<USER>\rdkit\RDKIT_~1.DIS\rdkit\__init__.py", line 22, in <module rdkit>
ImportError: LoadLibraryExW 'C:\Users\<USER>\rdkit\RDKIT_~1.DIS\rdkit\rdBase.pyd' failed: The specified module could not be found.
```

**Comment by grgi** [comment]
On Linux, above example works well.

**Comment by kayhayen** [comment]
Thanks for the report, this is using delvewheel, which ought to work, need to check out what is holding it back there.

**Comment by kayhayen** [comment]
i have just pushed a bit of anti-bloat work to factory branch which makes compilation a lot smaller, since it avoids including IPython which is terrible to have. However, the DLL inclusion seems to work, and still the extension module fails to load, this might be some sort of C runtime incompatibility.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

I am also preparing the hotfix release 1.3.7 with this fix contained.

Turns out, that the module extension loader of Nuitka didn't allow them to use DLLs from `os.add_dll_directory` which has been added now. Versions 3.8 or higher were affected of course only. It seems that `rdkit` was exposing this bug in the way these extension modules were loaded.

**Comment by grgi** [comment]
Thank you, the factory branch version is working. We are looking forward to 1.3.7!

**Comment by kayhayen** [comment]
The hotfix was released, I forgot the factory tag, so this escaped my attention.
