### ISSUE TITLE
Zeroconf crashes in standalone mode

### ISSUE THREAD

**Issue by trapezoid677** [Nuitka/Nuitka#2033]
1.4.1
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\bugs\zeroconf\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).

###   **> python -m pip freeze**

async-timeout==4.0.2
ifaddr==0.2.0
Nuitka==1.4.1
zeroconf==0.47.1

### **Example code:**

```
import zeroconf
print(zeroconf.Zeroconf())
```

### **Nuitka Options:**

python -m nuitka --mingw64 --standalone --run main.py

### ** Note if this is a regression**

It used to work with Nuitka 1.3.8 even in standalone mode

**Comment by kayhayen** [comment]
This not working feels kind of surprising, but since it's a regression, I am going to bisect this now. I was briefly looking at DLLs and data-files, but no DLLs and the data files do not solve the issue. I am getting this one.

```
Traceback (most recent call last):
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\Mini.py", line 2, in <module>
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\zeroconf\_core.py", line 450, in __init__
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\zeroconf\_utils\net.py", line 360, in create_sockets
  File "C:\Users\kayha\repos\Py2C\MINI~1.DIS\zeroconf\_utils\net.py", line 153, in normalize_interface_choice
RuntimeError: No interfaces to listen on, check that any interfaces have IP version IPVersion.V4Only
```

**Comment by kayhayen** [comment]
The git bisect shows this to be a bug of the new list method optimization. I will have to try and find out what excactly is being mis-optimized there. In 1.4.2 there was already a fix for problems with the list, but that one was more of the crashing kind, not having this symptom, and I reproduced still with factory version.

**Comment by kayhayen** [comment]
Ah, I think it's understood. The `result.extend()` before it is optimized into the specific operation, annotates result as escaped. Afterwards, it does too. But for the micro pass, where it comes into existance, it does not. And then boolean optimization of the variable gets a chance to optimize `not the_list_value` to `False` only seeing it initialized from empty.

This is actually a problem that should be demonstrable with `dict` code too. I distinctly recalled wanting to start with `dict` so these kinds of issues would already be ironed out, but alas, with dictionaries, methods are barely used in production code, so i guess that is why I never saw it. It also requires e.g. the code to be in a branch, to get the timing right. This will be fixed in 1.4.3 as soon as possible. The fix is of course to do in that call optimization the escaping that the default uncognized call does.

**Comment by kayhayen** [comment]
I have a fix for this, that I want to see run through my internal CI first. It changes the attribute node generation such that the "list.extend" re-representing node properly annotates that its values must be considered escape, even before the call one, `list.extend()` comes to exist. This made the bug go away. I also changed how call nodes interact with calls for value escape, to make the code to re-use more trivial.

I am hoping to put this into a 1.4.3 after the test suites completed. The zeroconf compiles. I will put it on the factory branch soon, and staging once I feel it's not obviously broken.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment]
I also updated staging, and there will be a 1.4.3 hotfix release starting soon.

**Comment by trapezoid677** [comment]
The fix works well
