### ISSUE TITLE
Possible tiny optimization for Python 3.9+

### ISSUE THREAD

**Issue by gdementen** [Nuitka/Nuitka#2059]
I noticed the call helpers use the public API Py_EnterRecursiveCall and Py_LeaveRecursiveCall but those are no longer macros/inline functions in Py3.9+. Assuming using the internal API is fair game (IIRC you use it already), you could use _Py_EnterRecursiveCall  and _Py_LeaveRecursiveCall instead.

**Comment by kayhayen** [comment]
This is deceipful code, but Nuitka does this:

```
#ifndef _NUITKA_FULL_COMPAT
// Remove useless recursion control guards, we have no need for them or we
// are achieving deeper recursion anyway.
#undef Py_EnterRecursiveCall
#define Py_EnterRecursiveCall(arg) (0)
#undef Py_LeaveRecursiveCall
#define Py_LeaveRecursiveCall()
#endif
```

So unless `--full-compat` is specified, it's not done, which is only happening when running Nuitka tests. This can in fact be improved however, my CI might like it.

**Comment by gdementen** [comment]
Thanks for the explanation, and sorry for the noise. I thought this would be required for module mode (but not  for standalone).

**Comment by kayhayen** [comment]
It is still valid information, slowing down my CI is not a good thing either. It is just not generally all relevant outside of the CPython test suites, etc.

My hunt for API functions is on hold while I finish 3.11 compatibility now, but I will surely resume, and this made me aware to also consider `--full-compat` as a valid use case. On Windows, it may well give a bunch of CPU savings.

**Comment by kayhayen** [comment]
Ah, these macros want a ``tstate``. But Nuitka is not yet good at passing it around sufficiently. I guess that means we would have to do our own variant there, but will then make this part of a bigger change that allows e.g. call code to have it passed by the raiser, such that e.g. `Nuitka_CheckFunctionResult` and others will have it more often. I need to convince myself of the cost that comes with `PyThreadState_GET()` and its use of `_Py_atomic_load_relaxed` vs. the cost of passing the pointer, I guess, in the general case without inlining chances, it has to be avoided. I will put this to delayed until I draw the line for exception handling specifically, and if e.g. framed code, would get and store this pointer where there is no chance of switching threads (i.e. outside of generators, coroutines, asyncgen). Then this will be solvable easily.

**Comment by kayhayen** [comment]
The macros are themselves creating a tstate, doing the check there, only the error itself is reported via an API call, which would be fine. In the new code, rather than a macro, an inline function is used, which is acceptable, same effect as a macros. The fact that no tstate is passed, doesn't appear to be much of an issue, no caller seems to close to having it.

I do not believe that there should be a considerable slowdown from this. I will check out `--full-compat` specifically when I try to look at API calls next time. But I do not believe there is this issue. For 3.11 I do not think I did it yet that tracing, so probably I can combine that.

But generally, I do not think this is a real optimization improvement.
