### ISSUE TITLE
"Error, couldn't find attached data. The parameter is incorrect."

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2080]
OS: Windows 10 21H2
Python: 3.11.2
Nuitka: 1.5rc11

After building with `nuitka project/project.py --trace-execution --quiet --onefile --static-libpython=no --enable-plugin=pyside6 --include-module=pytest --include-module=_pytest --include-module=unittest --nofollow-import-to=setuptools --nofollow-import-to=tkinter --windows-icon-from-ico=project/icon/favicon.ico`, the executable fails *once*, and works immediately afterwards:

```
(project_dev) C:\code\project>project.exe
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
Error, couldn't find attached data.
The parameter is incorrect.

(project_dev) C:\code\project>project.exe
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
ONEFILE: Determining payload start position.
ONEFILE: Checking header for compression.
ONEFILE: Entering decompression.
ONEFILE: Finishing decompression, cleanup payload.
ONEFILE: Preparing forking of slave process.
ONEFILE: Started slave process.
main(): Entered.
```

I will work on producing a minimal example, but I'll report this now in case this is a known or easily fixed issue. There is multiple code paths that emit "Error, couldn't find attached data", but I guess the traces show it must be this one:

https://github.com/Nuitka/Nuitka/blob/d394679cb31b301806a53fee7461fbeb3fc82125/nuitka/build/static_src/OnefileBootstrap.c#L241-L246

**Comment by bersbersbers** [comment]
This happens with an `empty.py` as well - an right now, it happens multiple times in a row:

```
(project_dev) C:\code\project>nuitka empty.py --trace-execution --quiet --onefile --static-libpython=no --enable-plugin=pyside6 --include-module=pytest --include-module=_pytest --include-module=unittest --nofollow-import-to=setuptools --nofollow-import-to=tkinter --windows-icon-from-ico=project/icon/favicon.ico
Nuitka:WARNING: The Python version '3.11' is not officially supported by Nuitka '1.5rc11', but an upcoming release will change that. In the mean time use Python version '3.10' instead or newer
Nuitka:WARNING: Nuitka.
                                                                                       
(project_dev) C:\code\project>empty.exe
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
Error, couldn't find attached data.
The parameter is incorrect.


(project_dev) C:\code\project>empty.exe   
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
Error, couldn't find attached data.
The parameter is incorrect.
```

**Comment by kayhayen** [comment]
This should happen to you with every version of Python, it's in code that isn't even using it, or so I would be thinking. My suspect is that your AV tool is not done with the file, and won't let the onefile access it yet. I have never observed it, but memory mapping the payload of onefile has be done in stable Nuitka as well. I would be interested if you can reproduce it on stable Nuitka with 3.10, you should. 

But now that I think of it, maybe the error was ignored before, but no longer is so.

**Comment by kayhayen** [comment]
So, provided this is reproducible for you, I suggest what I will do now, is to pass the error code back to calling code, and make the error exit indicate the value. Then we will know for sure what you get there. It would be nice to be more robust either way. 

I think memory mapping on Windows was relegated to check sum tests for cached onefile mode. And there it gracefully degraded to just not using the cache. So it may not be as reliably usable as the performance work wants it to be.

**Comment by bersbersbers** [comment]
> So, provided this is reproducible for you
It is!

> I suggest what I will do now, is to pass the error code back to calling code, and make the error exit indicate the value. Then we will know for sure what you get there. It would be nice to be more robust either way.

Sounds good - let me know when I shall continue testing (and I will see if I can test Python 3.10 as well).

**Comment by kayhayen** [comment]
I was checking with docs, and it seems I was comparing `CreateFileW` return value to `NULL (0)` rather than `INVALID_HANDLE (-1)` and now I wonder if it could spuriously happen for you that the handle has a value of `0`, or that a `CreateFileW` error, that is caused by a virus scanner blocking the fresh file remains undetected, and then the `-1` passed into `CreateFileMappingW` would require a file size, since it would be creating an anonymous mapping.

The later would make all sense to me. The first one I don't buy.

**Comment by kayhayen** [comment]
So, I updated factory with the enhancement to output the failing function of memory mapping. I didn't apply it to all function unlike I originally intended, but just the one where it fails what you see, so we can know it sooner.

And I fixed the wrong return value check, and audited Nuitka to not do it elsewhere, which it does not. Unfortunately I believe, in CRC32 checking, this bug was already present (on WIndows), but entirely harmless, since failed checksum calculation was not going to be an issue. I am tempted to rebase develop branch if this proves to be a fix, to retain git bisect for Windows.

We may now see that `CreateFileW` fails, and it might be due to AV preventing to opening of the executable for reading. If that's what's going on, it would be kind of surprising (are we not executing it in that very moment already, why is opening it for shared read an issue, or do we not share?).

Anyway, let me know how this works for you as soon as you can.

**Comment by bersbersbers** [comment]
Built with a9ad19b80f019c2b1e6fcf511322a7692e325d2b:
```
(project_dev) C:\Code\project>empty2.exe         
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
Error, couldn't find attached data:CreateFileW
The process cannot access the file because it is being used by another process.
```

SysInternals Process Explorer does not show a handle at all (run as Admin):
![image](https://user-images.githubusercontent.com/12128514/221431727-6c1f25db-0e7c-46ec-a6f0-dec847dc1504.png)

Process Monitor (filters: Path ends with empty2.exe, Result is not Success):
![image](https://user-images.githubusercontent.com/12128514/221432155-2a81cb16-2163-4bc4-9b49-0134db68f26e.png)

**Comment by kayhayen** [comment]
So, indeed, I believe this has to be AV tool or something like this. The solution there is typically to retry. But I also should make sure that `GENERIC_READ` is asking for shared access and not exclusive, the AV tool may only be a reader and not locking. From the error, this is not clear to me yet.

**Comment by bersbersbers** [comment]
> So, indeed, I believe this has to be AV tool or something like this. 

Possible! MsMpEng.exe would be one, vf_agent.exe a potential other one.

> The solution there is typically to retry. 

I am almost sure you mean retrying internally - but for the record: for `empty2.exe`, retrying never works. For `project.exe`, the 90 MB executable file with `pytest` etc, it usually fails only once and retrying working immediately.

> But I also should make sure that `GENERIC_READ` is asking for shared access and not exclusive, the AV tool may only be a reader and not locking.

Let me know if another Process Monitor output including SUCCESS calls will help with that.

**Comment by kayhayen** [comment]
Thanks for the great reply btw, the old code did use the same `CreateFileW` and so, this is not a regression likely. It's just that the code then checked for `INVALID_HANDLE_VALUE`. So the failure from within the title, is indeed from that bug, but that's just a corruption of the symptom. Stable Nuitka should give you `"Error, failed to access unpacked executable." and the same error.

I didn't properly get what you said about `empty` never working. I guess, executing the program triggers the AV to look at it briefly, if only to find out what it is about. 

I therefore think the only option the onefile bootstrap has there is to retry while running. With a delay and up to a timeout value of say 5 seconds. And of course, only if this is for the main executable, not for CRC32 checks, and only for the error code you have there.

**Comment by bersbersbers** [comment]
> I didn't properly get what you said about empty never working.

This :)
```
> empty2.exe
(fails)
> empty2.exe
(fails)
> empty2.exe
(fails)

> project.exe
(fails)
> project.exe
(works, for whatever reason)
```

Maybe AV caches results for big files.

> I guess, executing the program triggers the AV to look at it briefly, if only to find out what it is about.

Sounds reasonable, yes.

**Comment by kayhayen** [comment]
The information One comment mentions that `STATUS_FILE_LOCKED_WITH_ONLY_READERS` would not really be an error, and generally the hit rate of Google is very low. But I guess, we can handle it. Hold on, I will soon have it for you to try.

**Comment by kayhayen** [comment]
So, I pushed something that will make 50 retries with 0.1s delays in between. I didn't make a difference what caller it is, but you should see different behaviour now.

**Comment by kayhayen** [comment]
Hm, I went back to `CreateFileW` docs and it seems `0` as used by the onefile binary there is the least tolerant. Checking for other uses in Nuitka, funnily enough the anti-debugger plugin does `FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE` and I think, that is probably what I intended `0` to be, but it is quite the opposite. Let me put that, and then I think the error code you get becomes impossible to occur.

**Comment by kayhayen** [comment]
So, what probably happened then is that it's a race between AV and Nuitka. Nuitka is attempting to lock exclusively, and that can only succeed of the AV is not yet reading it. The race probably is dependent on your machine performance to become interesting, and size seems to matter. But since Nuitka no longer locks anything, it and AV will be able to coexist from here on peacefully on factory.

I believe that 1.4.8 should behave the same for you. Would you verify that the problem is gone on factory, and then try stable Nuitka as well, if it happens to show the error too? The code is having the `0` value for sharing too, and ought to also be affected, and maybe that gives rise to the idea of a 1.4.9 even, while I proceed to make a 1.5 short after. Surely now I think I know this is not about regression at all, but it would be nice if you confirmed it to be an improvement to stable as well.

Yours,
Kay

**Comment by bersbersbers** [comment]
35ea25e48383b8a4d6a2a356b835867f87e20c71 works somewhat, in the sense that it works once after building:
```
>empty4.exe
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
ONEFILE: Determining payload start position.
ONEFILE: Checking header for compression.
ONEFILE: Entering decompression.
ONEFILE: Finishing decompression, cleanup payload.
ONEFILE: Preparing forking of slave process.
ONEFILE: Started slave process.
main(): Entered.
```
but then never again :( Interestingly, when it does fail, it fails in much less than 5 seconds, so I wonder if the timeout is working properly.

Noticed that that commit was force-pushed away, so next up is a0602e5c2fd53fc62034b1cc91a06695b5735957. That one is working reliably :)

Will need to install Python 3.10 to test stable (right?), but I see how it can be interesting for you to know, so I am probably going to do that late tomorrow. Thanks so far!

**Comment by kayhayen** [comment]
You can use --experimental=python3.11 on stable, but I am not sure if will do onefile honestly, so 3.10 would be required most likely. But I can also just assume that the problem would be there, you confirming it is not really necessary, since the CreateFile has the same bug in stable already. But it sure would be nice.

**Comment by bersbersbers** [comment]
Alright, more tests:

- 1.4.8 (from PyPI) on Python3.10 works fine:
```
(project_3.10) C:\code\project>pip show nuitka
Name: Nuitka
Version: 1.4.8
Summary: Python compiler with full language support and CPython compatibility
Home-page: https://nuitka.net
Author: Kay Hayen
Author-email: Kay.Hayen@gmail.com
License: Apache License, Version 2.0
Location: c:\users\bers\.pyenv-win-venv\envs\project_3.10\lib\site-packages
Requires:
Required-by:

(project_3.10) C:\code\project>echo.>empty.py

(project_3.10) C:\code\project>nuitka empty.py --trace-execution --quiet --onefile --static-libpython=no
                                                                                                        
(project_3.10) C:\code\project>empty.exe   
ONEFILE: Entered main().
ONEFILE: Unpacking payload.
ONEFILE: Preparing forking of slave process.
ONEFILE: Started slave process.
main(): Entered.
main(): Prepare standalone environment.
```

- Develop on Python 3.11 still fails.
- Factory on Python 3.11 still works.

**Comment by bersbersbers** [comment]
- Develop on Python 3.10 fails.

**Comment by kayhayen** [comment]
From the source code review, 1.4.8 ought to have been affected too, since the `CreateFileW` there was locking too. Maybe because the error check was wrong, and never fired, it ended up giving other errors, or something. Since it's a race, it might not be reliable. But Nuitka not even temporarily locking the binary for anything, clearly must be an improvement.

**Comment by kayhayen** [comment]
This is now on develop and will be release as part of 1.5 shortly.

**Comment by kayhayen** [comment]
This is part of the stable release 1.5 that I just made.
