### ISSUE TITLE
Can Nuitka consider supporting zig?

### ISSUE THREAD

**Issue by vinayinvicible** [Nuitka/Nuitka#2082]
**Intro**
Zig as a language and it's [GCC/Clang replacement](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html) is gaining popularity in recent times. Zig also has it's own [build system](https://ziglearn.org/chapter-3/) that can replace scons.

**Problems it can solve**
- Zig build system can replace scons. Right now multiple versions of scons are being vendored along side Nuitka for various reasons. This will no longer be necessary.
- Zig build has builtin cache system. So, no need for ccache.
- Zig build has first class support for cross compilation.
- Zig has a builtin compiler which can be a replacement for gcc/clang/mvsc. This means even less system dependencies.
- Zig even provides a [pypi package](https://pypi.org/project/ziglang/) for convenience. This means we don't even have to rely on zig being available in the system.

All of the above means that Nuitka can be installed and used to compile code out of the box (potentially cross-compile). There won't be any need for system dependencies.

Zig build supports existing C code. So, we don't have to touch the existing C code to integrate zig.

Zig has not yet reached v1.0, and this is a very ambitious proposal that require careful rewrites to be backwards compatible. But, I hope you see the potential in it.

**Comment by kayhayen** [comment]
I am aware of `zig` and appreciate it. I think once CPython is built with zig successfully, Nuitka will support it too, because that will mean all the heavy lifting has been sorted out. 

It then truly replaces MSVC for the purposes of Python, then. I do recall e.g. times when older MinGW versions didn't do floating point math correctly (compatible) enough to get the same results. Emulating the MS bugs may not be a part of zig, or is it?

However, I will welcome PRs in that direction. Also I do not know how good it is for performance as a C compiler yet. We will not benefit from cross compilation yet, so performance would be what we care about. Can it do LTO with proper libpython as well. Does it do it as good? What about C level PGO? All of that needs to be explored.

**Comment by kayhayen** [comment]
Closing this, as I consider it a question to me, not something to work on myself. zig is very cool, esp. for cross compile, but only the idea is not worth being an open issue.

**Comment by jimkring** [comment]
I have been playing around with it here: https://github.com/jimkring/nuitka-zig-cc

**Comment by kayhayen** [comment]
Only as a C++ compiler limits the amounts of Python that can be supported, since C11 is now required for a while, we really would need to to support C11 with the features I think we reported to them. Has there been any progress on our issues?

**Comment by jimkring** [comment]
see #2741
