### ISSUE TITLE
Nuitka random error in scons: 'EnvironmentError' object has no attribute 'strerror'

### ISSUE THREAD

**Issue by jcrmatos** [Nuitka/Nuitka#210]
Hello,

I use a batch file to "compile" several Python modules, using this command
`nuitka --module --recurse-none --plugin-enable=pylint-warnings --warn-implicit-exceptions --warn-unusual-code <filename_to_process>
`
sometimes Nuitka returns this error
`scons: *** [gui_main.build\__constants.obj] AttributeError : 'EnvironmentError' object has no attribute 'strerror'
`
but the filename where it occurs varies.

Because the directory where the files reside is in OneDrive, I tested using another directory outside of OneDrive, but the error stills appears (randomly).

Output of python -m nuitka --version
(.venv) C:\Users\JMatos\OneDrive\Python\uniclave>python -mnuitka --version
0.6.0.6
Python: 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Int
el)]
Executable: C:\Users\JMatos\OneDrive\Python\uniclave\.venv\Scripts\python.exe
OS: Windows
Arch: x86

Thanks,

JM

**Comment by kayhayen** [comment]
This is a scons bug, that is hiding the real issue unfortunately.  I will try and push a change that makes it behave better in terms of the error message. It seems they are defining EnvironmentError themselves different from the one of Python, but expect it in the same module to have "strerror" if an exception was an instance of that.

From what it looks like, in Python3 there is no exceptions module, which is why the code regressed like that, removing the namespace, the Python2 version of the inline Scons copy doesn't have the issue.

Yours,
Kay

**Comment by jcrmatos** [comment]
Hello,

Ok, thanks.

Happy holidays.

Best regards,

JM

**Comment by kayhayen** [comment]
There is a bug fix on the factory branch that is going to be part of the next release.

**Comment by jcrmatos** [comment]
Ok, thanks.

**Comment by kayhayen** [comment]
I am keeping issues open until I make stable releases with the fixes.

**Comment by kayhayen** [comment]
Nevermind, I have no place where I state this policy, and I am unsure where to. Maybe right in the issue template.

**Comment by kayhayen** [comment]
Fixed in develop now, and closing it as I am making a release out of it real soon anyway.
