### ISSUE TITLE
Onefile: Multiprocessing launches processes through the onefile binary and then crashes

### ISSUE THREAD

**Issue by trapezoid677** [Nuitka/Nuitka#2145]
Using multiprocessing in onefile crashes the program execution. Starting the program from standalone or from inside the dist-folder works as expected. In a more complex program than the reproducer, the onefile program starts multiple instances of the program when executing multiprocessing routines. 

Nuitka 1.5.4
Commercial: None
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\python\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\cl.exe (cl 14.3).

Nuitka installed via pip, Python 3.10.10 from python.org, venv

Reproducer (antivirus check has probably to be disabled):

```
from multiprocessing import Pool

def f(x):
    return x * x

if __name__ == '__main__':
    with Pool(5) as p:
        print(p.map(f, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))

    input("Press Enter to continue...")

```

**Comment by kayhayen** [comment]
Due to the lack of options, I cannot tell if you were using cached or temporary unpacking with `--onefile-tempdir-spec` but honestly it should not have to matter. My immediate try with what I have internally right now, didn't trigger it. I am checking current develop now, which doesn't have the fix for #2141 in which the path from `sys.executable` is used, rather than `sys.argv[0]` but I currently don't see how it would impact that.

**Comment by trapezoid677** [comment]
Sorry, here are the options:

```
python -m nuitka ^
--msvc=latest ^
--lto=no ^
--onefile ^
--run ^
onefile_multi.py
```

**Comment by kayhayen** [comment]
Ok, not sure if it should be crashing for you. I think cached mode might, and if it did, it ought to be a bug though, since it's not supposed to encounter any locking issue in that case, but maybe it is. If you can, please share if you used the parameter I mentioned accordingly.

However, by accident, my fix made a huge optimization for onefile and multiprocessing. Going through the bootstrap again is of course possible, but so stupid, that I should be ashamed of noticing that it was happening only now. It's making things very slow. However, the new code will be using the bootstraped standalone executable automatically, and that is correct.

The fix is currently on factory, and soon staging, and will be in 1.5.5 release, however my CI main machine broke down and needs repair, so I am not entirely sure about a release today yet. Need to investigate my options there.

As a result, I ran the test on a machine weak enough to stall on your example with onefile unpacking. So maybe I didn't see the crash myself. I was using your options too.

**Comment by trapezoid677** [comment]
Factory 1.6rc5 works for me with the example and without any additional parameters!

**Comment by kayhayen** [comment]
This is part of the hotfix release 1.5.5 that I just made and will hit Nuitka commercial as well in a minute.
