### ISSUE TITLE
Detect nuitka on the fly

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#216]
Hello,

I wrote a piece of code that asks for admin rights on Windows / Linux and if not found, asks for elevation.
On Windows, it will ask for UAC elevation, keeps exit codes and allows to keep commandline arguments.
On Linux, it will try to rerun with sudo, keeping exit codes, output and commandline arguments too.
It currently works with the Nuitka compiler, and packagers like PyInstaller, py2exe, cx_freeze.

As of today, I'm using a sloppy nuitka detection on windows using:
```
sys.argv[0].endswith('.exe')
```
It gets worse when running on linux :)

On the other packagers, generally sys gets a frozen attribute that can be checked with:
```
getattr(sys, "frozen", False)
```

Is there any way to detect if current script is Nuitka compiled ? Like a constant or a variable that is set globally in a compiled nuitka program ?

Best regards.

**Comment by deajan** [comment]
Thanks for your answer, this could workaround the problem in a quite elegant way, but is not the most portable way.

But maybe there's some special variable, builtin, whatever attribute that indicates Nuitka is being used.
I've searched a bit with dict(sys) comparaison of CPython and Nuitka, but without success.

**Comment by kayhayen** [comment]
So far I have resisted the desire to make it recognizable if a program was compiled or not, with the intention that people should never write code geared to Nuitka. And there really ought to be no use case for it, when doing things semi properly, i.e. using `__file__` and `__path__` to find yourself as a package.

Should anything on PyPI start to contain code with `if __nuitka_compiled__` that clearly would be a defeat. The many instances of `frozen` are often wrong for Nuitka to consider, very often that is the code path that won't work. It's a bad idea.

However, the move towards a `libnuitka` will make it necessary become more transparent to what version of Nuitka has compiled code, and which one.

I think however, that I am going to add `__nuitka_compiled__` as a tuple with Nuitka version information, maybe even a `namedtuple` reusing the type of `sys.version_info` and put it in every module, ideally re-using its instance if it's from the same compilation. 

That type should be good enough, as CPython seems happy with it. On 2.6 that will be a tuple, but no users care about that anyway anymore, but 2.7 and higher it's going to be sweet.

Then in order to check for compiled program, i.e. main is compiled, go `hasattr(sys.modules["__main__"], "__nuitka_compiled__")` and in `__main__` or any module, go for `"__nuitka_compiled__" in globals()`.

Then Nuitka needs to treat itself that as a compile time computed attribute of known value, and would even optimize these things away theoretically. I do not think though that `globals()` is treated that way yet, nor will `sys.modules` lookups for a while.

It will open the door for Nuitka optimized code, something I disdain. But I should not try and make other people's decisions all that much.

**Comment by deajan** [comment]
Hmmmm... Didn't think of that point of view... It's indeed a very good way to aim for 100% compatible code.

In my case, I have written windows UAC elevation code which works differently between CPython, Nuitka and code freezers, so that's my use case.

Since CPYthon, frozen code and Nuitka set different sys.argv[0] values, and Nuitka sets this to the Python interpreter even if it is not the main executable, I have to make adjustements depending on those.

As of today, I detect Nuitka "by default", ie:
```
if getattr(sys, 'frozen', False):
    # Do specific code to make UAC calls work with frozen code
elif sys.argv[0].endswith('.exe') or not sys.argv[0].endswith('.py'):
    # Since we do not execute a ".py" script and sys.frozen is false, let's assume we run with Nuitka
    # Do specific code that makes UAC calls work with Nuitka
else
    # Do standard CPython code for UAC calls
```

Getting a `___nuitka_compiled___` tuple could be of help here.
In the meantime, could I Improve my "poor man's Nuitka detection ?"
My UAC code works, but I think this is kind of a "sloppy" way of executing the right code.

Corresponding Python code: https://gist.github.com/deajan/356eef79132f9753eb97c6f1ee3b5fff

**Comment by JorjMcKie** [comment]
For me this test works fine: ``if len(sys.path) < 2: print("running nuitka-frozen")``.
I admit: a little *bold*, but it had always been true ...

**Comment by kayhayen** [comment]
So I went for `__compiled__` and got it work with Python2 and Python3. But the version information is not passed from the Python code yet. It currently is hardcoded. I am putting this through my Buildbots first, because I am very sure, some of my tests output all module values, and need to learn to ignore it.

`__nuitka_version__(major=0, minor=6, micro=2, releaselevel='alpha')`

This is what it looks like, let me know if you have anything that should be there too. I had the idea that factory ought to be "alpha", and "develop" should use "candidate", and master "release" obviously, but for that factory detection, I guess more effort would have to be done and that's not likely to happen, so "alpha" will probably be removed.

As for release, the GSoC effort is pretty heavy on my time budget right now. But I will try to factor it into this week still. This one was clearly on the list I thought we must have. I will put it on factory once the version information is actually passed from its source in `nuitka.Version` package to the C compiler code.

**Comment by kayhayen** [comment]
I should switch my work flow to using PRs, but well, factory has the feature now. Of course I was thinking too complicated when I was thinking of how to pass version information of Nuitka to the C compiler. I now just put the values in the generated source directly, and that was straight forward, no need to pass anything via scons and defines.

Once this sees love from the CI, I think it's time to make it a release.

**Comment by kayhayen** [comment]
This is long released as 0.6.2 already.

**Comment by dstromberg** [comment]
I'm comparing CPython, Micropython and Pypy3 in a microbenchmark.  This works for those:
```
def interpreter_name():
    """Return a str description of the Python interpreter we're running on."""
    if hasattr(sys, 'pypy_version_info'):
        list_ = sys.pypy_version_info
    else:
        list_ = sys.implementation.version
    return '{}-{}'.format(sys.implementation.name, '.'.join(str(v) for v in list_[:3]))
```

I'm using it to output a different text file with performance numbers for each Python implementation, to later be fed to gnuplot.

I'm considering adding Nuitka to the graph, but it doesn't know itself.  I could pass a --nuitka flag to the benchmark, but then the benchmark still wouldn't know what version of Nuitka it's running on.  I guess I could extract the version from pip freeze, but that's a bit ugly, and no guaranteed to be accurate.

Far from a defeat, I'm finding __compiled__ not as nice as Pypy3's sys.pypy_version_info.  Pypy3 keeps sys.implementation.version for its "this is the version of Python we're compatible with."  IMO that's a much better solution.

**Comment by kayhayen** [comment]
But the Nuitka version is in the `__compiled__` attribute, is it not?

**Comment by kayhayen** [comment]
I don't get what's missing here:

> __nuitka_version__(major=0, minor=6, micro=16, releaselevel='candidate', standalone=False, onefile=False)

The oypy version info has only less. Notice, the last two fields are only in the upcoming release.

Yours,
Kay
