### ISSUE TITLE
Can a .pyd module compiled with nuitka be decompiled easily?

### ISSUE THREAD

**Issue by Ambro86** [Nuitka/Nuitka#2175]
Apologies for the question, but I read an issue which said that by compiling a module with nuitka in .pyd, it seems to be very easy to access the code, as the bytecode seems to be available. It was said that using inspect.getsourcelines() the code is printed.
I did a test and it doesn't show up for me.
Can you confirm that the code is not easily accessible, and if so, how not to include the bytecode in a .pyd module?
I tried searching, and it seems that the choice to include or not the bytecode is gone, or at least, I couldn't find it.
I'm referring to this sentence:
"Anyway, it seems when you compile source code as a module with Nuitka you're basically offering the source code of such modules quite easily as inspect.getsourcelines will work flawlessly."

And
"When compiling with Nuitka, you have the option to include bytecode, however. If you do this, then decompilation for the respective parts is as easy as it always is for Python bytecode. That would then be your own fault."
Found here:
https://github.com/Nuitka/Nuitka/issues/392
Thank you.

**Comment by kayhayen** [comment]
I believe there is an interest by some parties for people to not use Nuitka. The data contains function names, variable names as plain text indeed, unless you use Nuitka commercial and data hiding. But from these names, nobody can construct the code of course. Check out the details here: https://nuitka.net/doc/commercial/protect-constants-data.html

For honest mistakes, compiled code, in acceleration mode, retains a `__file__` attribute that points to the Python file. Then, if that source code is there, it will be accessible. In standalone or onefile mode, it is pointing to inside the dist folder, to help code find the data files. Same reason for acceleration mode. If people check out Nuitka in acceleration mode with inspect, they might be drawing wrong conclusions.

That said, I recall "competitors" who used `--debug` to demonstrate how "easy" it is to attack Nuitka compiled code with the the present debug information. So I am getting more doubts on honest mistaken claims, but they probably are honest most of the time.

There is indeed a choice to compile stuff as bytecode, it's done by plugins only at this time. The mixing of compiled and uncompiled code can be too difficult to want to deal with people who fail at doing it. Therefore I have not made it easy. I am not super exciting at the prospect of supporting all kinds of weird mixes inside packages. Maybe one day, when mixing packages in that way will be working for packages, source, bycode and compiled all well, but that issue has not seen the priority, because well, do not mix is a good workaround.

For the standard library, Nuitka uses bytecode most of the time. Generally we do not feel there is a lot of things to hide there, and at this time, also acceleration is not needed there. We have an option to enforce compilation of stdlib as well, but a bunch of stdlib must not be compiled, so that's kind of unfinished. We will go there, once caching works a lot better than it does now.
