### ISSUE TITLE
dill does not work in standalone mode, despite dill-compat (unable to save functions)

### ISSUE THREAD

**Issue by llamabeast1** [Nuitka/Nuitka#2178]
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
1.5.6
Commercial: None
Python: 3.9.16 (main, Mar  8 2023, 10:39:24) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: c:\users\alexw\ANACON~1\envs\NUITKA~1\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

* How did you install Nuitka and Python

pip, on Windows

* The specific PyPI names and versions

`dill==0.3.6`

Dill does not appear to be working properly when compiled as --standalone or --onefile, when using dill-compat. If a function is serialized using dill, then it fails and crashes.

Here's a minimal test script which fails:

```
import dill

def testFunction():
	pass

with open("dillTest.txt", "wb") as f:
	dill.dump(testFunction, f)
```

(compiled using `python -m nuitka dillTest.py --standalone --enable-plugin=dill-compat`)

When the compiled exe is run, it fails with the following error:

```
Traceback (most recent call last):
  File "C:\DILLTE~1.DIS\dillTest.py", line 14, in <module>
  File "C:\DILLTE~1.DIS\dill\_dill.py", line 235, in dump
  File "C:\DILLTE~1.DIS\dill\_dill.py", line 394, in dump
  File "C:\DILLTE~1.DIS\pickle.py", line 487, in dump
  File "C:\DILLTE~1.DIS\dill\_dill.py", line 388, in save
  File "C:\DILLTE~1.DIS\pickle.py", line 560, in save
  File "C:\DILLTE~1.DIS\dill-postLoad.py", line 44, in save_compiled_function
AttributeError: module 'dill._dill' has no attribute 'stack'
```

**Comment by kayhayen** [comment]
I seem to recall, that in `__main__` it may not have worked, but everywhere else?

**Comment by llamabeast1** [comment]
This also doesn't work:

```import dill

def dillTest():

	def testFunction():
		pass

	with open("dillTest.txt", "wb") as f:
		dill.dump(testFunction, f)


dillTest()
```

**Comment by kayhayen** [comment]
It might be necessary for the code to be in a separate module, and not the main program. But I am in no way sure of that and it's not the issue here.

The error you are facing is from different code. The post load Python code in `createPostModuleLoadCode` of `NuitkaPluginDillWorkarounds` seems to not work for latest dill. It provides a `save_compiled_function` that seems to want to use a `stack` from `dill._dill` and that seems to no longer match the internals of dill. 

I kind of added a plan to revisit the dill plugin and add coverage for it. But for now, this will have to wait for others to pick it up (cannot be that hard if you poke dill internals how to save a standard function) and wait for me to get to it.

**Comment by llamabeast1** [comment]
Thanks as always for the rapid response.

I thought it might help to try an earlier version of dill. Indeed it seems that this issue appeared in dill v3.5, as v3.4 and earlier don't have the same problem.

Unfortunately a different failure occurred (with dill v3.4, python 3.9, nuitka 1.5.6):

```
Traceback (most recent call last):
  File "C:\DILLTE~1.DIS\dillTest.py", line 3, in <module>
  File "C:\DILLTE~1.DIS\_dillModule.py", line 9, in dillTest
  File "C:\DILLTE~1.DIS\dill\_dill.py", line 276, in dump
  File "C:\DILLTE~1.DIS\dill\_dill.py", line 498, in dump
  File "C:\DILLTE~1.DIS\pickle.py", line 487, in dump
  File "C:\DILLTE~1.DIS\pickle.py", line 560, in save
  File "C:\DILLTE~1.DIS\dill-postLoad.py", line 69, in save_compiled_function
```

It occurred to me that this might be the __main__ issue you were referring to, so I tried moving the dill code to a separate module, but this made no difference. In case it helps, here is the full code:

dillTest.py:
```
from dillModule import dillTest

dillTest()
```

dillModule.py:
```
import dill

def dillTest():

	def testFunction():
		pass

	with open("dillTest.txt", "wb") as f:
		dill.dump(testFunction, f)
```

**Comment by kayhayen** [comment]
It may also have been limited with nested functions. Maybe if the `__qualname__` was used rather than the `__name__` the lookup in the table would work for it. If you move it to the top level, I would expect it to maybe work, but then also closure variables would have to be done, etc.

I didn't know it works with files. I think I originally added it for usage with some sort of multiprocessing usage.

**Comment by llamabeast1** [comment]
Hmm, you are correct that moving it to the top level works.

Unfortunately this doesn't work for my case where I am serializing quite a complex object which includes a lot of functions.

Is there any way I can make use of the __qualname__ idea, or does that require making changes to the dill plugin source code? (I'd be happy to do that in principle, but not remotely qualified!)

> I didn't know it works with files. I think I originally added it for usage with some sort of multiprocessing usage.

Yes, dill is amazing for saving the state of a program. It can save the state of pretty much all python objects, which makes for a fantastic save/load feature.

**Comment by KevinRodriguez777** [comment]
the MRE works nowadays, but i'm not sure if this issue should be closed, up to you.

**Comment by kayhayen** [comment]
Yes, lets close it then it then.
