### ISSUE TITLE
How to find the code is running from Compiled binary of from IDE ?

### ISSUE THREAD

**Issue by gaamaaresosa** [Nuitka/Nuitka#2184]
I was using PyInstaller and planing to move Nuitka.
I need to find the code is running from IDE or as compiled binary.
So I need to do some logics.

1) Do we have this option ?

2) Is it secured from reverse engineering ?
    I mean binary to source code like other CPython compilers.
    I hope you compile with GCC in linux to get direct machine code as native binary.    
    
3) Can we encryt and the strings (Passphrase and API Keys) 
     inside the source code on the fly while compiling ?

This is what I was usning in PyInstaller:
https://pyinstaller.org/en/stable/runtime-information.html
```
import sys
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    print('running in a PyInstaller bundle')
else:
    print('running in a normal Python process')
```

I think Cython has this option but not tested:

```
import cython

if cython.compiled:
    print("Yep, I'm compiled.")
else:
    print("Just a lowly interpreted script.")
```

**Comment by kayhayen** [comment]
Check out the user manual about how to use the `__compiled__` module and function attributes. Yes, you can recognize if code is compiled or not, but generally there is not really a need for it, because Nuitka is so compatible.

The code is impossible to reverse, as there is no bytecode. 

The data is protected, but my idea of `n-strings`  which would be more secure strings is not implemented yet, but going to come later this year. I actually hope sooner than later, but I cannot promise it yet. So far you can do this only on your own in Python code. In the future strings with `n'secret'` will have short life cycle and extra protections.

**Comment by gaamaaresosa** [comment]
@kayhayen Thank you so much.
Please check why the bundled binary is very huge is size.
Why its bundling Numpy and other extra stuff even for my simple source code ?
After build the binary file why its working via Python3 ?

I posted about these issues with Nuitka, but some one deleted it before investigating.
I took that he knows the issue well which he think this community don't wanted to know it.

**Comment by kayhayen** [comment]
I think I commented why I delete reports with insufficient information.
