### ISSUE TITLE
PyTorch: standalone executable throwing "AttributeError: 'MyModule' object has no attribute 'save_to_buffer'"

### ISSUE THREAD

**Issue by kohlerkane** [Nuitka/Nuitka#2189]
When using the attached Nuitka build command below to compile the attached sample code, running the generated executable throws the following error:

```
Traceback (most recent call last):
  File "/test_nuitka_crash/torch_crash.dist/torch_crash.py", line 12, in <module>
  File "/test_nuitka_crash/torch_crash.dist/torch/jit/_serialization.py", line 83, in save
  File "/test_nuitka_crash/torch_crash.dist/torch/nn/modules/module.py", line 1185, in __getattr__
AttributeError: 'MyModule' object has no attribute 'save_to_buffer'
```

I recently updated Nuitka versions (from 0.9.5) to address a separate issue that I had been tracking when I began noticing this -- prior to that, this appeared to be working fine and as expected (invoking what should be a valid attribute, `save_to_buffer()` of a Torch `Module`, inside the  `torch.jit.save(m, buffer)`function call in the code snippet below)

---

## Nuitka version (installed via pip 20.0.2)

```
1.5.6
Commercial: None
Python: 3.8.10 (default, Mar 13 2023, 10:26:41) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc).
```

## Relevant python modules

```
Nuitka==1.5.6
numpy==1.24.2
ordered-set==4.1.0
patchelf==0.17.2.1
torch==1.11.0
typing-extensions==4.5.0
zstandard==0.21.0
```

---

### torch_crash.py
Modified from a simple example provided in the pytorch docs (https://pytorch.org/docs/stable/generated/torch.jit.save.html)

```
import torch
import io

class MyModule(torch.nn.Module):
    def forward(self, x):
        return x + 10

m = torch.jit.script(MyModule())

# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.jit.save(m, buffer)

print("Done")
```

---

### Nuitka options used

```
python3.8 -m nuitka --standalone ./torch_crash.py
```

---

## Noteworthy mentions

Compiles without issue -- although in this particular environment, which was a fresh Ubuntu 20.04 Docker image built from the ground up specifically to narrow down this issue, I received 2 warnings:

```
Nuitka:WARNING: Standalone with Python package from Debian installation may not be working.
Nuitka-Scons:WARNING: You are not using ccache.
```

In my usual build environment where I first noticed this issue, I did *not* receive those warnings -- everything compiled without incident, though the `AttributeError` remained.  For that reason it seemed as though they are unrelated to this particular issue and alright to ignore.

It seems as though the biggest difference between when this was last working for me and now is the deprecation of

```
--plugin-enable=torch
```

which appeared to be doing some of the namespace resolution and handling of torch modules internally -- it's entirely possible that I have just not configured things properly during the Nuitka version update.

Thank you in advance for any advice you may have and please let me know if I can provide additional context

**Comment by kayhayen** [comment]
Regarding your warnings, the Debian warning is not as meaningless, read up the link it gives. The ccache warning, I just realized, may not be very informative. It's just about the C part compilation, were it to repeat identically will not use a cache. I am changing it to say `You are not using ccache, re-compilation of identical code will be slower than necessary.`

The pytorch changed a lot since that time. The plugin indeed did a few things, that are no longer done, all of which are very unlikely to be an issue, since a lot of torch is know to work. The error looks a bit strange, I will have to narrow it down. Due the long distance, I do not think a git bisect will help us at all. But it seems also like something that should be very identifyable. We need to keep in mind, how it may mean that something didn't load when it should.

Unfortunately the --report feature is too new to allow us identify if there is any difference in loading it.

**Comment by kayhayen** [comment]
```
import torch

class MyModule(torch.nn.Module):
    def forward(self, x):
        return x + 10


m = torch.jit.script(MyModule())
print(m)
```

With Nuitka, `MyModule` is not changed, like it is with uncompiled code. Does not become `RecursiveScriptModule(original_name=MyModule)` but stays `MyModude()` so something in the metaclass construction must be going wrong.

**Comment by kayhayen** [comment]
Ok, this is caused by the absence of the source code. The `jit` needs to have it in order to do the compilation. That would have to happen at compile time. Now what your code does, very much appears to be in line with what Nuitka would have to do. It would have to preprare the binary objects, and load them.

It appears, that for deployment, we either change Nuitka to contain the source code of your application there, such that the JIT of Torch will find it on the end user system, even if contained in the binary. With Nuitka commercial, it would be somewhat protected, but still. And then it could JIT from there on the target machine. Or we change the deployment such that the JIT compilation happens on the client side, maybe in the CPU only, and then that is deployed, maybe optionally with more graphics cards added, but that will be difficult to dispatch I assume.

For saving, something like `torch.jit.save(torch.jit.trace(model, (x)), "model.pth")` could be used and for loading `torch.jit.load("model.pth")` would have to be used. I understand that it may refer to names when `trace` is not used, and compiled code would work there fore, so using `trace` which is also said to not always work, would not be needed.

**Comment by kayhayen** [comment]
Yes, the more I think of it, that is how it should be done. The question is how much of this can or should be automated in Nuitka and if that's even possible on a practical level. Can you explain why you wanted to save in compiled code?

**Comment by kohlerkane** [comment]
Thanks for the response and my apologies for the radio silence, just wanted to reach back out with an update.  I'm in the middle of trying to push out a software release and haven't had much time to dig back into this.  I will try to get back to you with an answer ASAP.

**Comment by kayhayen** [comment]
I believe, this is a usage of compilation that is not going to work. You cannot JIT after compilation and save the result, you have to JIT before that and load in compiled.

**Comment by remleduff** [comment]
Out of curiosity, what changed in nuitka that makes this no longer worker where it used to?

Did nuitka previously keep some python source code around at runtime and discards it now? Would there be any way to add the capability to restore that behavior selectively?
