### ISSUE TITLE
Build time is too slow and executable is huge size.

### ISSUE THREAD

**Issue by gaamaaresosa** [Nuitka/Nuitka#2199]
I am fasinated with Nuitka because it converts *.py file to *.so (Native code)
Since few days I am trying Nuitka to make a successfull onefile binary.
Till now no success.

1) Every time buiding takes 45mins to 1 hour.
    For the production even if a small correction on scource code and wanted to release the update
    We have to wait for 1 hour.
    I don't know why you convert all the deep scanned system libraries too ?
    I am intested only my python modules are to be protected from bytecode and converted to *.so

2)  Say I have 5 python modules (*.py) and 1 main python file (*.py).
     How to make a single executable from Nuika
     I need *.py to c to *.so  only for these above 5 files.
     Rest of the system modules can be bundeled as it is (*.py)
     So the build time will be smaller.

3) Please give me tips to reduce the build time and one single file output by converting my selected *.py to *.so

$  python3 -m nuitka --version
1.5.7
Commercial: None
Python: 3.7.3 (default, Oct 31 2022, 14:04:00)
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: aarch64
Distribution: Raspbian (based on Debian) 10
Version C compiler: /usr/bin/gcc (gcc).

**Comment by Maxwell175** [comment]
It is recommended in this case to perform the build in a venv that only has the packages that you really need. Typically this issue is due to weird import logic within some packages that will cause Nuitka to pull in too many dependencies. Beyond that, you did not provide the list of packages that you are using and a short self contained example that takes so long to compile. Without commercial support, we are more strict about making sure all reports have all the information needed so we do not waste our time guessing.

**Comment by kayhayen** [comment]
The need to compile all code (convert) stems from using standalone mode. If you want a quick compilation, don't do it. Your 5 files will be really quick. And if you target a well known environment, they will work.

**Comment by gaamaaresosa** [comment]
@Maxwell175 
> It is recommended in this case to perform the build in a venv that only has the packages

Thanks for your swift response.
First of all I do remote development between PyCharm and Raspberry Pi from Windows 10
In this situation PyCharm doesn't work well when I set venv at Raspberry Pi.

More over even if I have 1000s of packages on my system a cleaver project scan only should fetch only the packages used on the given project right ?
So I should not worry venv of global.

**Comment by gaamaaresosa** [comment]
> The need to compile all code (convert) stems from using standalone mode. If you want a quick compilation, don't do it. Your 5 files will be really quick. And if you target a well known environment, they will work.

@kayhayen 
Thanks, I will further experiment to reduce the built time and built file size.

**Comment by kayhayen** [comment]
Wrong. A "clever" scan cannot detect optional dependencies being used just because they are there. For example, a bunch of code will use IPython if it's installed, which in turn will attempt to use every syntax highlighting framework on the planet, which will attempt to use all parsers, and also all web frameworks for rendering, and then all GUIs that are available from some of the dependencies.

If you are OK with slow Python startup from that, OK. But Nuitka is going to do the compatible thing, and make it happen on the end user machine too.

There is no way of knowing it. However, we do anti-bloat measures, namely to remove some dependencies by changing the code, to not use it. Some packages will still pull in e.g. IPython to your virtualenv, and we fight that with what we call anti-bloat. You are more than welcome to help there: https://nuitka.net/blog/tag/package_config.html

If you have something concrete, like an improvement, or observation, why you include a lot of stuff, fine. I personally develop in the full environment most of the time, and then try and do anti-bloat on those things. Then raise other issues, but I thnk this is not useful as it is now.

**Comment by gaamaaresosa** [comment]
@kayhayen 
Thanks again !
I generally avoid unnecessary arguments.
Always tell my experiance and opinions frankly.
My same project is also scanned by PyInstaller and build size in 10MB
I aggree Nuika crawls entire modules converts all the modules to native binary.
So 50% oversize is OK
But the output is 70MB size inside a huge folder.
(-onefile is set)
Inspite of that also the exe throw errors as this and that is missing.

Any how when I get time I will upload the samples.

**Comment by kayhayen** [comment]
Yes, bytecode is smaller, I am not surprised. Size is not a goal of Nuitka. Performance is. IP protection is for the commercial guys: https://nuitka.net/doc/commercial.html and that's size. The size of 70MB sseems good enough and mostly indistinguishable. There are people distributing 1GB of torch, they do not notice the difference.

So you stick with what is working for you, and you work with us to improve this. I am locking this, because I do not really think of this here as a chat forum. But you will be welcome on Discord.
