### ISSUE TITLE
FATAL: Error, failed to find path bazel-out/osx-x86_64-opt-ST-7396233f5981/bin/external/upb/python/lib_message_binary.so

### ISSUE THREAD

**Issue by dryarullin** [Nuitka/Nuitka#2213]
**Error description:**

FATAL: Error, failed to find path bazel-out/osx-x86_64-opt-ST-7396233f5981/bin/external/upb/python/lib_message_binary.so (resolved DLL to bazel-out/osx-x86_64-opt-ST-7396233f5981/bin/external/upb/python/lib_message_binary.so) for /Users/username/miniconda3/envs/pyqt_new/lib/python3.11/site-packages/google/_upb/_message.abi3.so, please report the bug.

**nuitka3 --version**

1.5.7
Commercial: None
Python: 3.11.0 (main, Mar  1 2023, 12:49:28) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/dryarullin/miniconda3/envs/pyqt_new/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

**pip freeze**
protobuf<=4.23.0rc2

**Additional description:**

 otool -L ./google/_upb/_message.abi3.so
```
 bazel-out/osx-x86_64-opt-ST-b50b65861838/bin/external/upb/python/lib_message_binary.so (compatibility version 0.0.0, current version 0.0.0)
 /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
 /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

There is no such path as "`bazel-out/osx-x86_64-opt-ST-b50b65861838/bin/external/upb/python/lib_message_binary.so`"

Similar issue: #1887

**Comment by kayhayen** [comment]
Yes, I agree, similar issue. I do not have yet looked into these as deep as I should, but the path `/bin/external/upb/python/lib_message_binary.so` is so suspiciously screaming strange setup to me. I wonder if this is because it is a relative path, and there is not a directory added to the search path. Not sure where this path would come from. Nuitka has to more or less manually emulate what macOS does there. Without a @loader_path or @executable_path or something like this, the directory this lives in, may just not be in the path, or Nuitka would apply it to where `_message.abi3.so` currently lives.

If you want to clarify these things for me, that would be helpful. I am getting that `pwd` is supposed to be added as a scan path too from what you quote there. Is that correct?

**Comment by dryarullin** [comment]
bazel-out/osx-x86_64-opt-ST-b50b65861838/bin/external/upb/python/lib_message_binary.so library with this search path is initially added to the list used by _message.abi3.so library. This initial behavior after installation from pip. But there is no lib_message_binary.so file in the whole system. This is independent of the search path. Maybe it's a package build problem. Maybe I don't understand something. I don't explicitly use protobuf in my program. One of my dependencies uses it.

I'm ready to help you, please, just try to give instructions more clearly. I recently started using Nuitka. Thanks.

**Comment by albertaouad** [comment]
I am facing the same issue as well.
Seems the originating problematic dependency is `protobuf` in my case a sub dependency of mlflow.
The only way for me to be able to complete the process is by ignoring protobuf using `--nofollow-import-to=google.protobuf` however, I know I need that for my application to run.

I don't know what else could be tried, it most likely seems to be an issue with protobouf build itself and not with Nuitka.

**Comment by dryarullin** [comment]
@albertaouad Can you help with a minimally reproducible example please?
