### ISSUE TITLE
`py.typed` file is not including in output wheel

### ISSUE THREAD

**Issue by bphillips-exos** [Nuitka/Nuitka#2219]
[PEP-561](https://peps.python.org/pep-0561/) outlines how packages should indicate they supply type information.

>Package maintainers who wish to support type checking of their code MUST add a marker file named py.typed to their package supporting typing.

The PEP also provides an example of how to include this information when using build backends like setuptools
```python3
setup(
    ...,
    package_data = {
        'foopkg': ['py.typed'],
    },
    ...,
    )
```

I am trying to build a wheel with Nuitka following [Use Case 5 - Setuptools Wheels](https://nuitka.net/doc/user-manual.html#use-case-5-setuptools-wheels) from the guide. My configuration for nuitka in my pyproject.toml file is very simple.

```toml
[build-system]
requires = ["setuptools>=42", "wheel", "nuitka", "toml"]
build-backend = "nuitka.distutils.Build"

[nuitka]
disable-ccache = true
```

I have tried to have Nuitka include the `py.typed` file in my package in the final wheel by specifying different variations of `incldue-package-data` and `include-data-files` including the equivalent of what is suggested in the PEP, however none of these approaches result in the `py.typed` file being included in the final wheel.

Since Nuitka already (very nicely!) generates a pyi file to be included in the wheel, it would be great to be able to include a `py.typed` file as well for consistent behavior with IDEs and static type checkers like mypy. 

Versions:
```
(.venv)  > python -m nuitka --version
1.5.7
Commercial: None
Python: 3.9.5 (v3.9.5:0a7dcbdb13, May  3 2021, 13:17:02)
Flavor: CPython Official
Executable: .venv/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

**Comment by kayhayen** [comment]
But looking into it, what I find is that the data file handling is entirely left to distutils, so this would be only relevant for commercial builds, where extension modules can have embedd files into themselves. The options you list, would have to give an error without using commercial and embedding.

Mind, you Nuitka is not building the wheel, it's only used to build the extension module, everything else is left to distutils/setuptools there.

I think you need to figure out how to provide data files with the `build` package, then you will have it correctly. The example using `setup()` would have to work already. If you find out how it' done please report here, I will gladly add data files to the examples, because I agree, this is very much not obvious.

**Comment by bphillips-exos** [comment]
> Mind, you Nuitka is not building the wheel, it's only used to build the extension module, everything else is left to distutils/setuptools there.

This was what  I was missing, I assumed Nuitka was building the wheel here. I had tried specifying the package data like this since the docs indicate other CLI parameters being specified this way and the CLI has options for `--include-package-data` and `--include-data-files`, but this does not work.

```
[nuitka]
include-package-data = "foopkg=py.typed"
```

However, specifying the package data under the setuptools section does indeed result in the desired wheel: extension module + `py.typed` file.

```
[tool.setuptools.package-data]
foopkg = ['py.typed']
```

Thanks!
