### ISSUE TITLE
Detect 32 bit compiler on 64 bit Python

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#225]
Hello,

I saw in the changelog
```
- Detect using MinGW64 32 bits C compiler being used with 64 bits Python
  with better error message.
```

While working on the dependency walker, I forgot to change my env variable to use MingGW64 64 bits on Python 64 bits tests.
Nuitka didn't complain using MingGW64 x86 so I guess that somehow this detection does not work.

In the meantime, I included a warning in the dependency walker if bitness don't match between python and dist libraries.

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
0.6.1
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Python37-64\python.exe
OS: Windows
Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.
Global installation via ```python -m pip install nuitka```

**Comment by kayhayen** [comment]
One thing that strikes me as odd is how you would get binaries when using the MinGW64 of the wrong architecture. I was getting compile time errors in those cases and there would be no binaries to walk for dependencies over, right?

Do MinGW-64 compilers cross compile from 32 to 64 bits and vice versa maybe? Because if they did, we could simply be using that ability, but that is just an aside.

**Comment by kayhayen** [comment]
Then most probably we just have to plug `-m32` and `-m64` or so to the compiler, and not worry about it any further? Adding that to `nuitka/build/SingleExe.scons` based on `python_arch` variable content (scons is potentially run with a Python of another arch than Nuitka) would be a trivial, but very welcome addition.

**Comment by kayhayen** [comment]
@deajan Did you have a chance to try this `-m32` or `-m64` business out? My minimal hope is that compilers will refuse in case of bits mismatch, or just do it in case of being cross compilers.

**Comment by deajan** [comment]
To be honest, my work does not leave me much time to work on Nuitka right now.
I'll try to push this on top of my todo list :)

**Comment by kayhayen** [comment]
You are definitely welcome when you have the time @deajan no worry. You made it clear that it's spare time only, and that means, I will try and assign things to you, but not hold my breath. :)

**Comment by kayhayen** [comment]
Creating the program will fail however, because `ld.exe` complains about incompatible stuff. That is however great, yet doesn't explain what people say, it cannot go unnoticed.

However, I have now added the detection of linker arch for Windows as well, and the "compiler arch" too, basically `objdump.exe` on `python.exe` and `gcc.exe` is being performed, and must match, or else it errors out. The `-m32/64` option can make it cross compile, but never link.

That way, people are spared from compiler errors for pointer size mismatches or linker errors. Could also do it for MSVC, but since Nuitka more often picks the correct compiler, it's less of a trap, and I don't know how to emulate `objdump` there.

Yours,
Kay

**Comment by kayhayen** [comment]
I have just added the check for MSVC as well. This should allow us to forget about the issue, will soon hit a pre-release.
