### ISSUE TITLE
22 detected antiviruses

### ISSUE THREAD

**Issue by samsunysoft** [Nuitka/Nuitka#2291]
1.6.3
Commercial: None
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\oreha\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).

Python - installed from the official site
Nuitka - installed via pip install nuitka
virtual environment - no

compile command: python -m nuitka --onefile get_license.py

https://www.virustotal.com/gui/file/772045dc8437d6bfcca691b5121abf9c14e164208a123685f05e8d4dcd767d75 

code:
![image](https://github.com/Nuitka/Nuitka/assets/135343382/7f83ec35-5ac9-481b-a918-a38cba6e3bc5)

without --onefile: two detected

https://www.virustotal.com/gui/file/2101d80b82ca12db667b3b906215912b94bf8ad243cee7e5f7781a6983588eb7?nocache=1

**Comment by kayhayen** [comment]
That downgrade from 22 to 2 by just using standalone is actually impressive. I do not monitor free Nuitka as much as commercial one naturally. I am sure, with Nuitka commercial plugins and instructions it would be better, but I would have to try myself for science. But since you are too stupid to post code rather than screenshots, not going to happen. Please provide proper code in text form, putting it inside triple ` will do. 

That said, right now Nuitka appears to be the preferred choice of malware authors. And the virus engines do not treat Python like C for that, i.e. if you choose to make the code non-inspectable, malice is assumed by some, since they cannot recognize if it's malware or not. Of course, they would have to do whatever it is they do for C programs. And maybe that's what I also recommend in Nuitka commercial and do with my plugins there. Not sure.

**Comment by kayhayen** [comment]
Also, onefile is not doing a lot of things, and itself is C, and I limited the amount of suspicious things it does for 1.6 and will continue to do so, but that's ridicolous.

**Comment by samsunysoft** [comment]
I'm not stupid. The code was provided to understand that this is not the problem. Here is the total program virus - print('hello world')

https://www.virustotal.com/gui/file/da9b40a0e067cd9fc8cacf53bce61d8af3c13e3ea08f427e0d86988fb6b0e5b5?nocache=1

**Comment by samsunysoft** [comment]
![image](https://github.com/Nuitka/Nuitka/assets/135343382/0f260eae-0dbd-4996-8c2b-e090741de7ed)

**Comment by kayhayen** [comment]
I dislike the vibe.
