### ISSUE TITLE
RFE: Keep track of all files copied into the build by writing their sources to a file.

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#2330]
Now in Nuitka, the computation of dependent libraries (and other files, like data and resources) follows very tricky rules involving the interpretation of multiple configuration files, complex heuristics, and ambiguous renaming. 
(and looks these rules will be constantly extended, see #2328, #2325… )

As a result, it's hard to figure out in the build how exactly binary files came from that libraries and other binary files.

It would be great if you could record these copies in a strict format (JSON, CSV, YAML) file  with semantic "source -> result"  for possible later analysis. (not `inclusion_logger` with "Ignoring non-identical DLLs for '%s', '%s' different from '%s'. Using first one and hoping for the best", "Colliding DLL names for %s…", etc).

**Comment by kayhayen** [comment]
Did you see `--report` ?

Most information is already there, e.g. what DLLs are included, why, etc. and e.g. right now as I read that, I am adding the information about distribution names attempted to lookup and the success of that.

It is my goal to make the compilation report include all relevant data. When using scipy and numpy is some versions, DLLs are all duplicated but different, terrible, that probably needs a hardcode solution, since these people are never going to make it consistent.

**Comment by belonesox** [comment]
Sorry, I looked at --report somedays ago, but somehow missed that required information already available in «included_dll» tags.

Thank you!

**Comment by kayhayen** [comment]
Even more, you can find what plugins influnced things, checked what conditions, distributions of modules used, with their versions, module usages and resolutions, and ever more. I am now removing the info traces for plugins, as e.g. the post load code is present there, the sys path, the versions, even exceptions if any, and on develop it now creates a report in case of a crash if not specified, it's really good stuff.

I believe it's a bit hard to discover, maybe I will make a message about it one day or enable it by default.
