### ISSUE TITLE
Question about import path

### ISSUE THREAD

**Issue by lytofd** [Nuitka/Nuitka#2338]
I  have encountered some problem about import path.

I used:

* System: Linux  
* Python: 3.8
* Nuitka: version 1.7.4

My file directory like this:

>code_pac  
>|----hello.py  
>|----test1.py  

hello.py
```
from  code_pac.test1  import test1
def talk(message):
    test1()
    return "Talk " + message

def main():
    print(talk("Hello World"))
	
```

test1.py
```
def test1():
    print('test1')
```
l want to  build my package with 
```
python -m nuitka --module code_pac --include-package=code_pac --remove-output
```

```
from code_pac.hello import main

if __name__ == '__main__':
    main()
```
that works well, but when modify hello.py 
```
from  code_pac.test1  import test1
```
to
```
from  test1  import test1
```

error would happens as below:
> ModuleNotFoundError: No module named 'test1'

so, how can i import test1 by
```
from  test1  import test1
```

**Comment by kayhayen** [comment]
I think that's compatible with Python. There is no `test1` module in your setup unless you somehow have `code_pac` directory in your `sys.path`, for which there are of course ways to do that, e.g. current directory, that kind of thing. You would have to do a relative import. And since you do not allow following to `test1` in module mode, Nuitka doesn't do it.

You are effectively duplicating your module code this way in Python (and would be Nuitka if you included it).

This is the case since Python3 was added. Previously it would attempt relative and absolute imports both, but that's no longer the case.

```
_future_absolute_import_default = python_version >= 0x300
```
