### ISSUE TITLE
unable to alter the color of input text

### ISSUE THREAD

**Issue by SirDank** [Nuitka/Nuitka#2352]
related to #2343 

Note: this has always worked as expected till `nuitka 1.6.3`

updated sample script:
```py

import time
from colorama import Fore, Style, init

init(autoreset=True)

# colorama colours
#reset = Style.RESET_ALL
red = Fore.RED + Style.BRIGHT
white = Fore.WHITE + Style.BRIGHT
green = Fore.GREEN + Style.BRIGHT

n = int(input(f"\n  {red}> {white}Enter a number{red}: " + green))
print(f"  {red}> {white}Square{red}: {green}{n*n}")
print(f"  {red}> {white}Cube{red}: {green}{n*n*n}")

time.sleep(4)
```

Expected Output: (executed script.py via console)
<img width="250" alt="image" src="https://github.com/Nuitka/Nuitka/assets/52797753/5f9cddc6-6391-44bc-8a1d-3b19f5216de1">

Actual Output: (executed via executable built by nuitka 1.7.6)
<img width="250" alt="image" src="https://github.com/Nuitka/Nuitka/assets/52797753/47380f3c-7f31-4ce8-b51d-c2e57940193e">

Error: As input is being taken, it should be displayed in "green"

errors.txt: empty

**Comment by kayhayen** [comment]
I reproduced this on Linux just now, both with Nuitka and pure Python. It seems that however changing the input color is supposed to work, it's not being done if stderr is redirected. I don't know if stderr is technically required to be associated to the terminal for stdin to be changed, but that's the fact it seems.

**Comment by SirDank** [comment]
is this fixed?

**Comment by kayhayen** [comment]
It is not an issue, if the behaviour with standard Python is the same. Nuitka is not tasked with fixing colorama or terminal interactions with Python there. I don't know how or why, but without stderr assiociated to the terminal, Python doesn't do coloring of stdin.

If you get `python test.py 2>err.txt` to work, when we can talk. The `--force-stderr` option is supposed to emulate that. Until 1.7 it was only modifying `sys.stderr` to go to a file, now the C level stderr is changed, so we can be sure to capture everything.

I think saying your issue is invalid, is wrong, but it's not even clear if it is fixable with standard Python, so why should Nuitka implement that, so I am putting wontfix there.
