### ISSUE TITLE
Problem with compiling with latest WinLibs and Python 3.11

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Nuitka/Nuitka#2367]
Can anyone tell me which specific version of [WinLibs](https://winlibs.com/) should I download for Python 3.11.4? I check different latest GCC 13.1.0 MSVCRT but still get such info:

```
Nuitka-Scons:INFO: For Python version 3.11 MSVC 14.3 or later is required, not None which is too old.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.
Is it OK to download and put it in '.\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3'.
```
 
I don't want download anything because I have this compiler in my own folder. Before run Nuitka I set this:
```
set CC=D:\WebTools\WinLibs_x64\bin\gcc.exe
set PATH=D:\WebTools\WinLibs_x64\bin;%PATH%;
```

but still Nuitka wants download some older compiler. This problem doesn't occur with Python 3.10.9.
```
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 ..\..\enigma.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.8' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Backend linking program with 14 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 14 C files using ccache.
```

More info:

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

python -m nuitka --version

```
1.7.8
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\Test\WinPythonPortable\python-3.11.4.amd64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc).
```

* gcc --version

```
gcc (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders) 13.1.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kayhayen** [comment]
Sadly, the broke our detection of WinPython, but it's not considered supported anyway.

```
def isWinPython():
    """Is this Python from WinPython."""
    return "WinPython" in sys.version
```

If you have a way to improve that it would be nice. I think that WinPython may actually work, but I do not check it out really. I am happy with Anacona and CPython myself.

Your non-desire to use an unsupported gcc version, doesn't bother me in the slightest. I will not support that.

It seems that your difference is that for Windows and Python3.11, MSVC with not the proper Windows SDK is being ignored, because we can only with in C11 mode there, and for Python3.10 you can still use the C++ as C11 workaround of older times, but Python will no longer work that way.

Since you absurdely only posted the working scons output and skipped the non-working one from 3.11 I cannot tell right now, if you didn't see a warning about that.

**Comment by ArkadiuszMichalski** [comment]
@kayhayen 

For WinPython 3.11.4 compilation works with latest Nuitka 1.7.8, but only if Nuitka download this proposed compiler:
```
Nuitka-Scons:INFO: For Python version 3.11 MSVC 14.3 or later is required, not None which is too old.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.
Is it OK to download and put it in '.\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3'.
```
Result:
```
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 ..\..\enigma.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.8' on Python '3.11' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: For Python version 3.11 MSVC 14.3 or later is required, not None which is too old.
Nuitka will use gcc from MinGW64 of winlibs to compile on Windows.

Is it OK to download and put it in '.\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3'.

Fully automatic, cached. Proceed and download? [Yes]/No : yes
Nuitka:INFO: Downloading 'https://github.com/brechtsanders/winlibs_mingw/releases/download/11.3.0-14.0.3-10.0.0-msvcrt-r3/winlibs-x86_64-posix-seh-gcc-11.3.0-llvm-14.0.3-mingw-w64msvcrt-10.0.0-r3.zip'.
Nuitka:INFO: Extracting to '.\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe'
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 14 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 14 C files using ccache.
```

This proposed version is not just some older version of WinLibs? Or is it some special compiler package to make everything work with Python11?

I just wanted to use some newer compiler from WinLibs project, but Nuitka doesn't detect it correctly for Python 11 (but somehow manages this proposed older version).

Maybe I need to point to the folder with the new compiler in some other way than I specified above with the `set` command?

**Comment by ArkadiuszMichalski** [comment]
In fact, it looks like WinPython detection doesn't do anything and doesn't set the relevant stuff.
https://github.com/Nuitka/Nuitka/blob/863b7ccc88d3bc8030d1874b542d430477e113ca/nuitka/PythonFlavors.py#L187

I copied the older compiler downloaded by Nuitka to another location and set the path to it in two ways:
```
set CC=D:\WebTools\WinLibs_x64\bin\gcc.exe
set PATH=D:\WebTools\WinLibs_x64\bin;%PATH%;
```

And still get the same message with no compiler (Nuitka offer to download it). It's a pity that WinPython has been completely omitted because so far everything has worked as it should. I don't know the exact path of detections/settings performed by Nuitka, and it will be hard for me to suggest something without a thorough analysis (unfortunately, I don't have time for that at the moment).

So right now I will be using:

- WinPython 3.10 + new compiler
- WinPython 3.11 + old compiler

**Comment by kayhayen** [comment]
Honestly, this is very confusing to me. But the first thing that strikes me as odd, is that despite you using `--mingw64` it attempted to use MSVC and told you about it. When it does that, it clears the compiler for use. That is probably the whole problem. I believe that Scons detected an unusable MSVC which spoils it for you. No relationship with WinPython at all.

Yes, the detection was once proper, since the project used to put its name there. From my cursory search on their repo, they became more shy. It seems there being a "winpython" in site-packages could be a way to identify it now.

From the Anaconda experience, the portable packages there are organized in ways that mismatch PyPI. So it could well become apparent, that package configuration may mismatch CPython, but maybe they are less intrusive than Anaconda, which tries to de-duplicate with explicit DLL directories, and modifying upstrem packages to fit.

I am not against supporting WinPython, I am just saying that you will have to work with me there, since I won't just go out and make sure it works with tensorflow, Anaconda and CPython are both already pretty much too much there.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
Due to the `match` issue reported, there is probably going to be a hotfix with this included, once its scope has been covered.

**Comment by kayhayen** [comment]
Seems, I forgot to add this to the hotfix and is on develop only, will be part of the 1.8 release.

**Comment by ArkadiuszMichalski** [comment]
@kayhayen Sorry for the delay, I'm currently under renovation and have limited access to a working machine.

I test this version  https://nuitka.net/doc/factory.html:
```
python -m nuitka --version
1.8rc8
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: WinPython
Executable: D:\WinPython\WinPythonPortable\python-3.11.4.amd64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc).
```

And in my case the compilation was successful (the compiler is detected correctly). Thanks for the quick fix.

**Comment by kayhayen** [comment]
And the Flavor too, very nice. It's good for bug reporting, so I know what I deal with.

**Comment by kayhayen** [comment]
Part of the 1.7.10 hotfix release I just made.
