### ISSUE TITLE
[QUESTION] Option to bundle python modules as bytecodes instead of C compilation

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#2377]
I noticed that Nuitka standalone can have modules as uncompiled in itself.
But I didn't find how to do it? (is it exists?)

Example: I want to prevent Nuitka to compile `requests` lib to C:
```shell
>nuitka --standalone --mingw64 --uncompiled-module=requests program.py
```

You are free to close immediately if this is stupid question.

**Comment by byehack** [comment]
So, I noticed that a lot of people also wanted this, Let's keep this issue open as older issues closed as non-goal feature.

**Comment by kayhayen** [comment]
The anti-bloat plugin can specify `bytecode` as a mode. It is however not going to work well in many cases without extra care taken, since the Nuitka runtime is what makes certain things work, and mixing compile and uncompiled inside packages is not working well, so essentially it's largely untested and unsupported at this point.

**Comment by kayhayen** [comment]
I close questions once answered, this would be kept track of in the roadmap, but I don't see this happen from my side in the near future.
