### ISSUE TITLE
Feature request: Is there anyway to let gcc compiler generate .map file as an option

### ISSUE THREAD

**Issue by JiaPai12138** [Nuitka/Nuitka#2397]
Title

For example generating an `output.map` file the the destination folder. I am using MinGW64 C11 compiler, not sure if `-Xlinker -Map=output.map ` or simply `/MAP` works

Is it possible to implement?

**Comment by kayhayen** [comment]
Counter question is why you want it. For VM protection, I recommend Nuitka Themida which is located here: https://nuitka.net/doc/bundles.html

In the user manual it is described how to pass extra flags to the C compiler and linker, so you can get anything you want to work, but of course, Nuitka Themida doesn't need that and works out of the box for that purpose.

**Comment by kayhayen** [comment]
I guess you might want to consider purchasing a bit of my time via https://nuitka.net/doc/commercial.html#pricing with either the priority package or the full package, otherwise, I am not going to able to consider this, since it takes away from other important things, and this is clearly commercial usage.

I do not know `vmp` but with funding, I might be able to look at adding support for it, but I can certainly help creating a map file.
