### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2433]
Python 3.12 is coming out in early October, and I am sure you will work towards supporting it. Currently, Nuitka says

> The Python version '3.12' is only experimentally supported by Nuitka '1.8', but an upcoming release will change that. In the mean time use Python version '3.11' instead or newer Nuitka.

A tracking issue will be useful for interested folks to follow along - here it is.

**Comment by kayhayen** [comment]
There is a bunch of changes in Nuitka that aim at their new hiding of the thread state requiring an API call to get at it. Unfortunately that would make it extremely slow on any Python to do anything. So passing this one along has become kind of a requirement for 3.12 to be acceptable performance, I did that first.

Other changes in current exception state prevent it from compiling at this time. I was looking at beta4 so far, hopefully it won't get worse.

**Comment by codeofdusk** [comment]
Python 3.12.0 [has been released](https://www.python.org/downloads/release/python-3120/).

**Comment by kayhayen** [comment]
Ok, main goal this time is to be faster. But honestly, I wasn't able to look at it in the past weeks, but I will try and see if the C side of things got any worse.

**Comment by kayhayen** [comment]
So, actually I took a dive yesterday, and checked it out. I finished a bit on the exception state change. They now only store the exception value, instead of a lazy stored type and value, which can be a constructor argument, and may never be created. I am not sure how they think it's faster to create the objects, maybe they are more catchable, but many exception raises that just set the KeyError and e.g. the key as a value, now need to construct the actual exception object, just to maybe get it checked for KeyError type.

This will affect a bunch of code. Maybe exception creation got faster, and I think it did. But avoiding it for immutable exceptions (args doesn't contain a list) would be nice. Maybe CPython does that in their bytecode. I didn't look at what caches do for them yet. But that is about performance. For compatibility, we can normalize in cashed fashions ourselves in the mid term.

**Comment by kayhayen** [comment]
The other thing I looked at is dictionary changes. For 3.11 we needed to define a bunch of then private types, which not only got changed, but exposed somewhat to use again, so many of the dict interface changes are now `< 3.11 >` only, which is showing that these things evolve too quickly these days. Anyway, with disabled dictionary optimization, this now compiles. We will have to update the Jinja2 template to do it fully, but that too is only about performance, for now there is an experimental flag to just not use the optimized code, but generic Python API. That is slow, but will allow us to see runtime and not depend on this code correctness when checking other code correctness.

**Comment by kayhayen** [comment]
One thing I started to look at only, is how strings changed.

This from 3.11
```
typedef struct {
    PyASCIIObject _base;
    Py_ssize_t utf8_length;     /* Number of bytes in utf8, excluding the
                                 * terminating \0. */
    char *utf8;                 /* UTF-8 representation (null-terminated) */
    Py_ssize_t wstr_length;     /* Number of code points in wstr, possible
                                 * surrogates count as two code points. */
} PyCompactUnicodeObject;
```

that is now in 3.12

```
/* Non-ASCII strings allocated through PyUnicode_New use the
   PyCompactUnicodeObject structure. state.compact is set, and the data
   immediately follow the structure. */
typedef struct {
    PyASCIIObject _base;
    Py_ssize_t utf8_length;     /* Number of bytes in utf8, excluding the
                                 * terminating \0. */
    char *utf8;                 /* UTF-8 representation (null-terminated) */
} PyCompactUnicodeObject;
```

So the `wstr_length` is gone, and the way these two lengths interacted and when which one is initialized or not, is gone. We got a few functions that emulate CPython for string creation and in-place concatenation that is not slower than what CPython does because of API calls, and sometimes even faster, because we specialize for knowledge there. This won't be too bad I think, but pretty annoying. I believe the length handling makes this more difficult and I think that `kind` has gotten more plentiful, maybe the ones with surrogates now got their own kind, it seems there are more things to check in 3.12, which allows a bit more specialization to us maybe.

And then, what I also saw is that long objects changed, the `int` of Python3. They used to do this:

```
struct _longobject {
    PyObject_VAR_HEAD
    digit ob_digit[1];
};
```

And that was basically a standard variable size object, with the object size abused to carry the sign.

In 3.12 this is like so:

```
typedef struct _PyLongValue {
    uintptr_t lv_tag; /* Number of digits, sign and flags */
    digit ob_digit[1];
} _PyLongValue;

struct _longobject {
    PyObject_HEAD
    _PyLongValue long_value;
};
```

The variable size nature is now done manually. And it seems the digit count, sign and whatever flags means is stored there.

Our Jinja2 templates will be affected by that, but I believe sign and digit count are already abstracted, and it might actually be relatively easy, and functions like `Nuitka_LongFromCLong` might need a lot of changes, and the few cases where that is not true, it can be done easily. This is e.g. a template, where the `digits` are pointers gotten through abstract code, but the size correction for negative to negative value is done manually, and probably needs abstraction too. Here is our in place code for longs that are not small values:

```
        if (a_negative) {
            if (b_negative) {
                *operand1 = _Nuitka_LongAddInplaceDigits(*operand1, b_digits, b_digit_count);
                Py_SET_SIZE(*operand1, -Py_ABS(Py_SIZE(*operand1)));
            } else {
                *operand1 = _Nuitka_LongSubInplaceDigits(*operand1, b_digits, b_digit_count, -1);
            }
        } else {
            if (b_negative) {
                *operand1 = _Nuitka_LongSubInplaceDigits(*operand1, b_digits, b_digit_count, 1);
            } else {
                *operand1 = _Nuitka_LongAddInplaceDigits(*operand1, b_digits, b_digit_count);
            }
        }
```

So the hope is that this will largely be harmless. I didn't find any "flags" being used on longs. One thing that is new is that `_PyLong_IsCompact` can be used for things, and `_PyLong_CompactValue` seems to give easily comparable values, that might be useful for shortcutting comparisons. This is an example of an expanded `long >= long` comparison helper:

```
static PyObject *COMPARE_GE_OBJECT_LONG_LONG(PyObject *operand1, PyObject *operand2) {
    CHECK_OBJECT(operand1);
    assert(PyLong_CheckExact(operand1));
    CHECK_OBJECT(operand2);
    assert(PyLong_CheckExact(operand2));

    PyLongObject *operand1_long_object = (PyLongObject *)operand1;

    PyLongObject *operand2_long_object = (PyLongObject *)operand2;

    bool r;

    if (operand1_long_object == operand2_long_object) {
        r = true;
    } else if (Py_SIZE(operand1_long_object) != Py_SIZE(operand2_long_object)) {
        r = Py_SIZE(operand1_long_object) - Py_SIZE(operand2_long_object) > 0;
    } else {
        Py_ssize_t i = Py_ABS(Py_SIZE(operand1_long_object));
        r = true;
        while (--i >= 0) {
            if (operand1_long_object->ob_digit[i] != operand2_long_object->ob_digit[i]) {
                r = operand1_long_object->ob_digit[i] > operand2_long_object->ob_digit[i];
                if (Py_SIZE(operand1_long_object) < 0) {
                    r = !r;
                }
                break;
            }
        }
    }

    // Convert to target type.
    PyObject *result = BOOL_FROM(r);
    Py_INCREF(result);
    return result;
}
```

**Comment by kayhayen** [comment]
So, what we might be able to do there, is to check for compactness do that first, like they seem to do:

```
    if (_PyLong_BothAreCompact(a, b)) {
        return _PyLong_CompactValue(a) - _PyLong_CompactValue(b);
    }
```

The code that is given here, is the difference and sufficiently usable for longs of decisions, and two longs can be bitored before testing with a shift for compatness, so that's probably quick indeed. For Nuitka that means a bunch of more abstractions, and of course a branch if compactness is a thing at all in a given version.

**Comment by kayhayen** [comment]
So, the string changes are probably next, might be easy to make once I find a good time slot for it. And then a long migration can be done without taking compactness into account immediately, and maybe we can do Hello World with that already. I have to make a hotfix though

**Comment by leet0rz** [comment]
Is 3.12 supported yet?

**Comment by bersbersbers** [comment]
> Is 3.12 supported yet?

@leet0rz you seem to know how GitHub works. How likely do you think it is that Python 3.12 is supported, given that
- 3.12 is not mentioned at https://github.com/Nuitka/Nuitka
- 3.12 is not mentioned at https://pypi.org/project/Nuitka/
- 3.12 is not mentioned at https://nuitka.net/doc/Changelog.html
- This issue is still open.
- This:
  https://github.com/Nuitka/Nuitka/blob/e17eb822e7091ee4f20ae882f706b2d7628e3f22/nuitka/PythonVersions.py#L52-L54

**Comment by kayhayen** [comment]
@bersbersbers thanks, that made my day ❤️

**Comment by leet0rz** [comment]
> @bersbersbers thanks, that made my day ❤️

And it gave me the answer I was looking for 😁 Thanks guys, peace.

**Comment by kayhayen** [comment]
Actually 1.9 has bunch of changes aimed at 3.12 support, but it's not nearly complete yet. Passing the thread state around is e.g. part of the work that will allow it to not be absurdly slow on Windows with its Python DLL being slow to get it.

I added it to the roadmap though, and changelog has something for the careful reader.

```
-  User Manual: Added promise to support newer Python versions as soon
   as possible.
```

**Comment by rupurt** [comment]
You’re a machine @kayhayen

**Comment by mishamsk** [comment]
> You’re a machine @kayhayen

second that!

**Comment by vmtest888** [comment]
> You’re a machine @kayhayen 

+1

**Comment by rupurt** [comment]
@kayhayen do you any pointers or a guide in what and how you looking for changes in new python version changes that are needed in Nuitka?

**Comment by kayhayen** [comment]
@rupurt you are missing a verb. Check out my 3.11 post series and wait for a coming 3.12 post series and monitor that for whatever the question was intended to be, it will answer it likely

**Comment by FlippantDev** [comment]
so when is it gon release? (no pressure tho)
pyinstaller is marking my app trojan and i cant keep submitting file requests to ms it takes them 2-3 hours to get back

**Comment by heham** [comment]
2024.2.22,it's not support yet

**Comment by leet0rz** [comment]
> > 2024.2.22,it's not support yet
> 
> Thanks! If you did this regularly, we could all get rid of our calendars. (There is some irony in my post.)

I mean at this pace Nuitka might as well start development for 3.13 now. Bet python 3.13 will release before Nuitka supports 3.12 🐌

**Comment by FlippantDev** [comment]
why is the development so slow anyways?

**Comment by KevinRodriguez777** [comment]
> why is the development so slow anyways?

Because the @kayhayen is the only developer working on Nuitka, maybe if more people joined in and helped with Nuitka development, we could have faster support for features that people want, as it is, Kay Hayen is working on a backlog of issues that require his attention before being able to move on to new issue issues or features like python 3.12 support, as it stands, yeah 3.13 might release before nuitka supports 3.12, do you want to change that? then please contribute to Nuitka Development if you have the know how.

**Comment by kayhayen** [comment]
Thanks @KevinRodriguez777 for your kind comment. Let me state it clearly however, I am not alone in this, you are e.g. doing all you can to make things easier for me, and to help grow the community. Very much appreciated.

From my experience, plenty of people understand the craziness of a single developer keeping up with changes a community of developers implement. When coroutines and asyncgen got implemented, this literally took a year of my life, and of those people who did it, I guess. I do never complain about any of that. It's my choice. There could absolutely be the expected number of compilers as compatible and powerful as Nuitka, namely zero. I decided I will try making it or die, of old age.

My visions take time to come to fruition. In my last TWN I made exciting things about the optimization I want to do. I made more of that. It's also correct that I am catching up. And I seem to have decided that I want to do scalability first, and to onboard the new technical writer that will help make Nuitka more successful.

I also have yet to see a reason why 3.12 is the only Python to be used. Nobody is claiming for it to be faster (unlike with 3.11) and rather to the contrary. So I am not panicking if it will take a bit longer. I can only do so much, and scalability is something that needs an effort this spring, and I will be more productive, and Nuitka will be better for it. I want to do 3.12 in the summer, and I think optimization break through for integer loops in autumn. That's my roadmap. If you are a sponsor of Nuitka commercial, you can discuss it with me, and I will do your stuff sooner. 

If you are not, forget the level of entitlement for a moment and feel the love I have for you, trying to improve what Python can do for all of us. Otherwise use what works for you, and if Nuitka is not among if for lack of support of Python 3.13, well yes, then go away.

As a side note here, the Python version that supports no-GIL, whichever it is, I will clearly focus on being there as soon as possible, since that will matter more than anything (for performance) in a long time.

And getting back to it. People doing Yaml work that are not me. People joining the Nuitka issue triage team. People that help users with issues, and break it down for me to the really simple reproducer that I can solve with only a couple of hours effort very hard things, those are great to have and I am blessed by all of you who help me there.

I am overdue with TWN next, I will probably write one the other day. Today I had a bunch of private stuff going on here, that distracted me, but I will be using TWN to make this more clear.

A really good way of contributing to Nuitka right now is e.g. to proof read the Website, that we are currently restructuring, me and the technical writer, it has a fantastic new section: https://nuitka.net/pages/website-manual.html

Anyway, peace and out. Please comment only in upvote fashion and or if you have news to add. I am getting notifications about every single message in the tracker, and I would like to keep it that way. Comments that have no value are detracting me and are the opposite of helping. That said, let me not imply that you are wrong to be asking the questions you did. I just think that common sense could tell you some of the answers given, but I can see how that's not happening in all cases. I am stupid elsewhere all the time, don't look for my issues elsewhere. ;-)

**Comment by kayhayen** [comment]
There is progress there, I did the necessary changes to abstract the `long` repr changes, and I commented out, the bits we need from `str` to do in-place operations, those will be doable, it now fails to link. Specifically the "current exception" functions need to be made more general. Python changed to forcing to have an exception value at all times, and only that, with a traceback attached to it, rather than the traditional triple of (exception type, maybe value of that type, maybe to be normalized by creating it delayed, and exception_traceback).

When this is under control, we can hope for running it. The goal I have is to make 3.12 support and then 3.13 support with noGIL in quick succession. Due to massive help e.g. from @Maxwell175 and @KevinRodriguez777 to mention only the most active ones, I am able to focus on that more now. It feels I only need to convince myself to not refactor too heavily for the exception changes.

There, the triple that needs to be saved and restored frequently, as it's a common pattern for code to not change it, while working with things that themselves create exceptions and handle them in C code, should become more of a struct, so that code can be the same for all versions. Similar things were done for other such triples in the past, namely the published exception, frame exceptions, the like.

Things are looking increasingly good. There will be a posting during this week that details the status.

**Comment by akbartaimurr** [comment]
cant wait to switch lmfao, pyinstaller keeps false positive-ing my software as a virus :(

**Comment by kayhayen** [comment]
In my book, there are little reasons to use 3.12, I understand 3.11 gave a boost, but 3.12 was preparing for the GIL stuff, and actually looses single core performance that they sort of made up for with some changes, but it wasn't the break through. Much different with 3.13 though.

**Comment by bersbersbers** [comment]
I could imagine that the most important reason to switch (at least for some people, including me) is the short binary support of older versions, on Windows in particular. We'll be seeing the final 3.11 release in less than two weeks - after that, Windows users are on their own, even regarding security fixes.

> Final regular bugfix release with binary installers:
> 3.11.9: Monday, 2024-04-01

https://peps.python.org/pep-0664/#bugfix-releases

**Comment by sebdelsol** [comment]
> We'll be seeing the final 3.11 release in less than two weeks - after that, Windows users are on their own, even regarding security fixes.

Not really PEP 664 says:
>After that, it is expected that security updates (source only) will be released until **5 years after the release of 3.11.0 final**, so until approximately **October 2027**.

And it's not that hard to build those versions or find those builds from trusted sources.

**Comment by bersbersbers** [comment]
> find the binary builds from *trusted sources*

That's relative, I suppose. Where would you recommend getting Windows installers for 3.10.12, for instance?

**Comment by kayhayen** [comment]
Can we not have this discussion here please @bersbersbers ?

**Comment by kayhayen** [comment]
Just letting you know, I pushed for 3.12 support this recent week a bunch, and did refactorings to make the portability of the code go well for Nuitka. As you probably don't understand, supporting 3.11 and 3.12 with the same code requires abstractions, and after first managing to get the long changes abstracted and running correctly for 3.11 and below again, with that taking a few iterations, I have continued on the current exception handling. Generators, Coroutines, and Asyngen, which have each implementations and interactions with one another in Nuitka, as well as uncompiled generator integration, do a horrible amount of work with exception state, preserving, restoring, inspecting, setting it all in the helper code.

That took an eternity to get migrated and again bug free for pre-3.12, but it now compiles for 3.12, and in fact, the only remaining issue, is that for unicode in-place `+=` we need a sort of replication of Python core code, or else it's terribly slow. That one will essentially have to be redone, since Python cleaned up their unicode implementation a bunch, removing a lot of legacy features.

We already take advantage of that in a few places, but this function will be a bit of effort to replicate (correctly), and then we are off to launching the empty module test successfully.

I got a few functions that abstract things, but do `assert(false)` in C now. There is a few functions I added yesterday, for compatibility with Nuitka code generation. You know, the tripe of exception type, value, traceback, is deeply woven into code generation. Morphing that as well to use "exception_state" struct with is 3 or 1 things, and work with abstracting helper code on that only, is another big task that gets delayed.

That said, running it for the first time, and maybe getting a hello world moment is probably bound to happen this week. I cannot tell yet, but I believe the code for raising e.g. `ZeroDivisionError` instances, probably needs some changes too. Python seems to now require to not be lazy about object creation, which feels slower, but the avoided checks and normalization, I can see how it reigns in on that. But there might be cases, where Nuitka wants to be lazy, and others where it does not. We certainly would prefer to still handle a `KeyError` without ever having the exception created for best local performance.

Code generation will probably have to change a bunch. Generated code will probably have to offer variations to itself, and helper code needs to be audited for exception normalization or passing. 

But all of that can come later. Once 3.12 runs anything, we can look at why it's going to be slow or wrong.

Wish me luck with emotes rather than comments, but if you have like good questions or remarks, don't hold back. 

I expect to make Nuitka this Week posting once I have a hello world of 3.12 again. Much of what I wrote here, will belong there.

**Comment by pHiney** [comment]
> Just letting you know, I pushed for 3.12 support this recent week a bunch, and did refactorings to ...

Given the changes, was there value in making the product work for both 3.12 and <3.12 ?
Just throwing up the idea to split off a fork for pre and post 3.12. Allowing one to move to legacy ?

Thanks again for your efforts. 
pH

**Comment by kayhayen** [comment]
My customers see the value I believe. Not everybody moves to the latest and greatest software at release time. You can easily spend many weeks to workaround breakages in your PyPI packages, and changes that come from having to update to latest XYZ of all the things, and then finding, and important requirement isn't yet doing it, so you rewrite parts of your program to use an alternative, that however doesn't do all the things.

Life for professional software developers is like, we will update when the beta testers got the worst bugs fixed, upstream have moved to stable and good releases that work with it. That's usually 1-2 years down the road. So adopting 3.11 is probably mostly a thing when 3.12 is obsolete in your world.

That's the junior software developer introduction. Now on to why I don't want to do it.

Dropping older Python versions, means, I will be making changes without a baseline to compare. Right now, I can test many of my 3.12 developments with older Python versions. For 3.11 I have made the experience, that making the 3.4 feature set work, and debugging that, and being able to compare 3.4 with the change Nuitka code and pure Python, has helped tremendously in finding bugs.

For example also now, the `long` changes, when I implemented the 3.12 changes, I wouldn't be able to execute them at all, unless I also complete like 3 other big items. I would never know why something is failing, and it could be everything. By making those changes in a fashion, that pre-3.11 broke, I have not had to debug this in a 3.12 environment, but git bisected changes, where I could even revert parts of the finally found commit, and execute it in 3.11, find the bug that also affects 3.12.

For me, having a working thing, that I can test with, at all times, is super critical. 

I know, it's super cool advice to give, make the problem smaller, then it becomes easy. But to me it's like suggesting to dissolve NASA and found a new agency to go to the moon. Very likely, that's going to be extremely more expensive and you won't ever get there.

**Comment by kayhayen** [comment]
So, Python3.12 had its hello world moment. Currently raising and/or catching and exception crashes it, but I know there are problems, and I also have MinGW64 happy with debug mode enabled, but MSVC is giving a bunch of valid warnings still, that I should address first, and for exceptions specifically, there are a few operations that are not implemented yet, and errors, e.g. I get this one: `Assertion failed: ob->ob_type != &PyLong_Type, file C:\PYEC3A~1\include/object.h, line 231` indicating it's pretty like that I need to fix the warnings. But it feels good. From here, it won't be long anymore until basic tests work, or so I am hoping.

**Comment by kayhayen** [comment]
So, many basic tests have started to work. Runtime assertions pointed to places where the `long` changes are not yet entirely good, and it seems those MSVC warnings are very valid. Nuitka works in `long`, but effectively Python can now use `Py_ssize_t` and that can be larger, and might be on Windows there. A bunch of changes are going to be needed there, but for now it appears to be correct, maybe largely just not optimal. I took note of a bunch of optimization that our long object creation code could get, ones that will also apply to pre-3.12, esp. for the object creation, which has become slower in 3.11 with Nuitka. That would be great to address.

Right now I am at "GeneratorExpressionsTest" in the alphabetically run test set, and it's leaking an iterated object of generator expressions, it seems, probably somewhere the changes for tracebacks to be always attached and retrieved from the exception value are not yet good.

I have not yet marked 3.12 as experimentally supported. I will do it once I have the basic tests running. I am now auditing the code for exception handling, where there maybe a transferred ownership of an exception is not released.

But overall, very good news. I think 2.2 will release maybe without this being on, not sure yet. I would much rather have it not work at all than very badly, and it's making quick progress, but on the other hand, regressions for pre-3.12 are frequent unfortunately with the many refactorings. Right now it looks good, so maybe it's a good point to release and then focus on 3.12 changes and be disruptive until stabilizing for 2.3 release one month later.

**Comment by kayhayen** [comment]
So, I have been sprinting a bunch, and the exception handling stuff seems to have had more issues, and some of them hard to find, but I eventually figured them all out, so the "basic" tests of 3.12 are passing. I saw a few other test suites pass as well after I added 3.12 to my internal CI. I am waiting now for the results of running everything. The CPython 3.11 test suite, completed with 3.12 successfully is the next phase.

For standalone, I encountered the need to add `type ` statements, that produce type aliases it seems, since stdlib does it, but with that standalone seemed to work right away, at least on Linux with 3.12, waiting for CI results for that too now, sometimes Windows was more problematic, but I don't expect that.

I am not even putting this on the factory branch yes, before I see CI results, but once I do, I expect to also make a pre-release with 3.12 Python support being experimental.

**Comment by 123GitHub0123** [comment]
For now, I think python3.11 is a better choice. 3.12 is more of a transitional version from 3.11 to 3.12. It is not as stable as 3.11 in many areas, its performance is not as good as 3.12, and even it does not improve much for 3.11. Maybe it would be wise to put more effort into 3.11 and 3.13, but there are a lot of partners who choose 3.12, but I'm not optimistic about it.
Thanks to @kayhayen for the ongoing development of nuitka to make distribution efficient.

**Comment by KRRT7** [comment]
> For now, I think python3.11 is a better choice. 3.12 is more of a transitional version from 3.11 to 3.12. It is not as stable as 3.11 in many areas, its performance is not as good as 3.12, and even it does not improve much for 3.11. Maybe it would be wise to put more effort into 3.11 and 3.13, but there are a lot of partners who choose 3.12, but I'm not optimistic about it. Thanks to @kayhayen for the ongoing development of nuitka to make distribution efficient.

do you expect 3.13 to simply work out of the box without any of the changes from 3.12 and complying with 3.11?

**Comment by 123GitHub0123** [comment]
At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!

> > 目前，我认为 python3.11 是一个更好的选择。3.12 更像是从 3.11 到 3.12 的过渡版本。在很多方面都不如3.11稳定，性能不如3.12，甚至对于3.11也没有太大的提升。也许在 3.11 和 3.13 上投入更多精力是明智的，但是有很多合作伙伴选择了 3.12，但我对此并不乐观。感谢  nuitka 的持续发展，使分销高效。
> 
> 您是否希望 3.13 开箱即用，无需与 3.12 相比进行任何更改并遵守 3.11？

At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!

**Comment by KRRT7** [comment]
> At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!
> 
> > > 目前，我认为 python3.11 是一个更好的选择。3.12 更像是从 3.11 到 3.12 的过渡版本。在很多方面都不如3.11稳定，性能不如3.12，甚至对于3.11也没有太大的提升。也许在 3.11 和 3.13 上投入更多精力是明智的，但是有很多合作伙伴选择了 3.12，但我对此并不乐观。感谢  nuitka 的持续发展，使分销高效。
> > 
> > 
> > 您是否希望 3.13 开箱即用，无需与 3.12 相比进行任何更改并遵守 3.11？
> 
> At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!

3.12 support is **necessary** for 3.12

**Comment by 123GitHub0123** [comment]
> > At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!
> > > > 目前，我认为 python3.11 是一个更好的选择。3.12 更像是从 3.11 到 3.12 的过渡版本。在很多方面都不如3.11稳定，性能不如3.12，甚至对于3.11也没有太大的提升。也许在 3.11 和 3.13 上投入更多精力是明智的，但是有很多合作伙伴选择了 3.12，但我对此并不乐观。感谢  nuitka 的持续发展，使分销高效。
> > > 
> > > 
> > > 您是否希望 3.13 开箱即用，无需与 3.12 相比进行任何更改并遵守 3.11？
> > 
> > 
> > At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!
> 
> 3.12 support is **necessary** for 3.13

That may be good for many people who use 3.12, but it will cost you more energy, and I admire your work attitude.

**Comment by KRRT7** [comment]
> > > At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!
> > > > > 目前，我认为 python3.11 是一个更好的选择。3.12 更像是从 3.11 到 3.12 的过渡版本。在很多方面都不如3.11稳定，性能不如3.12，甚至对于3.11也没有太大的提升。也许在 3.11 和 3.13 上投入更多精力是明智的，但是有很多合作伙伴选择了 3.12，但我对此并不乐观。感谢  nuitka 的持续发展，使分销高效。
> > > > 
> > > > 
> > > > 您是否希望 3.13 开箱即用，无需与 3.12 相比进行任何更改并遵守 3.11？
> > > 
> > > 
> > > At least I think nuitka support for 3.12 is unnecessary, it will waste your energy too much!
> > 
> > 
> > 3.12 support is **necessary** for 3.13
> 
> That may be good for many people who use 3.12, but it will cost you more energy, and I admire your work attitude.

3.12 introduced changes in cpython's source code that is neccesary for 3.13, without having 3.12 working, it's impossible to get 3.13 to work.

**Comment by 123GitHub0123** [comment]
> 3.12 introduced changes in cpython's source code that is neccesary for 3.13, without having 3.12 working, it's impossible to get 3.13 to work.

The release of 3.12 is currently in a transitional phase, and it is anticipated that 3.11 and 3.13 will be adopted by a larger number of partners compared to 3.12. However, for Nuitka, the addition of support for 3.12 may not have long-term utility.

**Comment by 123GitHub0123** [comment]
> > 3.12 introduced changes in cpython's source code that is neccesary for 3.13, without having 3.12 working, it's impossible to get 3.13 to work.
> 
> The release of 3.12 is currently in a transitional phase, and it is anticipated that 3.11 and 3.13 will be adopted by a larger number of partners compared to 3.12. However, for Nuitka, the addition of support for 3.12 may not have long-term utility.

But expect nuitka to get better

**Comment by kayhayen** [comment]
Nuitka has no opinions about what Python versions its users use. It supports Python 2.6 to 3.12 (soon enough), and it will add 3.13, in terms of priority, I decided that before doing 3.12, scalability projects and catching up on legacy issues, was more important, since 3.12 wasn't what 3.11 meant to users. For 3.13, with no GIL, indeed, things will be entirely different.

The constant proposal to skip or dump Python versions is evidence of ignorance of the proponent, but I get it. It's a very common suggestion to make in every context, and people feel it's good one. And also people feel like it just hasn't been considered yet, and that's not why it's done. I am ignorant in other contexts a lot.

That said, indeed all the work done for 3.12 support is extremely likely necessary for 3.13, I don't think there is anything that will be changed again, and a gap in version support makes no sense at all anyway. What I still recall and am influenced by, is that for 3.5.0 Nuitka implemented coroutine support, only to discover that 3.5.2 changed so much, that it was essentially a duplicate effort. Nuitka's code is still ridden with the defines that make that possible. Also, sometimes, for 3.7, 3.8, 3.9 there were larger transitions that re-implemented stuff. I think dictionaries changed a bunch, and we got to redo stuff there over and over, but it's not a drama really. It's not what takes us so long.

But honestly, dropping of skipping Python versions won't do much for me. I have outlines in the past, how Python 3.4 was very useful for me to get 3.11 to work. Just because it's a smaller amount of code that is needed for it, it was so useful to be able to skip coroutines and asyncgen when working on Python3 generators. Getting everything to work at once can be extremely hard.

What takes us so long this time around, is that Nuitka has become the premier choice of many projects, and is held up to a very high standard, that has only ever increased. When people will be starting to use Nuitka with 3.12 without an experimental label, they will know it's going to work well for them except for very few corner cases, and then just pitch perfect. And 3.11 was extremely high effort, due to extremely invasive core changes. It seems 3.12 is easy again. But the amount of time spent on 3.11 was causing backlog in other areas, that needed to be caught up with.

The level of support for packages, esp. AI packages, is also continuously increasing. And the big Yaml transition for package configuration to make it easy to expand by others, and scalability work is all happening on the side, while also making the preparations for the huge performance boost, that we expect to see this autumn at 3.13 release. The loop analysis break throughs that I blogged about, they also took time of course. And while being a side effect of the scalability work, that was also a lot of time sunk there. And the bugs found when taking more advantage of it, were old, but still needed debugging to retain correctness. In some cases, Nuitka optimized now, but was exposed to do it wrong. These changes are always enhancing correctness of the full package, but sometimes hard.

I think it made sense, to focus on scalability for some time, and performance too, and on package support all the time, and interesting examples are e.g. the recent addition of working Tensorflow JIT, and probably soon also Numba JIT. All of that is a huge burden on development time, that we do once, and then benefit forever from. The Tensorflow JIT probably was known for a very long time, but only recently, the structure of Nuitka made it easy to add it. Years of refactoring and cleanups are needed for these types of advances to be only a few days of work then.

Right today, we were discussing how WASI could be used to start proper cross compilation support, which again will eat up a lot of time, but might enable a lot of useful things. That's the next big line of expanding Nuitka into more effort territory.

Nuitka is a big ship that advances on all ends all the time, even if it takes years, but sometimes, hard decisions must be made. Like when I didn't do cross compilation despite many requests, but always followed a plan that will make it possible one day. Or like when I decided that 3.12 wasn't immediately going to be worked on full time, but in a dedicated sprint later. Of course, I always did refactorings that were getting me closer, but not the deeper push I made in the last 4 weeks.

Honestly, I am very happy with the direction things in Nuitka land are taking. I will be looking at the state of 3.12 this weekend, but I won't make changes I know to be necessary yet, as I don't want to destabilize 2.2 release for pre-3.12 further. For me that release is going to be more important than anything else right now. 

I think, finishing 3.12 with 2.3 is good enough, and working on the interesting performance and scalability improvements, that I noticed possible for 3.11 too, in that frame, is probably good enough. My focus once 3.12 sort of works will be to look at the Python3.13 beta/release candidates, and get them supported on a hello world level soon. I am super curious how bad no-GIL is for Nuitka in terms of implementation.

Actually now, looking at 3.13 changes would be possible, and might be worth my time, so I can take it into account. But I think I will want to debug 3.12 and add its new features first. From the looks of it, should be relatively easy, but 3.11 test suite with 3.12 is coming first. There is still going to be plenty of time I hope before 3.13 lands.

Anyway, lets bare with people that make ignorant suggestions in good faith. This year is super exciting for Nuitka. The support of 3.12 is not going to be ground breaking, for no-GIL 3.13 however, it might kick of a bunch of extremely nice things.

**Comment by marcellodesales** [comment]
@kayhayen I'm here looking for 3.13 support :) We love Nuitka and kudos to all the efforts for 3.12! Appreciate all the notes on the upgrade and I will keep following it...

**Comment by kayhayen** [comment]
The current pre-release works for up to test_inspect, passing test_coroutines, test_generators and test_asyncgen on the way, but it seems there are still issues with some form of frames, that I need to figure out. Chances are good for this to be finished for a 2.3 relatively soon.

I am working with the 3.10 test suite here, since I never really did the 3.11 test suite fully, doing that on the side. It had not a lot of functional changes, so it shouldn't matter.

**Comment by kayhayen** [comment]
So, the `test_inspect` crash was the last thing to resolve, now the 3.10 test suite is running fine with Python 3.12 it seems. I have annotated that as fully supported for the 2.3 release which I expect to make in the coming week. As I will be on holiday, I don't know if I want to make a release that then I will want to hotfix.

The story continues in #2834 now, I consider this resolved.

**Comment by kayhayen** [comment]
The 2.3 release has just been made and Python 3.12 is now considered officially supported. Of course, take it with a grain of salt, newly supported versions will more likely have issues, than ones that are longer supported. For now, I would recommend using 3.10 or 3.11 personally, but surely hotfixes will be had for anything that comes up in good report form.
