### ISSUE TITLE
basename(__name__) always returns python file name

### ISSUE THREAD

**Issue by zloidemon** [Nuitka/Nuitka#244]
Linux
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

Versions
```
$ python -m nuitka --version
0.6.2rc3
Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
Executable: /home/vg/tmp/.venv/bin/python
OS: Linux
Arch: x86_64
```

Example code
```
import os
name = os.path.basename(__file__)

print(name)
```

Output by use python:
```
(.venv) vg:~/tmp$ python test.py
test.py
(.venv) vg:~/tmp$ ln -s test.py 123
(.venv) vg:~/tmp$ python 123
123
(.venv) vg:~/tmp$ rm 123
```

Build log
```
(.venv) vg:~/tmp$ python -m nuitka --follow-imports test.py --explain-imports
findModule: Enter to search 'site' in package None level 0.
_findModule: Enter to search 'site'.
_findModuleInPath: Enter site in None
findModule: Found absolute imported module 'site' in filename '/home/vg/tmp/.venv/lib/python3.5/site.py':
findModule: Enter to search 'os' in package None level 0.
_findModule: Enter to search 'os'.
_findModuleInPath: Enter os in None
_findModuleInPath: Using search path ['/home/vg/tmp', '/home/vg/tmp', '.', '/home/vg/tmp/.venv/lib/python35.zip', '/home/vg/tmp/.venv/lib/python3.5', '/home/vg/tmp/.venv/lib/python3.5/plat-x86_64-linux-gnu', '/home/vg/tmp/.venv/lib/python3.5/lib-dynload', '/usr/lib/python3.5', '/usr/lib/python3.5/plat-x86_64-linux-gnu', '/home/vg/tmp/.venv/lib/python3.5/site-packages'] for None
Candidates OrderedSet([('/home/vg/tmp/.venv/lib/python3.5', 1, '/home/vg/tmp/.venv/lib/python3.5/os.py'), ('/usr/lib/python3.5', 1, '/usr/lib/python3.5/os.py')])
_findModuleInPath: _findModuleInPath2 gave /home/vg/tmp/.venv/lib/python3.5/os.py
findModule: Found absolute imported module 'os' in filename '/home/vg/tmp/.venv/lib/python3.5/os.py':
```

Run binary file
```
(.venv) vg:~/tmp$ ln -s test.bin 123
(.venv) vg:~/tmp$ ./123
test.py
```

I expected same result as python execute script but got `test.py` instead `123`. I tried use `--file-reference-choice=runtime` but it didn't solve an issue.

**Comment by kayhayen** [comment]
That is a Python peculiarity how it treats launching through a symlinks. I will need to look into how they do it to decide how to emulate it.

**Comment by byehack** [comment]
```python
import psutil
__file__ = psutil.Process().exe()
```
this will work.

**Comment by kayhayen** [comment]
Ok, I think I got this one figured out, it's like this. For modules, Python tends to have an absolute path in tracebacks. Which is why there is code like this:

```
    def getCompileTimeFilename(self):
        """ The compile time filename for the module.

        Returns:
            Full path to module file at compile time.
        Notes:
            We are getting the absolute path here, since we do
            not want to have to deal with resolving paths at
            all.

        """
        return os.path.abspath(self.getSourceReference().getFilename())
```

For programs, this is then used and made relative, but effectively only for standalone mode, it can only be even considered to be made relative, as we have other code like this:

```
        module_filename = context.getOwner().getRunTimeFilename()

        # We do not care about release of this object, as code object live
        # forever anyway.
        if Options.getFileReferenceMode() == "frozen" or os.path.isabs(module_filename):
            template = "module_filename_obj = %s;"
        else:
            template = "module_filename_obj = MAKE_RELATIVE_PATH(%s);"

        statements.append(
            template % (context.getConstantCode(constant=module_filename))
        )
```

So I actually forgot why this ever happened, but there was always this difference with the traceback for main program to be absolute from Nuitka (and only that one) and not the others. 

And then for runtime filename, we simply defer to compile time filename, right now:

```
        reference_mode = Options.getFileReferenceMode()

        if reference_mode == "original":
            return self.getCompileTimeFilename()
```

But I guess, that is not where things should happen. Of course, Nuitka likes to not use relative and absolute filenames in a mix, as it allow duplication of files imported to happen. Cleaning this up will be hard, but is what's need to solve the issue.

I think the absolute paths are there, so moving allows to still find data files for modules, even if paths are relative. So many times, that is what allows the importing. 

Puh, I guess, this one is complex to solve and involves a decision. At least the original directory probably needs to be still in `__file__` while for main program, the basename could be changed only.

**Comment by kayhayen** [comment]
I have been doing the hardcoded `__file__` for accelerated mode on purpose. The idea is not to produce a duplicate that then can be moved, and will behave identical, but rather something that will do the same thing, and then doesn't require to move data files looked up through `__file__`. 

However, there is `--file-reference-choice` and I am starting to think that `runtime` should be derived from the binary name if possible, but I am very damn sure that some people rely on `.py` to be the suffix of the main script. What comes into play as well is that there is already https://nuitka.net/doc/user-manual.html#onefile-finding-files and I believe, people ought to use `sys.argv[0]` and not `__file__` in their programs, if that's what they are looking for. Therefore I reject this.
