### ISSUE TITLE
when specific sys.module["module_name"], packed exe executed error

### ISSUE THREAD

**Issue by wandth** [Nuitka/Nuitka#2452]
I what to import submodule which dependecny current python version 
so I write that code 
![image](https://github.com/Nuitka/Nuitka/assets/34237282/e946a64b-e6ab-40c2-84ee-f488d5a75b14)

it executed fine  as a script

but when i packed it: 
``` shell
"Z:\Scripts\Python39\python.exe" -m nuitka  --standalone main.py
```
then exectue it, it get  some errors
![image](https://github.com/Nuitka/Nuitka/assets/34237282/45299c4c-a0b9-48e4-955e-d4628ac2ce79)
 
- python version: **python3.9.10**
- nuitka version: **nuitka 1.8.2**
- os version: **windows10 22h2**

this is whole code
[nuitkaTest.zip](https://github.com/Nuitka/Nuitka/files/12679161/nuitkaTest.zip)

how could i solve it,

thanks

**Comment by kayhayen** [comment]
Renaming packages at run time like that, doesn't rename their children as well for Nuitka.

**Comment by kayhayen** [comment]
In this case, when you are replacing a module that is compiled with one that is as well, we could handle it, but not if you renamed it to something outside of the compilation. We could check for this, and handle it maybe, if we recognize that you are trying to import a name of an already imported module, to redirect to another name, which is what Python will do due to using `__path__` for the package to locate, whereas Nuitka currently is name based.

I think we also check the `__path__` and construct the module name to load from that. Needs more thought clearly.

**Comment by wandth** [comment]
@kayhayen 
hi， I found if i redirection vendor truly package  name, its works fine 
just like that
``` python
import sys

PY3 = sys.version_info > (3,)
vendor_module_name = "test"

if PY3:
    import vendor.customer_module.py_3.test
    sys.modules[__name__ + "." + vendor_module_name] = sys.modules["vendor.customer_module.py_3.test"]
else:
    import vendor.customer_module.py_2.test
    sys.modules[__name__ + "." + vendor_module_name] = sys.modules["vendor.customer_module.py_2.test"]
```

**Comment by kayhayen** [comment]
Well, for Nuitka any solution that involves code changes is bad, so I am never proposing it really. I think this kind of parent search is already being done in accelerated mode for extension module loading, it wouldn't be out of the ordinary to do that extra consideration. I will have to delay it though until 3.12 is under control, since it's not super critical for the time being.

**Comment by kayhayen** [comment]
I don't think I want to start allowing this, code that does this, needs to be cleaned up to not do it.
