### ISSUE TITLE
FileDialog PyQt5&GTK error

### ISSUE THREAD

**Issue by danielj-genesis** [Nuitka/Nuitka#2520]
Factory Nuitka as requested:
1.9rc6
Commercial: None
Python: 3.8.10 (default, Oct  4 2023, 11:36:56) 
Flavor: Unknown
Executable: /home/daniel/Desktop/nuitka_tests/env/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 18.04.6
Version C compiler: /usr/bin/gcc (gcc).

Python3.8.10 from source with, only enabled optimizations, created a new venv from it and then pulled factory from pip

`python -m pip freeze`:

```
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip
ordered-set==4.1.0
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.13.0
zstandard==0.21.0
```

Breaking sample code:

```
import sys
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QFileDialog

class FileDialogExample(QMainWindow):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        self.setGeometry(100, 100, 400, 200)
        self.setWindowTitle('File Dialog Example')
        self.button = QPushButton('Open File Dialog', self)
        self.button.setGeometry(150, 80, 150, 30)
        self.button.clicked.connect(self.showFileDialog)

    def showFileDialog(self):
        options = QFileDialog.Options()
        options |= QFileDialog.ReadOnly
        file_dialog = QFileDialog()
        file_name, _ = file_dialog.getOpenFileName(self, 'Open File', '', 'All Files (*);;Text Files (*.txt);;Python Files (*.py)', options=options)
        if file_name:
            print(f'Selected File: {file_name}')

def main():
    app = QApplication(sys.argv)
    ex = FileDialogExample()
    ex.show()
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()
```

- Provide in your issue the Nuitka options used
Built with: `python -m nuitka --standalone --enable-plugin=pyqt5 --report=compilation-report.xml pyqt5_file_dialog.py`

This code is built on **Ubuntu 18.04** and works from the *.dist build folder on the same system:
On moving to an **Ubuntu 22.04** system and trying to run the same way I get the following issue as described.
When clicking the file dialog button:

```
...
...
...
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(main.bin:21344): Gtk-WARNING **: 13:54:50.175: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
```

GTK is not being explicitly installed by pip as shown on the venv freeze and I'm not trying to use GTK for anything. I won't attach the build xml but it was shared by email if useful. Just posting here if the code or reference is helpful.
Thanks

**Comment by kayhayen** [comment]
So, lets resume here.  You privately already reported a compilation report, that I was looking at right an noticing that Qt integrates with what will be the Gnome and other GTK based desktops file dialog. It uses a Qt plugin that will of course only load when these DLLs are available, and probably fallback to something Qt native if needs be.

Nuitka currently follows these DLL dependencies, and on a user system, rather than a container, GTK is probably installed, whereas we usually avoid that. This is something that should be done right though. Right now there is an experimental `--experimental=no-outside-dependencies` that was intended to address it, but turned out to cause issues elsewhere, so it remained unfinished.

I enhanced its code now for factory/staging such that the decision of system package or not should be a lot more reliable even for non-Debian, since it now explicitly finds pip/conda package status or not, and is more robust in detecting Debian system package correctly as a result.

With that, one can hope that the issue of including GTK for Qt plugins goes away. The option is only implemented for the Qt plugins right now, so there might be other similar issues to be caused. However, the Qt plugins not picking up system DLLs should have to be more or less correct. However, a bare system might find some things lacking as a result. We might have to ultimately relax it or make the decision per DLL names or something like that.

I will now look into creating the Ubuntu LTS containers for `run-inside-nuitka-container`, such that I can reproduce this more easily on my side and e.g. compare the results from the various OSes more easily. I already have a CentOS8 image added, that was nearly complete anyway. Doing Ubuntu will naturally be very easy for me. I will get back to you with analysis results.

**Comment by danielj-genesis** [comment]
Thanks for checking this out, should I try from factory again then to see if it's working or wait? And I'm curious if you think this same issue could be contributing to some **pyqt5+glfw+cv2** issues too, I notice that when I have a simple pyqt5 script that renders a triangle with glfw and then tries to save the image with cv2 I get : `/glfw/__init__.py:912: GLFWError: (65543) b'GLX: Failed to create context: 0'` directly running the binary in the built *.dist folder on the **Ubuntu18** machine so that one doesn't even work compiled.

I can definitely get some sample code for that in another ticket too but glfw alone is behaving strangely as but only when the dist folder is **moved** to another computer. Would it be best to add these as two more independent tickets?

**Comment by kayhayen** [comment]
I was on a trip the other day, resuming now, but there might be a potential corruption issue with 3.11 that I definitely also need to look at, I hate those most, but this is mostly about fiddling to get the LTS containers right. Maybe pollute them GTK for testing purposes, and see it not being included, that kind of thing. For this feature however, I also need to check how "outside" is decided, is that outside of the package, because naturally the Python installation itself is fair game too, e.g. with Anaconda, their included DLLs are system compatible by their design. So, this is mostly still reviewing and testing things today, and making it easier to test, when e.g. I will add a report feature that shows why DLLs are not included (one that for diffable reports of course will not be done) so we can like see what gets rejected and if we feel that is OK. Basically I am still improving the tooling here.


I think this might develop into a selection in Yaml, where it says if PyPI packages should include outside DLLs or not. Some depend on things from the system, e.g. PyGTK, and some absolutely treat everything on the system as optional. But I am hoping that this is effectively the solution to all our issues.

**Comment by danielj-genesis** [comment]
>there might be a potential corruption issue with 3.11 that I definitely also need to look at

For python? I'm planning to stick with 3.8.10 but if it's a good idea I can tweak the pip packages versions I only stuck to these because they work working well.

**Comment by kayhayen** [comment]
I do not consider that the specific package versions play a role at all at this time, so stick to what you have, no problem. This is a very general issue probably. As for the 3.11 issue, that's one where people complain that `os.__file__` gets lost or isn't set, and I meant that just for priority, that's critical for me today too, doesn't seem this is affected at all, or for that to be a generally impactful issue.

**Comment by kayhayen** [comment]
So, the 3.11 thing is clarified, see my commercial posting, now turning to creating X11 display capable containers for all these versions, and trying to see if I can reproduce the GTK and the fontconfig thing. The later I am aware is also an issue for tk-inter, and it probably needs to be on a global list. But I would love to be able to build/run easily in pairs. In the past, I used VMs for it when it involves X11 displays, but that's not tenable really, and `run-inside-nuitka-container` surely can learn to pass a display on, even if only a Xonwayland, which is what I need to have on my favorite WSL setup.

**Comment by kayhayen** [comment]
So, doing X11 in my podman Windows is going to be off limits for a while. I managed to create 18.04 and 16.04 containers, but I think the later cannot even run PyQt5, my bad. 

In doing so, I recognized that their default Ubuntu Pythons were not capable of doing the detections I want them to do for package status. Specifically the pkg_resources sometimes yields packages with no metadata. It's very strange, and I think it is for Debian packages only, so we can use that still to detect pip/conda install or not.

I manage to get the example compiled now, and libfontconfig is indeed pulled in by Qt plugins. I am compiling right now with the experimental flag --experimental=no-outside-dependencies to see what and if it changes things. I will then try and compare with system Qt, so as to see that there, we do still include it all, as that build mode (where you have like a fixed OS, but maybe not with all DLLs) is continuing to work. 

For Nuitka, the reporting will now use `pkg_resources` for metadata versioning, so for older Python, it should give more information now. This is kind of vulnerable, as I noticed that using those pip internal interfaces, is not very much working everywhere, but we can deal with that over time, and actually I might be able to dial it back again, since what I was originally thinking, namely that "pip" would have the metadata of those problem packages, isn't true anyway.

The detection also now recognizes more top level packages. Previously we were filtering for Python files, but of course, e.g. a package may only contain extension modules. I noticed that when I saw that the PyQt5-Qt5 package was not recognized as using the `PyQt5` namespace.

So this kind of got a lot more polish now, and I am now getting where I want to be with building that. Requiring to be able to parse all packages and specifically to get PyQt5 and cv2 right, is a big deal. 

I was also using `opencv-python-headless` and then noticed, that for the `cv2` and options-nanny, the distribution name is hard coded, so that also drove a bunch of improvements, where this got cleaned up. No longer will it have to fall back to `cv2` importing to check its version, now it knows from metadata correctly.

**Comment by kayhayen** [comment]
So, diffing the compilation report shows that we got the desired effects, in terms of DLL inclusion. I saw a shift for some DLLs from `PyQt5` Qt plugin usage as a reason for a DLL to `cv2` or `glfw` usage. Those are not good, and I think I shall first change that PyQt/PySide plugin code, to becoming per package decisions, where we will have to be dealing with sub-packages, etc. properly. as well. 

This feels easy now, hopefully, I can manage that a lot quicker. And I suspect, there is going to be a bunch of fallout from the new package scan requirements, but we can achieve wide working relatively quickly.

**Comment by danielj-genesis** [comment]
That sounds promising. Is there anything that I should do to keep this more stable like using the pyqt5.GL bindings instead of glfw ones or build on a different Ubuntu version?

**Comment by kayhayen** [comment]
Using headless is a good enough idea, I don't think it matters. I am right now generalizing the code into the yaml configuration driven thing, hoping to get a very clean dist for your example here, independent of versions. I believe glfw should be working perfectly, I don't know how good or bad `pyqt5.GL` is, I would not recommend making the switch. Nuitka is just going to do it all fine real soon now. 💯

**Comment by kayhayen** [comment]
So, I think I solved this, but not in the correct way. Nuitka is attaching "package name" to DLLs, and `_ctypes` has no package name, and therefore is never being asked about in the DLL plugin, and then is not dealt with. I am currently trying to see if it now works, I was missing PyOpenGL in my container, those kinds of things, and I am trying to run it on Fedora 37 or so, which I am curious if that itself is a problem for Ubuntu Python builds. I am closing in on this though. It seems the default handling should be done in the general plugin code and not the DLL plugin, and it should consider stdlib used DLLs as something to include over non-stdlib ones. The DLL set I was seeing looked perfect though, so this is now only a question of refactoring and hopefully finding it to work on modern Fedora flawlessly.

**Comment by kayhayen** [comment]
I just  managed to compile on Ubuntu 18.04 run it on Fedora 38, using Debian Python (which should be kind of worst case) with no single warning, and it saving the image. I will strive to make it clean now.

I feel like "package name" attached to DLLs is not really enough, modules should be allowed to be tracked for DLLs too, which would be a bigger change, but for now, the new default would apply to all packages, and to no global namespace extension module, which is kind of unacceptable. The package name is currently used to decided extended DLL search paths for used DLLs of a package, e.g. PySide6 also searching in shiboken6, but not globally of course. But in order to decide stdlib DLL, we need to know the module name a DLL came from. This is mostly a cleanup, and I will have a report file to compare to to see if it is still remaining as good.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory and staging branches, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
I am very happy with the state of this implementation. I think an issue that remains now, is that stdlib kind of pulls in DLLs by default, and that `tkinter` will pull into `libfontconfig` therefore still. I need to maybe check `tkinter` separately, on this. For `_ctypes` it is needed to pull in `libffi` but the other one is off limits, need to see if there is more cases like that and maybe treat them through configuration rather than stdlib check.

**Comment by kayhayen** [comment]
I believe now would be a good time to test this, I am intent on making a 1.9 release as soon as possible, just doing a bit of house keeping.

**Comment by danielj-genesis** [comment]
Hi @kayhayen, I tested this ticket's sample code and I can confirm it's working now :)

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
