### ISSUE TITLE
[bug] Can't import * from a chinese(non latin1?) module

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2542]
```python
from 测试 import 这里
# translate: from test import here
这里()
# here.test

from 那里 import 另一个测试

另一个测试()

from 测试.这边 import *
# not pass here
# trying to import everything from a unicode module

为什么呢()
```

[test.zip](https://github.com/Nuitka/Nuitka/files/13328031/test.zip)

it will fails after `from 测试.这边 import *`

related to #2541

**Comment by shenjackyuanjie** [comment]
example passsed! ( wait for more test to close it

**Comment by kayhayen** [comment]
So, actually there were more issues to find. The star import was converting the unicode module names to UTF8 to check if they start with `"_"` in which case they should be ignored. However, that was not possible in your example and then it segfaults.

While debugging it, I discovered that MSVC hates the literals generated for `__file__` with `--debug` in accelerated mode, and probably was even producing incorrect values.

Also we were writing "module_name" directly into the template, using it with PGO inconsistently, which needs investigation, since that should have failed to work. But PGO seems to not work currently anyway.

We keep issues open until the release is made. However 1.9 is really close these days.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by shenjackyuanjie** [comment]
test are passed!

**Comment by kayhayen** [comment]
Adding the test to Nuitka is going to reveal how git/autoformat won't really like these file names.

**Comment by shenjackyuanjie** [comment]
lol, just "LET ME PASS"

**Comment by kayhayen** [comment]
I found an issue with isort, also hates the Chinese module name in the code, but I added a workaround for it, and so it's going to be in the 1.9 release also.

**Comment by kayhayen** [comment]
The test case also found an issue, where Python2 cannot delete Python3 build folders with these module names in filenames, that I also fixed, there is a good amount of small issues fallout from this one.

**Comment by kayhayen** [comment]
Part of the 1.9 release I just made.
