### ISSUE TITLE
qtawesome need it's font resource file

### ISSUE THREAD

**Issue by shenjackyuanjie** [Nuitka/Nuitka#2543]
![image](https://github.com/Nuitka/Nuitka/assets/54507071/82184f6d-cee9-4ccd-a2ac-d45a649f5c31)

sorry for the screenshot

textpath: `\QtEasyDesigner.dist\\qtawesome\\fonts\\fontawesome4.7-webfont.ttf`

pypi: https://pypi.org/project/QtAwesome/

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)
