### ISSUE TITLE
Question/suggestion: possibility to unpack and repack onefile binary

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2620]
Problem: a lot of useful libraries depends on LGPL code. As I understand LGPL license, distribution of such libraries in commercial projects requires technical possibility to update this libraries. In relation to Nuitka, this can be achieved by using "standalone" option instead of "onefile", so, such libraries will be places separately. However, "onefile" option is much more convenient for end-user.

So, my question: Is there a technical possibility to unpack "onefile" binary, substitute one or more dependencies and repack it back for file built with free or commercial version of Nuitka?

If not, may you give advice about multiplatform runnable SFX archive creator, that allows unpack and repack?

**Comment by kayhayen** [comment]
I have refused to do this (myself) in the past, but I am planning to add this, mostly because AV vendors are judging onefile by similarity, and being unable to look into it makes every malware fingerprint match hello world.

However, I am not sure when this happens. I am busy still with other stuff. I have restructured the format to be more archive-like already with some changes, also aimed at improving caching behavior. Still then I noticed that I want to make another change, where cache misses for only some files are entirely unlikely, and therefore we can separate headers and file data, into a mode that is both fast to unpack and efficient, but also needs uncompression only if one cache miss occurs, which is however going to be like always or never, and this format could then also be used for temp file. Once I finalize this, making a Python tool to unpack the archive is going to come. I do not think I will make a tool to update it, but maybe I will, but then it should be easier to create it for everybody. At that time definitely, the archive format should be described.

For now, there is no tool for repacking. One may come into existence in the future though. For a new sponsor I could imagine accelerating it maybe.
