### ISSUE TITLE
When I publish my software to microsoft store, the package build by nuitka, It told me that products must not contain or enable malware as defined .

### ISSUE THREAD

**Issue by riverbird** [Nuitka/Nuitka#2681]
I publish my program to microsoft store, the package build by nuitka, when I wait for several days, It told me the status "Attention needed"，and the report detail show me：
products must not contain or enable malware as defined by microsoft criteria for Unwanted and Malicious Soft. See https://learn.microsoft.com/zh-cn/microsoft-365/security/intelligence/criteria?view=o365-worldwide
How can I fix the problem?

**Comment by kayhayen** [comment]
Nuitka is the preferred choice of malware authors due to its protection of the source code, and the inability to investigate behavior of the program without deep analysis. This leads to Nuitka compiled binaries being reported as malware based on being similar to it, even for small programs, esp. for programs that use Crypto libraries and that deal with Crypto payments in particular.

There are ways around this, but further action will be needed, they are described here: https://nuitka.net/doc/user-manual.html#windows-virus-scanners

Naive compilation however is exactly what malware authors do, so it's not going to be sufficient to get your binaries not flagged.
