### ISSUE TITLE
WIndows Defender flagging qt application as Program:Win32/Wacapew.C!ml

### ISSUE THREAD

**Issue by dreisicht** [Nuitka/Nuitka#2685]
I'm building this pyside6 application: https://github.com/dreisicht/renderrob/

I'm building it successfully on my own windows machine with windows version 23H2 or in a github action.

I'm building in the simplest case with this command: `nuitka --plugin-enable=pyside6 --windows-icon-from-ico=icons/icon.ico  .\renderrob.py `
The build process runs smoothly:
```
Nuitka-Options: Used command line options: --standalone --plugin-enable=pyside6 --windows-icon-from-ico=icons/icon.ico
Nuitka-Options: --enable-console .\renderrob.py
Nuitka: Starting Python compilation with Nuitka '2.0' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 60 files (no progress information available for this stage).
Nuitka-Scons: Compiled 58 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 58
Nuitka-Postprocessing: Adding 8 icon(s) from icon file 'icons/icon.ico'.
Nuitka-Plugins:pyside6: Including Qt plugins 'iconengines,imageformats,platforms,styles,tls' below 'PySide6\qt-plugins'.
Nuitka: Keeping build directory 'renderrob.build'.                                                           
Nuitka: Successfully created 'renderrob.dist\renderrob.exe'.
```

For reference, a simple hello world program is working on my machine.
I've also tried using pyside6-deploy, but that has the same result.

In the past months not using `--onefile` and enabling the console by leaving away the `--windows-no-console` and `--disable-console` was helping, but with the newest windows defender update it is always marked as `Program:Win32/Wacapew.C!ml` or `Trojan:Win32/Wacatac.H!ml`

Any help would be highly appreciated!

**Comment by kayhayen** [comment]
Nuitka is the preferred choice of malware authors due to its protection of the source code, and the inability to investigate behavior of the program without deep analysis. This leads to Nuitka compiled binaries being reported as malware based on being similar to it, even for small programs, esp. for programs that use Crypto libraries and that deal with Crypto payments in particular.

There are ways around this, but further action will be needed, they are described here: https://nuitka.net/doc/user-manual.html#windows-virus-scanners

Naive compilation however is exactly what malware authors do, so it's not going to be sufficient to get your binaries not flagged.
