### ISSUE TITLE
Swappable PySide6 when compiling with --standalone for LGPL compliance

### ISSUE THREAD

**Issue by Mephiiistopheles** [Nuitka/Nuitka#2691]
Hello,

I'm currently exploring the implications/practicalities of using Nuitka in standalone mode to compile a (potentially) commercial application with a PySide6 GUI, and all of the fun LGPL implications that go along with this. I have seen a couple of previously posted issues (from several years ago) discussing this issue, but some aspects of this remain unclear to me for the current version of Nuitka.

If I use Nuitka to compile my application with --standalone, is it possible for users to swap out the copies of PySide6 and shiboken6 that would be bundled with the compiled application (as it would appear, given the appearance of PySide6 and shiboken6 folders within the .dist folder created by Nuitka) or am I misunderstanding something?

If this is not the case and it is necessary to use, for example, --no-follow-import-to=pyside6, should the --enable-plugin=pyside6 option then be excluded?

Any advice on this front would be much appreciated.

**Comment by kayhayen** [comment]
Standalone doesn't enforce the files, only `--onefile` currently has no ability to update the contained files, but turning it into an archive format is something that is being worked on, but not at highest priority, but it is expected to come into exististance later this year.

**Comment by kayhayen** [comment]
I am not a lawyer, nor your advisor, certainly not for free. All files in a standalone compilation are replaceable, please do with that information as you'd like. Nothing in Nuitka standalone itself requires a license violation.

If you do not provide your source code however, replacing the LGPL parts with their Python code will be impossible right now. For PySide6, I would recommend purchasing their commercial license in that case, since it alleviates you off the LGPL.

I do not support manual copying of PySide6 into standalone dist folders. I do not intend to keep or make that work at all, but you may have some luck in figuring out how it works with a given Nuitka version maybe still, but don't expect any support from me for that. With time, more and more features might make it easier, but it's a long and slow road I feel.

**Comment by kayhayen** [comment]
Python code ends up in the main binary in all modes at this point, but you compile them separately as modules and then use that as input for the compilation, so I guess it's feasible to do it that way, it's just a matter of how you use Nuitka.
