### ISSUE TITLE
Mac OS Homebrew x86_64 python-tk lib error

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2709]
I have Mac OS 13 on x86_64, python@3.10 and python-tk@3.10 installed via brew, nuitka installed via pip3.10 .

  > python -m nuitka --version

```zsh: command not found: python```

>  python3.10 -m nuitka --version

```
2.0.2
Commercial: None
Python: 3.10.13 (main, Aug 24 2023, 12:59:26) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Homebrew Python
Executable: /usr/local/Cellar/python@3.10/3.10.13_2/bin/python3.10
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

  > python3.10 -m pip freeze

```
coloredlogs==15.0.1
configparser==6.0.0
contourpy==1.2.0
cycler==0.12.1
flatbuffers==23.5.26
fonttools==4.48.1
humanfriendly==10.0
kiwisolver==1.4.5
matplotlib==3.8.2
mpmath==1.3.0
Nuitka==2.0.2
numpy==1.26.4
onnx==1.15.0
onnxruntime==1.17.0
opencv-python==4.9.0.80
ordered-set==4.1.0
packaging==23.2
pillow==10.2.0
protobuf==4.25.2
pyparsing==3.1.1
python-dateutil==2.8.2
six==1.16.0
sympy==1.12
zstandard==0.22.0
```

> cat 1.py

`from tkinter import *`

This example itself is "running" without error. But Nuitka doesn't build it:

>  /usr/local/bin/nuitka3 --standalone ./1.py

or

> python3.10 -m nuitka --standalone ./1.py 

Gives output:

```
Nuitka-Options: Used command line options: --standalone ./1.py
Nuitka-Options: Detected static libpython to exist, consider
Nuitka-Options: '--static-libpython=yes' for better performance, but errors may
Nuitka-Options: happen.
Nuitka: Starting Python compilation with Nuitka '2.0.2' on Python '3.10'
Nuitka: commercial grade 'not installed'.
Nuitka-Plugins:WARNING: Use '--enable-plugin=tk-inter' for: Tkinter needs TCL
Nuitka-Plugins:WARNING: included.
Nuitka: Completed Python level compilation and optimization.                    
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 3
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 3
FATAL: Error, failed to find path @loader_path/../../../../opt/tcl-tk/lib/libtcl8.6.dylib (resolved DLL to /usr/opt/tcl-tk/lib/libtcl8.6.dylib) for /usr/local/opt/python-tk@3.10/libexec/_tkinter.cpython-310-darwin.so from 'None', please report the bug.
```

May be the problem related to the fact, that python-tk 3.10 installed via brew, not via pip3.10.

**Comment by kayhayen** [comment]
I don't think Tk is pip installable. Homebrew is not as well supported as CPython, although we claim kind of support for it. The value `@loader_path/../../../../opt/tcl-tk/lib/libtcl8.6.dylib` appears kind of an extreme value. It appears as if it was running one level too high there, assuming `/usr/local/opt` is where it should go, and not `/usr/opt`.

**Comment by kayhayen** [comment]
The bad thing is that I won't have a x86_64 Homebrew setup myself, as I only got access to an M1 machine. I will try and see if I got a similar error there. Homebrew and Tk might be underused.

**Comment by kayhayen** [comment]
So this happens when I try to run my tk-inter standalone test:

> FATAL: tk-inter: Could not find Tcl, you might need to use '--tcl-library-dir' and if that works, report a bug so it can be added to Nuitka.

I believe we are not finding this by default. And you are not following this:

> Nuitka-Plugins:WARNING: Use '--enable-plugin=tk-inter' for: Tkinter needs TCL
> Nuitka-Plugins:WARNING: included.

I am not sure if that doesn't render your report as invalid, but I am also not convinced the plugin avoids no finding those libs, but it might or ought to.

**Comment by kayhayen** [comment]
So, I added the detection of Tcl/Tk for Homebrew, getting at the prefix path for Homebrew reliably might be a bit difficult, for now just going up enough levels from the Python prefix is supposed to work.

Thanks for your report, this is enhanced on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. I need you to state if enabling the plugin helps it to resolve those DLLs. If not, I will need the `otool -L /usr/local/opt/python-tk@3.10/libexec/_tkinter.cpython-310-darwin.so` and also `otool -l /usr/local/opt/python-tk@3.10/libexec/_tkinter.cpython-310-darwin.so`.

My suspect is that we need to have for Homebrew a lib directory added to the scan. The ".." might be taking a wrong turn, because of symlink resolution, if we ever do realpath, easily that might be breaking it.

**Comment by kayhayen** [comment]
This is part of the 2.0.3 release I just made.

**Comment by ioctl-user** [comment]
I have to upgrade my environment.

For now I'm running Python 3.11 instead of 3.10 and Nuitka 2.0.3 instead of 2.0.2.
In these new versions bug disappeared.

So, we can assume it's fixed.
