### ISSUE TITLE
Nuitka doesn't warn about absent modules in standalone mode.

### ISSUE THREAD

**Issue by ioctl-user** [Nuitka/Nuitka#2727]
MacOS x86_64, universal python package installed from the official web site.

  > python3 -m nuitka --version

```

2.0.4
Commercial: None
Python: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /usr/local/bin/python3
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang 15.0.0).

```

Here is an example of code, which imports absent module:

> cat 1.py
```
import nosuchimport as nsi

nsi.print()

```

Nuitka builds it without error or warning in standalone mode:

>  python3 -m nuitka --standalone 1.py
```
Nuitka-Options: Used command line options: --standalone 1.py
Nuitka: Starting Python compilation with Nuitka '2.0.4' on Python '3.11'
Nuitka: commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.                    
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka-Scons: Backend linking program with 6 files (no progress information
Nuitka-Scons: available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 4
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 2
Nuitka: Keeping build directory '1.build'.                                    
Nuitka: Created binary that runs on macOS 10.9 (x86_64) or higher.
Nuitka: Successfully created '1.dist/1.bin'.

```

Sure, compiled binary doesn't work:

>  ./1.dist/1.bin
```
Traceback (most recent call last):
  File "/Users/build/example/1.dist/1.py", line 1, in <module>
ModuleNotFoundError: No module named 'nosuchimport'
```

Could Nuitka show error in case of module import problem in standalone mode?

**Comment by kayhayen** [comment]
Yes, it does in compilation reports, check out --report result.

**Comment by ioctl-user** [comment]
Nuitka doesn't show any warning and returns error code 0 -- no error.

It's not clear, that the report should be generated and examined.

**Comment by Maxwell175** [comment]
Well, the problem is that things like this are common in python:

```py
try:
    import modulea
except ImportError:
    import fallback as modulea
```

Would you really want Nuitka to complain every time that modulea fails to import, even though that might totally be expected? You might say that well, Nuitka should warn if it was uncaught. The problem with that is that it might also be part of a greater fallback strategy that is caught by an except block in a file that is importing this file.

**Comment by kayhayen** [comment]
Modules not found, is something for pylint to do. Also you are expected to compile with Nuitka in an environment where you tested your program already. Skipping that step by you, is a choice you can make, but Nuitka cannot hold your hand there.

Nuitka reports everything it found or didn't find precisely in the report. You can monitor it even for changes if you want to. It's very powerful to notice sudden module removals or additions, from PyPI package updates.

I remember a time, where Nuitka did have these warnings. The result was that nobody read any warning at all anymore, since as Maxwell correctly says, this is very common, I think it happens even in standard library, but I might be making that up now.

**Comment by kayhayen** [comment]
From Nuitka changelog, 0.5.2

```
  More complete whitelisting of missing imports in standard library.
  These should give no warnings anymore.
```

**Comment by kayhayen** [comment]
They are indeed going to be different, plenty of packages only support sometimes optional optimization for only one arch, or won't work on the target arch. Without you testing if the original program works, nothing in Nuitka can make it work magically, as it cannot change the software you are using, it only compiles what is there, and strips e.g. x86_64 code out of, but it won't invent missing code from there.

Complain to Apple about the lack. Or just have your arm64 users use the x86_64 binaries. But from Nuitka, you can get nothing here, except the technical ability to package working (on that target arch) programs. It's not a real cross compilation at all, Nuitka doesn't support those.
