### ISSUE TITLE
Libraries issues

### ISSUE THREAD

**Issue by newtothisthing212** [Nuitka/Nuitka#2738]
Hi!
Are these Python 3 libraries compatible with Nuitka?
OS
Shutil
Subprocess
Sys

**Comment by KevinRodriguez777** [comment]
> You can use all Python library modules and all extension modules freely.

https://nuitka.net/doc/user-manual.html

**Comment by kayhayen** [comment]
Nuitka goes far beyond standard library, it's supposed to work with almost anything from PyPI, definitely working with AI stuff, PySide6, many GUI frameworks, database stuff, etc. since it's extremely compatible. It just currently doesn't allow code to access source code of compiled code, but we might add that in the future.
