### ISSUE TITLE
Cannot use UNC paths on Windows VMs 

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#2767]
Consider we run hyper-v virtual machine with Windows10 with shared folder from host machinge.

We share host folder, say `c:\distro` to shared folder `c:\distro` inside guest windows.

Sharing folders inside VM works using internal SMB-protocot to share.
That is `c:\distro` is link/reparse point to some UNC path:

`c:\distro` → `
UNC\172.25.112.1\vgt-f3b9b581c1ff10f09ed1e8cb26cb9407-20a8cb417636f2ec99c61d61999295b2`

![image](https://github.com/Nuitka/Nuitka/assets/1609739/c924e841-40a9-4d3e-a649-e0ad7f014bf2)

So, for these path, inside Nuitka (I checked last version, this function not changed yet) there is function

```python
def _getRealPathWindows(path):
...
    _real_path_windows_cache[path] = os.path.join(
        os.path.dirname(path), result.rstrip("\r\n")
    )
...
```

that makes path incorrect and unusable (`c:\UNC\some_UNC_path`, ):

![image](https://github.com/Nuitka/Nuitka/assets/1609739/c602d67a-35a1-482f-a60a-062aa1ab38ec)

Looks like be better dont touch UNC paths?

I made small couple of line path ("works for me", and I can provide PR), but may be I missing some important case?

**Comment by kayhayen** [comment]
Screenshots and no version information, I am sure you can do better, and I have indeed changed something there recently for #2732 and this code for resolving symlinks is needed, because many tools don't work with non-real paths. I think the issue solution there was to indeed avoid resolve something different.

**Comment by kayhayen** [comment]
I fixed `getFilenameRealPath` to undo the damage in case drive letters get lost, but it may not be general enough to cover these mounts in the middle of things. You are more than welcome to make it walk the path up if it should be necessary.

**Comment by belonesox** [comment]
Sorry, I liked to make bug reports completely reproduceable,
but VMs in Windows world are strange, there is no reliable way to make it reproduceable:

- [Windows sanboxes are strangely broken for now](https://github.com/belonesox/demo4bug-strange-file-corruption-on-windows-sandbox-and-shared-folders-with-link)
- [Working VirtualBox are incompatible with working Hyper-V](https://github.com/MicrosoftDocs/WSL/issues/798)
- ...

So, I would like to know, what virtualization have you on your windows stand, to make reproduceable examples.with vagrant for example.

I catch the issue sometimes ago, make quick fix "works for me", and several weeks tests on my different projects. So, I miss the https://github.com/Nuitka/Nuitka/issues/2732 and unfortunately, there are no linked commits that closed this issue to check.

I tried to check latest pre-release commit ea9093d970a1275f8c5ed7598752a6cbcb9aa403

and the issue still persists 

[nuitka-crash-report.zip](https://github.com/Nuitka/Nuitka/files/14615684/nuitka-crash-report.zip)

**Comment by kayhayen** [comment]
The commit history of the `nuitka.utils.FileOperations.py` has it. Due to rebasing for perfect git bisection, I don't use commit hashes as much as others do.

That change handles top level, but can surely be extended.

Like I said, many tools cannot work with symlinks, and need short paths in 8.3 style to work reliably. This includes tools from big companies. The realpath does more than it's supposed to do there, but it cannot do only one thing. Reverting it to drive letter paths, was easy for me. I imagine you can make it more general.

**Comment by kayhayen** [comment]
So I merged your PR, and will put it on my factory branch, I don't think I really want to make this part of a relatively late hotfix, since it risks breaking existing setups. I tried Python 2.7 and 3.10 where Python is a symlink and it continued to work, that is something I care about. Moving it out to a separate function is bound to make the code maybe more readable.

**Comment by kayhayen** [comment]
Thanks for your PRs, these are all super useful, keep em coming :)

**Comment by kayhayen** [comment]
Part of the current pre-release.

**Comment by kayhayen** [comment]
Part of the 2.2 release I just made.
