### ISSUE TITLE
Virus total 29/72 antiviruses say my program compiled with Nuitka has virus

### ISSUE THREAD

**Issue by RobertAzovski** [Nuitka/Nuitka#2805]
![image](https://github.com/Nuitka/Nuitka/assets/111636889/1adaf7fc-10e1-4ea7-8f97-e07ca8441823)

It happened before, like 3-5 avs usually concerned but this time there is a lot.

`Network Communication
IP Traffic
192.229.211.108:80 (TCP)
20.99.184.37:443 (TCP)`

What are these IPs ?

**Comment by RobertAzovski** [comment]
There was a dll of tls-client included in final exe, may be this is a reason ?

**Comment by kayhayen** [comment]
Nuitka is the preferred choice of malware authors due to its protection of the source code, and the inability to investigate behavior of the program without deep analysis. This leads to Nuitka compiled binaries being reported as malware based on being similar to it, even for small programs, esp. for programs that use Crypto libraries and that deal with Crypto payments in particular.

There are ways around this, but further action will be needed, they are described here: https://nuitka.net/doc/user-manual.html#windows-virus-scanners

Naive compilation however is exactly what malware authors do, so it's not going to be sufficient to get your binaries not flagged.

**Comment by RobertAzovski** [comment]
https://www.virustotal.com/gui/file/cb47a9d5173ff27cecdedbb4f35f9537387fe4e032049dc4673125daf494bfe0/detection

Please, can you check this. Should I be concerned if popular AVs do not detect but some others do ?

https://github.com/FlorianREGAZ/Python-Tls-Client this is the obly lib I used for my program

**Comment by KevinRodriguez777** [comment]
false positives are common across different AVs, the IP you provided is an microsoft datacenter IP, check if your program is making any request to that sort of IP, regardless nuitka does not, the source code is public and you can verify it yourself

**Comment by kayhayen** [comment]
I have seen this happen in the past with Azure IPs, some of the Microsoft AV stuff calls home to check unsigned executables or verify existing signatures, pretty sure of that. However Virus Total sometimes hates on those IPs.

**Comment by HydraDragonAntivirus** [comment]
Nuitika is very obfuscated, and antiviruses can't create true detection about that so they generally flag too obfuscated python programs as malicious.
