### ISSUE TITLE
ImportError: failed to find libmagic.

### ISSUE THREAD

**Issue by MagicalDrizzle** [Nuitka/Nuitka#2829]
> python -m nuitka --version
```
2.1.6
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Python: Official installer
Nuitka: pip

  > python -m pip freeze
```
Nuitka==2.1.6
python-magic-bin==0.4.14
```
minimal reproducible:
`nuitka --standalone test.py`
```py
# test.py
import magic
```
Output:
```
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\test.py", line 1, in <module>
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\magic\__init__.py", line 1, in <module magic>
  File "C:\Users\WDAGUtilityAccount\Desktop\test.dist\magic\magic.py", line 189, in <module magic.magic>
ImportError: failed to find libmagic.  Check your installation
```

Manually copying the `magic` module folder in `site-packages` to the `test.dist` folder solves the issue. It seems nuitka is having trouble adding the package to the output folder.

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)
