### ISSUE TITLE
pyocd does not work in its entirety

### ISSUE THREAD

**Issue by Dozingfiretruck** [Nuitka/Nuitka#2850]
python ：3.11
nuitka  ： 2.1
pyocd ： 0.36.0

python -m nuitka --version
```
2.1
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3)
```

How did you install Nuitka and Python
`pip install`

pyocd can work but not entirety,and run without errors(such as can not probe device and so on)

This is also the case in pyinstaller but  It can be solved in the following ways:
![image](https://github.com/Nuitka/Nuitka/assets/24759100/4bd15194-e3f5-4e7e-a2ea-c5909e4b2490)
Add pyocd/probe 、pyocd/rtos 、pyocd/tools and pyocd-0.36.0.dist-info/entry_points.txt manually
Pls how does it work under nuitka？

**Comment by KRRT7** [comment]
can you share a minimal reproducible example?

**Comment by Dozingfiretruck** [comment]
> can you share a minimal reproducible example?



> can you share a minimal reproducible example?

This requires hardware, which you may not have there, and requires a daplink debugger and a microcontroller to see the results

**Comment by kayhayen** [comment]
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by kayhayen** [comment]
Basically it seems you need to include the meta data, for that there is yaml configuration to say so, that would replace the entry points file. And you would have to add data-dirs for it to work. All of that is relatively easy. If you can contribute that, it would be great.

**Comment by kayhayen** [comment]
Going to merge that for the next hotfix of Nuitka.

**Comment by Dozingfiretruck** [comment]
> Going to merge that for the next hotfix of Nuitka.

Thanks for the help, this project is fantastic！！！
