### ISSUE TITLE
Generate c-sources multithreaded

### ISSUE THREAD

**Issue by n-bes** [Nuitka/Nuitka#2974]
Hi, I noticed that the **"Generating source code for C backend compiler"** step only consumes one CPU (single thread). Is it possible to do this stage using all cores?

**Comment by KRRT7** [comment]
i had looked into making this multi threaded in the past, but it caused issue, i don't remember with what, however, this wouldnt make Nuitka use more cores at the present (due to the GIL) unless we were using python 3.13 free threaded  build or multi processing, the C source generation is quite fast at the moment, maybe optimizations can be made in the future though

**Comment by kayhayen** [comment]
I don't think this issue contributes anything right now, so I am closing it. It's a valid suggestion, but we will need full caching to work, which will mean modules are entirely independent, which they currently are not.
