### ISSUE TITLE
console pop up when my exe executes another exe (already disabled windows console mode)

### ISSUE THREAD

**Issue by magicaly2** [Nuitka/Nuitka#3073]
i wrote a program and compiled it into .exe using nuitka with --windows-console-mode=disable.

whenever my program execute bcpandas.to_sql, a console (bcp.exe from ODBC Driver for SQL Server) keep popping up
how do i hide/not show that?

note: the console popping up i mentioned IS NOT my program's console, its another console from bcp.exe
note: when i run my code in visual studio code, i dont see this bcp.exe console

**Comment by Dnyarri** [comment]
As long as I understand, you are talking about subprocess in your program.

Now, does that bcp.exe have something like quiet mode so you can add a switch to your subprocess.run or subprocess.Popen or whatever?

If not, do tricks like 
https://stackoverflow.com/questions/1016384/cross-platform-subprocess-with-hidden-window
help?

<i>when i run my code in visual studio code, i dont see this bcp.exe console</i>

Nodoby sees console in VSCode since it's redirected to VSCode own terminal window ;-)

**Comment by kayhayen** [comment]
Please reproduce your issue using `pythonw.exe` and you will see this is standard Python behavior. Nuitka is not deploying your Visual Code environment, which is a terminal environment, you need to disable your console in Python and then it will become obvious to you what happens if you run a console program, it opens a window for it...
