### ISSUE TITLE
segfault on mac arm

### ISSUE THREAD

**Issue by fensoft** [Nuitka/Nuitka#3099]
My environment:
```
2.4.8
Commercial: None
Python: 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)]
Flavor: Homebrew Python
Executable: ~/virtualenv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 14.6.1
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

nuikta installed on venv/pip with this requirements.txt:
```
PySide6==6.7.2
nuitka==2.4.8
```

Minimal example code:
```
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QApplication, QMainWindow

# nuitka-project: --standalone
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --macos-create-app-bundle
# nuitka-project: --debug

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
    

app = QApplication()
app.exec()
```

**Comment by kayhayen** [comment]
This is not enough information to reproduce because there is no `pip list -v` output.

**Comment by kayhayen** [comment]
With CPython and not Homebrew, and current 2.5 release, I am getting this:

```
Assertion failed: (Py_REFCNT((&_Py_NoneStruct)) == _Py_IMMORTAL_REFCNT), function Nuitka_Function_New, file CompiledFunctionType.c, line 1328.
```

That is because older PySide6 is not fully compatible with Python3.12 immortal objects, and accidentically de-immortalizes them, which is semi-OK, Python survives that, but debug mode of Nuitka wants to identify cases where it expects to deal with immortal objects, but then they are not immortal. Can be disabled with `--no-debug-immortal-assumptions` for at least since 2.5 release, maybe sooner, and then it runs fine. There is no segfault, but an abort.

As such this is not a Nuitka issue, surely PySide6 is being improved eventually to no longer do that. I think Python had assertions against that, but removed them for release, but maybe 3.13 does them and that will trigger fixes in extension modules more globally.
