### ISSUE TITLE
How to include dll exe files? --include-raw-dir not work, --include-data-dir change its behavior

### ISSUE THREAD

**Issue by chianjin** [Nuitka/Nuitka#3116]
- Nuitka version
  > python -m nuitka --version
  2.4.8
  Commercial: None
  Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
  Flavor: CPython Official
  Executable: E:\Project\realesrgan-gui\.venv\Scripts\python.exe
  OS: Windows
  Arch: x86_64
  WindowsRelease: 11
  Version C compiler: C:\Program Files (x86)\Microsoft Visual 
  Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).

- How did you install Nuitka and Python
  Download from python.org and `pip install nuitka`

- The specific PyPI names and versions
  > python -m pip list -v
  Nuitka      2.4.8   E:\Project\realesrgan-gui\.venv\Lib\site-packages pip
  ordered-set 4.1.0   E:\Project\realesrgan-gui\.venv\Lib\site-packages pip
  pip         24.2    E:\Project\realesrgan-gui\.venv\Lib\site-packages pip
  zstandard   0.23.0  E:\Project\realesrgan-gui\.venv\Lib\site-packages pip

I have a folder containing command line appication, with some dll, exe files under project folder.
Using previous versions Nuitka, I use `--include-data-dir` option to copy the whole folder to the dist folder.
When I updated Nuitka, it seems Nuitka changed the `--include-data-dir` option's behavior, does not copy
dll, exe files. So I tried to use `--include-raw-dir` option, but it does not work.

Building command as blow:
`nuitka --show-progress --show-memory --standalone --windows-console-mode=disable
 --windows-icon-from-ico=realesrgan.ico --include-raw-dir=realesrgan=realesrgan
 --include-data-dir=locale=locale --include-data-file=realesrgan.png=realesrgan.png
 --plugin-enable=tk-inter --output-dir=build RealESRGAN-GUI.py --verbose`

So, how can I do?

**Comment by kayhayen** [comment]
Closing for lack of feedback. I have no reason to believe raw copying doesn't work as expected.

**Comment by jaimetur** [comment]
I have the same problem. I would like to include a whole dir which contains executable files and dlls but if I use --include-raw-dir, the directory is included but the binaries has not exec permission

**Comment by kayhayen** [comment]
Permissions or ownership, and what not of data files are not preserved. If were included as binaries via user package configuration, they would get the x-bit.

Also posting the "same problem" is useless when it's not.

Posting below closed or unrelated issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
