### ISSUE TITLE
Question : in --standalone mode compile just the src/ library and deliver the external dependecnies like a venv or preferably zipped. 

### ISSUE THREAD

**Issue by saifjarboui** [Nuitka/Nuitka#3198]
Hi,
is there a way to compile only my library through its entry point and then distribute the dependencies ( like creating a venv for them and place them there and activate the venv before execution) something close to what pyinstaller does.
The library has many dependencies ( scipy,plotly, pandas..) compiling them all is an overkill.

**Comment by KRRT7** [comment]
I wonder if we could get a hybrid of Nuitka + venvstacks, which sort of would fix these two problems:
http://venvstacks.lmstudio.ai

**Comment by saifjarboui** [comment]
> I wonder if we could get a hybrid of Nuitka + venvstacks, which sort of would fix these two problems: http://venvstacks.lmstudio.ai
@KRRT7  sounds promising, and yes the idea is close to something like that.

**Comment by kayhayen** [comment]
Yes, it's called multidist and once our setuptools integration supports it, you can use that. For now it works only by producing a package out of yours that then can be installed into a distribution.

Once we learn to include Python modules as source code and have that work as well as it does when it's compiled, we could consider it, but that's a hard issue receiving no help ever since it was first created, and as such it's a duplicate to ask for it. I understand that the demand is there, but without the help, I don't see it on the roadmap. And help is not to make it work, help there would mean to also support it. For me personally compiled standalone of everything is hard enough already.

**Comment by kayhayen** [comment]
I think it's clear what you think should be done. I don't know anybody who will do it though.

**Comment by septfleur** [comment]
I encounter the same issue here. Trying to compile pandas and polars takes forever. The target system already have them installed in venv but it can't be leveraged by nuitka. Sad to know it's not on the roadmap.

**Comment by KRRT7** [comment]
@septfleur https://nuitka.net/user-documentation/use-cases.html#multidist

**Comment by voilasept** [comment]
@KRRT7 Thanks. My question is about not include big libs (polars and pandas) in the compile. The link you gave is about distributing multiple binaries together. I may missed something is there a connection?
