### ISSUE TITLE
nuitka-1.6.6 worked successfully on msys64 but now nuitka-2.5.1 fails

### ISSUE THREAD

**Issue by noeldiviney** [Nuitka/Nuitka#3204]
Hello Kay.
Have installed nuitka-2.5.1 and run my test.
Full details are in the following nuitka-2.5.1.zip
 
[nuitka-2.5.1.zip](https://github.com/user-attachments/files/17796379/nuitka-2.5.1.zip)

Cheers Noel Diviney

**Comment by kayhayen** [comment]
> FATAL: Failed to download 'https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-msvcrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.1-mingw-w64msvcrt-12.0.0-r
2.zip' due to '<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>'. Contents should manually be copied to 'C:/Users/esdev/
AppData/Local/Nuitka/Nuitka/Cache/DOWNLO~1/gcc/x86_64/14.2.0posix-19.1.1-12.0.0-msvcrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-llvm-19.1.1-mingw-w64msvcrt-12.0.0-r2.zip'.
FATAL: Failed unexpectedly in Scons C backend compilation.


I actually also saw this, seems MSYS2 cannot download via HTTPs, this is more an error of MSYS2 there. I personally tried installing certifi and the like, on Windows it's supposed to use system certificates. I executed it on Windows proper, which downloaded it, and the issue went away.
