### ISSUE TITLE
startup time very slow when using docling package

### ISSUE THREAD

**Issue by drewbroadbent** [Nuitka/Nuitka#3260]
When compiling a python script which imports the docling package, it takes a long time to do anything when launching the exe. This is before the docling package is imported in the script. I used a print before the import to check this and it takes a minute or so for it to be outputted.

What can I do to reduce this time substantially?

Can be replicated by:

test.py:
from docling.document_converter import DocumentConverter

Nuitka:
Python -m nuitka --onefile test.py

**Comment by kayhayen** [comment]
Since it uses massive dependencies, these need to be unpacked and used on the target machine, and that just takes time. Speeding up onefile can be achieved by using cached mode, and there is more on the roadmap to make it even faster, but that's about it.

**Comment by drewbroadbent** [comment]
> Since it uses massive dependencies, these need to be unpacked and used on the target machine, and that just takes time. Speeding up onefile can be achieved by using cached mode, and there is more on the roadmap to make it even faster, but that's about it.

Thank you for the fast response.

What is "cached mode"?

**Comment by kayhayen** [comment]
This is not the interactive user manual though, please read the docs of Nuitka for onefile.

**Comment by javajawa** [comment]
Hello @kayhayen! I'm experiencing a similarly shaped issue (though I'm also seeing long startup times in `standalone`). Starting a new GH issue felt redundant, but am struggling to find the documentation you are referring to.

The few places `cached mode` appears in relation to onefile across the GH organisation are:

- A reference in the [release 8 docs](https://github.com/Nuitka/Nuitka-website/blob/4d65a204d8084ab664173c59e9c1d7500f026f16/site/posts/nuitka-release-08.rst?plain=1#L417) that it is planned;
- https://github.com/Nuitka/Nuitka/commit/42f6e9c32412bd26e62c29699df5c824c8a639e3 which adds a potentially relevant option with a help string but no associated documentation update;
- [Release 10](https://github.com/Nuitka/Nuitka-website/blob/4d65a204d8084ab664173c59e9c1d7500f026f16/site/posts/nuitka-release-10.rst?plain=1#L191) suggesting caching around the the tempfile, which I feel is not relevant to a first time launch (if I'm understanding the flow correctly);
- A [one liner](https://github.com/Nuitka/Nuitka-website/blob/4d65a204d8084ab664173c59e9c1d7500f026f16/site/user-documentation/nuitka-package-config.rst?plain=1#L692) about a configuration option called `onefile_cached` which again feels unrelated to first time start ups.

Which of these should I be looking at?

**Comment by kayhayen** [comment]
I really appreciate the time spent by you on this @javajawa, so here is my time for you:

The cached mode is implemented. Check the `--onefile-tempdir-spec` help. It's not really a tempdir obviously in cached mode, needs a usability cleanup one day for better naming.

Onefile has an SFX part on top of standalone, otherwise it will be the same. So if standalone si slow to start, onefile will only be slower. Large file sizes will harm its startup mostly, slow disks of course too.

In cached mode, except for first startup, this SFX should be faster, since files do not get written, but only read for verification. The archive mode indeed is an approach to making it faster there too, since it's more skippable, with compression per file.

But I since have recognized, that I should prefer to have a sort of index of all files contained in the onefile archive, that allows for verifying checksums, and with the assumption that they always hit, it will be not necessary to do any skipping of compressed file data at all, and it will typically hit all or no files unless files included got modified. 

Some packages key on the running binary path. When it's not unique, that key changes on every run with onefile temp mode. We added a setting to Nuitka package configuration for a package that feels like running binary path is sufficient for locking, or whatever it was when it is of course not, and the original path ought to be used.

Generally this effort is stalled. I am working on Winter of Scalability, my effort to reduce compile time scalability issues for some larger modules. I will get back to onefile, but not in the next 2 months. Once all the roadmap items are implemented (you didn't find https://nuitka.net/changelog/roadmap.html#onefile-speed-standard), it will be much better. I realized, that this recognition of how to change the format to be 2 pass is not yet realized in the roadmap itself.
