### ISSUE TITLE
Standalone: passlib fails to import correctly

### ISSUE THREAD

**Issue by mitchbte** [Nuitka/Nuitka#332]
Hi, I'm trying to build a standalone application which uses passlib. The compilation works but I think something is being optimized out or the inclusion of only part of the library is causing issues.

Packages
```
pip install passlib
```
Version
```
nuitka --version
0.6.2
Python: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
Executable: E:\projects\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```
Sample code
```
from passlib.hash import sha512_crypt as sha512

print('hello')
print(sha512.using(rounds=5000).hash('password'))
print('bye')
```

Great tool by the way. Thanks for the effort!!
Cheers. Mitch

**Comment by kayhayen** [comment]
For Python3 this crashes for me at least on Windows, due to Nuitka false assuming that attempts to import an embedded value will always give something that has a `__spec__` value. That is definitely hotfix material. I think it should have struck on Windows too, maybe it's a 0.6.3 regression (released yesterday), and that would explain it.

Otherwise, there is a hidden dependency indeed. I am adding it too. But I guess, it depends on which hashes you use. With --include-module things worked, but I added `passlib.handlers.sha2_crypt` as a hidden dependency and now it's good.

I put it on the factory branch: http://nuitka.net/doc/factory.html

Yours,
Kay

**Comment by mitchbte** [comment]
Solved! Thanks for that.
