### ISSUE TITLE
openSUSE Python2 qt5 test fails in enum

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#357]
```
[ 1649s] Consider output of recursively compiled program: PyQt5Plugins.py
[ 1649s] Comparing output of 'PyQt5Plugins.py' using '/usr/bin/python' with flags silent, expect_success, standalone, remove_output, ignore_infos, plugin_enable:qt-plugins ...
[ 1688s] --- /usr/bin/python (stdout)
[ 1688s] +++ nuitka (stdout)
[ 1688s] 
[ 1688s] @@ -1,2 +1 @@
[ 1688s] 
[ 1688s] -[PyQt5.QtCore.QByteArray('bmp'), PyQt5.QtCore.QByteArray('cur'), PyQt5.QtCore.QByteArray('gif'), PyQt5.QtCore.QByteArray('ico'), PyQt5.QtCore.QByteArray('jpeg'), PyQt5.QtCore.QByteArray('jpg'), PyQt5.QtCore.QByteArray('pbm'), PyQt5.QtCore.QByteArray('pgm'), PyQt5.QtCore.QByteArray('png'), PyQt5.QtCore.QByteArray('ppm'), PyQt5.QtCore.QByteArray('svg'), PyQt5.QtCore.QByteArray('svgz'), PyQt5.QtCore.QByteArray('xbm'), PyQt5.QtCore.QByteArray('xpm')]
[ 1688s]  
[ 1688s] --- /usr/bin/python (stderr)
[ 1688s] +++ nuitka (stderr)
[ 1688s] 
[ 1688s] @@ -1 +1,5 @@
[ 1688s] 
[ 1688s] +Traceback (most recent call last):
[ 1688s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3/tests/standalone/PyQt5Plugins.dist/PyQt5Plugins.py", line 20, in <module>
[ 1688s] +  File "/home/abuild/rpmbuild/BUILD/Nuitka-0.6.3/tests/standalone/PyQt5Plugins.dist/enum/__init__.py", line 347, in __call__
[ 1688s] +TypeError: unbound method __new__() must be called with QCborKnownTags instance as first argument (got EnumMeta instance instead)
[ 1688s]  
[ 1688s] Exit codes 0 (CPython) != 1 (Nuitka)
[ 1688s] Error, outputs differed.
```
https://build.opensuse.org/package/show/home:jayvdb:py-bridge/python-Nuitka?rev=6

**Comment by jayvdb** [comment]
My very uneducated guess is that this is caused by the python2-qt5 package using the python2-enum34 package, effectively de-vendoring it, which I suspect the Nuitka internals or Nuitka tests are not expecting.

https://build.opensuse.org/package/view_file/openSUSE:Factory/python-qt5/python-qt5.spec?expand=1

**Comment by kayhayen** [comment]
There once was a `enum` plugin in Nuitka, that was solving the issue for Python3 enum package, but then it turned out that the decorator call for `__new__` was not really necessary for Python3 anymore, as it doesn't have real staticmethod as a separate function type anymore.

The enum package manually calls a `__new__`  from a namespace of another package and expects it to be not decorated with `staticmethod` which it is only by Python for the created class. From Nuitka source:

```
    # CPython made these optional, but secretly applies them when it does
    # "class __new__".  We add them earlier, so our optimization will see it.
    if (
        python_version < 300
        and node.name == "__new__"
        and provider.isExpressionClassBody()
    ):
        _injectDecorator(
            decorators, "staticmethod", ("staticmethod", "classmethod"), source_ref
        )

```

The version requirement was not always there. Probably it lead me to removing it in this commit 1480af96417cfc058d0a342f6ebb6b879f2da0b3 and that was premature due to the backport.

Can you confirm this test is going to work on that enum source in question:

` "temp_enum_dict['__new__'] = __new__" in source_code`

The plugin simply wraps the compiled functions in a `staticmethod` and then things work.

And just a general comment, if it works with CPython and not Nuitka, that's a bug of Nuitka. :)

Yours,
Kay

**Comment by jayvdb** [comment]
> Can you confirm this test is going to work on that enum source in question:
> `"temp_enum_dict['__new__'] = __new__" in source_code`

Im not sure what you need me to do here.

**Comment by jayvdb** [comment]
This is now resolved in factory.
