### ISSUE TITLE
AsyncQT decorator TypeError

### ISSUE THREAD

**Issue by Bomberus** [Nuitka/Nuitka#368]
I used the asynqt example with PyQT5: [See here](https://raw.githubusercontent.com/gmarull/asyncqt/master/examples/aiohttp_fetch.py).

This script should show you a QT Window, with a fetch button. Pressing the button will show you some fetched resources.

With cmd: `python -m nuitka --follow-imports --recurse-all --plugin-enable=qt-plugins nuitka-bug.py` 

and starting nuitka-bug.exe I get the error, when pressing the fetch button on the gui.

```Traceback (most recent call last):
  File "C:\Users\_\AppData\Local\Continuum\miniconda3\envs\magicbottle\lib\site-packages\asyncqt\__init__.py", line 614, in wrapper
    asyncio.ensure_future(fn(*args, **kwargs))
TypeError: on_btnFetch_clicked() takes 1 positional argument but 2 were given
```

Adding generic arguments to [on_btnFetch_clicked](https://github.com/gmarull/asyncqt/blob/master/examples/aiohttp_fetch.py#L49) fixes the example (see *args).

```python
@asyncSlot()
async def on_btnFetch_clicked(self, *args):
  self.btnFetch.setEnabled(False)
  self.lblStatus.setText('Fetching...')

  try:
    async with self.session.get(self.editUrl.text()) as r:
      self.editResponse.setText(await r.text())
  except Exception as exc:
    self.lblStatus.setText('Error: {}'.format(exc))
  else:
    self.lblStatus.setText('Finished!')
  finally:
    self.btnFetch.setEnabled(True)
```

It seems to me like there are issues with the decorator?

---
Version Information
---
Compiler: VC 2019 Build tools
Nuitka: 0.6.3
Python: 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
Executable: C:\Users\D062318\AppData\Local\Continuum\miniconda3\envs\magicbottle\python.exe
OS: Windows
Arch: x86_64

Installed via : pip

Package           Version
aiodns            2.0.0
aiohttp           3.5.4
altgraph          0.16.1
async-timeout     3.0.1
asyncqt           0.7.0
Nuitka            0.6.3
pefile            2018.8.8
pip               19.0.3
PyQt5             5.12.1
PyQt5-sip         4.19.15
pywin32           224
pywin32-ctypes    0.2.0

**Comment by kayhayen** [comment]
I thought slots work with PyQt5, I would believe they don't with PySide2, this might need a PyQt upstream fix. 

Not sure if asyncio or PyQt5 is to blame, but I reproduced it. Lets see, if I can reduce the test case somewhat. My guess would be asyncio though, but I need to check.

**Comment by kayhayen** [comment]
Total mystery to me, I added traces to the decorator, and it seems the actual call is being done with something that looks good for a self and a boolean value False, which is causing the issue of too many args

I am totally at loss, why this could be. I looked at PyQt, and they don't do it there at least.

**Comment by kayhayen** [comment]
I replaced it with a mere function, no asyncSlot, and then it indeed receives only one argument, namely `False` when I click the button.

I am assuming now, there is something in asyncqt that makes it check for decoration in an incompatible way. The compile method, when annotated as a slot, simply gets something the decorated method is not getting.

Yours,
Kay

**Comment by Bomberus** [comment]
Hi Kay,
thank you very much for looking into the issue, love your project and the hard work you put into.

I tried to replicate the issue without QT, but was not able to.
I think the boolean value is passed in the clicked signal of the QPushButton: https://doc.qt.io/qt-5/qabstractbutton.html#clicked

See demo example: https://gist.github.com/Bomberus/368e181b6e5afae7eb315bf945f7ba3b

So I think this issue is actually with asyncQT and it seems in combination with Nuitka this library is behaving correctly ...

Best regards
Pascal

**Comment by kayhayen** [comment]
I am getting more and more convinced, that this issue is really a PyQt5 issue.

So what I see happening if I include "asyncqt" as bytecode, is that it works, and gets only one argument. When it's a compiled function, it gets two though.

I removed the `functools.wraps` as it seems not needed, and makes things more clear. Before even `fn` is considered, i.e. the `async` function, there is an extra argument, which is semi-correct I believe, because `clicked` in fact has one argument, a boolean, that indicates something apparently.

Now for some reason, the star argument and keyword argument receiving function is called with no arguments, because `@pyqtslot` is called with no arguments. That means, the code that I looked at, fails to attach the signature, but I had output it, and it was there, so no clue what that is about, and the PyQt5 code looks innocent of any discrimination really, doesn`t check the callable at all.

**Comment by kayhayen** [comment]
I looked at sip, and there is a chance that it does discriminate, but it didn't look to bad.

One thing I noticed in PyQt was a comment like this:

 ```
    // We make repeated attempts to call a slot.  If we work out that it failed
    // because of an immediate type error we try again with one less argument.
    // We keep going until we run out of arguments to drop.  This emulates the
    // Qt ability of the slot to accept fewer arguments than a signal provides.
```

That is really suspicous. However, due to the function being called having star args all the way, there is no immediate `TypeError` possible, i.e. one from attempting the call, but it would be on the inside and have a stack trace. My trace also confirms that.

**Comment by kayhayen** [comment]
So, your workaround should indeed be, to use the full signature.

I think I found a very strong candidate for a bug fix in PyQt5:

There is the file `qpy/QtCore/qpycore_pyqtboundsignal.cpp` and in there, we have the function, get_receiver, which has only 3 options

a) A `sipGetMethod` passing object, which our function is not, for even two reasons. I forgot, but I think it accepts only real methods and real Python functions.
b) Be a `sipGetCFunction` which are the CPython C implemented functions.
c) Anything else, also compiled functions.

Only in case a) the signature is considered. I can probably come up with an upstream patch there, that will make it recognize the `__pyqtsignature__` in cases of compiled functions too. This might take me a bit though, since I lack the time now.

Yours,
Kay

**Comment by kayhayen** [comment]
This slot thing may work better on modern Nuitka with @pyqtslot and the pyqt5 plugin, it seems we should treat @asyncSlot the same.

**Comment by kayhayen** [comment]
We having something for @pyqtSlot and I just noticed from this issue that @asyncSlot exists and can be treated the same, expect it to show up in 2.1.1 and soon on factory.

**Comment by kayhayen** [comment]
This is part of the 2.1.1 hotfix release I made
