### ISSUE TITLE
factory openSUSE RsaUsing.py on Python 2

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#370]
When using branch factory Nuitka-0.6.3.1556202417, on openSUSE Python 2.7

```console
[  538s] Consider output of recursively compiled program: RsaUsing.py
[  538s] Comparing output of 'RsaUsing.py' using '/usr/bin/python2' with flags silent, expect_success, standalone, remove_output ...
[  601s] --- /usr/bin/python2 (stderr)
[  601s] +++ nuitka (stderr)
[  601s] 
[  601s] @@ -1 +1,2 @@
[  601s] 
[  601s] +Nuitka:INFO:Missing optimization, used fallback: ('Add', <class 'nuitka.nodes.shapes.BuiltinTypeShapes.ShapeTypeList'>, <class 'nuitka.nodes.shapes.BuiltinTypeShapes.ShapeTypeStr'>)
[  601s]  
[  601s] Error, outputs differed.
[  601s] Error exit! 1
[  601s] error: Bad exit status from /var/tmp/rpm-tmp.fnbPwf (%check)
```

**Comment by kayhayen** [comment]
Great, that is with debug mode I suppose. It seems to be a static raise, going to check where the optimization is missing for this one.

**Comment by kayhayen** [comment]
Just a small warning there, I don't think I ran nearly enough tests with this info on, although I think the CPython test suites, I did, and standalone at least once on Windows. 

This therefore might happen more often, or it may not. I cannot reproduce it here, with my pip installed rsa on Python. It would indicate an upstream problem, or a Nuitka bug if it's a false alarm. After I fix this, feel free to run it with `--warn-implicit-exceptions` (not yet recognized because that pair has not been classified, thus the warning) and report the exact source code. It is definitely smelly for Nuitka detect such obvious errors.

**Comment by kayhayen** [comment]
I added the indication that those "+" will raise TypeError, give it a spin, it's on factory.

**Comment by jayvdb** [comment]
I think this one is fixed, and I am giving `--warn-implicit-exceptions` a spin now.

**Comment by jayvdb** [comment]
Also not seeing it on Python 3.

**Comment by jayvdb** [comment]
Havent seen this for a long time; gamma rays?

**Comment by jayvdb** [comment]
Grrr.  maybe I closed it too soon.

I have hit this once now in develop (but maybe it is fixed in factory only).

```
[ 1158s] Comparing output of 'RsaUsing.py' using '/usr/bin/python2' with flags silent, expect_success, standalone, remove_output ...
[ 1280s] [ 1257.862200] watchdog: BUG: soft lockup - CPU#1 stuck for 26s! [cc1:13918]
[ 1281s] [ 1258.172047] watchdog: BUG: soft lockup - CPU#3 stuck for 31s! [cc1:13905]
[ 1280s] [ 1257.862200] watchdog: BUG: soft lockup - CPU#1 stuck for 26s! [cc1:13918]
[ 1281s] [ 1258.172047] watchdog: BUG: soft lockup - CPU#3 stuck for 31s! [cc1:13905]
[ 1383s] --- /usr/bin/python2 (stderr)
[ 1383s] +++ nuitka (stderr)
[ 1383s] 
[ 1383s] @@ -1 +1,2 @@
[ 1383s] 
[ 1383s] +Nuitka:INFO:Missing optimization, used fallback: ('Add', <class 'nuitka.nodes.shapes.BuiltinTypeShapes.ShapeTypeList'>, <class 'nuitka.nodes.shapes.BuiltinTypeShapes.ShapeTypeStr'>)
[ 1383s]  
[ 1383s] Error, outputs differed.
[ 1383s] Error exit! 1
```
