### ISSUE TITLE
Tests: Add search mode that continues running tests after failure

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#372]
It would be helpful if the test runner had an option to continue after the first error.  This would reduce the amount of test runs needed to determine which bits are working vs failing.

It can be really dumb, and just emit the error information immediately, and store a global failure status so it reports a non-zero exit status at the end.  I would rather kick off a build with all tests enabled and then come back an hour later and read a large log to identify all failures, rather than constantly restart the tests with different test dependencies present.

Ideally it reports the number of failures at the end, and even better would be reporting the error information at the end also.

I can understand avoiding creating too many features in a custom test runner.  Has there been an attempt to wrap the tests in an existing test runner?  Maybe a shell based test runner, like @bats-core?

**Comment by kayhayen** [comment]
@jayvdb it actually has had that option, just don't use `search`, but I might have removed that, but I think the reporting of the sum exit code is not done, I would have to check that. The search modes are easy to implement, just check out `nuitka.testing.Common` and `createSearchMode`, we could make one that runs all the tests and then reports.

For my Buildbots, I typically am happy with them finding no errors, or first one, mostly because they can burn a lot of CPU on trying all the tests, and failing with same error.

I am forever ashamed to not use `py.test`, but literally, Nuitka doesn't do anything like it does. I hope one day somebody turns it into something even better, interface wise. I was too lazy for proper command line parsing back then. Mostly because I was also thinking, surely this will be replaced by something intended for such things later. But I didn't find it yet.

For the test runner, it is required to work on Windows too. I know I am using bash there, but I don't want to require it. So bash is a no go. But feel free to suggest or research more. I am definitely open to replacing this.

**Comment by jayvdb** [comment]
Ya, bats is not a good option for lots of reasons.  py.test, by itself, would also have more negatives than positives.  When the output is predictable , https://github.com/myint/cram is beautiful, and comes from a long linage of testing tools with very similar approach.

Without knowing your testing infrastructure very well, the approach I would looking for is something like using python with Jinja2 to generate yaml usable with a tool like https://github.com/b33j0r/climactic , which can be run standalone or within pytest.

The primary feature I believe you want is to compare the output of Nuitka with the output of another program (python raw).  These custom checkers https://github.com/realead/exetest#custom-checkers look maybe suitable.

It may still make sense to serialise the output of the raw python results into a yaml or cram format, which makes it easier re-produce and re-test the test sequence while debugging.  But it wouldnt be ideal to need to generate all of the raw python results before starting to execute the first tests.

https://github.com/emilkarlen/exactly seems to have a good match of features.

**Comment by kayhayen** [comment]
We are using Jinja2 based tests generation for performance tests, where many constructs are to be put under isolation. That one is not integrated with the standard runner really, as it is married with Valgrind, keeps numbers, stores data, etc. but it could done be more tightly.

For normal tests, we can rely on the CPython test suites most of the way, except they are relatively bad with reference counting leaks, as the last releases, my tests were reporting bugs in CPython that were not yet noticed. I think even 3.7.0 was broken that way.

The sweet feature of the current test approach, is that `print()` is all it takes to cover most of the things with great ease.

 And when e.g. Python 3.8 is added, yeah, I am going to not know the expected results. And the result is different for every Python version, minor versions inclusive. You don't have any idea how much CPython likes to refine and occasionally break grammar with every release. :)

With the `cpython_cache` I am saving my machine CPU cycles, from not having to run the Python version over an over, but it needs to consider all changes, esp. e.g. in `test.support` or data files, to know if a conserved output is still good.

While debugging, I am using `resume` as a search mode. It retries the last thing over and over, until it works.

And consider my "compile the world" test. In that one, I am scanning all library paths, and compile them, just to find errors raised in the C compiler, without and with debug mode maybe. That runs endlessly, does no comparison, because you can't just execute random code. 

And doing that strace/dtruss/depends.exe based standalone test, yeah, that is very specific too. 

So basically I need collection of test cases, search modes, and actions that do very specific stuff, nobody else does. I don't think I need a spec of expected results for a minor version on a specific OS and specific architecture.

The action basically is a call to `nuitka` or `compare_with_cpython` which does it for us. I am not sure there is a lot to gain in that.

Using `py.test` on the other hand, would make it more clear to people what this is. They would understand test collection, wouldn't define functions `test_something()` without ever calling them, the main problem is that this is a undocumented system, that nobody knows from elsewhere. Maybe one day, we will make the test runner more of a `py.test` plugin of some sorts, using its UI and reporting, down to producing `junit.xml` and the stuff.

I think the things proposed add only complexity, but do not add usability, do they. Still need to discover the exe test cases, and define the code or config to test them. Nah, I think py.test may not have to offer anything for actual execution, but the framework would be sweet. People would have docs that tell where to add test options. :)

**Comment by kayhayen** [comment]
@bksahu Do you want to give this a spin, you added a search mode "only" already, adding "all" would be really useful for the 3.8 development that I am going to do. Basically you only need to make sure to ask the search mode for a final exit code value.

**Comment by bksahu** [comment]
@kayhayen Sure. I would love to. :smiley: Please assign me.

**Comment by kayhayen** [comment]
I would say, this issue is dealt with, just don't use search is a good enough reply for now. One day, we need to cleanup that interface of test runners.
