### ISSUE TITLE
Windows standalone WoW error with loading libraries when path is short

### ISSUE THREAD

**Issue by deajan** [Nuitka/Nuitka#382]
Hello,

I think I found a quite nasty bug in Nuitka's standalone executables, that affects only 32 bit executables on a 64 bit system.

I compile my programs (tried 3 different ones) with Python x86, and execute them on my x64 system. So far so good, everything works.
Now if I happen to move the standalone dist folder, sometimes it works, sometimes it doesn't.
I've used procmon to trace down the problem.
It seems that if the path to the executable has more than 16 chars, it works. If I have a path of 16 chars or less, the executable launches and exits without any further action.

Eg:
Does not work and outputs nothing:
```
C:\abcdefghijklmnop>installer.exe
```
Works as it should:
```
C:\abcdefghijklmnopq>installer.exe
```

Using procmon, I realised that the paths to the libraries aren't okay when less than 17 characters are used in the path to the standalone directory:
Non working version:
```
CreateFile | C:\abcdefghijklmnop\d_win32sysloader.pyd | NAME NOT FOUND | Desired Access: Read Attributes,   Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode:   Read, Write, Delete, AllocationSize: n/a
-- | -- | -- | --
```
Working version:
```
CreateFileMapping | C:\abcdefghijklmnopq\_win32sysloader.pyd | FILE LOCKED WITH ONLY READERS | SyncType: SyncTypeCreateSection,   PageProtection: PAGE_EXECUTE_READ
-- | -- | -- | --
```

I've done multiple tries with different executables, sometimes there are 16 bit unicode characters in front of the library to load (had ```C:\testdir\ii\㍮愲楰瀭敲潌摡win32api.pyd``` for instance).
So I guess there is some kind of buffer overflow happening here.

Hopefully this is enough in order to catch the error.

Best regards (and sorry for not being much around in the nuitka community atm).

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

OS is Windows 10 x64 1809
```
0.6.3
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Executable: C:\Python37-32\python.exe
OS: Windows
Arch: x86
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

Plain python -m pip install nuitka

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.
Not a code issue.

*  If this is a regression (used to work in an earlier version of Nuitka),
   please note what you know about that.
I honestly don't know.

**Comment by deajan** [comment]
Updated to Nuitka 0.6.4rc3, problem seems not to happen anymore.

**Comment by kayhayen** [comment]
Hello @deajan you missed 0.6.3.1 hotfix release, which was precisely because of this. I think it was done weeks ago. I am announcing these on the mailing list, but we might need a better way to make them obvious on Github too.

I never managed to see the issue, but there were errors when creating DLL filenames to load.

@@ -87,7 +87,8 @@ static char *copyModulenameAsPath(char *buffer, char const *module_name) {
 static void wcscat_char(wchar_t *target, char c) {
     target += wcslen(target);
     char buffer_c[2] = {c};
-    mbstowcs(target, buffer_c, 1);
+    size_t res = mbstowcs(target, buffer_c, 2);
+    assert(res == 1);
 }

The above code had been wrong, and used for a while I think, when I changed it to internally use unicode rather than ANSI paths on at least Windows. to work, the char buffer needed to terminate by a random character on the stack. Your length analysis may point to reasons why this is the case. For me, it never crashed or failed to load anything. On the other hand, this couldn't really work ever. :)

Luckily this was already found and solved.

Yours,
Kay
