### ISSUE TITLE
Nuitka doesn't work with pywebview

### ISSUE THREAD

**Issue by TokenChingy** [Nuitka/Nuitka#412]
I'm trying to use the Python module [pywebview](https://github.com/r0x0r/pywebview) with Nuitka and I'm not able to to get it to work. I've tried to manually copy over the `WebBrowserInterop.x86.dll` and `WebBrowserInterop.x64.dll` files from `site-packages/webview/lib` and still no success. Am I missing something or is Nuitka not linking/including something correctly?

`Python, Nuitka, and System Information`
```
0.6.3.1
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] 
Executable: C:\Python37\python.exe
OS: Windows
Arch: x86_64
```

`main.py`

```python
import webview

webview.create_window(title="Hello World!", url="https://www.google.com/")
```

`build.sh`
```bash
#!/bin/bash

if [ "$1" == "" ]; then
  echo "Usage: $0 -source"
  exit 1
fi

if [ -d "./dist" ]; then
  rm -rf ./dist
  mkdir ./dist
else
  mkdir ./dist
fi

python -m nuitka --show-progress --standalone --recurse-all --experimental=use_pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse --include-package=webview --output-dir=./dist $1

d="$(sed s/[\.py]//g <<< $1)"

mv ./dist/$d.dist/* ./dist

rm -rf ./dist/$d.build
rm -rf ./dist/$d.dist
```

`./main.exe`
```sh
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\jason\Projects\scratchpad\webview\dist\Python.Runtime.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at clrModule.PyInit_clr()
```

Any help on this would be great! – Jason.

**Comment by psytron** [comment]
Did you make any progress on this? 
Have you tried CEF / [cefpython](https://github.com/cztomczak/cefpython) ?

**Comment by TokenChingy** [comment]
I have not, I haven't had the need for it at work anymore. I have tried using cefpython, it also did not work.

**Comment by psytron** [comment]
Why no more need? Did you find alternate solution for web GUI in Python app?

**Comment by TokenChingy** [comment]
Too much of a hassle, we ended up just using a node backend via Electron.

**Comment by psytron** [comment]
This would be great. It would enable Nuitka compiled apps to have cool infinitely complex UI.

**Comment by gggggeorge** [comment]
@TokenChingy  I have had a similar issue -I believe you are simply missing:

**Python.Runtime.dll**

I would think Nuitka would copy this to the "Nuitka dist" dir., bit it appears not...?

----
Perhaps change your bug subject line to: "**Nuitka missing Python.Runtime.dll**", because I think that is the real issue, probably having nothing to do with pywebview & Win10, I believe.  Maybe the Nuitka team would take notice, then.

I'm curious about this issue, as well.

----
For me, the solution (work around?) was to simply copy (I'm using **Python 3.7.x**):

FROM:
`C:/Python/Python37/Lib/site-packages/Python.Runtime.dll`

TO:
`[the nuitka dist dir.]`

Maybe you just need to add this "manual copy" to your build.sh script.

----
Also, actually, I'm using Nuitka to feed into PyInstaller -and at Pyinstaller, I actually do this copy, but the effect is the same, in your context, I believe.


Thanks,
George H.
02/04/2021 6:32pm ET

**Comment by kayhayen** [comment]
@gggggeorge is that DLL the pywebview runtime or what is it?

**Comment by gggggeorge** [comment]
Hi @kayhayen,

I'm glad you replied because it jogged my memory, and I did some checking.

When I replied, yesterday (02/04/2021), I quickly assumed it was part of the "Python install", but today I realize that it is seemingly part of **pythonnet** install...?

[https://pypi.org/project/pythonnet/](https://pypi.org/project/pythonnet/)

From what I understand, when you do a:

`pip install pythonnet`

-the above will install Python.Runtime.dll (as well as do other things) into:

`C:/Python/Python37/Lib/site-packages/Python.Runtime.dll`

NOTE: I'm using Python 3.7.x.

----
I am using pythonnet in my project, and I noticed that when building **Nuitka**, I needed to copy this file to the Nuitka Dist. dir. -if I wanted to try running my EXE from the Nuitka Dist. dir. (I would only do this for testing).

I have **PyInstaller** take the EXE (created by Nuitka), and copy over the **Python.Runtime.dll** (and many other files: *.py, *.dll, etc.) and then PyInstaller creates an EXE, and this PyInstaller EXE is actually what the end-user runs.

----
I just did some checking into **pywebview**, and it seems **pythonnet** is needed for **pywebview** -at least on a Windows computer...?

I base the above from reading this, where Python.Runtime.dll is asked about a few times:

[https://github.com/r0x0r/pywebview/issues/343](https://github.com/r0x0r/pywebview/issues/343)


Thanks,
George H.
02/05/2021 2:55pm ET

**Comment by TokenChingy** [comment]
Hi @gggggeorge thanks for this, I will have a look at this some time and report back. I haven't actually used Nuitka for quite some time now.

**Comment by yurh** [comment]
@TokenChingy  Try this.
Copy all files in folder python/lib/site-packages/cefpython3/* to you dist folder.
And also copy python/lib/site-packages/Python.Runtime.dll

**Comment by yurh** [comment]
And you need to copy python27.dll python34.dll python35.dll python36.dll to c:\windows\syswow64

**Comment by yurh** [comment]
Use cef instead of mshtml. 
webview.start(gui='cef')

**Comment by chanchan69** [comment]
I fully fixed this issue by copying the Python/Lib/site-packages/Python.Runtime.dll into my Nuitka directory along with the dlls located in Python/Lib/site-packages/webview/lib

**Comment by dmwyatt** [comment]
> I fully fixed this issue by copying the Python/Lib/site-packages/Python.Runtime.dll into my Nuitka directory along with the dlls located in Python/Lib/site-packages/webview/lib

Yeah this works.  I just copied the whole webview folder which also works because of how pywebview looks for the DLLs.

## To be clear this is how you make pywebview work with Nuitka:

From virtualenv copy `Lib\site-packages\Python.Runtime.dll` and `Lib\site-packages\webview\` to your dist directory and this will get pywebview working with Nuitka.

<hr>

As far as "fixing" Nuitka to work with pywebview...I'm not sure what Nuitka should do.  `pywebview` dynamically builds paths to DLLs in [interop_dll_path](https://github.com/r0x0r/pywebview/blob/d41dd4a01cbe02aeca143e9248eafeaf32377b28/webview/util.py#L221).  That function does a bit of accounting for how pyinstaller bundles things (that's what the frozen/unfrozen comments are referring to) and pyinstaller has a hook specifically for pywebview so it knows how to bundle it. @kayhayen would have to give some input here, but I don't know of a way to solve this in the general case since the files are located dynamically.

**Comment by kayhayen** [comment]
Thanks, those pointers will be good enough. 

I think for Nuitka, this ought to be good enough:

```
    # Unfrozen path
    dll_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'lib', dll_name)
    if os.path.exists(dll_path):
        return dll_path
```

That should point to ``webview/util`` as a folder for the DLLs inside the dist folder, because ``__file__`` is updated correctly with Nuitka.  Not sure why PyInstaller needs more help there, but I also don't care.

**Comment by kayhayen** [comment]
I made a plugin that includes the DLLs for pywebview on Windows. Seems that pywebview only works with Python 3.7, so is this obsolete stuff I guess. Anyway, it's on factory: https://nuitka.net/doc/factory.html and you can try it out, it will be in the next release.

**Comment by dmwyatt** [comment]
@kayhayen pywebview supports up to Python 3.9. (Though, because of dependency on pythonnet when on Windows it only works on windows up to 3.7 (maybe 3.8 I don't remember.))

However, if anyone stumbles across this issue, it will likely work fine for you on Windows Python 3.9+ if you just build pythonnet from source or download a pre-compiled wheel from [the usual source](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonnet)

pythonnet has some problems in some apparent edge cases that they're working on. That has prevented them from doing an official release for 3.8+.

**Comment by kayhayen** [comment]
The change is on develop branch right now, and will be part of the next release.

**Comment by kayhayen** [comment]
This is part of the 0.6.18 release.
