### ISSUE TITLE
openSUSE PySideUsing failing on Python 2, but test suite doesnt set an exit code

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#426]
```
[ 1262s] Comparing output of 'PySideUsing.py' using '/usr/bin/python2' with flags silent, expect_success, standalone, remove_output, ignore_infos, ignore_warnings ...
[ 1281s] --- /usr/bin/python2 (stdout)
[ 1281s] +++ nuitka (stdout)
[ 1281s] 
[ 1281s] @@ -1,3 +1,2 @@
[ 1281s] 
[ 1281s] -The answer is:42
[ 1281s] -Slot should have made output by now.
[ 1281s] +The answer is:Slot should have made output by now.
[ 1281s]  
[ 1281s] Error, outputs differed.
```

**Comment by kayhayen** [comment]
Yes, PySide2 is unsupported due to never merging our stuff.

Recently we added a test for something not properly mocked, and made it skip. I will switch to this method, making it skip for PySide2 too.

**Comment by jayvdb** [comment]
If this is PySide2, should the filename be rename from PySideUsing.py to PySide2Using.py ?

**Comment by kayhayen** [comment]
Well, PySide2 is equally not supported, but here I thought it was indeed providing only, PySide2, but maybe it also provides a PySide compatibility, that I don't know.

I have changed the test to be skipped, as there is not really a point in executing it and ignoring the result at this time. We have done similar with BotoUsing recently. They are both skipped now.

I am closing now due to low relevance to everybody outside of us two.
