### ISSUE TITLE
How to control __file__ location

### ISSUE THREAD

**Issue by JonnyTech** [Nuitka/Nuitka#467]
Create `test.py`:

```
#!/usr/bin/env python3.7
import os.path
print(">> " + __file__)
```

Then execute to show file location:

```
$ ./test.py
>> ./test.py
```

Compile with nuitka:

```
$ nuitka --version
0.6.4
$ python3.7 -m nuitka --follow-imports test.py
```

Try new file:

```
$ ./test.bin 
>> /home/user/dev/test.py
```

Hmm, ok, slightly different but correct location.

Now move file elsewhere:

```
$ cp test.bin /tmp/
$ cd /tmp/
$ ./test.bin 
>> /home/user/dev/test.py
```

The output should be:

```
$ ./test.bin 
>> /tmp/test.py
```

What is going on?

**Comment by kayhayen** [comment]
For acceleration, the binary by default pretends to live where it was, hardcoding the original location. There is however an option to make that choice, check `--help` output, seems `--file-reference-choice=runtime` is what you expect. That however requires to copy data files along, which on the same system is not necessarily useful.

Yours,
Kay

**Comment by JonnyTech** [comment]
Thank you very much, Kay.

**Comment by ralienpp** [comment]
I'd like to double-check a few things, @kayhayen, to make sure I understand Nuitka's approach correctly. I try Nuitka 0.7.6, installed via pip, with this [minimal PySide6 example (attached)](https://github.com/Nuitka/Nuitka/files/8410317/qt6buttons.txt):

 `root@ea5336f2a4e3:/arc# /opt/py39/bin/python3 -m nuitka  --plugin-enable=pyside6 --follow-imports  --file-reference-choice=runtime qt6buttons.py -o qt6buttons.exe`, and I get the following warning:

`Nuitka-Options:WARNING: Using non-default file reference mode 'runtime' rather than 'original' may cause runtime issues.` Although compilation works, running the program produces this error:

```
15:42 $ ./qt6buttons.exe 
PySide6/__init__.py: Unable to import Shiboken from  /opt/py39/lib/python39.zip, /opt/py39/lib/python3.9, /opt/py39/lib/python3.9/lib-dynload, /opt/py39/lib/python3.9/site-packages
Traceback (most recent call last):
  File "/home/alex/arc/demo/qt6buttons.py", line 4, in <module>
    from PySide6.QtCore import Qt, QSize
  File "/home/alex/arc/demo/PySide6/__init__.py", line 111, in <module PySide6>
  File "/home/alex/arc/demo/PySide6/__init__.py", line 60, in _setupQtDirectories
  File "/home/alex/arc/demo/shiboken6/__init__.py", line 25, in <module shiboken6>
ModuleNotFoundError: No module named 'shiboken6.Shiboken'
```
Obviously, the warning is there for a reason. I am trying to understand what the best practice is, and what actually happens when `--file-reference-choice=runtime` is used.

Like the original poster, I saw that the original location is hardcoded, which is not suitable for my case, where I have lots of places in the code, where something is loaded dynamically. My solution is to use relative paths and the default, `--file-reference-choice=original`, with a remark that whoever runs the compiled binary, must first `cd` into its directory, such that `os.getcwd()` will be the right starting point for relative paths. This approach works, but it implies that I have to change some other parts in our code to adapt to it, because we change the current directory on several occasions.

Before I start reworking that logic, I'd like to understand in what way I'm misusing `--file-reference-choice=runtime`, perhaps there's a nicer way to deal with this.
