### ISSUE TITLE
setup.py cmdclass distribution problem for package pyyaml

### ISSUE THREAD

**Issue by tommyli3318** [Nuitka/Nuitka#476]
`error: invalid command 'bdist_nuitka'` is raised when `python setup.py bdist_nutika` is called for the package `pyyaml`

Nuitka fails to hook onto the `setup.py` of `pyyaml` because of its special `cmdclass` configuration.

Platform: Windows
Python 3.7.0 (x32)
Nuitka 0.6.5rc3

Steps to reproduce:
1. Create and activate a new virtualenv
2. `git clone https://github.com/yaml/pyyaml.git`
3. `cd pyyaml`
4. `python setup.py bdist_nutika`

**Comment by kayhayen** [comment]
We should investigate, if for the bdist_nuitka installed hook, it is possible to get a hand at these, to patch them. Otherwise, we may just as well have to git up on this, due to its non-standardness. Not sure if our hook is even called. Can you add something in `bdist_nuitka`, like an `assert False` and see if we do get called?

**Comment by tommyli3318** [comment]
> Not sure if our hook is even called. Can you add something in bdist_nuitka, like an assert False and see if we do get called?

Just did, AssertionError is not raised so it seems we do not get called at all.

**Comment by kayhayen** [comment]
Then there is nothing we can do. Lets just ignore pyyaml then.
