### ISSUE TITLE
Error, call to 'install_name_tool'

### ISSUE THREAD

**Issue by 25shmeckles** [Nuitka/Nuitka#51]
I get this error when running nuitka installed via `pip3 install nuitka`
Python 3.6.3
macOS 10.12.6 
Looks like to be an Xcode-related problem. Any solutions?

```
Nuitka:WARNING:The version '3.6' is not currently supported. Expect problems.
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: more than one input file specified (libpython3.6m.dylib and --change)
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
Error, call to 'install_name_tool' to fix Python library path failed.
```

**Comment by 25shmeckles** [comment]
Anyone on this??

**Comment by kayhayen** [comment]
I think you ought to check out what changed there, for install_name_tool.

**Comment by 25shmeckles** [comment]
Sorry for my ignorance, but I don't get it. Looks like Nuitka is calling 'install_name_tool' with the wrong params, or am I wrong? The error pops out after `nuitka-run myscript.py`

**Comment by kayhayen** [comment]
yes, and if you want it fixed, you are to provide the information what changed for that command. I have no MacOS X. Otherwise this issue is useless and may only suggest that it's a known problem that will be dealt with. It won't unless there is information gained.

**Comment by 25shmeckles** [comment]
"you are to provide the information what changed for that command" 
I have no idea about that. I only know that I have installed nuitka on macOS and it doesn't work.

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Kay Hayen <notifications@github.com> Date: 3/12/18  13:19  (GMT+01:00) To: kayhayen/Nuitka <Nuitka@noreply.github.com> Cc: Alessio Marcozzi <alessio.marcozzi@gmail.com>, Author <author@noreply.github.com> Subject: Re: [kayhayen/Nuitka] Error, call to 'install_name_tool' (#51) 
yes, and if you want it fixed, you are to provide the information what changed for that command. I have no MacOS X. Otherwise this issue is useless and may only suggest that it's a known problem that will be dealt with. It won't unless there is information gained.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kayhayen/Nuitka","title":"kayhayen/Nuitka","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kayhayen/Nuitka"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kayhayen in #51: yes, and if you want it fixed, you are to provide the information what changed for that command. I have no MacOS X. Otherwise this issue is useless and may only suggest that it's a known problem that will be dealt with. It won't unless there is information gained."}],"action":{"name":"View Issue","url":"https://github.com/kayhayen/Nuitka/issues/51#issuecomment-372290936"}}}

**Comment by ArtemFaust** [comment]
I also met this problem and could not find a solution 
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: more than one input file specified (libpython3.6m.dylib and --change) 

otool -L /anaconda3/lib/libpython3.6m.dylib 
/anaconda3/lib/libpython3.6m.dylib:
	@loader_path/anaconda3/lib/libpython3.6m.dylib (compatibility version 3.6.0, current version 3.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

conda --version
conda 4.5.4

nuitka3 --version
0.5.30

**Comment by mingwandroid** [comment]
I'm also running into this, happily I work for Anaconda Inc, doing packaging work so am in a good position to figure this out. One thing to note about our Python interpreter is that it is statically linked and the dylib is provided only for embedded use cases.

**Comment by kayhayen** [comment]
Checkout these @mingwandroid 

https://github.com/Nuitka/Nuitka/blob/9fc78dd4acbbe56274a22f6a3c159fcdd14f4f6b/nuitka/freezer/Standalone.py#L1060

https://github.com/Nuitka/Nuitka/blob/9fc78dd4acbbe56274a22f6a3c159fcdd14f4f6b/nuitka/build/SingleExe.scons#L1981

I am not so sure about Xcode differences, could it be that AnaConda is on an older toolset? And they changed it. I would welcome a command that works for both.

You are also welcome to enhance my attempt in SingleExe.scons to automatically pickup Anaconda tool change, which currently happens for Windows, and expand it to MacOS.

Yours,
Kay

**Comment by mingwandroid** [comment]
Thanks for the pointers Kay.

BTW, have you seen the [LIEF](https://github.com/lief-project/LIEF) project? It allows all sorts of queries to be performed on ELF, MachO and PECOFF files in a cross platform way. On the downside, it is a somewhat heavy dependency!

**Comment by kayhayen** [comment]
As I noticed in #81 the correctness of these values is highly optional, manylinux is one example of getting it wrong. Another case was pyenv where it typically would be built in an unusable way and should be avoided.

I am still investigating this one. Somebody was going to do PR where the distutils compiler might be used, but e.g. with AnaConda on Linux, gcc-6 cannot link it, too old, gcc-8 is too new, and gcc-7 from system crashed on it. Only the CondaCC can do it with LTO yet. I am kind of assuming that if we picked up the CondaCC (if installed) more automatically, it might work fully. If not installed, it won't work, and due to the cross compile naming scheme, scons does not pick it up lightly.

See #95 for the discussion.

So unfortunately @mingwandroid it's not that easy. That is why this is basically currently only on if `"Anaconda" in sys.version`, checkout nuitka/MainControl.py where that happens. I have not managed to see it working on anything but Miniconda/Anaconda yet.

**Comment by mingwandroid** [comment]
> Somebody was going to do PR where the distutils compiler might be used, but e.g. with AnaConda on Linux, gcc-6 cannot link it, too old, gcc-8 is too new, and gcc-7 from system crashed on it. Only the CondaCC can do it with LTO yet

That someone is me :-)

Do you have any reference or details for:

> gcc-8 is too new

Does it emit relocations that our linker cannot handle? We use `binutils 2.31.1` at present which is pretty recent.

**Comment by kayhayen** [comment]
@mingwandroid sorry about my confusion regarding that PR. :)

Basically gcc-6, gcc-7, and gcc-8 all have different bytecode and cannot be mixed. According to this page: https://gcc.gnu.org/wiki/LinkTimeOptimization this is an internal data structure being saved, and there is no way this stays consistent.

This probably also explains why not even my Debian Testing gcc-7 and CondaCC which is a gcc-7 too worked together.

The takeaway for me was that LTO (with gcc) works if everything is compiled by the same compiler version, which however is not a problem for CondaCC.

I bet that LLVM wouldn't have that issue, as their bytecode is a real stable interface or so I am assuming.

This mess also explains why LTO is actively disabled when linking with the LTO library in Conda.

```
    elif static_libpython and not lto_mode:
        env.Append(CCFLAGS = ["-fno-lto"])
        env.Append(
            LINKFLAGS = ["-fno-lto"]
        )

```
Because LTO is on for gcc by default for a while now, in this instance, it must be disabled. This also means that no advantage is taken from LTO despite it being possible. With the PR of yours, we can then however enable it, as we can expect `libpython` and all Nuitka compiled C code to be compiled with the same compiler.

**Comment by kayhayen** [comment]
@mingwandroid Using CondaCC on Windows, I am getting spurios errors like this, `collect2.exe: error: ld returned 5 exit status`, does that ring a bell? Googling this error didn't reveal anything to me. I am only getting that error with CondaCC though, and I think both arches, although last I have seen in on 32 bits.

**Comment by kayhayen** [comment]
The fix to this issue was to to consistently call the tool with `-change` rather than `--change` which seems to be more universally working. I think this was solved in another issue, but the link was never made.

**Comment by noonchen** [comment]
I encountered this issue again when the build was almost finished: 

```
Nuitka-Plugins:INFO: qt-plugins: Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'STDF Viewer.dist/PyQt5/qt-plugins'.
Nuitka-Plugins:INFO: numpy: Copied 'matplotlib/mpl-data'.
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: input file: STDF Viewer.dist/PyQt5/qt-plugins/.DS_Store is not a Mach-O file
Error, call to 'install_name_tool' to fix shared library path failed.
```

Platform:
macOS 11.0.1

Nuitka version:
0.6.10
Python: 3.8.6 (default, Nov 20 2020, 23:57:10) 
Executable: /usr/local/opt/python@3.8/bin/python3.8
OS: Darwin
Arch: x86_64

Here is the output of `install_name_tool` in terminal:
```
install_name_tool
Usage: /Library/Developer/CommandLineTools/usr/bin/install_name_tool [-change old new] ... [-rpath old new] ... [-add_rpath new] ... [-delete_rpath old] ... [-id name] input
```
