### ISSUE TITLE
Cannot import file/folder as object

### ISSUE THREAD

**Issue by namuyan** [Nuitka/Nuitka#512]
About
----
Now, many python developers use typing and find **circular import error**.
So we avoid this by import file/folder as object.
However, CPython allow this way but Nuitka not allow now.

Problem
----
* Nuitka 0.6.5
* Python: 3.6.7 64-bit
* Windows x86_64

I try to compile with [fastAPI](https://github.com/tiangolo/fastapi) and find error.
```ext
Traceback (most recent call last):
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fast.py", line 1, in <module>
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fastapi\__init__.py", line 7, in <module fastapi>
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fastapi\applications.py", line 3, in <module fastapi.applications>
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fastapi\routing.py", line 8, in <module fastapi.routing>
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fastapi\dependencies\utils.py", line 23, in <module fastapi.dependencies.utils>
  File "C:\Users\nicert\PycharmProjects\bc4py\fast.dist\fastapi\utils.py", line 5, in <module fastapi.utils>
ImportError: cannot import name 'routing'
```
FastAPI use this technique to avoid circular imports. [problem](https://github.com/tiangolo/fastapi/blob/master/fastapi/utils.py#L5)

Simple example
----
```text
import_bug
├── __init__.py
├── a.py
└── b.py
```

```python
# a.py
from import_bug import b
from typing import Optional


class A:
    def __init__(self):
        self.b: Optional[b.B] = None

    def set(self, new):
        self.b = new
```

```python
# b.py
from import_bug import a
from typing import Optional


class B:
    def __init__(self):
        self.a: Optional[a.A] = None

    def set(self, new):
        self.a = new
```

```python
# bugger.py
from import_bug.a import A
from import_bug.b import B


if __name__ == '__main__':
    a = A()
    a.set(B())
    print(a, a.b)
```

compile by
`python -m nuitka --mingw64 -j 2 --show-progress  --show-scons --recurse-all --standalone bugger.py`

error
```text
Traceback (most recent call last):
  File "C:\Users\nicert\PycharmProjects\nicert\bugger.dist\bugger.py", line 1, in <module>
  File "C:\Users\nicert\PycharmProjects\nicert\bugger.dist\import_bug\a.py", line 1, in <module import_bug.a>
  File "C:\Users\nicert\PycharmProjects\nicert\bugger.dist\import_bug\b.py", line 1, in <module import_bug.b>
ImportError: cannot import name 'a'
```

**Comment by namuyan** [comment]
I edit fastapi to work. I find **another related bug** of uvicorn (dependency of fastapi).

Generated program process is blocked without any errors and is out of control, .
[On this code](https://github.com/encode/uvicorn/blob/master/uvicorn/importer.py#L20), they try to import `uvicorn.protocols.http.auto` by `importlib`

Example
----
```text
app.py
hello.py
```

```python
# app.py
import importlib
import hello
import uvicorn


def check_import(module_str):
    print("try to import", module_str)
    try:
        module = importlib.import_module(module_str)
    except ImportError as exc:
        if exc.name != module_str:
            raise exc from None
        message = 'Could not import module "{module_str}".'
        raise Exception(message.format(module_str=module_str))
    print("finish import", module)
    return module


if __name__ == '__main__':
    check_import("hello")
    check_import("uvicorn.protocols.http.auto")
    print("OK")
```

```python
# hello.py
def nice():
    return "2"
```
compile
----
```bash
python -m nuitka --mingw64 -j 2 --show-progress  --show-scons --recurse-all --standalone --windows-icon=favicon.ico \
--nofollow-import-to=cryptography \
--nofollow-import-to=numpy \
--nofollow-import-to=gevent \
--nofollow-import-to=matplotlib \
--nofollow-import-to=IPython \
--nofollow-import-to=Cython \
--nofollow-import-to=setuptools \
--nofollow-import-to=distutils \
--run \
app.py
```
result
----
```error
try to import hello
finish import <module 'hello' from 'C:\\Users\\jkdfh\\PycharmProjects\\bc4py\\app.dist\\hello.py'>
try to import uvicorn.protocols.http.auto
Traceback (most recent call last):
  File "C:\Users\jkdfh\PycharmProjects\bc4py\app.dist\app.py", line 21, in <module>
  File "C:\Users\jkdfh\PycharmProjects\bc4py\app.dist\app.py", line 12, in check_import
ModuleNotFoundError: No module named 'uvicorn.protocols'
```
But, no trouble on normal usage of `importlib` like example, only on uvicorn.

**Comment by JorjMcKie** [comment]
The ``uvicorn.protocols`` import issue may be related to a dependency not detectable by a source code parser. In which case we would need to extend a Nuitka plugin by another "implicit import" related to this package.
Let me verify this. You could also try adding an additonal follow import to it.

**Comment by JorjMcKie** [comment]
@namuyan - I was able to reproduce your error ``ModuleNotFoundError: No module named 'uvicorn.protocols'`` using the uvicorn provided example server.
After a bunch of new entries in Nuitka's implicit imports plugin, the standalone compile & run of that server worked.
I will upload the respective changes. If you want to shorten the feedback loop you can replace that plugin in your nuitka installation with this one:
[ImplicitImports.zip](https://github.com/Nuitka/Nuitka/files/3625143/ImplicitImports.zip)
It lives in ``nuitka/plugins/standard``.

**Comment by namuyan** [comment]
Thank you for quick response!
It looks work by `--plugin-enable=implicit-imports`.
I remember that there is such a way.

https://github.com/namuyan/fastapi
https://github.com/namuyan/uvicorn
I have solved another way, just fork and edit like these.

**Comment by kayhayen** [comment]
@JorjMcKie I simply forwarded develop to your branch, but I guess this change is not yet there, right?

**Comment by justin0mcateer** [comment]
I am having the same problem with FastAPI. It appears to be a run-time problem with the way the 'from {module} import {sub-module}' statement behaves. It does not appear to be a compile time problem. I am seeing that the 'routing.py' submodule is being compiled and linked by Nuitka, but the program still complains that it is not able to find it at run-time.

I am also using Uvicorn and I can say that the problem with Uvicorn and the problem with FastAPI are not the same. The Uvicorn issue seems to be solved merely by using 'include-module' directives. This is my compile command:
```
python -m nuitka --standalone --follow-imports --show-progress --show-scons --show-modules --jobs=15 --include-module=uvicorn.logging --include-module=uvicorn.protocols.http --include-module=uvicorn.loops --include-module=uvicorn.lifespan --include-module=uvicorn.protocols.websockets uvicorn_test.py
```

However, neither the 'include-module' nor the 'include-package' directives are helpful in solving the FastAPI run-time issue. This is my compile command with FastAPI:
```
python -m nuitka --standalone --follow-imports --show-progress --show-scons --show-modules --jobs=15 --plugin-enable=implicit-imports --include-package=pydantic --include-package=fastapi --include-module=uvicorn.logging --include-module=uvicorn.protocols.http --include-module=uvicorn.loops --include-module=uvicorn.lifespan --include-module=uvicorn.protocols.websockets fastapi_test.py
```

This compiles fine and includes the 'fastapi.routing' submodule as demonstrated by the Nuitka and Scons output"
```
Nuitka:INFO:Included compiled module 'fastapi.routing'.
```
scons: building `fastapi_test.build/module.fastapi.routing.o' because it doesn't exist
gcc -o fastapi_test.build/module.fastapi.routing.o -c -fvisibility=hidden -std=c11 -fwrapv -fpartial-inlining -ffile-prefix-map=fastapi_test.build/static_src=/home/jmcateer/.local/share/dephell/venvs/nuitka_fastapi-7F4f/main/lib/python3.7/site-packages/nuitka/build/static_src -fno-var-tracking -O3 -pipe -D_NUITKA_STANDALONE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=165 -D_NUITKA_MODULE_COUNT=730 -D_NUITKA_EXE -I/usr/include/python3.7m -I/usr/PC -Ifastapi_test.build -I/home/jmcateer/.local/share/dephell/venvs/nuitka_fastapi-7F4f/main/lib/python3.7/site-packages/nuitka/build/include -I/home/jmcateer/.local/share/dephell/venvs/nuitka_fastapi-7F4f/main/lib/python3.7/site-packages/nuitka/build/static_src fastapi_test.build/module.fastapi.routing.c
```

The object file also appears in the linker input at '@sources.tmp':
```
fastapi_test.build/module.fastapi.routing.o
```

However, when the program is run, it fails immediately on startup with the following error:
```
ImportError: cannot import name 'routing' from 'fastapi' (/home/jmcateer/Documents/nuitka_fastapi/fastapi_test.dist/fastapi/__init__.py)
```

@namuyan seems to have worked around this issue by modifying FastAPI. However, this is not an uncommon import pattern and modifying the upstream FastAPI library is not really a good option for me.

Any specific ideas about why this fails and run-time and how we could fix in Nuitka, versus modifying the compiled code?

The test code being compiled is attached.
[fastapi_test.zip](https://github.com/Nuitka/Nuitka/files/3898794/fastapi_test.zip)

**Comment by kayhayen** [comment]
This has been solved through a duplicate, cyclic name imports have been working for a while now.
