### ISSUE TITLE
Reproducible builds from Nuitka

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#534]
When building using `build_with_nuitka` enabled, and very likely at other times, it appears that the artifacts of each build is different, even if the inputs are identical.

Avoiding that is a major push across the industry at the moment.  It allows fast-finish CI, and also allows third parties to perform an identical build from the source to verify that the first party/vendor distributed binaries were not corrupted somewhere along the way.  See https://en.wikipedia.org/wiki/Reproducible_builds

Compare

https://build.opensuse.org/packages/python-anyjson/job_history/home:jayvdb:Nuitka/openSUSE_Tumbleweed/i586

and

https://build.opensuse.org/packages/python-simplejson/job_history/home:jayvdb:Nuitka/openSUSE_Tumbleweed/i586

with

https://build.opensuse.org/packages/python-anyjson/job_history/devel:languages:python/openSUSE_Tumbleweed/i586

and

https://build.opensuse.org/packages/python-simplejson/job_history/devel:languages:python/openSUSE_Tumbleweed/i586

where the status "unchanged" means that the rebuild was identical and the new artifacts were therefore discarded.

Distros usually have a tool like https://github.com/openSUSE/build-compare/ which does the comparison and discards differences which are known to be irrelevant, especially build dates which get injected into built files.

It would be great if Nuitka could have reproducible builds, perhaps as a build option if it would be disruptive to other users / development processes.

**Comment by jayvdb** [comment]
The built dso differ in ELF sections .dynsym, .dynstr, .rel.dyn, .rel.plt, .init, .text, .fini, .rodata, .eh_frame_hdr, .eh_frame, .init_array, .fini_array, .data.rel.ro, .dynamic, .got, .got.plt, & .data,

**Comment by jayvdb** [comment]
https://github.com/Nuitka/Nuitka/issues/543 may have helped a little, but I am still seeing variation in many ELF sections.

Locking down `PYTHONHASHSEED=1` might help, like it apparently does with PyInstaller (https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#creating-a-reproducible-build)

That might be a more feasible first iteration, but shouldnt be the final destination.

However I should add that so far I have found PyInstaller builds to be quite reproducible without locking down `PYTHONHASHSEED` - that part of their docs might be out of date.

Test suites for this issue should re-do the same build and expect (almost) identical .so files - see build-compare mentioned above to see what differences are considered acceptable.

**Comment by kayhayen** [comment]
Nuitka does `PYTHONHASHSEED=0` since forever, and the reflected test, that I removed recently (and should add back, now that Jinja2 and markupsafe inline copy work), was used to prove that it generates the same source code after being compiled with itself. Variations should have been found there. However, there might be C options to use.

Can you elaborate on this some more, I think I am a fan of determism and there might be compiler notes, etc. that I would have to disable. Also not sure if anything uses date of other macros, and Nuitka would have to do something about that.

**Comment by kayhayen** [comment]
I really would need help with the tooling there, I right now don't see what kind of differences two binaries have there. I am willing to work and minimize those as much as possible, indeed I would expect them to be not there, but there may be things I do not know about yet.

**Comment by jayvdb** [comment]
To reproduce, build a DSO from a python library, and then build it again an hour later, and do a binary compare the two DSOs.  It might be necessary to `touch` the source .py files again to trigger this behaviour, but I doubt that is the cause.  https://stackoverflow.com/a/28808194/5037965 will give more details about ELF differences

**Comment by andriuss-amd** [comment]
`diffoscope` tool is fairly good at showing differences between two elf files.

**Comment by kayhayen** [comment]
@andriuss-amd thanks for that poiter, a quick test of compiling same user, same dir, same machine, revealed no differences for standalone, even `diff -r ` didn't find anything. So that is what I expected. Now I wonder, what the test setup should be to prove that it's reproducible. I try to be resistant against file system differences. Is there some binary to run it, such that it will shake up file system ordering, and the like? My reflected test supposedly should find things, but I will never know if any sorting is missing somewhere.

**Comment by jayvdb** [comment]
As this was raised many years ago, very likely something has changed since then that has solved this.  Thanks for retesting @kayhayen .  I dont have time to recreate the same build setup, esp given it sounds like it has already been solved, so it is better to close this and let someone create a new issue if they can create a reproducible set of steps.
