### ISSUE TITLE
Question: How to compile without system library dependencies

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#538]
Is there a way to compile a standalone version without any system library dependencies? I don’t absolutely need a static binary. It could be many files with dynamic libraries but I would like to have no dependencies to libs in /lib/.

The reason I need it is for portability mostly on system that have recent glibc version. Right now, I compile on a debian (stretch) host using Python 3.6.8 and nuitka 0.6.5.

**Comment by jayvdb** [comment]
If you need absolutely no dependency on /lib, you can not use glibc, unless you can remove any dependency on pthreads. 
See https://www.google.com/search?q=%22libgcc_s.so.1%22+%22pthread_cancel%22

The alternative is to build static Python against a different libc.

If you can accept a dependency on libgcc_s , then it is possible, but you will need to carefully build your static Python otherwise you run into problems with duplicate/missing symbols.  See https://github.com/Nuitka/Nuitka/issues/95

And then you need to hack a bit to get Nuitka to find your static Python .a

```sh
# Force static support
sed -i 's/return "Anaconda" .*$/return True/' nuitka/Options.py
# Help Nuitka find the static lib to link against
sed -i 's:python_lib_path, "libpython" + python_abi_version + ".a":"/usr/lib/python3.7/config-3.7m-i386-linux-gnu/libpython3.7m.a":' nuitka/build/SingleExe.scons
```

I am just going through this process myself ;-)

I just removed the Py_GetArgcArgv collision by excluding `main.o` from the .a, but now I have a bunch of undefined references to PyCore*/PyConfig*/others.

**Comment by kayhayen** [comment]
Current factory branch no longer has these issues, @jayvdb by just making the symbol weak.

The standalone cannot make glibc for newer kernels work with older ones. You absolutely have to build on the oldest system you intend to support, going forward then often works. The other way around, not so much.
