### ISSUE TITLE
Nuitka setup.py injector (build_with_nuitka alternative)

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#553]
The setup.py hook currently needs to be manually added, and this is error prone as the order of `setup()` args is important.

https://github.com/ninjaaron/fast-entry_points has a neat approach which is to update the `setup.py` with a CLI tool.  It is a bit buggy https://github.com/ninjaaron/fast-entry_points/issues/18 , but should work most of the time.

I'd like to contribute the same here, as I have the logic required to edit the setup.py of ~300 packages to correctly initiate Nuitka bdist.

Where would be the best spot to add the code, and should it be a separate CLI console script (seems more appropriate) or args for the existing one?

**Comment by kayhayen** [comment]
@jayvdb I have a couple of questions about this:

a) The order of arguments is not guarantueed to be in the keyword dictionary before 3.7, and maybe is only there in 3.6, but definitely not before. What do you mean with this. Can you give an example, I am not that familiar with distutils there.

b) Why not use `bdist_nuitka` as a target? That requires no modification at all. I think we used that for the GSoC project, check the `tests/PyPI-pytest` folder, it should also work for most things.

Yours,
Kay

**Comment by kayhayen** [comment]
As an aside, I would recommend using `redbaron` to make the actual modification of the setup call, that is what it was developed for. I previously used it for autoformat of Nuitka source, when I still had strong feelings about it. Now I just use black, except for sorting pylint comment ids, which is not something black does.

It's a heavy dependency, but you get to search very precisely for the call arguments, look at them, and change them with relative ease and high reliability.

As for fast entry points, the pkgutil ones are nasty indeed. For Nuitka compilation to give more benefit, these should be used indeed. For now, scripts are left untouched, but we could also hook script creation in much the same way and do a minimal executable. Esp. once we get `libnuitka` to be shared with the `.so` and `.exe` that could make things fast. I really want to get to #102 eventually, and that is anther reason, isn't it. @jayvdb

**Comment by kayhayen** [comment]
@tommyli3318 can you spend some thoughts on how we can make runners with nuitka that are as fast as possible.

Right now are using mere Python scripts, which then import main program from our compiled packages, but maybe it could be faster to launch via executable. You are free to come up with a minimal dependency approach.

**Comment by kayhayen** [comment]
Having looked at it, @tommyli3318 and I were initially confused, because wheels do not have any overhead in their runners, and checking the link given, we found that the project *only* makes sense for when no wheels are used.

Question becomes, if we care about the use case of direct install, which Nuitka does *not* aid in, to be fast for Nuitka compiled stuff. I would argue, the above project could be used in that instance, but this seems to be out of the scope of Nuitka otherwise, as we are focussing on wheels.

Does using `bdist_nuitka` not resolve your need to edit the `setup.py` at all? It's intended to!

**Comment by jayvdb** [comment]
`bdist_nuitka` does not help when I last looked, because distros use `setup.py build` and `setup.py install` as two very distinct phases, and they use lots of options for the install cmd, because during package creation the filesystem (and system site-packages) is readonly except for the special path (called the buildroot) where an overlay of the filesystem is prepared, which will become the deb/rpm.

I'll recheck this issue soon.  Looking forward to seeing the new functionality.

I've been doing quite a bit of 'setup.py' rewriting in https://github.com/dephell/dephell/pulls/jayvdb and https://github.com/dephell/dephell_setuptools has been spawned.

**Comment by kayhayen** [comment]
So, you want Nuitka to compile during normal install and not only `bdist_nuitka`. Now that you mention it, the RPM packaging that we have for Nuitka, also creates no wheel.

This seems feasible, I mean, we modify `build` and `install` in `bdist_nuitka`. I guess, this is mostly about figuring out what our install ought to do extra. I would still prefer a separate target, like `install_nuitka` to start with, as it avoids the `setup.py` modification, but that's just minor detail.

I guess, we never tried `install` with `build_with_nuitka`. Maybe @tommyli3318 you want to give it a try, and report what happens if you do replace the wheel building in the PyPI test (which would mean it's no longer a wheel test though) with simply doing `install`. I guess, then you do have the issue of patching `setup.py` though, but a dirty hack may do for one example.

**Comment by kayhayen** [comment]
Adding a `install_nuitka` target should be easy though as well, just need to copy the existing `install` class I guess and add it to the setup hook that also gets `bdist_nuitka` to be known.

**Comment by jayvdb** [comment]
I need a build phase only, that does not try to do an install.  A `build_nuitka` command would be good enough.

**Comment by kayhayen** [comment]
You are right @jayvdb that should do, and be easy. Actually I think it's trivial. It just needs to be exposed in the setup.py of nuitka in the list of distutil.commands, and I see no reason, why it wouldn't work. I am adding `install_nuitka` because it might be used by somebody else eventually.

We named our `bdist` target differently, but not `build` and `install`. Not sure what the purpose of that is, but lets first see if this helps.

@tommyli3318 once I merge factory to develop, can you try an adapted version of the PyPI test suite, with just using `install_nuitka` rather than going through a wheel?

We might be done with the injector level crap, but I guess, the runners are still slow, but maybe the other project can handle that. But why couldn't we. I guess it's not so hard to intercept and make a runner like wheels do.

**Comment by kayhayen** [comment]
@jayvdb do you still need that command?

**Comment by kayhayen** [comment]
Closing for lack of feedback.
