### ISSUE TITLE
Mismatch between Python pei-x86-64 and MinGW64 ('pei-i386') arches

### ISSUE THREAD

**Issue by fireundubh** [Nuitka/Nuitka#573]
Nuitka fails to build the executable with MinGW64 on GitHub Actions (Windows Server 2019) due to the following error:

> Error, Mismatch between Python pei-x86-64 and MinGW64 ('pei-i386') arches

Here's the [full log](https://github.com/fireundubh/pyro/commit/febab2fc497bf8cb9db9cb5833f6e51131b0e9e2/checks/304055373/logs). You'll notice there's no `pyro.exe` referenced in the log after the following command is executed.

Arguments:

> pipenv run nuitka --standalone pyro --include-package=pyro --experimental=use_pefile --python-flag=no_site --python-flag=nosite --python-for-scons=C:\hostedtoolcache\windows\Python\3.7.5\x64\python.exe --assume-yes-for-downloads --plugin-enable=multiprocessing --show-progress --file-reference-choice=runtime --mingw64

Other info:

- GitHub pre-installs [MinGW64 via chocolatey](https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Install-MinGW.ps1) using `choco install mingw`.
- `choco install mingw` installs [MinGW-w64 8.1.0](https://chocolatey.org/packages/mingw).

**Comment by kayhayen** [comment]
The mismatch appears to be real. You seem to ignore the error exit from Nuitka, never a wise thing.

You need the Python and MinGW64 arches to match.  From the link you gave, it looks like the MinGW installed is 32 bits, and thus not usable for 64 bits Python. Either change to x86 Python or x64 MinGW.

**Comment by fireundubh** [comment]
Huh, I tried `choco install mingw` locally. It looks like choco installs both arches, so there must be an environment variable that needs to be set in a GitHub Actions build script to select the x64 arch. Thanks.

**Comment by Squirrel8475** [comment]
Same happened to me under Windows, the arch reported for mingw64 is _None_ when installing the compiler with conda and i386 via the windows installer. Could not bring it to work unfortunately.

**VIA CONDA**

mingw64 installation was made using miniconda  : _conda install m2w64-gcc libpython_ . The CC env variable was defined by _CC=C:\Users\xxx\.conda\envs\yyy\Library\mingw-w64\bin\gcc.exe_ .

> Error, mismatch between Python binary ('C:\Users\xxx\.conda\envs\yyy\python.exe' -> 'pei-x86-64')
>  and C compiler ('C:\Users\xxx\.conda\envs\yyy\Library\mingw-w64\bin\gcc.exe' -> 'None') arches.

Also tried linking: _x86_64-w64-mingw32-gcc.exe_ instead of _gcc.exe_, with same error message. Plateform is Windows with python 3.8.5. gcc works well in command window and _whereis gcc_ shows the right version.

**VIA WINDOWS INSTALLER**

Downloaded from https://sourceforge.net/projects/mingw-w64/files/mingw-w64/, installed for version 7.3.0 with x86_v64 and adjusted CC environment variable. Error message:

> Error, mismatch between Python binary ('C:\Users\xxx\.conda\envs\yyy\python.exe' -> 'pei-x86-64') and C compiler ('C:\Program Files (x86)\mingw-w64\i686-7.3.0-posix-dwarf-rt_v5-rev0\mingw32\bin\gcc.exe' -> 'pei-i386') arches.
