### ISSUE TITLE
Scalability issue requires a lot of memory for code that uses large constants

### ISSUE THREAD

**Issue by gggggeorge** [Nuitka/Nuitka#628]
[large.txt](https://github.com/Nuitka/Nuitka/files/4250668/large.txt)

Hi,

I've been successfully using Nuitka on:

1. Win7 x86 (32 bit)
2. Win10 x64 (64 bit)

with no issues, until the following scenario -on Win7 (1):

I have a large python file (**large.py** -it is attached as **large.txt**) that is approx. 8.4MB -when this file is smaller (say 2KB) I have no issues, but when it is larger, I get the following error message (only on Win7 x86):

**python -m nuitka --standalone "./large.py"**

```
cc1.exe: out of memory allocating 65536 bytes
scons: *** [module.__main__.o] Error 1
```

I only have this problem with the large python file, on the Win7 x86 computer -never on the Win10 x64.  I realize it is some sort of memory limitation, but how can I get around this?

Also, I ran TaskManager -> Performance tab, and I got:

CPU: 100%
Memory: 1.72GB

-the above was the max Memory used when I ran Nuitka on Win7.  There is 4GB of memory installed on Win7.

----
FYI: on Win10 (x64), the large.py gets translated/compiled to:

large.c (45MB)
large.o (15.2MB)

Also, I'm using the same versions of: Python, Nuitka & mingw-w64 for both Win7 & Win10.

----
Here is my environment for Win7 (4GB RAM) (1):

**python -m nuitka --version**

```
0.6.7
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit
 (Intel)]
Executable: C:\Python37-32\python.exe
OS: Windows
Arch: x86

```

**mingw-w64:**

`CC=C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe`

```
C:\Program Files\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin>gcc.exe --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

----
----
Here is **large.py** (this is the approx. 2KB version -this version works):

```
myList = [ 
  {
    "CatWalkingAcrossKeyboard":"idimd903e9u0uiowqem82",
    "asdasd":"ieoi298y2398r92838ry283r",
    "Uare":"ooooooooo990282i92i9wi",
    "tyrtyrty":[ 
      "anythingGoesHere eee23 , BB4, ZEP98"
    ],
    "RevUpYourEngines":"ScottyKilmer"
  },
  {
    "CatWalkingAcrossKeyboard_ver2.0":"idimd903e9u0uiowqem82",
    "czxczcx":"oo2340982134oooo990282i92i9wi",
    "fghfghfh":"jktybw45vwvwtvw4e5ybw2r2x3c23c23rc 2  32r23r",
    "hjkhjkhjk":[ 
      "anythingGoesHereAgainuuu eee23 , BB4, ZEP98"
    ],
    "RevUpYourEngines2":"ScottyKilmer"
  },
]

```
-the "real" large.py (attached as large.txt) is basically the same format of the above, but each of the two items is repeated each about 15,000 times (using random string values -they must not be repeating strings because it looks like Nuitka does some of "optimization/collapsing" of "same strings").  This is the version that fails.  Yes, this is very odd, I know, but it should still work, yes?

----
----
Also, it looks like this might be related to #447...?

Thanks,
George H.
02/25/2020 10:22am ET

**Comment by kayhayen** [comment]
That issue you referenced is very invalid, so we can't know.

I will eventually do this. Where it is about constant values, I will make special purpose marshal code for Nuitka that is going be more like bytecode to build constant values, then this won't be an issue. It will hopefully address some scalability issues.

I would have to confirm, but I believe, Nuitka will put most of your constants generation into the `large.c` as only values used in two modules are in a shared place, but that one often has the same problem only more. And then it creates a sub-constant for each element, and gives the C compiler a hard code looking at a lot of code that is only run once and getting large.

My plans are aiming at also solving the caching issue, because many constants blob references are made, for string values, and these are volatile across program changes. Therefore this is not an easy problem to solve, since I will still want to make this half way efficient, as well as suitable for adding in data obfuscucation for the commercial folks. 

The plan is to work on this during March, but it's a big change clearly. No idea how long it will be until it's usable.

**Comment by kayhayen** [comment]
This has been implemented a lot time ago. There is still a size limit for a constants blob per module, but it's not code anymore.
