### ISSUE TITLE
How to require Nuitka to include a module

### ISSUE THREAD

**Issue by alanhamlett** [Nuitka/Nuitka#636]
Probably because of all the dynamic `__import__` calls used to load lexer classes:

https://github.com/pygments/pygments/search?utf8=%E2%9C%93&q=__import__&type=

When adding each lexer file with `--recurse-to=pygments.lexers.c_cpp`, Nuitka doesn't respect the recurse-to and still ignores these modules:

`Nuitka:WARNING:Not recursing to unused 'pygments.lexers.c_cpp'.`

The module `pygments.lexers.c_cpp` **is** used in my program, how do I tell Nuitka to not override my recurse-to arguments?

**Comment by kayhayen** [comment]
Let me know why reading the `--help` output wasn't sufficient to answer the question, but try reading the `--include-module` and `--include-package` sections.

The recursion options are for allowing the automatic detection to go there. The inclusion options are required.

The warning is there, because allowing Nuitka to recurse is nice, but was not used.

**Comment by alanhamlett** [comment]
Oh, got it. Should have used `--include-module` instead of `--recurse-to`. Thanks!
