### ISSUE TITLE
Standalone distribution with library sub-directory path

### ISSUE THREAD

**Issue by devkral** [Nuitka/Nuitka#66]
It would be useful to have not all the library files cluttering the executable folder if standalone was chosen.
Some optional subdirectory path under which the library files are stored if specified would be cool.

**Comment by kayhayen** [comment]
The issue is that there is no cross platform way of specifying anything beyond "where the binary lives", e.g. on MacOS, the install_name_tool cannot make things longer, so it might exceed, on Windows it is not even possible.

I am not going to work on this. If somebody wants to make it an option for platforms that do support it, go ahead. I am not interested myself.

**Comment by 4O4** [comment]
I believe this can be done with an additional launcher or wrapper program / script, which simply sets `DYLD_FALLBACK_LIBRARY_PATH` (macOS) or `LD_LIBRARY_PATH` (Linux) or `PATH` (Windows) environment variable and then launches the main executable. That's the easiest solution which covers all major platforms.

**Comment by kayhayen** [comment]
MacOS can get binary relative paths with `install_name_tool` already, much like $$ORIGIN linking for Linux already. The Windows wrapper script and/or symlink or `.lnk` file would work too. It's just a matter of who does it.

**Comment by 4O4** [comment]
What about the length limitation when using install_name_tool? I don't have any Mac and I don't know this tool, but it seems like a valid concern.

**Comment by kayhayen** [comment]
There is macOS bundle support in the new release. It's not right now used to distribute files much better, but that's where this is solved for macOS now. Generally onefile mode is for people who hate clutter I guess.
