### ISSUE TITLE
Question: Make compilation faster?

### ISSUE THREAD

**Issue by emrecpp** [Nuitka/Nuitka#699]
Hello,
It took 11-13 minutes to build everytime.
Is it way to make faster this time? Because 7-8 minutes CPU usage around %20, then 2-3 minutes CPU USAGE %100 then last 2-3 minutes cpu usage around again  %20.
My specs;
3700X 8 Core 16 Thread
DDR4 16GB 3600MHZ RAM
3.5GB Read/3.3GB Write SSD
So i think this is not because of the hardware.
What am i missing?
My python version: 3.7.5
This is my build code:
python -m nuitka --plugin-enable=qt-plugins --standalone --recurse-all --show-progress C:\Users\Emre\Desktop\Nxd\Nxd\Main.py
[First 7-8 min cpu usage low, stay this command]
![build after 7-8min](https://user-images.githubusercontent.com/29755479/81195442-7f48de80-8fc6-11ea-9022-fc7904902254.png)

[Total Finish]
![builddone](https://user-images.githubusercontent.com/29755479/81195510-9ab3e980-8fc6-11ea-9b64-0a6b9759f1a9.png)

Thank you!

**Comment by kayhayen** [comment]
The time is acceptable to me for compilation which means a lot of Python code and composition of a standalone system.

If you want to cache C compilation, there is usage documented in the user manual. Caching of Nuitka optimization results is coming eventually, but not a priority right now, there is an issue for that.

Otherwise, for your use case, repeated compilation is normally not needed. To test, you can use normal Python or mere acceleration mode.
