### ISSUE TITLE
Chinese  prompt shows garbled code.

### ISSUE THREAD

**Issue by gyk2850647** [Nuitka/Nuitka#713]
Hi,
I want to ask a question.

nuitka --mingw64  --standalone --show-progress --show-memory --plugin-enable=qt-plugins --plugin-enable=pylint-warnings --recurse-all --recurse-not-to=numpy,jinja2 --output-dir=out --nofollow-imports  --plugin-enable=tk-inter LogCatch.py

python 3.5.2 64bit
nuitka 0.6.8.1
os:Windows
Arch:x86_64

Use nuitka to package the python script into an exe program. After running the program, the Chinese prompt information in the python script is displayed as a garbled state on the cmd command line.

Does nuitka support Chinese?

**Comment by kayhayen** [comment]
It should, there is a hotfix coming for a problem with some file paths, which cause issues. I am not sure what you mean by prompt information though. Maybe this is another problem. Can you provide a more clear example or even reproducer?

**Comment by kayhayen** [comment]
The hotfix is out, let me know if it still persists, otherwise closing for lack of feedback, feel free to reopen with the wanted example.

**Comment by gyk2850647** [comment]
Thank you.
I have tried to replace all Chinese in the code with English.
The Chinese prompt message I said was something like this: print ("脚本已经运行."  )
The print output statement is displayed on the cmd command line.

**Comment by kayhayen** [comment]
I am not sure, are you saying it works now?

**Comment by gyk2850647** [comment]
yes.
Replace all Chinese in the code with English, and the script will run normally.

**Comment by kayhayen** [comment]
The script runs the same with native Python and Nuitka compiled. Both do not display the character. However, if I copy and past them to a better terminal, they are these chinese characters. That should mean, the font used is wrong and likely has no Chinese characters.

Your problem is that the terminal is not good at that apparently. I failed to redirect output in either terminal to a file, to be able to compare it, but using another terminal, both Python and Nuitka can display it, but this should be proven.

Please only report where Nuitka behaves differently from Python. Not where your program does not behave in a way you don't like, ok?
