### ISSUE TITLE
[Feature Request] Copying files from library

### ISSUE THREAD

**Issue by OliverCWY** [Nuitka/Nuitka#724]
In view of the compilation time, is it better to provide an option to simply copy the code of the libraries and then executing with python37.dll? Many libraries are already optimized and sacrificing the compilation time may not worth it.

**Comment by kayhayen** [comment]
I don't understand what you are asking here.

**Comment by OliverCWY** [comment]
Sorry, what I mean is, instead of compiling the libraries, it may be a better option to simply follow and copy some of the packages to the root directory of the programme and using python.dll to execute in the standalone mode. For many libraries, the execution time may be dependent on other factors such as network and the c-backend. This can reduce the compilation time significantly, without sacrificing much performance. 
![image](https://user-images.githubusercontent.com/25003495/82754856-59af3800-9e02-11ea-9c19-912db8c96269.png)

**Comment by kayhayen** [comment]
You can do this by compiling what you care about as an extension module, and then use another tool to deploy. Right now I don't see that happening for lack of manpower. Also I don't really see the point, to me it's more important to make compilation time for 3rd party modules a non-issue, rather than avoiding it.

Not sure if it's helpful to keep this open, unless you are willing to implement it, are you?
