### ISSUE TITLE
Why does standalone mode include unused libraries.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#725]
```
0.6.9rc2
Python: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)]
Executable: C:\Python37x86\python.exe
OS: Windows
Arch: x86
```

try to compile a HelloWorld script without any module import:
`nuitka --standalone --mingw64 test.py`

after compile, there are some .pyd and .dll files that any modules never used them:
```
_sqlite3.pyd
_tkinter.pyd
comctl32.dll
sqlite3.dll
tcl86t.dll
tk86t.dll
```

i deleted above files and tried to run the app and it works without any problem.

i found these unused files with `--show-modules` option:

![image](https://user-images.githubusercontent.com/26390254/82743787-3d20ea80-9d85-11ea-8e26-cf10866cf644.png)

**Comment by kayhayen** [comment]
In standalone mode, Nuitka includes the standard library no questions asked. It does also include the extension modules and DLLs used because of that.

Right now, Nuitka is not scalable enough and certainly doesn't have the caching facility needed, to make this realistic. Once we are able to accelerate standard library with acceptable compile times, where things will be only slow once, I don't care enough about the overhead.

Detecting if e.g. sqlite3 or tkinter is not used by some parts of the standard library optionally depending on its use is non-trivial. I won't be bothered with doing it for standalone mode only.

On the roadmap for Nuitka is new constants access code, that will make it realistic to allow modules without program wide optimization to be cached and re-used across programs. Once he have that, might be talking about standard library for accelerated mode. Right now, for accelerated mode it's output ignored and use from system Python, causing a lot of potential lost.

Next up would be to apply this to standalone optimization. For me also, this means to be able to re-use Nuitka optimization by re-loading it from disk per module, and then to only do program global optimization, e.g. eliminating unused functions from a module, while caching that result with dependencies too.

This is all probably not happening this year. But once I see this in place, I am willing to go for size optimization of the distribution, because for accelerated mode, there will already be full analysis done. Doing guess work on standard library without analysing it deeply, it just is going to waste my time, even if it gives a more optimal result sooner. That I don't care about.

Questions are closed, that doesn't mean, there aren't issues for it, I am thinking there are, but I am too lazy to look them up. But I believe answering this question makes sense, as this won't be solved by Nuitka soon.

**Comment by byehack** [comment]
so if nuitka doesn't have plan for don't import these modules and libraries, i should delete them manually.
but anymore thanks for reply.
