### ISSUE TITLE
Optimizing lambda call with star dict argument crashes

### ISSUE THREAD

**Issue by niki-sp** [Nuitka/Nuitka#737]
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

$python -m nuitka --version
0.6.9rc4
Python: 3.8.2 (default, Apr 27 2020, 15:53:34) 
Executable: /home/user/nu-test/dev/bin/python
OS: Linux
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.
$pip install Nuitka-0.6.9rc4.tar.gz 

[geometry.py.txt](https://github.com/Nuitka/Nuitka/files/4723960/geometry.py.txt)
error when compiling this simple file:

Problem with statement at geometry.py:12:
->         (lambda mod, **kwa: getattr(mod, 'unittest').main(mod, **kwa))(

Problem with statement at geometry.py:7:
->     if __name__=='__main__':

Problem with statement at geometry.py:6:
-> if __debug__:

Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'geometry.py', 'module_name': <ModuleName geometry>}>'.

**Comment by kayhayen** [comment]
That's for the nice reproducer. This is a case apparently not seen before. The argument matching for star dict arguments, returns a list of pairs, rather than a node. All users for built-ins deal with that, by accepting pair arguments for constructing the node. 

However, when used for function call optimization (which happens only very little right now, due to limitations still in place), the star argument is expected to be just another node, but not a list of pairs, so I put an adapter in there, that creates it for now.

The pair vs. node stuff ought to be cleaned up, as also where Nuitka hands around keys and values separately.

I expect to make this part of a hotfix in the next days.

**Comment by kayhayen** [comment]
This is on factory now: https://nuitka.net/doc/factory.html

**Comment by niki-sp** [comment]
factory works perfect. Thanks!

**Comment by kayhayen** [comment]
This is part of the 0.6.8.4 release I just made.
