### ISSUE TITLE
Getting Error - ModuleNotFoundError: No module named 'sklearn'

### ISSUE THREAD

**Issue by manpreet1994** [Nuitka/Nuitka#767]
Nuitka version - 0.6.7/0.6.8.4 (tried for both versions)
Platform - Ubuntu 18.04
Installed Nuitka via pip
Python - 3.6.5

**For Reproducing the issue:-**
Dependency - pip install profanity-check ==1.0.3

I'm compiling a test file check.py which looks like below

`from profanity_check import predict_prob`
`print("Random test check")`

I'm compiling like this:-

`python -m nuitka --follow-imports --enable-plugin=numpy  --standalone  --show-progress check.py `

Error i'm getting while running the binary
ModuleNotFoundError: No module named 'sklearn'

Am I missing anything?
NOTE: I have tried hinted compilation and dev copy of Nuitka also.

**Comment by kayhayen** [comment]
I think, the options used are having the wrong default. I guess, when I added them, I made a mistake in defaulting to false for `--include-scipy` and `--include-matplotlib`, so I think I need to change it to `--no-include-scipy` and `no-include-matplotlib` and then change hinted compilation accordingly.

Very bad. I guess I caused a lot of regressions there. @JorjMcKie

**Comment by kayhayen** [comment]
I am encouting a problem loading `scipy.linalg._fblas.pyd` not sure now, if that is because of the plugin not handling the DLLs, it doesn't find stuff where it scans for, and actually there are no DLLs for SciPy installed in my Windows and Python 3.7 now, so I wonder, what is it.

I am too fed up though, with these sorts of issues. And I think, I need to turn import tracing and dependency walker, into a combination, and detect loaded DLLs, at least ones at import time, automatically. We can fork a process that does all the ".pyd" imports, and use our run time DLL loading detection, to find the ones that are being used. Either all at once for a program, that's probably quick, although extension modules might be slow to load, or for each extension module separately, and in either case, we could do it cached.

So I think I am holding off for these kinds of issues. Any comments @Nuitka/nuitka-pushers on this? Even takers? We need to create an issue for that. The idea is old, but at the time, dependency walker was very slow (in the way we used it), but now it's very fast, so this might be practical.

**Comment by zlyxm** [comment]
Excuse me, is there any progress on this issue?

**Comment by kayhayen** [comment]
This doesn't run for me at all now, but for what I can tell, sklearn is working well for a while now, for as long as `joblib` is not used with the `loky` backend, something which I am addressing separately.
