### ISSUE TITLE
Loop variables used in 2 loops inside a loop can cause infinite optimization loop

### ISSUE THREAD

**Issue by eyeing** [Nuitka/Nuitka#780]
bash-4.2$ nuitka3 --version
0.6.8.4
Python: 3.8.2 (default, Jun 16 2020, 17:24:50) 
Executable: /vendor/tools/FOSS/python/3.8.2_Apex_20200616a/x86_64/bin/python3.8
OS: Linux
Arch: x86_64

This did not happen in an earlier version of nuitka (i only tested 0.6.6). I've prepared a package; it comes from a much more complex set of code that would stimulate this issue. I've narrowed it down to a smaller combination of files and commands, but in the process also broke the functionality of the code. However, this is done to isolate the issue into a smaller set of lines/imports in order to build a light test. The loop also breaks easily when some simple changes are made, there is an example of that in launch.py. The nuitka command used is:
nuitka3 --standalone --follow-imports --show-modules --show-progress --plugin-enable=numpy --include-matplotlib ./strangeness/strange.py

I can work around this issue by downgrading to an older version of nuitka or adding small changes to the code. However, I thought this would be an interesting case for regression.

[strangeness.zip](https://github.com/Nuitka/Nuitka/files/4887805/strangeness.zip)

**Comment by kayhayen** [comment]
I managed to reproduce this. Since this is a loop optimization bug, this is as good as it gets, thanks a lot!

My initial suspect, is that the loop variable being re-used in another loop, is fooling the loop optimization where these two loops don't let their respective loop variable finish, and so neither one finishes. Very cool stuff. 

This is demonstrated by changing `list_1` to `list_2` in the second loop.

Obviously, there is a possibility for optimization here. The `for` loop sets `list_1` and ignores the old value, even if it was set at entry to an unknown, that doesn't mean, that influences the loop. It however hates loop variables at entry to be unknown, but this is from another loop. Maybe the loop needs to be keyed in somewhere, where it is not yet.

**Comment by eyeing** [comment]
There are quite a few other ways to break the loop, that seem to be unrelated to "list_1". For example:
- there is an "encode" function in t2g that is completely unused. If that code is removed, the loop does not exist
- strangeness only does an import of launch; if the compile occurs directly on launch, the loop does not exist
- only the variable dictionary "Var" is used from VarClass. If the dictionary is declared directly in the launch scope instead of going through launch, the loop does not exist

If a simple testcase with only the for conditions were created, i'm not sure the infinite loop would be reproduced.

**Comment by kayhayen** [comment]
I need to verify all of those all well. I noticed that two modules were having the issue of reporting incomplete loop types with `--verbose`. One of these was `t2g`. An incomplete loop variable state forces a next pass. 

This is pure fantasy, but they might each take turns in being considered not finished, triggering another pass. Nuitka then iterates over all the program again. They could play ping/pong this way. Some of the code, you remove, could be necessary to trigger the state of doing a ping pong.

First thing definitely is that the `--verbose` output for incomplete loops should be become better at explaining what variable caused it and how. My loop SSA seems to have a thinko here. But from pure thought, what I came up with, is that the loop variable trace, not knowing what loop it refers to, can be fooled into considering loop traces of other loops as if it's belonging to its own state of the loop. And also, the inner loops might prevent the outer loop from being considered complete, while the outer may prevent the inner loops from being complete.

I honestly didn't consider nested loops well enough it seems. If it also turns out, the result is not stable, that could well be, because of the non-distinction of what loop's initial trace we are having. Every loop can do that do a variable, and in the end, that seems like it cannot work well at all.

It's a scary issue. I will definitely look at this over the long weekend that starts tomorrow. Let me compliment you on the report, very good one, and well reduced to the point, where it's becoming funny.

**Comment by eyeing** [comment]
I'm not sure if this is ultimately related to #783 , but it sounds like this is a major endeavor to solve and i understand trepidation around any major rework. 

It wasn't difficult for me to identify a workaround by playing with my code, after i isolated to the loops that caused it: it was much harder to minimize the code to a small testcase than finding a workaround. If there is a limit on loop attempts and associated error message on which part(s) of the code it was looping over, it would help users to come up with workarounds in their code and deterministically breaks the infinite loop. This gives an engineering solution to the infinite loops by asking users to pick up some of the load in the meantime. In the future, there can be alternate algorithm(s) after the loop limit is met, and can potentially be a smaller work overall.

I know you're a wizard with code; if this feels like an "unclean" suggestion, please ignore it. :)

**Comment by kayhayen** [comment]
Actually that is probably what I should go for, like a timeout on the loop, just to make the stable version workable.

However, some optimization is expected to be complete before generating the code. So aborting after a fixed amount of rounds  is an option.

However, to be fully honest, I decided to delay looking into this, and to finish invasive branches I got. One is, the new constants code is coming to develop soon. And the other is the locals scope completion, something I have tried to finalize, and will so today, but it probably means, I will only continue with this not immediately.

So in terms of honestly, I have had the thinking process of what is necessary, but I didn't yet try it out, to see if it just works. But your idea is good enough for a hotfix. Nuitka can abort loop optimization after 10 attempts, and put all loop variables to unknown type, fixed, an be workable. Giving a warning about it, would be good, but we don't need a report. And maybe, this kind of thing, ought to become part of any solution. There would always be a chance of this kind of algorithm to not finalize due to a bug.

Sorry for the delay, but I didn't want to be overwhelmed by 3 big changes, all unfinished, and then other bug report load....

Yours,
Kay

**Comment by kayhayen** [comment]
And actually, I think I will aim at adding the check immediately, with the warning, then this is unblocked, and can even be hotfix material.

**Comment by kayhayen** [comment]
So, while doing pre-release testing for the changes I was talking about, I encoutered issues with this simple code:

```
def f():
    noops = 0
    while noops < 4:
        if cond:
            noops += 1
            continue
        noops = 0
```

This is only a single loop, and a single type on Python3, where it works, but on Python2 due to `long` and `int` being a possibility, it doesn't converge immediately, and then it never will. On this, I can surely test the automatic aborting if too many attempts have been made. I am assuming that merge usage with different types, even though a subset is causing this.

It may well cover your issue as well, and that there is no need for having 2 loops at all, we will see.

**Comment by kayhayen** [comment]
There has been a workaround on factory, and now is on develop. I still need to check out the example above, but your issue should be gone with the latest pre-release.

**Comment by eyeing** [comment]
Thank you! Testing.

**Comment by eyeing** [comment]
Sorry for the delay, I ran into some issues with PyPI with develop vs production releases colliding, causing the experiments to go sideways.

Looks like I have different piece of code that is still looping, although the original is fixed. I'll look at how to address this on my end by isolating to the nested loops that are causing the loops.

**Comment by kayhayen** [comment]
I have something like a new loop code, that seems to work better. I will shortly publish it.

**Comment by kayhayen** [comment]
This is the last release 0.6.9 already for a while.
