### ISSUE TITLE
Nuitka logs are ugly and not user friendly

### ISSUE THREAD

**Issue by ManPython** [Nuitka/Nuitka#845]
In version 0.6.9.1 Nuitka logs are ugly and not user friendly, whole is like "river" that flow in window.
```
Python36\python -m nuitka --follow-imports --windows-dependency-tool=pefile --experimental=use_pefile_recurse main.pyw
←[91mNuitka-Scons:WARNING: Didn't find ccache for C level caching, follow Nuitka user manual description.
←[0mNuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running 'gcc -o "module.View.main_window.o" -c -std=c11 -fwrapv -ftrack-macro-expansion=0 -fpartial-inlining -fno-var-tracking -O3 -pipe -D_WIN32_WINNT=0x0501 -D_NUITKA_EXPERIMENTAL_USE_PEFILE_RECURSE -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D_NUITKA_SYSFLAG_NO_RANDOMIZATION=0 -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=0 -D_NUITKA_EXE -IE:
...etc
```
There are whole hudge cards of long continous lines.. 

Regarding the previous version as belong this was more friendly around:
```
Nuitka:INFO:PASS 1:
Nuitka:INFO:Initial optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:PASS 2 ... :
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Total memory usage before running scons: 23.61 MB (24756224 bytes):
```
Regarding the Nuitka-GUI - proposal
https://github.com/Nuitka/NUITKA-Utilities/issues/8#issuecomment-481046586
I sugessting something like this: PROFILE as Compilator PROFILE Settings (it's due to proposed convention for GUI where settings are for GUI and other)

```
Nuitka:COMPILER:start:2020-09-29 17:00:11
Nuitka:INFO:version:0.6.9.1
Nuitka:INFO:Python: 3.6.8
Nuitka:INFO:Platform: Windows-7-6.1.7601-SP1
Nuitka:PROFILE:compiler:mingw
Nuitka:PROFILE:output:my_app.exe
Nuitka:PROFILE:full-compat:true
...etc
Nuitka:INFO:PASS 1:
Nuitka:INFO:Initial optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:PASS 2 ... :
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module '__main__', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for '__main__'.
Nuitka:INFO:Total memory usage before running scons: 23.61 MB (24756224 bytes):
```
Not sure is good to start like `Nuitka:I` sounds bether to use timestamp
It's good to grab `start_time` and `end_time` of compilation to offer in final log `Compilation_time`

```
2020-09-29 17:44:33;INFO:Doing module local optimizations for '__main__'.
2020-09-29 17:44:35;INFO:Total memory usage before running scons: 23.61 MB (24756224 bytes):
2020-09-29 17:44:35;INFO:Compilation time: 00:40:00
```
This all can be usfeull in colab and logs analyse.

**Comment by kayhayen** [comment]
The logging is undergoing big changes in the past release cycle and more to come.

I am changing Nuitka from silent by default to informative by default. The scons warning is there to make it easy to recognize for users, what action took so long. You not having installed a C caching tool is a warning now. Slow compilations with silence from Nuitka were frequently causing confusion. Nuitka therefore now announces this. The long lines are there, because it's hard to get back from these to the original command, and it's different for Windows and non-Windows, and that's more work than I wanted to initially spend on this. For now it serves the purpose, as the module name (more or less uniquely) can be found in there.

I am going to add more outputs about the final product, its useability, etc. in future releases. I am going to live with it being broken for a while. This is not actionable itself, but it's a line of action for Nuitka development to improve this. Still closit it though, there is no clear direction in this issue.
