### ISSUE TITLE
Standalone: Including .so files from standard library is wasteful

### ISSUE THREAD

**Issue by torchsmoke** [Nuitka/Nuitka#864]
When I compile my program without any imports many .so files are included that I do not need. For example audioop.so, libsqlite3.so.0, libx11.s0.6 and libtcl8.6.so. The more packages I have installed the more they become. So my program grows to 30Mb. But my compiled program itself only needs 7Mb.Can you fix that?

**Comment by kayhayen** [comment]
That's something that `--recurse-stdlib` might do, not sure though. But at the cost of increased compile times, and it has been known in the past to not work, maybe still does not.

For me, this is tied to caching. Once stdlib can be used in cached form, no problem at all, lets keep this open as a reminder. The libsqlite3 is very probably stupid to use, as nothing imports it. But without analysis, I didn't want to support guess work.

Would you be interested in helping to get the XML streaming and restoration to work?

**Comment by Ben-Faessler** [comment]
I would like to help.  I just need more detailed information about the problem.

**Comment by kayhayen** [comment]
Ok, then I am going to add in something that will write the XML to cache, and check if reading it back from there will give the same result for code generation. We could aim for that to be achieved for standard library, and then we could use it there as a starting point.

Right now, Nuitka has internally for the modules, a tree of things, where e.g. an assignment statement is a node, and these can be written to XML with `--xml`. And in theory, this can be read back too. But that is very incomplete and bit rotten, i.e. got out of sync with actual nodes. So if a operator node has a left and right argument, these are nodes too, any maybe it has an operator, and then the XML will contain that. You can look at that output right now, for any script. You get the idea maybe.

Basically, we would then make a cached mode, where it reads Python, optimizes a module, and then writes the XML files and generate C code from it. And then a by default inactive mode, where it reads from the cache if possible, invalidating it if the checksum mismatches, then generates the C code from it.

That will crash a lot, with missing arguments, no such argument, or generate things differently. I think sometimes, the XML output is loosing some information too. That's mostly only debugging work, and should be possible to point to a class constructor, and its `getDetails` functions.

I can implement the basic caching logic, and make it hidden, but tell you how to use it, and then you can give it a go, and try and get as many issues found and solved. Sometimes we also have had issues that this would find, e.g. when code like this happens:

```
try:
    something()
finally:
     another()
```

Then we already now, clone nodes at run time. And sometimes similar errors have occurred, e.g. because an argument name changed for the constructor, and that only got noticed when this kind of node was used in this way. Because the finally code gets put into several exit handlers, being duplicated, depending on what `something()` does, e.g. return or raise an exception both.

**Comment by Ben-Faessler** [comment]
Of course, they do not have to do it immediately.
I will read the developer manual and think about it. When you are ready you can report it to me.

**Comment by kayhayen** [comment]
So, with 1.7 already, hello world on Windows is very small. The solution was a bit error prone though, since within stdlib, dependencies are not tracked. The option `--recurse-stdlib` however, with 1.8 is maybe obsolete. Nuitka now analyses all the modules, and handles some cases of bloat in stdlib.

Depending on how your Python is built, e.g. this is preventing inclusion of `_socket.so` unless something explicitely imports the socket module of course:

```
- module-name: 'email.utils'
  anti-bloat:
    - description: 'avoid socket module usage'
      replacements_plain:
        'import socket': ''
        'socket.': '__import__("socket").'
      no-auto-follow:
        'socket': "can break calls of 'email.utils.make_msgid()'"
      when: 'not has_builtin_module("_socket")'
```

On Windows, only `unicodedata.pyd` is included other than the Python DLL, I didn't check for Debian Python yet, how good we are there, but surely we can try and get lower there too. I think the `unicodedata` will be needed for `idna` encoding that a handful of packages could end up needing.

That Windows result is the same as 1.7, but with maybe a lot less bugs. Therefore we can now try and go further, lets see what Debian Python does.

**Comment by kayhayen** [comment]
This is from 1.8 right now on Ubuntu with 3.10:

> python3.10 bin/nuitka tests/onefile/HelloWorldTest.py

```
HelloWorldTest.bin  _codecs_iso2022.so  _codecs_tw.so    _json.so            audioop.so     termios.so
_codecs_cn.so       _codecs_jp.so       _contextvars.so  _multibytecodec.so  libexpat.so.1
_codecs_hk.so       _codecs_kr.so       _crypt.so        _opcode.so          libz.so.1
```

**Comment by kayhayen** [comment]
That's also an improvement over 1.7 which added `_dbm.so`  and `_opcode.so`, so down by 2 just by proper analysis.

**Comment by kayhayen** [comment]
So, including `json.tool` is always garbage, it's binary runner script, so lets lower the bytecode burden there.

**Comment by kayhayen** [comment]
For zipapp, no need to include its runner, and calendar the same, and if both are not automatically included (I do not think extension modules expect them) then also `argparse` is gone which I guess it ought to be.

**Comment by kayhayen** [comment]
Removing json might be a bit painful for extension modules, I very much suspect it is wanted by quite a few, so that will cause disruption, until we got a proper message to raise for them if found missing at runtime.

**Comment by kayhayen** [comment]
From the looks of it, `json` package is prepared to work even without `_json`, so what I am going to do is to make a conditional no-auto-follow with a message that explains the downside, such that then people can know and override it. That message will be given for every Ubuntu Python compilation until we make `json` non-automatic as well.

**Comment by kayhayen** [comment]
So we now get this:

> Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically to avoid bloat, but this may cause: because of may slow down by using fallback implementation.

But only if an import is done. The default inclusion of `json` does not trigger inclusion of the dependency `_json`, so we are down by one, `json_so` is not included anymore.

The kind of config for this is also fairly easy:

```
- module-name: 'json.encoder'
  anti-bloat:
    - description: 'avoid _json module usage'
      no-auto-follow:
        '_json': "may slow down by using fallback implementation"
      when: 'not has_builtin_module("_json")'
```

The no-auto-follow is a recent addition, that I have yet to describe, and in a sense also to make it fully workable, such that in non-deployment mode, it helps finding issues with it at runtime like with the extension modules I mentioned.

**Comment by kayhayen** [comment]
The `audioop` module is just generally removed along with the audio modules using it from the list. Same for termios, I do not think that `tty`, `pty` and `getpass` are seeing a lot of usage. We could avoid `termios` in `getpass` since it has a fallback too, but I don't want to there now.

**Comment by kayhayen** [comment]
Also got rid of `_opcode` and `_contextvars` leaving us with ultimately only encoding related extension modules, that we do not want to mess with right now. Also Ubuntu Python has 2 DLLs the libpython pulls in. I wonder if static libpython could avoid these there as well somehow, but a non-Debian Python will be a better choice to achieve these things anyway.

**Comment by kayhayen** [comment]
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment]
So, I also did a bunch of work coming from macOS, that removes a few more modules there. But on that OS, things like `math` and `random` or `struct` cannot really be done like that. So we stop there. That conclused this activity for now.

**Comment by kayhayen** [comment]
So, `_datetime` being optional killed numpy, I have reverted that, but the change is on develop and will give much better results now for many environments. I am closing this early for lack of general relevance at this point, but I will as usual notify when the release was made.

**Comment by kayhayen** [comment]
Part of the 1.8 release I just made.
