### ISSUE TITLE
Question about ccache under conda on windows

### ISSUE THREAD

**Issue by DanCodigaMWRA** [Nuitka/Nuitka#889]
[ This is not a bug report or a feature request but rather just a question that I was led to, when reading the documentation. ]

I am using nuitka, on Win64, in the following way. The goal is a standalone executable file, created from a .py file such as this example hello.py (which imports and uses only numpy):

```
def talk(message):
    return "Talk: " + message
def main():
    print( talk("Hello World"))
    from numpy import ones, shape
    print('size = %s' %str(shape(ones([20,3]))))
    input('hit enter when done')
main()

``` 
First, I use conda to create a py3.7 virtual environment, in which I include:
* nuitka (0.6.9.6)
* m2w64-gcc
* numpy, pandas, scipy, matplotlib and other common packages that I tend to use.

Then I get the files **get-hints.py**, **nuitka-hints.py**, and **hinted-mods.py** (all from the github repo) and put them in a folder together with hello.py.

Next, I cd in to the folder, activate my conda env, and from within it I execute
- python get-hints.py hello.py

which creates the json file, and 
- python nuitka-hints.py hello.py 

which creates the executable file hello.exe, inside the folder hello.dist (it also creates folder hello.build).

The executable is created and it can be run successfully. This is nice. 

However the compilation can be relatively slow (10s of minutes), and the resulting folders are pretty large (100s of megs if including numpy and matplotlib etc). I would like to learn what improvements can be made (to the compilation speed and the size of the resulting hello.dist folder). 

I noticed in the documentation there is emphasis on improvements from using ccache, and I also noticed there is a warning during the compilation:
- Nuitka-Scons:WARNING: You are not using ccache.

So here is my question: 
Is there any way for me to use ccache, while still doing my compilation from within the conda env (note: I don't install gcc outside of what has been included by conda in the virtual env)?
If so, how would I do that?

(If you have other more general suggestions, beyond using ccache, for how I can make improvements they are very welcome too of course.)

**Comment by DanCodigaMWRA** [comment]
Update on this. I added ccache to the set of modules included in my conda env. I no longer get the warning that ccache is not being used. However I have re-run nuitka a few times this way and not noticed much or any reduction in its execution time. 

I do still see this warning:
- scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly


I wonder if this is related to the way ccache seems to be used, but apparently not reducing execution times.

**Comment by kayhayen** [comment]
The version of Nuitka on develop would download ccache automatically, and one that works better than the one in Anaconda, I had to switch, because the version in Anaconda was misbehaving, i.e. hanging endlessly, where the official binary from the ccache project does not.

Using the CondaCC is going to be deprecated soon, I have removed the automatic fallback to it on develop already, since using a gcc 5.2 is not useful as opposed to a gcc 10.2, and that Nuitka will download too.

I am hoping to have things more out of the box working that way, and of course, for me to remove the nightmare of people not being able to pick proper binaries themselves, esp. not for MinGW64.

As for the warning, that is because you didn't specify `--msvc` in which case, the scan for MSVC is not happening. Right now you are using the CondaCC by means of falling back to gcc as a second attempt. As I always have MSVC on my system, I cannot see that. I am however going to drop the warning, it could easily be misunderstand as a request to install it, where obviously that is not deemed necessary.

And for the caching, Nuitka outputs an overview at the end, that indicates how successful it has been, which indicates it. Of course the C compiler is not necessarily the slow thing, sometimes it is, sometimes it is Nuitka. For the later, the good news is that on develop, there have been very many scalability improvements, all geared at speeding up Nuitka. And then there is #887 for which my analysis found that some modules trigger many more global optimization passes than necessary, which for large programs can bit hard. I hope to solve that issue before releasing 0.6.10, but definitely develop will already be somewhat better for you.

**Comment by DanCodigaMWRA** [comment]
Okay that's fine, I will continue to ignore the Virtual Studio warning if I see it.

> The version of Nuitka on develop would download ccache automatically, and one that works better than the one in Anaconda, I had to switch, because the version in Anaconda was misbehaving, i.e. hanging endlessly, where the official binary from the ccache project does not.
Using the CondaCC is going to be deprecated soon, I have removed the automatic fallback to it on develop already, since using a gcc 5.2 is not useful as opposed to a gcc 10.2, and that Nuitka will download too.

So, for future versions 0.6.10 onward, I should plan on:
- not needing to include ccache in my conda env (because nuitka won't use it anyway)
- nuitka will automatically go get the ccache exe file for me and use it.

Correct?

**Comment by kayhayen** [comment]
I am not yet taking steps to disable the existing ``ccache`` scan, so as to not break people's environments. But I am sure tempted to do so. There is an option `--assume-yes-for-downloads` that allows Nuitka to do things non-inactively as well, but since it's cached, it's only relevant for CI. 

Right now, I want make sure 0.6.10 doesn't have too many problems with the new tools. But surely I am at least going to add checks for gcc to be at least version 8 or higher soon after that release. Refusing to use the existing tool is a bit harsh, but at least for installation instructions of Nuitka, those are going to become easier.

I will decide this based on feedback I get after release.
