### ISSUE TITLE
install_name_tool error: .DS_Store is not a Mach-O file

### ISSUE THREAD

**Issue by noonchen** [Nuitka/Nuitka#902]
I encountered this issue again when the build was almost finished, using the hinted-compilation method: 

```
Nuitka-Plugins:INFO: qt-plugins: Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'STDF Viewer.dist/PyQt5/qt-plugins'.
Nuitka-Plugins:INFO: numpy: Copied 'matplotlib/mpl-data'.
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: input file: STDF Viewer.dist/PyQt5/qt-plugins/.DS_Store is not a Mach-O file
Error, call to 'install_name_tool' to fix shared library path failed.
```

* Please check whether the bug was already reported or fixed.
This error has been reported in #51 , but in the current case, simply ignoring .DS_Store might fix the issue, any advice on how to bypass it? Thanks in advance.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
Platform: **macOS 11.0.1**
Nuitka version:
0.6.10
Python: 3.8.6 (default, Nov 20 2020, 23:57:10) 
Executable: /usr/local/opt/python@3.8/bin/python3.8
OS: Darwin
Arch: x86_64

* How did you install Nuitka and Python.
Python 3.8: brew
Nuitka: pip

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.
this issue is not seen in 0.6.9.6

**Comment by kayhayen** [comment]
We should filter these files away when copying plugins. For now, you can just delete the file in your installation.

**Comment by noonchen** [comment]
I think this issue is also fixed in 0.6.10.4, not seeing any error during the build.

**Comment by kayhayen** [comment]
That's not true @noonchen this is going to be a spurious error. The plugin copy process needs to be ignoring non-DLL files or at least not claim for them to be DLLs, that's a bug. Obviously if you didn't open the folder in the Finder, this kind of file may not exist, but I didn't do anything to change it yet. Unfortunately this is not a high priority by itself, but I was working on the process of data files provision somewhat, and ideally what is going to happy is that the plugin changes to something that scans the folder and yields DLL and data file inclusion descriptions rather than a folder copy with describing it after the fact.

But there are a bunch of plugin changes that need to go first before making this plugin robust against this is going to happen.

**Comment by kayhayen** [comment]
These data files are ignored by Nuitka for a while now.
