### ISSUE TITLE
How to include own compiled extensions?

### ISSUE THREAD

**Issue by MyraBaba** [Nuitka/Nuitka#910]
Hi 

I have my own extesions compied to .so in the : 

my extension in the folder : 

mxx
----- myton
------------xxx.so

How I can properly include this ?

**Comment by kayhayen** [comment]
This can only be done for standalone mode, otherwise, it should be loaded from the installation. Use `--include-module` there. Depending on where the PYTHONPATH points to with more or less dots. Assuming these are Python packages, and mxx ending up in `sys.path` for Nuitka, e.g. by setting `PYTHONPATH` you do `--include-module=mxx.myton.xxx` and you are good.

Nuitka will then analyse the DLLs needed by it, and include them too.
