### ISSUE TITLE
Enforce the use of MinGW64 on Windows. Defaults to off.

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#928]
Wrong:
--mingw64 Enforce the use of MinGW64 on Windows. Defaults to off
![image](https://user-images.githubusercontent.com/64806740/104184040-e6efdd00-5423-11eb-8d3a-9adf3fcd123f.png)

--mingw64 Enforce the use of MinGW64 on Windows. Defaults to on

input:
`python -m nuitka --standalone  --windows-uac-admin "E:\Download\test.py"`

Output:
```
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\andre\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 12
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist\\test.exe'.
```

**Comment by kayhayen** [comment]
I don't understand what you mean here?

**Comment by Pro100rus32** [comment]
> I don't understand what you mean here?

`--mingw64 `Force use MinGW64 in Windows, turn it off, but it uses it without using `--mingw64`


_Maybe I just don't understand correctly, then Google translator is to blame :)_

**Comment by kayhayen** [comment]
The `--mingw64` only has an effect in selecting which compiler is used by default. It disables the scan for MSVC and instead makes one for gcc, and also enables the automatic download. Ultimately it's more of a `--no-msvc` which since it's found via registry, you cannot disable in any other way. My goal is clearly to have it being unnecessary. I forgot how far the develop branch is with that quest though.
