### ISSUE TITLE
Nuitka makes list.append much slower

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#983]
I've tried to compile a prime number sieve using nuitka 0.6.12.1 in order to investigate in what extent can nuitka speed up a python program, but the result was a bit disappointed. It showed Nuitka made the program 15%~30% slower than before. When I removed the `list.append`, the performance backed to normal, but still no performance gain.  

Platform: Windows
CPU: Ryzen7 1700
RAM: DDR4-3200*2
Python: 3.8.7 (x64)
Nuitka: 0.6.12.1

**Compiler command:**
``
nuitka --mingw64 --standalone --show-progress --output-dir=C:\Users\home\Desktop\1 "C:\Users\home\Desktop\Prime number.py"
``

**Before using Nuitka (with `list.append`):**
![2021-02-11 150425](https://user-images.githubusercontent.com/60065064/107609692-b4334180-6c7a-11eb-934c-78f4aadc41fd.png)

**After using Nuitka (with `list.append`):**
![2021-02-11 150452](https://user-images.githubusercontent.com/60065064/107609668-96fe7300-6c7a-11eb-9251-48c044ef5c46.png)

**Before using Nuitka (without `list.append`):**
![2021-02-11 151849](https://user-images.githubusercontent.com/60065064/107610476-9e268080-6c7c-11eb-8431-83926ffc6ac9.png)

**After using Nuitka (without `list.append`):**
![2021-02-11 151823](https://user-images.githubusercontent.com/60065064/107610463-99fa6300-6c7c-11eb-984b-4f39b47a9abe.png)

**Code (with `list.append`):**
```Python
import math
import time
import os

def prime(n):
    if n <= 1:
        return 0
    for i in range(2, n):
        if n % i == 0:
            return 0
    return 1


if __name__ == "__main__":
    s = time.time()
    n = 50000
    result = []
    for i in range(2, n + 1):
        if prime(i):
            result.append(i)
    e = time.time()
    print(round(50000/(e-s),2),'/s')
    os.system('pause')
```

**Code (without `list.append`):**
```Python
import math
import time
import os

def prime(n):
    if n <= 1:
        return 0
    for i in range(2, n):
        if n % i == 0:
            return 0
    return 1


if __name__ == "__main__":
    s = time.time()
    n = 50000
    result = []
    for i in range(2, n + 1):
        if prime(i):
            a = i
    e = time.time()
    print(round(50000/(e-s),2),'/s')
    os.system('pause')
```

**Comment by kayhayen** [comment]
I agree with that, and it's a shame. In previous releases, even more so, because e.g. dictionary operations and list operations have been optimized on the C level, for where they are used, but they are not optimized into. So what's going on, is that the current loop optimization, doesn't detect that the `.append ` call is causing a potential escape of whatever it is, but being escaped is different from being unknown.

Therefore, these things are not yet optimized. I will need to be at the drawing board for this release cycle and see to it that "unknown", "escaped" and loop variable tracing interact more gracefully.

This is also the reason why integer C types (could be used for the loop variables) are not yet operational. Passing a variable marks is as escaped, if it's a loop variable, and nothing ever recognizes this to be the only escape, so it's not real.

Loop optimization is tricky, and admittedly, I haven't yet figured it fully out. Since I first introduced it 3 releases ago, I had to make corrections to it and I am glad it recognizes things now only correctly. But the differentiation from escaped and unknown must be pushed further. An escaped list e.g. is of course still a list, just not one where we can have value knowledge.

**Comment by kayhayen** [comment]
I got 14104.74 /s (CPython) vs 17688.68 /s (Nuitka) these days, which is a nice speedup. More will be hand in the future, when looping over those ranges happens in C int.  But since append to list is hard to optimize, that's a very welcome sight. Testing with 3.10 btw.

**Comment by kayhayen** [comment]
Your second form changed from 15679.39 /s (CPython) to 19119.11 /s (Nuitka) so that is reversed too. But I feel there ought to be a lot more possible. Anyway, seems we addressed this at some point.
